### ISSUE TITLE
total energy consumption

### ISSUE THREAD

**Issue by LucaGT78** [StyraHem/ShellyForHASS#103]
Congratulations on integrating with shelly,
I have seen that, for example regarding shelly 2.5, the total energy consumption value is not displayed (the shelly stores it).

When I configured shelly with mqtt I used this as:

- platform: mqtt
   name: "Cons_Tot_Stu"
   state_topic: "shellies / shellyswitch25-xxxxxx / relay / 0 / energy"
   qos: 0
   unit_of_measurement: "W"

then to have the value in Wh I divided the value by 60.

Could this parameter also be added?

Thanks

**Comment by Kedryn** [comment]
Same for Shelly PM, there are some counter missing, like total power

**Comment by chemelli74** [comment]
@Kedryn , can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by vistalba** [comment]
I run also a Shelly 1PM on 1.5.9 and there are some missing parameters:

In HA only this is visible:
```
ip_address: 192.168.1.123
shelly_type: Shelly 1 PM
shelly_id: C4A991
discovery: CoAP-discovery
ssid: somessid-iot
rssi: -63
uptime: 11124
device_temp: 49
over_temp: false
has_firmware_update: false
latest_fw_version: 20200122-090726/v1.5.9@4b657c90
firmware_version: 20200122-090726/v1.5.9@4b657c90
cloud_enabled: true
cloud_connected: true
mqtt_connected: false
cloud_status: connected
consumption: 712.1
unit_of_measurement: W
friendly_name: What ever
```

For example http://shellyip/stauts get stuff like:

- meters/0/counters/[0-2]
- meters/total

**Comment by hakana** [comment]
Total is in beta 9 just released

**Comment by hakana** [comment]
What do you need the counters for?

**Comment by vistalba** [comment]
I want to calculate the power consumption in kWh (like in Shelly cloud but local).
As I understand counter is "W/min" for the last 3 minutes.

**Comment by chemelli74** [comment]
@vistalba, @LucaGT78 , do you agree on closing this one and moving to #168 ?

Thank you,

Simone

**Comment by vistalba** [comment]
@chemelli74 did you mean #169?

**Comment by vistalba** [comment]
For me it is okay. Better check #169
