### ISSUE TITLE
FW 1.5.6 removes CoAP exec commands

### ISSUE THREAD

**Issue by rufik** [StyraHem/ShellyForHASS#104]
**Firmware 1.5.6**
Devices: Shelly1, Shelly1PM, Shelly2, Shelly2.5, Shelly Dimmer, Shelly2LED, ShellyEM, Shelly4Pro, ShellyPlugS, ShellyPlug
_Changelog:_
- _CoAP executions commands removed completely (status messages work same as before)_

https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/2432286643537352

**The question is** - does it affect ShellyForHASS addon?

**Comment by TASSDevon** [comment]
Would also like to know this before upgrading Shelly's fw.

**Comment by hakana** [comment]
No, we don't use them. We use CoAP for status only.

**Comment by TASSDevon** [comment]
Thanks for the quick update, reading bits and pieces on the ShellyForHASS intro, I figured it was using CoAP for events and REST api for commands, would that be correct? Perhaps you could explicitly state it like that on the integration info page so people in the future know what's up :-)

**Comment by hakana** [comment]
You are welcome to help to update. Right now my time is limited for this project so all help is appreciated.
