### ISSUE TITLE
Question on handling click events

### ISSUE THREAD

**Issue by TASSDevon** [StyraHem/ShellyForHASS#105]
I would like to capture click events from my Shelly 2.5 (roller shutter mode).

I have an empty 'shelly:' configuration (everything default).

My Shelly's show up as

 sensor.shelly_shsw_25_XXXXX_1_consumption

Can I use this sensor in the event_data's entity_id? Or would I have to add some additional configuration to the shelly platform? Could you perhaps give an example?

Thanks!

**Comment by hakana** [comment]
See readme, section Event and you have an example there.

https://github.com/StyraHem/ShellyForHASS/blob/master/README.md
