### ISSUE TITLE
Shelly disconnected on hassio 103.3

### ISSUE THREAD

**Issue by wifi75** [StyraHem/ShellyForHASS#106]
Maybe it is the last firmware, but all entities are . disconnected, what can I do?

**Comment by hakana** [comment]
Did it work before?

**Comment by wifi75** [comment]
Yes... I think after last firmware update

**Comment by wifi75** [comment]
I confirm the problem it is the last update firmware 1.5.6 ! Because I tryed to downgrade hassio to 102.1, and shelly not found!

**Comment by wifi75** [comment]
I'have update component to beta versione 0.1.3,now I see agian all entities but but they respond to the command slowly

**Comment by chemelli74** [comment]
@wifi75 , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
