### ISSUE TITLE
Feature Request: Shelly 2.5 Voltage sensor

### ISSUE THREAD

**Issue by aleksandrov1995** [StyraHem/ShellyForHASS#107]
Hello,

In the latest firmware update, a voltage property was added to the /status endpoint. Would it be possible, to be added as a sensor ?

![20191201_103520](https://user-images.githubusercontent.com/12535078/69911731-45c4e380-1428-11ea-9503-5cb9dbc17b9c.jpg)

Regards,
Marin

**Comment by hakana** [comment]
Will be added to next version

**Comment by chemelli74** [comment]
Please upgrade to 0.1.7b1 and recheck.

Simone

**Comment by aleksandrov1995** [comment]
Hello, sorry for the late feedback, i just updated and the voltage is now present. Thank you for you consideration to implement it.
