### ISSUE TITLE
Cloud key 

### ISSUE THREAD

**Issue by wifi75** [StyraHem/ShellyForHASS#108]
hello where should I add this code exactly?

cloud_auth_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
cloud_server: "shelly-5-eu.shelly.cloud"

**Comment by hakana** [comment]
Diect under shelly: in config.yaml. let me know if it working.

**Comment by wifi75** [comment]
but only shelly: 
with claud key?
or also the code like the screenshot?
![Screenshot_2019-12-01-23-32-30-865_com android chrome](https://user-images.githubusercontent.com/31816231/69921531-f10a8280-1492-11ea-8136-a96a4ef3a848.png)

**Comment by wifi75** [comment]
very strage two entities not found...
in the shelly Cloud it is all ok.
![Screenshot_2019-12-01-23-51-40-055_com android chrome](https://user-images.githubusercontent.com/31816231/69921766-a63e3a00-1495-11ea-9f87-db1a283dd684.png)

**Comment by chemelli74** [comment]
@wifi75 did you manage to get it working ?

Simone

**Comment by wifi75** [comment]
hello @chemelli74 I am honest, since I had the problem I went to mqtt, I would like to go back to your custom but I am always afraid that it will happen again.

**Comment by chemelli74** [comment]
> hello @chemelli74 I am honest, since I had the problem I went to mqtt, I would like to go back to your custom but I am always afraid that it will happen again.

Hi @wifi75 , just let me know if you want to retest with latest build or if you prefer that we close the issue.
Thank you,

Simone

**Comment by wifi75** [comment]
Hello, close the issue, but i wat to try new version.
