### ISSUE TITLE
Problems with some Shelly  1 PM detection

### ISSUE THREAD

**Issue by Kedryn** [StyraHem/ShellyForHASS#109]
As you can see from the pic, i have two Shelly 1 PM,
one is discovered with all values, the other  not. 
Runnin ShellyForHass 0.1.3

![image](https://user-images.githubusercontent.com/12759632/69967116-11305500-1518-11ea-818b-b56d00243df7.png)

**Comment by wifi75** [comment]
I'have some problem, then  the component is very slow

**Comment by chemelli74** [comment]
@Kedryn ,@wifi75 can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
