### ISSUE TITLE
Shelly Dimmer device temp and power usage

### ISSUE THREAD

**Issue by Kranzy** [StyraHem/ShellyForHASS#110]
Hi is it possible to get device temp and power usage for the shelly dimmer?

On my test HA install I am using full discovery with only 'shelly:' in my config file.

No sensors added for device temp or power usage.

Thanks

**Comment by mamrai1** [comment]
I have the same request. At least showing power will be beneficial.. At least temp warning works.

**Comment by gurkburk76** [comment]
Bump on this, without havinf to separate it into mqtt.

**Comment by Wieringerwerf** [comment]
yes +1 for me on power usage on dimmers, should be small fix...

**Comment by chemelli74** [comment]
@gurkburk76 , @Wieringerwerf can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by xaviml** [comment]
Hi @chemelli74,

I confirm that with the 0.1.6b7 now I see device_temp, but I do not see the power usage. In my configuration.yaml I have `shelly:` and this is what I see on the light attributes:
![Screenshot from 2020-01-22 12-46-04](https://user-images.githubusercontent.com/3974003/72891811-5fdabe00-3d15-11ea-9418-474d62e7321f.png)

**Comment by hakana** [comment]
You need to add:
```yaml
shelly:
  sensors:
    - power
```

**Comment by xaviml** [comment]
Sorry, I didn't check under the `sensor` domain. Now I see a new sensor with power consumption. Thanks for the awesome work!
