### ISSUE TITLE
Shellies only added as entities and no devices during auto-discovery

### ISSUE THREAD

**Issue by craigrallen** [StyraHem/ShellyForHASS#112]
When auto discovery is running, the local shellies are discovered as entities, but no devices are created to link associated entities to. A consequence of this is device automations aren't possible using the lovelace automation.

When adding them via modified auto discovery a device id can be associated and child entries linked. 

Is this a bug or a feature?

**Comment by cbear92** [comment]
Also have this problem, but I can't seem to find any way to modify the auto discovery to generate a device. What code did you add in?

**Comment by hakana** [comment]
Hi,

I need to look into this!

I guess devices is something newly added and that we not support today.

/Håkan

Från: craigrallen <notifications@github.com>
Skickat: den 8 december 2019 11:27
Till: StyraHem/ShellyForHASS <ShellyForHASS@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [StyraHem/ShellyForHASS] Shellies only added as entities and no devices during auto-discovery (#112)


When auto discovery is running, the local shellies are discovered as entities, but no devices are created to link associated entities to. A consequence of this is device automations aren't possible using the lovelace automation.

When adding them via modified auto discovery a device id can be associated and child entries linked.

Is this a bug or a feature?

**Comment by craigrallen** [comment]
Hi Hakan,

Hope the additional information helps.

The two devices added via the integration are a Shelly 1 and a Shelly 2. The plan is to add 10 more, but want to resolve the devices issue prior to adding more. The others will be RGBW2, Shelly 2.5 and Shelly 4 Pro.

Here are the entities from the entities register

![image](https://user-images.githubusercontent.com/56693437/70615423-ad3f1800-1c0c-11ea-81b5-67d9824a90bf.png)

Here you can see the devices register and no devices showing as shelly.

![image](https://user-images.githubusercontent.com/56693437/70615493-ca73e680-1c0c-11ea-9b49-1866cf468413.png)

Hope this helps

**Comment by rogervdf** [comment]
Having the same problem with my Shellies. @craigrallen could you share your configuration.yaml by any chance?

**Comment by chemelli74** [comment]
@rogervdf , @craigrallen can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by craigrallen** [comment]
Just flashed the one of the two units, update not showing available for the Shelly2 via their app. Updated to beta and it works a treat. Love that it shows as a full integration. Have to say great work, really think you've nailed it. I'll test more thoroughly and feedback any bugs, but you've genuinely made the plugin excellent.

**Comment by rogervdf** [comment]
This seems to be fixed!
