### ISSUE TITLE
Shelly devices on other vlan with pfsense

### ISSUE THREAD

**Issue by kasteleman** [StyraHem/ShellyForHASS#113]
I'm using the plug-in and it works fine when al my devices are in the same vlan as HASSIO. But when i move the devices into a seperate vlan the plug-in does not discover them anymore. I'm aware of the proxy script, but can not use it and therefore looking for a method of implementing the same functionality on my pfsense box. Can anyone help me out on this one?

**Comment by kasteleman** [comment]
Had a look at the latest commit 0.1.4 and found the option CONF_DISCOVER_BY_IP = 'discover_by_ip'
Can i use that option to configure the specific device and if so how?

**Comment by hakana** [comment]
Hi,

You need to enable multicast on UDP 224.0.1.187 port 5683 between VLANS, it using igmp to announce.

Br Håkan

Från: kasteleman <notifications@github.com>
Skickat: den 9 december 2019 08:37
Till: StyraHem/ShellyForHASS <ShellyForHASS@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [StyraHem/ShellyForHASS] Shelly devices on other vlan with pfsense (#113)


I'm using the plug-in and it works fine when al my devices are in the same vlan as HASSIO. But when i move the devices into a seperate vlan the plug-in does not discover them anymore. I'm aware of the proxy script, but can not use it and therefore looking for a method of implementing the same functionality on my pfsense box. Can anyone help me out on this one?

**Comment by hakana** [comment]
Hi,

Yes you can specify an array of ip addresses:

shelly:
  discover_by_ip:
    - '192.168.64.218'

Br Håkan

Från: kasteleman <notifications@github.com>
Skickat: den 9 december 2019 11:02
Till: StyraHem/ShellyForHASS <ShellyForHASS@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: Re: [StyraHem/ShellyForHASS] Shelly devices on other vlan with pfsense (#113)


Had a look at the latest commit 0.1.4 and found the option CONF_DISCOVER_BY_IP = 'discover_by_ip'
Can i use that option to configure the specific device and if so how?

**Comment by kasteleman** [comment]
Thx, enable multicast on UDP 224.0.1.187 and using discover_by_ip solved it. Only 1 small thing tho, when i switch the shelly 1 to on in HASSIO gui, the shelly 1 switches on but the switch in HASSIO switches back to off for half a min or so and then switches back to on again. Seems like the state isn't reported back immediately.

**Comment by hakana** [comment]
Your CoAP messages are not received by the plugin, therefore, you have a delay. It will also be a fix for this in the next release that forces a poll after an update.

**Comment by kasteleman** [comment]
Ok, so nothing i can do about that but wait until the next release? Any ETA?

**Comment by tintii** [comment]
HI @kasteleman 

could you describe in further detail what configuration you set on pfsense?

I'm in a very similar situation to you.

Cheers

**Comment by vistalba** [comment]
Does this setup also work with shelly H&T?

**Comment by kasteleman** [comment]
I did not solve it, but found a workaround by using the discover_by_ip
option and the scan_interval. Otherwise my devices aren’t discovered and
the status isn’t updated. So it is working, but not as I hoped for. I
suspect I do not have the right firewall and forward rules  applied.

Op za 4 jan. 2020 om 00:14 schreef vistalba <notifications@github.com>

**Comment by vistalba** [comment]
How does the proxy script work? 

Do I have to install this on the Gateway of the both  networks or just as a avM in the Shelly/iot VLAN?

**Comment by chemelli74** [comment]
@vistalba, documentation says:

Update the script with the ip-address of your HASS installation and r**un it on a computer/router etc that are connected to same nettwork as your Shellies**. Firewall and routing must be enabled, TCP 80 HASS -> Shelly and UDP 5683 Shelly -> HASS

Does this clarify your doubt ?

Simone

**Comment by vistalba** [comment]
@chemelli74 Not really. If the proxy node is only in shelly network, then it will also need some rules between proxy -> HASS?

**Comment by hakana** [comment]
Yes it need UDP 5683 from proxy -> HASS. It sending UDP direct to IP and is not using multicast.

**Comment by vistalba** [comment]
Okay... I suggest to add this to documentation:

Proxy has NIC only in Shelly network.

FW Rules:
Shelly's -> HASS udp 5683
Proxy -> Hass udp 5683
HASS -> Shelly tcp80

**Comment by chemelli74** [comment]
@vistalba, please confirm everything works in your use case so we can update the documentation accordly.

Simone

**Comment by pathia** [comment]
> 
> 
> Your CoAP messages are not received by the plugin, therefore, you have a delay. It will also be a fix for this in the next release that forces a poll after an update.

Is this fix already implemented in the latest release? It looks to me like it isn't. Thanks.

**Comment by chemelli74** [comment]
> Your CoAP messages are not received by the plugin, therefore, you have a delay. It will also be a fix for this in the next release that forces a poll after an update.
> 
> Is this fix already implemented in the latest release? It looks to me like it isn't. Thanks.

@pathia, did you test the proxy script ?

Simone

**Comment by pathia** [comment]
(not trying to hijack the thread!) 
Unfortunately not since I don't have a machine in my IoT vlan. 
Retrieving the current state after we send a command would make it sort of usable for me.

**Comment by chemelli74** [comment]
If you cannot test proxy script, I'm going to close this thread.

Simone

**Comment by pathia** [comment]
I understand what your saying, but I was only asking about the suggestion you did about polling the status immediately after a switch command. I don't want any linux machine in between these two vlans.

**Comment by chemelli74** [comment]
> I understand what your saying, but I was only asking about the suggestion you did about polling the status immediately after a switch command. I don't want any linux machine in between these two vlans.

Polling status after update is implemented.
If it doesn't work for you, please open a new issue after upgrading to 0.1.6 final release and atatch debug log.

Simone

**Comment by kasteleman** [comment]
Yes, finally got it working with pfsense. Keyword: IGMP Proxy
Configured IGMP Proxy with igmp enabled. On the LAN interface where HA runs a downstream type and on the other vlan (shelly devices vlan) a upstream type with network 224.0.1.187. 
Now in HA it shows discovery: CoAP-message and no delayed status update any more
