### ISSUE TITLE
Support for Transitions - Shelly Dimmer, Shelly RGBW2

### ISSUE THREAD

**Issue by Kranzy** [StyraHem/ShellyForHASS#114]
Hi, just wondering what is involved in adding support for transitions for the Dimmer and RGBW2?

I would like to be able to use this in automatons separate from the night mode built & transitions built into the stock firmware as when changing values in HA using node red the stock firmwares transition setting doesn't apply.

**Comment by chemelli74** [comment]
@Kranzy , can you retest with 0.1.6b7 and update to latest firmware 1.5.8 as well ?

Thank you,

Simone

**Comment by Kranzy** [comment]
Just tested with Dimmer on 1.5.8 and 0.1.6b7 and using transition in light.turn_on when changing from 10% brightness to 100% and transition had no effect.

**Comment by Kranzy** [comment]
no update for RGBW2 firmware yet.

**Comment by chemelli74** [comment]
> Just tested with Dimmer on 1.5.8 and 0.1.6b7 and using transition in light.turn_on when changing from 10% brightness to 100% and transition had no effect.

Thx for testing. Updated issue label.

Simone

**Comment by hakana** [comment]
I think I saw something about it should be supported by Shelly but when checking the Shelly API I can't find anything. Does anyone know if there is support for this?

**Comment by skeptizzle** [comment]
Just chiming in. 
It really is something that should be supported, I would really like to transition my ceiling lights in the bedroom in the morning.
I guess I will stick with Zigbee bulbs for now!

**Comment by SciTii** [comment]
any ideas how to solve that problem? I would really like to have transition without creating super complicated automations in node red

**Comment by chemelli74** [comment]
> I think I saw something about it should be supported by Shelly but when checking the Shelly API I can't find anything. Does anyone know if there is support for this?

Cannot find documentation reference anywere :-(

Simone

**Comment by Kranzy** [comment]
Does the latest firmware supporting transition between brightness allow us access to use the transition function in Home Assistant now??

`Dear all. Firmware 1.6 are released. Your devices will offer you update up to 2 hours. 

Exclusions: 
Shelly4pro and Door Sensor will receive update in few days. 


Log changes:

New features: 

•	Shelly3EM - MQTT Energy topics 

•	Shelly DUO&Vintage Actions 

•	Dimmer activation switch 

•	Dimmer managable debounce

•	Shelly1/PM temperature ADD-ON format F/C 

•	Shelly Flood Actions 

•	Shelly Dimmer toggle command over MQTT 

•	Disable Factory reset from the switch 

•	Device is owned from someone flag

•	Disable long push to switch on relay

•	DHT22 - support for Shelly1/PM Add-on

•	Internal Temepratyre and Humidity actions for Shelly1/PM Add-on

•	MQTT for external sensors Shelly1/PM Add-on

•	Countdown timer in WebUi

•	Dimmer - transition time is valid when brightness is changed. 



Fixes:

•	Shelly 2.5 Roller Mode: Coap description incorrect

•	Shelly Plug-S: Coap description incorrect

•	Dimmer - Factory reset from Button is not correct 

•	Shelly1 Duo - color temperature is not correct

•	Shelly Duo&Vinatge CoAP missing

•	Backup Wi-Fi do not work with fixed IP 

•	Dimmer - night mode do not report to the cloud

•	Not correct cloud On/Off status

•	Default settings must be unchanched after OTA

•	HT - MQTT - temeperature offset not correct

•	Shelly Dimmer - No brightness status update when changing brightness from switch

•	Shelly 2.5 Coap - device/relay description link not correct

•	Add "Timer" on status

•	H&T - offset missing in REST (Json)

•	MQTT still no on/off report for Light contollers.

•	Shelly Sense Coap: device description broken

•	Duplicate Serial even different content of Coap Update

•	Coap sensors updates include all sensor values

•	Shelly RGBW2 / 1PM Coap description broken

•	Shelly Bulb Coap description broken

•	Fix dimmer schedules to enable transition to on and off state

•	Power on default - does not trigger Actions and AutoOff `

**Comment by hakana** [comment]
Transition is not supported as Shelly devices not supporting it. I will check if I can find a solution later but it does not have highest priority.

**Comment by Kranzy** [comment]
Is that including the 1.6 firmware. One of the new features is `Dimmer - transition time is valid when brightness is changed.`

**Comment by hakana** [comment]
I have not checked that jet, but if it is supported for dimmer it is very nice

**Comment by chemelli74** [comment]
> Is that including the 1.6 firmware. One of the new features is `Dimmer - transition time is valid when brightness is changed.`

No reference in official updated API docs.
Sorry.

Closing this issue as "missing in firmware". When and if this feature will be implemented, a new issue can be opened to add support in this plugin.

Simone

**Comment by fyksen** [comment]
Any news on this?

**Comment by skeptizzle** [comment]
> Any news on this?

Check the firmware. As far as I know it's still not a feature.

**Comment by gfduszynski** [comment]
Looks like version 1.9.0 now supports transition
https://shelly-api-docs.shelly.cloud/#changelog

**Comment by richRubie** [comment]
@gfduszynski i believe this is just for adjusting the global setting.
I think we need it on a per action basis.

So we can set it globally here
https://shelly-api-docs.shelly.cloud/#shelly-dimmer-sl-settings
But we need it here
https://shelly-api-docs.shelly.cloud/#shelly-dimmer-sl-light-0

**Comment by chemelli74** [comment]
> @gfduszynski i believe this is just for adjusting the global setting.
> I think we need it on a per action basis.
> 
> So we can set it globally here
> https://shelly-api-docs.shelly.cloud/#shelly-dimmer-sl-settings
> But we need it here
> https://shelly-api-docs.shelly.cloud/#shelly-dimmer-sl-light-0

You are right, would be cleaner.
But anyway there is only 1 light per dimmer ;-)

Simone

**Comment by gfduszynski** [comment]
@richRubie You are right, I've got too optimistic while reading change log :)

**Comment by richRubie** [comment]
@chemelli74 
I don't want to highjack a closed issue, so tell me if there is a more appropriate channel.

The use case I have is:
I have a shelly dimmer with a standard on/off light switch. When i flick it on or off i want it to come on straight away (maybe over 1-2 secs) . This is where the global variable is used.
What i also want to do is have the light turn from 10 => 100% over a period of time.

I have no idea the best way to do this, do you have suggestions?

**Comment by ndcoxhead** [comment]
Is this not what is needed ? (under parameters) from **https://shelly-api-docs.shelly.cloud/#shelly-dimmer-1-2**

transition | number | Transition time for on/off: 0..5000 ms
fade_rate | number | Brightness change speed when button is pressed: 1..5
