### ISSUE TITLE
Devices not located if no internet connection is available

### ISSUE THREAD

**Issue by notrix** [StyraHem/ShellyForHASS#116]
I have raspberry PI and shelly 1 connected to each other via wifi and no internet connection is available. If I plug in internet cable to rpi - homeassistant detects shelly1 and then I can disconnect cable. That way everything works fine. But if I start homeassistant with no internet - shelly devices are shown as not available.

My ques is that component is trying to access shelly cloud, but fails to create socket.

There is error in log:
`Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 176, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/shelly/__init__.py", line 359, in setup
    pys.open()
  File "/srv/homeassistant/lib/python3.7/site-packages/pyShelly/__init__.py", line 100, in open
    self._coap.start()
  File "/srv/homeassistant/lib/python3.7/site-packages/pyShelly/coap.py", line 29, in start
    self._init_socket()
  File "/srv/homeassistant/lib/python3.7/site-packages/pyShelly/coap.py", line 45, in _init_socket
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
OSError: [Errno 19] No such device
`

**Comment by hakana** [comment]
Try the igmp_fix and see if that help. Connection to cloud will be in a loop so it is not a problem it fail first time.

**Comment by notrix** [comment]
Hi @hakana, I have tested configuration with igmp_fix turned on and it had no impact. Same error is seen in logs.

```yaml
shelly:
  igmp_fix: true

**Comment by chemelli74** [comment]
@notrix , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by chemelli74** [comment]
Since 0.1.6b7 there is a new configuration parameter:

`host_ip`

 So you can specify the network interface.
Please try and report back.

Thank you,

Simone

**Comment by notrix** [comment]
I have upgraded firmware to v1.5.9
Updated shelly component to 0.1.6b7

And it works! `host_ip` did the trick

Thank you!
