### ISSUE TITLE
Udating does not change from 0.1.1 to 0.1.5

### ISSUE THREAD

**Issue by suds32** [StyraHem/ShellyForHASS#118]
Installed  and updated via HACs but it will not update to 0.1.5, says still on 0.1.1.
Also get cloud service error 
Invalid config for [shelly]: [cloud_auth_key] is an invalid option for [shelly]. Check: shelly->shelly->cloud_auth_key. (See /config/configuration.yaml, line 63). Please check the docs at https://home-assistant.io/integrations/shelly/
Which implies ti has not updated so did in manually and get the same error.
when you look at the /config/custom_components/shelly/init.py it shows version = “0.1.5”

**Comment by hakana** [comment]
Have you restarted HASS?

**Comment by Misiu** [comment]
@suds32 is this still an issue?

**Comment by hakana** [comment]
@Misiu , Thanks helping clean up!

**Comment by chemelli74** [comment]
@suds32, , can you please retest with 0.1.6b6 ? Please post your configuration.yaml as well.

Thank you,

Simone

**Comment by suds32** [comment]
All good now thanks

**Comment by Misiu** [comment]
@suds32 if everything works please close this issue. Thanks

**Comment by suds32** [comment]
all sorted
