### ISSUE TITLE
Status delay

### ISSUE THREAD

**Issue by nickmaleao** [StyraHem/ShellyForHASS#120]
Home Assistant 0.103.0
Shelly smart home 0.1.5
Shelly1 firm: V1.5.6

Hi,

I just started using this addon , followed all the instructions and got all the shellys automaticaly imported on ha.

But after some tests of trying to turn off/on some switches i noticed that there is a delay on the status update of the entity.

I did a trace in wireshark on the hassio vm and noticed that that status of the entity only gets updated when there is a status HTTP get message, although the multicast coap messages are received.

It's this normal behavior? or can i do something to get a faster status update?

[Pcap](https://drive.google.com/file/d/1LE_sG0btvbYETP_lPWd5-c_BSbxq-HYj/view?usp=sharing)

Best regards.

**Comment by hakana** [comment]
The plugin uses two methods to get status, CoAP and Http poll. When CoAP not working you get a delay, you can change the poll interval by the setting, scan_interval in config.yaml. But if you can get CoAP working in your network it is the best way.

**Comment by nickmaleao** [comment]
I've done some more tests and have found a fix if i a change the gateway.

Currently in the vm i have 2 interfaces:

eth0 192.168.1.11/24 (LAN_NETWORK)
eth0.11(vlan11) 192.68.11.1/24 (IOT_NETWORK)

The default gateway 192.168.1.1 is associated with the network 192.168.1.11/24 (LAN_NETWORK), although i can receive the multicast packets (224.0.1.187.5683) as seen in tcpdump it seems the packets don't arrive at Shellypy.

Does anyone know if there is any problem using two different interfaces on the same host with docker/Shellypy.

**Comment by gieljnssns** [comment]
I'm also seeing a status delay.
I have 4 Shelly plugs (no status delay)
And I have 8 Shelly 2.5 's (status delay 1min)
The funny thing is, when I restart  HA there is no status delay for any device, but after some time only the Shelly switches are having a delay.
This is my config:
```
###  Shelly  ###
shelly:
```

When I change to: 
```
###  Shelly  ###
shelly:
  discover_by_ip:
    - '192.168.79.61'
    - '192.168.79.62'
    - '192.168.79.63'
    - '192.168.79.64'
    - '192.168.79.65'
    - '192.168.79.66'
    - '192.168.79.67'
    - '192.168.79.68'
    - '192.168.79.69'
    - '192.168.79.70'
    - '192.168.79.71'
    - '192.168.79.72'
```
I'm seeing just the same, no delay at start and after some time...
My shellys's are having fixed ip from router

and when I change to
```
###  Shelly  ###
shelly:
  discovery: true
  scan_interval: 10
```
I'm having no delay at start and after some time a delay of 10sec.

**Comment by gieljnssns** [comment]
@nickmaleao 
Where did you change the gateway?

**Comment by hakana** [comment]
Try igmp_fix flag

**Comment by gieljnssns** [comment]
> Try igmp_fix flag

So like tis?
```
###  Shelly  ###
shelly:
  discovery: true
  igmp_fix: true
```

**Comment by nickmaleao** [comment]
> @nickmaleao
> Where did you change the gateway?

I've change it on the vm, for now i only have one network interface in the hassio vm and everything is working fine.

It seems that a multicast group can only be binded to a single interface, maybe with network namespaces it could be possible to use multiple interfaces but that would require some programming skills.

https://stackoverflow.com/questions/11234671/multiple-multicast-on-multiple-interfaces.

I will close this issue for now, tks for the help.

**Comment by hakana** [comment]
I will add host_ip in next release so you can specify interface.
