### ISSUE TITLE
0.1.5 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by TASSDevon** [StyraHem/ShellyForHASS#121]
I've recently updated to v0.1.5 and I noticed this error this morning:

```
Error receiving CoAP UDP, 'charmap' codec can't decode byte 0x90 in position 538: character maps to <undefined>, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 157, in _loop
    payload = s(data[pos + 1:])
  File "/usr/local/lib/python3.7/site-packages/pyShelly/compat.py", line 23, in s
    return str(x, 'cp1252')
  File "/usr/local/lib/python3.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 538: character maps to <undefined>

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 157, in _loop
    payload = s(data[pos + 1:])
  File "/usr/local/lib/python3.7/site-packages/pyShelly/compat.py", line 23, in s
    return str(x, 'cp1252')
  File "/usr/local/lib/python3.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 538: character maps to <undefined>

```

I've never gotten this error before, I have 3 Shelly 2.5 in roller shutter mode. They all still seem to work fine though. 

Any thoughts?

**Comment by genem2** [comment]
Likewise. Just started today. HA 0.103.4

**Comment by hakana** [comment]
Thanks, it got CoAP message from some other device, need to add length check of message to avoid this.

**Comment by Stefan300381** [comment]
the same?

`2020-01-16 20:07:47 ERROR (CoAP) [pyShelly] Error receiving CoAP UDP, 'charmap' codec can't decode byte 0x8d in position 158: character maps to <undefined>, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 165, in _loop
    payload = s(data[pos + 1:])
  File "/usr/local/lib/python3.7/site-packages/pyShelly/compat.py", line 23, in s
    return str(x, 'cp1252')
  File "/usr/local/lib/python3.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 158: character maps to <undefined>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 165, in _loop
    payload = s(data[pos + 1:])
  File "/usr/local/lib/python3.7/site-packages/pyShelly/compat.py", line 23, in s
    return str(x, 'cp1252')
  File "/usr/local/lib/python3.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 158: character maps to <undefined>`

**Comment by chemelli74** [comment]
@Stefan300381 , which version of the plugin are you running ?

Simone

**Comment by Stefan300381** [comment]
@chemelli74 
meanwhile 0.16 beta 6
but still such messages in the log:

```
2020-01-21 13:19:20 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/report_state.py", line 45, in async_entity_state_listener
    if entity_data == old_entity.query_serialize():
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 442, in query_serialize
    deep_update(attrs, trt.query_attributes())
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/trait.py", line 1288, in query_attributes
    ERR_NOT_SUPPORTED, "Querying state is not supported"
```

**Comment by chemelli74** [comment]
@Stefan300381 can you please enable debug log for pyshelly ?
Which version of HA are you running ?

Thank you

Simone

**Comment by chemelli74** [comment]
Seems it's a decoding issue based on the default code page used by your Python installation: https://stackoverflow.com/a/58771838

Will ask author if CP can be forced by code.

Simone

**Comment by Stefan300381** [comment]
@chemelli74 

docker container 0.104.0

**Comment by chemelli74** [comment]
@Stefan300381 please share debug log.

Thank you

Simone

**Comment by Stefan300381** [comment]
I'm new to hass, can you explain how to enable debug log in the docker container?

**Comment by chemelli74** [comment]
> I'm new to hass, can you explain how to enable debug log in the docker container?

Open docker->container->homeassistant->details->terminal->bash

Then edit /config/configuration.yaml adding those lines:

```
logger:                                                                                                                                                                                                     
  default: warn                                                                                                                                                                                             
  logs:                                                                                                                                                                                                                                                                                                                                                          
      pyShelly: debug   
```

Simone

**Comment by chemelli74** [comment]
@TASSDevon, can you update to latest beta9, HomeAssistant 0.104.0 or newer, and latest firmware ?

Simone

**Comment by chemelli74** [comment]
@Stefan300381, can you upgrade to 0.1.6 final and add 

```
attributes:
  - payload
```

to your configuration ?
Then post log so we can see the offending CoAP message.

Simone

**Comment by TASSDevon** [comment]
@chemelli74 Sorry, didn't see your mention. I'll let you know when I see the message pass by as well.

**Comment by chemelli74** [comment]
> @chemelli74 Sorry, didn't see your mention. I'll let you know when I see the message pass by as well.

Any update ?

Simone

**Comment by TASSDevon** [comment]
No, haven't seen the error yet.

**Comment by chemelli74** [comment]
> No, haven't seen the error yet.

Since how many days ?

**Comment by TASSDevon** [comment]
Quite a while, the error didn't pop up very often, sorry I can't be of more help at the moment, I also have no clue which device other than the Shelly ones is using CoAP on my network.

**Comment by chemelli74** [comment]
Goign to close the issue, if youo have problem in future feel free to open a new one.
