### ISSUE TITLE
WARNING (Poll) [pyShelly] Error, 401 Unauthorized

### ISSUE THREAD

**Issue by paparapapapapa** [StyraHem/ShellyForHASS#123]
Hi there, I'm setting up my HASS system and I came across this component. For the time being I just have one Shelly1 wired to a light; discovery found it but it is always unavailable in HASS. I tried the announce automation that works for many people but no success. Shelly web interface works 100% tho. I have no cloud set up.
Also, it doesn't work anymore via MQTT (Mosquitto).

Now, this was just a premise, maybe my error has to do with that, maybe not. Please help me understand.

HASS logs:

> Error, 401 Unauthorized
9:05 AM /srv/homeassistant/lib/python3.7/site-packages/pyShelly/utils.py (WARNING) - message first occured at 9:04 AM and shows up 2 times

> 2019-12-18 09:04:39 WARNING (Thread-6) [pyShelly] Error, 401 Unauthorized
2019-12-18 09:05:29 WARNING (Poll) [pyShelly] Error, 401 Unauthorized
2019-12-18 09:05:39 WARNING (Thread-12) [pyShelly] Error, 401 Unauthorized
2019-12-18 09:06:29 WARNING (Poll) [pyShelly] Error, 401 Unauthorized
2019-12-18 09:06:39 WARNING (Thread-13) [pyShelly] Error, 401 Unauthorized
And it goes on and on...

I know nothing about python syntax, here it is utils.py:

`  GNU nano 3.2                                            utils.py                                                       

    res = ""
    success = False
    conn = None
    try:
        LOGGER.debug("http://%s%s", host, url)
        conn = httplib.HTTPConnection(host, timeout=5)
        headers = {}
        if username is not None \
            and password is not None:
            combo = '%s:%s' % (username, password)
            auth = s(
                base64.b64encode(combo.encode()))  # .replace('\n', '')
            headers["Authorization"] = "Basic %s" % auth
        conn.request("GET", url, None, headers)
        resp = conn.getresponse()

        if resp.status == 200:
            body = resp.read()
            #LOGGER.debug("Body: %s", body)
            res = json.loads(s(body))
            success = True
            LOGGER.debug("http://%s%s - Ok", host, url)
        else:
            res = "Error, " + str(resp.status) \
                            + ' ' + str(resp.reason)
            LOGGER.warning(res)
    except Exception as ex:
        success = False
        res = str(ex)
        if log_error:
            exception_log(ex, "Error http GET: http://{}{}", host, url)
        else:
            LOGGER.warning(
                "Fail http GET: %s %s %s", host, url, ex)
    finally:
        if conn:
            conn.close()

    return success, res

`

Any help would be much appreciated! Thank you

**Comment by hakana** [comment]
Look like you have restricted login enabled on Shelly, you need to specify the same user and password in config.yaml.

**Comment by paparapapapapa** [comment]
This was the issue thank you. It worked adding:

```
shelly:
  username: xxx
  password: xxx
```

but then I unrestricted the login :)

Current config.yaml has: 

```
shelly:
  devices:
    - id: "76A154"
      light_switch: true
      name: Luce esterna stanzino
```

Now it works but the toggle switch on HASS return to "off" position after about 3 seconds with the light still on. So to turn the light back off I have to toggle the soft switch back on and then off quickly. I tried all the "button type" settings but behavior doesn't change. 
Shelly web interface works ok.

Any guess?
Thank you

**Comment by hakana** [comment]
If you wait for a minute will it get right status then?

**Comment by paparapapapapa** [comment]
Yes it does. 
In the history graph the light appears unavailable for a minute when it behave like this.

**Comment by chemelli74** [comment]
@paparapapapapa , you still have this issue with 0.1.6b6 ?

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by paparapapapapa** [comment]
Hi Simone, I’m sorry I’m sometimes so fickle a community member.
Turned out it was the new text editor I installed on my iPhone that was changing all the simple single and double quotes with the angled ones.
A simple “find and replace” on all my yamls fixed this issue and others.
Thank you.
