### ISSUE TITLE
brighness setting on shelly dimmer from HA

### ISSUE THREAD

**Issue by mamrai1** [StyraHem/ShellyForHASS#124]
when calling service light.turn_on the 100% brightness on shelly dimmer is 255?:
e.g.
entity_id: 
  - light.shelly_shdm_1_xxxxx
brightness:  255
sets the birghtness to full and 
entity_id: 
  - light.shelly_shdm_1_xxxxx
brightness:  100
sets the brightness to 39%..

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
