### ISSUE TITLE
 404 error on pyShelly scripts

### ISSUE THREAD

**Issue by Engelbert** [StyraHem/ShellyForHASS#126]
- fresh hassio install on a pi 3b+
- updated to latest version

- discovery works
- status is found correctly
- can not use device from hassio though

```
Error, 404 Not Found
5:21 PM custom_components/shelly/cover.py (WARNING)
```

**Comment by hakana** [comment]
Hassio cant access the url of the Shelly device, do you have firewall not allowing this?

**Comment by floge77** [comment]
Hi @hakana,

I would like to re-open the issue as I experience exactly the same problem and I do not know how to further proceed.

I have a shelly1 running and accessible at 192.168.178.71 in my local network.
I can access the web ui via my notebook, as well as when I ssh into homeassistant and curl the ip address.

configuration.yaml looks like:
```yaml
shelly:
  discover_by_ip:
    - '192.168.178.71'
```
I installed via hacs and run on version 0.16. hassio is running on version 0.105.4.

When I configure only `shelly:` in my configuration.yaml I get no log at all wrt. to shelly, but also no entities in the shelly integration on hassio.
