### ISSUE TITLE
is this still working with home assistant?

### ISSUE THREAD

**Issue by aristosv** [StyraHem/ShellyForHASS#127]
I am using home assistant version 0.102.3. As per the instructions, I created a "shelly" folder under "custom_components" and copied the 5 .py files in there. I then added "shelly:" in configuration.yaml.

When I check the config, I get a message saying "Component error: shelly - Integration 'shelly' not found."

**Comment by hakana** [comment]
Sounds like you have errors in the permission for the files or something like that.

I recommend you to use HACS to install plugins easily.

**Comment by aristosv** [comment]
I don't have HACS. I am running HA in docker. What are the correct permissions for this to work?

**Comment by hakana** [comment]
I can't help with this. This is not an issue of this plugin.

Please install HACS and it will take care of setting up it correctly.
