### ISSUE TITLE
Add Shellies to Zones

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#129]
Is there a way to assign a shelly device to a specific 'zone' in HASS?

I want to be able to group them in rooms just like I can with devices.
The Shelly switches only show up in the list of entities. 
I don't seem to be able to set a zone for an entity...

**Comment by hakana** [comment]
I will try to fix this in next release

**Comment by hakana** [comment]
Fixed in 0.1.6.b4

**Comment by chemelli74** [comment]
Hi,

should I find the devices in zones under configuration->integrations->Shelly for home automatically ?
here it's not the case:

![image](https://user-images.githubusercontent.com/57354320/72482269-6b058980-37fd-11ea-8dea-cc580ceef723.png)

Simone

**Comment by hakana** [comment]
You can set the zone for each device for your self.

I don't understand your question?

**Comment by chemelli74** [comment]
> You can set the zone for each device for your self.

Sorry, I misunderstood. I was expecting the plugin to get automatically Area from Cloud.

Simone

**Comment by hakana** [comment]
Yes, I will probably add a setting for this and create areas for each room.

**Comment by filmgarage** [comment]
Cool. This works fine for me. However, I do not see the manufacturer and model info in the device list (not very important but can be useful at times...)
I must say that the term ‘ZONE’ is a bit confusing for me. I don’t understand the logic of Home Assistant. I guess ‘ROOM’ would be a better description. (I am aware that you can’t change that. ;-)
If you decide to synchronize with the Shelly App I suggest you synchronize using the ‘rooms’ assigned in the app. 
I am a big fan of the logic of Apple’s ‘Home App’. Apple organizes devices in rooms. Each room can be assigned to more than one zone for floor levels or type or other custom value. I wish HA would adapt to this standard.
