### ISSUE TITLE
Over power sensor doesn't get the "friendly name"

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#131]
Hi,

I think the image says all:

![2019-12-30 18_10_52-Window](https://user-images.githubusercontent.com/57354320/71592983-75076700-2b32-11ea-96e9-f81c10ea0f94.png)

Thank you,

Simone

**Comment by hakana** [comment]
Please, check if this working in 0.1.6.b4

**Comment by chemelli74** [comment]
Using 0.1.6b6 seems it over power is completly missing:

![image](https://user-images.githubusercontent.com/57354320/72477461-dd6f6d00-37ef-11ea-9d9b-e05055ecabd5.png)

Simone

**Comment by chemelli74** [comment]
See also #146 

Simone

**Comment by chemelli74** [comment]
Fixed using 0.1.6b8
