### ISSUE TITLE
Incosistent status between sensor and switch

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#134]
Hi,

I just noticed that I have a issue with ch2 of my shelly2.5.
Status in not consistent based on that of the switch (and this is the right one):

![image](https://user-images.githubusercontent.com/57354320/71683812-ded27b80-2d93-11ea-8297-2b291c83b0cf.png)

vs

![image](https://user-images.githubusercontent.com/57354320/71683821-e4c85c80-2d93-11ea-8f68-760e75bf0d57.png)

Thx for investigating,

Simone

**Comment by hakana** [comment]
The top show the state of relay (light) and the below of the actual switch. So they can be different.

**Comment by chemelli74** [comment]
> The top show the state of relay (light) and the below of the actual switch. So they can be different.

@hakana, thank you for the explanation. Now that I read it, was so obvious.

Simone
