### ISSUE TITLE
double click on momentary switch 1 of shelly dimmer

### ISSUE THREAD

**Issue by carameljm** [StyraHem/ShellyForHASS#135]
On a Shelly dimmer, I cannot seem to get double click to work as a trigger in Hassio (with a momentary switch 1 of shelly dimmer)
Is this because of the device?
It seems like the "sensor.shelly_shsw_1_xxxxxx_1_switch" updates too slow.

**Comment by carameljm** [comment]
I think double click is already a predefined action on the shelly dimmer, which turns on the light at full brightness.

**Comment by jacha05** [comment]
Yes the shelly does not support this, unclear if it ever will? But you can build your own logic with this via mqtt and nodered/appdeamon

**Comment by hakana** [comment]
Have you checked the click event, see read.me file.
