### ISSUE TITLE
Shelly offline: Client exceeded max pending messages

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#138]
Hi,

when one or more Shelly devices are offline, after a few hours you get the following message in HA log:

`2020-01-08 10:32:03 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140226542307664] Client exceeded max pending messages [2]: 512`

I suggest to add a smaller timeout to http connection so that they close faster.

Simone

**Comment by hakana** [comment]
If I add smaller than 5 sec we got problems with time-out so that is not a good solution. What scan interval are you using and how many devices.

**Comment by chemelli74** [comment]
> If I add smaller than 5 sec we got problems with time-out so that is not a good solution. What scan interval are you using and how many devices.

Humm, is already quite small; you are right.
The bad is that in such situation I end up with so many pending connections that the timeout seems to non work correctly.
Can you please recheck ?

Thx,

Simone

**Comment by hakana** [comment]
On what HW and OS are you running?

**Comment by hakana** [comment]
Can you run netstat on HA machine and see what the status of the connections are?

**Comment by chemelli74** [comment]
> On what HW and OS are you running?

Docker on Synology 

Simone

**Comment by hakana** [comment]
Can you do a netstat on it?

**Comment by chemelli74** [comment]
Hi, current situation with a lot of TIME_WAIT but so far is all working. I bet that when ShellyForHASS report the issue, there would be a lot more unfinished sessions:

![image](https://user-images.githubusercontent.com/57354320/72517946-8c459480-3854-11ea-94c2-a46c152b27cd.png)


Simone

**Comment by chemelli74** [comment]
Hi,

after upgrading HA from 0.103.0 to 0.104.1 I cannot see the issue anymore.
Since more than 4 days are passed, I close the issue.

Simone

**Comment by johntdyer** [comment]
I think this is the same issue I am seeing in #164
