### ISSUE TITLE
[Feature request] Add support for new devices

### ISSUE THREAD

**Issue by Misiu** [StyraHem/ShellyForHASS#139]
This integration is already awesome (it should be listed on Shelly page!), but Shelly is adding new devices to its family, so if you find the time please add support for them:

~~- Temperature Sensor Addon for Shelly 1/1PM~~
- Shelly 3EM
- Shelly Duo
- Shelly Vintage A60
- Shelly Vintage ST64
- Shelly Vintage G125

**Comment by mattia480** [comment]
If possible it would be useful to add also the new Shelly Door/Window Sensor (SHDW-1) [Product](https://shop.shelly.cloud/shelly-door-window-wifi-smart-home-automation#63)

**Comment by hakana** [comment]
Temp addon and Door/Window added, I will add more when I receive them

**Comment by Misiu** [comment]
@hakana thank you for the update! I'm still waiting for Shelly 1 Addon's, so I'll test them as soon as they arrive! Shelly Duo is also on the way, so I can help with testing it.

**Comment by thundergreen** [comment]
I'm interested in the vintage bulb. Once u 5ested it could you please add it ?

**Comment by emilp333** [comment]
Any information when Shelly 3EM might be supported?
I have one installed if you need any information. 

Keep it up!

**Comment by chemelli74** [comment]
What if we open a thread for each device "family" so we can close each once integrated ?

Simone

**Comment by chemelli74** [comment]
Individual issue for each family opened: #191 and #195.
Closing.

Simone
