### ISSUE TITLE
Cannot discover devices on another NAT

### ISSUE THREAD

**Issue by vdiogo** [StyraHem/ShellyForHASS#141]
I have all my Shelly devices in a NAT (Google WiFi) and Raspberry PI on another NAT (home
Router) and tried discovery using IP on config.yaml and no luck. I don’t want to use port forwarding for security reasons and can’t have a script running on some server to bypass the proxy.

**Comment by vistalba** [comment]
How do you think that the device should communicate if you don't want to use port-forward/access rules or a proxy?

This is not possible.

**Comment by hakana** [comment]
I will add status update from the cloud later, maybe that is a way for you if the devices are in Shelly cloud? I will close this issue as it is not an issue with the plugin.
