### ISSUE TITLE
Host is unreachable

### ISSUE THREAD

**Issue by mickaelmarin** [StyraHem/ShellyForHASS#145]
Hi,

I use shellyforhass for control of my cover and dimmer, but I also have Shelly H&T configured with mqtt (shelly H&T wakeup only to send temp and Hum and the rest of the time is down).

I discover my shelly2.5 and dimmer by IP my conf is:

shelly:
    discover_by_ip:
    - '192.168.1.99'   # dimmer
    - '192.168.1.102'  # cover
    - '192.168.1.103'  # cover
    - '192.168.1.104'  # cover
    - '192.168.1.105'  # cover

It is possible to add param that disable the discover of specific IP ?

Thanks for your good job on this integration, it work very well with my dimmer and cover.

Mickael

**Comment by hakana** [comment]
No, why do you want that?
You can disable discovery and mdns, then no other devices then specified will be discovered.

**Comment by mickaelmarin** [comment]
I tested with this param:

FYI my shelly H&T IP is 192.168.1.100

For covers and dimmer I configured as below and restart Home Assistant:

shelly:
  mdns: false
  discovery: true
  discover_by_ip:
    - '192.168.1.99'  #dimmer
    - '192.168.1.102' #cover1
    - '192.168.1.103'  #cover2
    - '192.168.1.104'   #cover3
    - '192.168.1.105'   #cover4

When the shelly H&T send the temp and hum to mqtt broker , after that I have "Host is unreachable" every minutes in my log.

thanks

**Comment by hakana** [comment]
What version do you use of ShellyForHass?

**Comment by mickaelmarin** [comment]
I use 0.1.6.b3 (I look in __init__.py,  __version__ = "0.1.6.b3"

**Comment by hakana** [comment]
Ok, then you have something that is not an official release, b3 was only for internal testing. Try the latest release 0.1.6.b5.

https://github.com/StyraHem/ShellyForHASS/releases

**Comment by mickaelmarin** [comment]
I downloaded and  replace by the new version. No host unreacheble anymore but I have this

Wed Jan 15 2020 17:52:11 GMT+0100 (heure normale d’Europe centrale)
Error update loop, local variable 'block' referenced before assignment, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 228, in _update_loop
    self.check_by_ip()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 170, in check_by_ip
    if block in self.blocks:
UnboundLocalError: local variable 'block' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 228, in _update_loop
    self.check_by_ip()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 170, in check_by_ip
    if block in self.blocks:
UnboundLocalError: local variable 'block' referenced before assignment

**Comment by hakana** [comment]
Fixed in Beta 6
