### ISSUE TITLE
Shelly 2.5 with extra "-1" in switch name

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#151]
Hi,

moving from 0.1.5 to 0.1.6.b6 added a "-1" to Shelly 2.5 in switch mode:

![image](https://user-images.githubusercontent.com/57354320/72483125-3cd57900-3800-11ea-8795-495b01fe825e.png)

Simone

**Comment by hakana** [comment]
Will be fixed in beta 7

**Comment by chemelli74** [comment]
Confirm fixed in 0.1.6.b7

Thank you,

Simone
