### ISSUE TITLE
[Feature request] No voltage sensor on Shelly EM

### ISSUE THREAD

**Issue by faberix76** [StyraHem/ShellyForHASS#152]
Hello, i can't find any dscovered sensor for main power voltage  from the shelly EM. Is there any manual configuration to enable it?
Regards.

**Comment by hakana** [comment]
Voltage is not supported right now, I change this to a [Feature request]

**Comment by herik63** [comment]
Many thanks for the support!

**Comment by faberix76** [comment]
Thanks!!!

**Comment by hakana** [comment]
Close this because it is included in #181
