### ISSUE TITLE
Use "serial" attribute to limit DB entries

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#154]
Hi,

based on a very quick check of the code, seems that shelly_http_get() always store the answer in the DB.
I would propose to store and check the "serial" attribute to validate if something changed; if not data pulled should be discarded and not stored in the DB.

The smaller the DB of HA is the better it works (history, logbook, restart, etc.).

Simone

**Comment by hakana** [comment]
The serial updates often so that will not change anything. I think the problem is the uptime counter, maybe we should drop that. But the best is if we analyze what is written to the database and when.

**Comment by chemelli74** [comment]
Hi,

seems serial change only if a real value/status change not if the only change is the uptime.
Can you verify if this is the case also on your side ?

Thank you,

Simone

**Comment by hakana** [comment]
I don't know what trigged the serial but when I did a relead of status page the serial update every 5 sec. Maybe it was because of power change or simular.

**Comment by chemelli74** [comment]
Seems "serial" is not available for REST api; will be implemented in future releases.

We should think about #165 to limit DB entries.

Simone
