### ISSUE TITLE
Cover in integration

### ISSUE THREAD

**Issue by rogervdf** [StyraHem/ShellyForHASS#156]
On current pre-release, activating a scene through the integration on a cover gives:

Failed to call service scene/turn_on. value must be at most 100 for dictionary value @ data['position']

**Comment by chemelli74** [comment]
@rogervdf , can you post your configuration.yaml, log file and screenshot of the lovelace UI ?

Thank you,

Simone

**Comment by rogervdf** [comment]
So all devices are now on 1.5.9, and I updated to beta 7, same issue though. I'm guessing it's trying to set the wrong data type.

Here is the log. The rest is all vanilla. 
[home-assistant.log](https://github.com/StyraHem/ShellyForHASS/files/4101942/home-assistant.log)

**Comment by chemelli74** [comment]
@rogervdf, I don't see any line refering to this plugin. Can you please enable debug log for "pyShelly" ?

Thank you,

Simone

**Comment by rogervdf** [comment]
Ok Simone, here is a log with debug enabled
[home-assistant.log](https://github.com/StyraHem/ShellyForHASS/files/4102627/home-assistant.log)

**Comment by chemelli74** [comment]
> Ok Simone, here is a log with debug enabled
> home-assistant.log

@rogervdf, I noticed a couple of things:

- since 10:41, when pyShelly debug starts, no errors recorded
- roomba integration has configuraiton issues

Can you please disable roomba integration and restart HA? Such action will clean the log and start over.

Thank you,

Simone

**Comment by rogervdf** [comment]
Roomba does not have integration issues. Instead, it has a limitation of one user at the same time, so sometimes it errors out.

Error is still the same on roller shutter:
Failed to call service scene/turn_on. value must be at most 100 for dictionary value @ data['position']

Activating a scene does work though for a Shelly dimmer
[home-assistant.log](https://github.com/StyraHem/ShellyForHASS/files/4104014/home-assistant.log)

Here is a clean log, thanks for looking into it Simone!

**Comment by chemelli74** [comment]
@rogervdf, what if you go in HA->developer tools -> states and look for the Shelly entity.
I'm interested in the value of "position"; I bet you'll find 101 or 102.

Thank you,

Simone

**Comment by rogervdf** [comment]
I opened one roller shutter and closed the other. The value in position is fluctuating. Most of the time it's -1. The one that I opened shows 107 or 101 occasionally.

**Comment by chemelli74** [comment]
> I opened one roller shutter and closed the other. The value in position is fluctuating. Most of the time it's -1. The one that I opened shows 107 or 101 occasionally.

Was expecting something similar :-(
I think you found a firmware bug as the value should be between 0 and 100 like all percentages.

Can you post on [https://www.facebook.com/groups/ShellyIoTCommunitySupport/](url) and tag "Dimitar Dimitrov" ?

Thank you,

Simone

**Comment by rogervdf** [comment]
Hi Simone,

So good news, I can confirm the problem is not on your end. The issue seems to be on the calibration. I have two roller shutters, in one case the calibration leads to good results and then the scene works. In the other case the calibration completes but without the desired outcome values in the embedded system. As such you can consider this 'fixed' on your end!

Thanks,
Roger

**Comment by chemelli74** [comment]
From Shelly development:

```
#define RC_POS_NOT_CALIBRATED 101
#define RC_RESULT_MAXTIME_OPEN1 102
#define RC_RESULT_MAXTIME_OPEN2 103
#define RC_RESULT_MAXTIME_CLOSE 104
#define RC_RESULT_CLOUD_INTERRUPT 105
#define RC_RESULT_BUTTON_INTERRUPT 106
#define RC_RESULT_HTTP_INTERRUPT 107
#define RC_RESULT_MQTT_INTERRUPT 108
#define RC_RESULT_OVERPOWER 109
#define RC_RESULT_OBSTACLE 110
#define RC_RESULT_SAFETY_SWITCH 111
#define RC_RESULT_LOW_POWER 112
```
So based on the value you see, you can identify the problem ;-)

Simone
