### ISSUE TITLE
Shelly's, Synology, Docker, Homeassistant

### ISSUE THREAD

**Issue by htpbreewel** [StyraHem/ShellyForHASS#160]
I use a Synology NAS running HA in a Docker container. See the BeardedTinker series on Youtube.
Everything works fine until I apply the ShellyForNas solution for my Shelly's. The Shelly's work but the volume usage of the NAS goes from 4% to 98% and makes the NAS very slow. When I delete the ShellyForNAS components the volume usage is 4% again.
Do you have any comments?

**Comment by chemelli74** [comment]
@htpbreewel , I'm on the same setup as you.  I don't have such behaviour. How many devices are configured in Shelly ? Do you have debug log active ? Any error in log ?

Simone

**Comment by htpbreewel** [comment]
In my Synology NAS I uninstalled Docker and everything in it. Started 
from scratch and installed only Docker and HA. Same 100% volume load.
I have 2 Shelly Plug-S, 1 Shelly-2.5 and 1 Shelly-1 and disconnected 
them all from the mains and reconnected them one by one and restarted HA 
after every reconnect.
The Shelly-2.5 caused the problem. Without this one the volume load was 
normal.
I did a factory reset on the 2.5 while HA was switched off and now it 
works correctly with normal volume load.
I noticed that if you change network settings like static ip-addresses 
in the Shelly app while HA is running on the NAS this can give problems.

If you want more info, please ask.
Henk.

Op 22-1-2020 om 07:48 schreef chemelli74:

**Comment by chemelli74** [comment]
Thx for the feedback,

Simone
