### ISSUE TITLE
WiFi signal card doesn't show rssi value

### ISSUE THREAD

**Issue by fiorentino77** [StyraHem/ShellyForHASS#163]
Hi,
before all, thank you so much for this great addon!
I've installed all cards showed on this page but the last one (WiFi signal) doesn't show WiFi values of my shelly.
Any ideas?

Thanks in advance,

Alessandro

**Comment by hakana** [comment]
Can you send a picture, please?

**Comment by fiorentino77** [comment]
Sure,
here it is:
![Cattura](https://user-images.githubusercontent.com/56383979/73104317-6ffdc380-3ef6-11ea-88c7-1abc151132ac.PNG)

**Comment by hakana** [comment]
Can you see the WiFi strength if you click on the entity?

If you want the sensors you need to add it to config.yaml
```yaml
shelly:
  sensors:
     -all
```
See spec of different options here:
https://github.com/StyraHem/ShellyForHASS#sensors

**Comment by fiorentino77** [comment]
Fixed! Thank you so much.
Is it possible to assign an customize icon to sensor.shelly_shsw_pm_XXXXX_consumption entities?

**Comment by astrandb** [comment]
HA has a general approach to that type of customization. Please refer to:
https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by hakana** [comment]
Great, better to use HA customization for change icons.

**Comment by chemelli74** [comment]
> Sure,
> here it is:

<off-topic>
@fiorentino77 Which theme are you using for your HA lovelace ?
</off-topic>

Simone

**Comment by fiorentino77** [comment]
> > Sure,
> > here it is:
> 
> off-topic
> @fiorentino77 Which theme are you using for your HA lovelace ?
> /off-topic
> 
> Simone

Darkmix theme
