### ISSUE TITLE
Round power consumption to one decimal place

### ISSUE THREAD

**Issue by janbernhardt** [StyraHem/ShellyForHASS#166]
Hi,

I love your integration. Works perfectly!
I would like to ask if you could round the power consumption value (used as an attribute and as a sensor value) to have only one decimal place. It looks strange, when sometimes the Watt value has 5 decimal digits that are not so much meaningful anyway.

Many thanks!

**Comment by chemelli74** [comment]
Hi,

just configure the following parameter:

`power_decimals`
 
Round power sensor values to the given number of decimals

Simone

**Comment by chemelli74** [comment]
@janbernhardt, any feedback ? If working can you close the issue please ?

Thank you,

Simone

**Comment by chemelli74** [comment]
Hi all, 

just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
