### ISSUE TITLE
Add Support for long DeviceID

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#167]
As announced there are some problems with deviceID.

They facing into issues because the last 6 digits from MAC addresses aren‘t unique anymore.

For all new devices in future deviceID will be the whole MAC address.

I got a test firmware - because I‘m facing into this issue with one device - from allterco. Now this device doesn‘t work anymore with ShellyForHASS.
The old entity doesn‘t get any update. I added the new long deviceID in configuration but there is no new entity with this.

Edit:
See message from Dimitar here:
https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/2552658274833521/

So next week there will be more and more devices with longer IDs.

So for example my Shelly H&T:

old entity: sensor.shelly_shht_1_f383b2_battery_attr
new entity: sensor.shelly_shht_1_98f4abf383b2_battery_attr

**Comment by chemelli74** [comment]
Hi @vistalba, can you report witch version if the plugin are you using ?

Thank you,

Simone

**Comment by vistalba** [comment]
Version installed: 0.1.5

**Comment by chemelli74** [comment]
Hi, long ID is supported since 0.1.6b7, please update.

Simone

**Comment by hakana** [comment]
Did you specify the long id in config.yaml?

**Comment by chemelli74** [comment]
@vistalba, please retest with 0.1.6 final and report back.

Simone

**Comment by vistalba** [comment]
Works for me.
