### ISSUE TITLE
1.6.0beta9: current consumption update in HA

### ISSUE THREAD

**Issue by morph027** [StyraHem/ShellyForHASS#169]
I'm testing 1.6.0b9 right now and besides #168 i've noticed the HA GUI is not updating the current consumption in realtime anymore (still need to check if this was the case in beta8, but im quite sure it worked).

CoAP messags are popping immediately when hitting the switch (either physical or in HA), but it takes some time to show up in HA (see the video: https://gofile.io/?c=SKpTNy)

I can see the value has changed from `consumption` to `current_consumption`:

```
Jan 26 10:18:33 homeassistant hass[6444]: 2020-01-26 10:18:33 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:18:48 homeassistant hass[6444]: 2020-01-26 10:18:48 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:19:03 homeassistant hass[6444]: 2020-01-26 10:19:03 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:19:18 homeassistant hass[6444]: 2020-01-26 10:19:18 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:19:34 homeassistant hass[6444]: 2020-01-26 10:19:34 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:19:49 homeassistant hass[6444]: 2020-01-26 10:19:49 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:20:04 homeassistant hass[6444]: 2020-01-26 10:20:04 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:20:19 homeassistant hass[6444]: 2020-01-26 10:20:19 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:20:34 homeassistant hass[6444]: 2020-01-26 10:20:34 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:20:49 homeassistant hass[6444]: 2020-01-26 10:20:49 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:21:04 homeassistant hass[6444]: 2020-01-26 10:21:04 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:21:19 homeassistant hass[6444]: 2020-01-26 10:21:19 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:21:34 homeassistant hass[6444]: 2020-01-26 10:21:34 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:21:55 homeassistant hass[6444]: 2020-01-26 10:21:55 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:22:04 homeassistant hass[6444]: 2020-01-26 10:22:04 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:22:19 homeassistant hass[6444]: 2020-01-26 10:22:19 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:22:34 homeassistant hass[6444]: 2020-01-26 10:22:34 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:22:49 homeassistant hass[6444]: 2020-01-26 10:22:49 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:23:04 homeassistant hass[6444]: 2020-01-26 10:23:04 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:23:19 homeassistant hass[6444]: 2020-01-26 10:23:19 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:23:34 homeassistant hass[6444]: 2020-01-26 10:23:34 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'consumption': 0}
Jan 26 10:23:50 homeassistant hass[6444]: 2020-01-26 10:23:50 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0}
Jan 26 10:23:50 homeassistant hass[6444]: 2020-01-26 10:23:50 INFO (Thread-7) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:24:05 homeassistant hass[6444]: 2020-01-26 10:24:05 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:24:19 homeassistant hass[6444]: 2020-01-26 10:24:19 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:24:35 homeassistant hass[6444]: 2020-01-26 10:24:35 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:24:50 homeassistant hass[6444]: 2020-01-26 10:24:50 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:24:50 homeassistant hass[6444]: 2020-01-26 10:24:50 INFO (Thread-10) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:25:05 homeassistant hass[6444]: 2020-01-26 10:25:05 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:25:20 homeassistant hass[6444]: 2020-01-26 10:25:20 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:25:35 homeassistant hass[6444]: 2020-01-26 10:25:35 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:25:50 homeassistant hass[6444]: 2020-01-26 10:25:50 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:25:50 homeassistant hass[6444]: 2020-01-26 10:25:50 INFO (Thread-13) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:26:05 homeassistant hass[6444]: 2020-01-26 10:26:05 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:26:20 homeassistant hass[6444]: 2020-01-26 10:26:20 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:26:35 homeassistant hass[6444]: 2020-01-26 10:26:35 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:26:50 homeassistant hass[6444]: 2020-01-26 10:26:50 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:26:50 homeassistant hass[6444]: 2020-01-26 10:26:50 INFO (Thread-16) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:27:05 homeassistant hass[6444]: 2020-01-26 10:27:05 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:27:20 homeassistant hass[6444]: 2020-01-26 10:27:20 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:27:36 homeassistant hass[6444]: 2020-01-26 10:27:36 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:27:50 homeassistant hass[6444]: 2020-01-26 10:27:50 INFO (Thread-19) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:27:51 homeassistant hass[6444]: 2020-01-26 10:27:51 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:28:06 homeassistant hass[6444]: 2020-01-26 10:28:06 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:28:21 homeassistant hass[6444]: 2020-01-26 10:28:21 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:28:36 homeassistant hass[6444]: 2020-01-26 10:28:36 INFO (CoAP) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
Jan 26 10:28:50 homeassistant hass[6444]: 2020-01-26 10:28:50 INFO (Thread-22) [pyShelly] Update id:CC958C-4 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'over_power': False, 'total_consumption': 54.22}
```

HA shows not entity with `current_consumption`:

![Screenshot from 2020-01-26 13-57-17](https://user-images.githubusercontent.com/600106/73135563-d47a6900-4043-11ea-8a37-92b8ecb2b328.png)

**Comment by morph027** [comment]
my shelly config in HA:

```yaml
shelly:
  username: !secret shelly_user
  password: !secret shelly_password
  sensors:
    - all
```

**Comment by vistalba** [comment]
I run into the same issue as reported here:
https://github.com/StyraHem/ShellyForHASS/issues/165#issuecomment-578531111

Some more information about my config:

https://github.com/StyraHem/ShellyForHASS/issues/165#issuecomment-578541564

It does work on 0.1.6b8 and also on current release 0.1.5.

Device is one Shelly 1pm.

**Comment by vistalba** [comment]
Okay... I did some more testing on this beta9 issue with my two 1pm.

What I can say is that it works generally. But if the load on 1pm is "static" (so long time constant near the same load) it doesn't seem to update the values in HA. I've to wait a longer time than before.

You can see it in the screenshot attached:
![image](https://user-images.githubusercontent.com/12324196/73608866-46b0f780-45c8-11ea-9a3b-42158ee83037.png)

What you can see is when I've installed bata9 this morning.
So it looks like the values are updated not so often as before.

On the other 1pm I've very constant load as you can see here:
![image](https://user-images.githubusercontent.com/12324196/73608903-8d9eed00-45c8-11ea-8b80-6e1f361666aa.png)

The problem here is that the value are updated not so often as before. 
![image](https://user-images.githubusercontent.com/12324196/73608918-a5767100-45c8-11ea-9d4a-e5a287b61cfd.png)
This results in "unconstant" consumption in a hour. You can see until 21:00 the graph is very simliar for each hour. The last few hours are not so regular. But consumption was constant.

cc @chemelli74 Any idea why this happens?

I hope this explaination is clear enought. It's diffucult for me to explain it on english.

**Comment by chemelli74** [comment]
@vistalba , do you have access to a linux machine ? I would ask to run followng command:

```
curl -s http://x.x.x.x/status | jq .meters[0].total
curl -s http://x.x.x.x/status | jq .meters[1].total
```

so you can check if they are consistent.

Simone

**Comment by vistalba** [comment]
@chemelli74 
Yes, I do.

`
~curl -s http://user:password@192.168.1.xx/status | jq .meters[0].total
1290484
`

`
~curl -s http://user:password@192.168.1.yy/status | jq .meters[0].total
4399086
`
after serval seconds/minutes:
`
~curl -s http://user:password@192.168.1.xx/status | jq .meters[0].total
1291003
`

`
~curl -s http://user:password@192.168.1.yy/status | jq .meters[0].total
4400197
`

So they are not consistant. The values do change. 
With beta 8 it was working fine. Only with beta 9 I run into this wired issues.

**Comment by chemelli74** [comment]
> So they are not consistant. The values do change.

Humm, seems all fine to me. "0" and "1" are two different loads of your Shelly 2.5 so make sense that total is different.

> With beta 8 it was working fine. Only with beta 9 I run into this wired issues.
> Edit: May it is important. I do not use new "total_consumption" in beta 9. I use the "consumption" which is "cunrrent_consumption" I think?

I had same inconsistency, so I just deletde those entities and rediscovered.

Simone

**Comment by vistalba** [comment]
> > So they are not consistant. The values do change.
> 
> Humm, seems all fine to me. "0" and "1" are two different loads of your Shelly 2.5 so make sense that total is different. What is reporting Shelly's mobile app ?
> 
> > With beta 8 it was working fine. Only with beta 9 I run into this wired issues.
> > Edit: May it is important. I do not use new "total_consumption" in beta 9. I use the "consumption" which is "cunrrent_consumption" I think?
> 
> I had same inconsistency, so I just deletde those entities and rediscovered.
> 
> Simone

It is not a Shelly 2.5. It is a Shelly 1pm. There is only one load.

How can I delete the entity to check if that helps?
The inconsistency comes from this... example:

1h a device consumes constant 18W.
At the end of the hour utility_meter shows 0 kWh instead of 0.018 kWh (or if you round 2 -> 0.02kWh).

But the utility_meter has this issue because consumption is just read once... after that consumption values stick on 18W for about 2h. (Value doesn‘t change at all).

**Comment by vistalba** [comment]
I tried with your suggestion and deleted all entities of the Shelly 1pm. 

1.6.0beta9 has recreated them. But same issue so far. My load has a constant consumption of 18W at the moment... 

This entitiy is not updated anymore because until the 18W is changed... this result in wrong calculation of kWh:
`sensor.shelly_shsw_pm_c12345_consumption`

The new entity "total_consumption_attr" is updated frequently... but is not used at all on my HA (so far).
`sensor.shelly_shsw_pm_c12345_total_consumption_attr`

So for me, this update from 1.6.0beta8 to 1.6.0beta9 is a breaking change. Because all of my existing power meters are not working anymore.

Downgraded to beta8 for now.

Let me know what I can test to provide you more useful information.

**Comment by vistalba** [comment]
I just found out that now also in beta 8 I run into this issue (may because I deleted the entity?).
Now downgraded to 0.1.5 and now it does refresh much more often. But what I also see is that now the consumption is no more "18W" it does switch between "17.5W" and "18.20W".
So there are more details. May this is relevant?

**Comment by vistalba** [comment]
@morph027 @chemelli74 
I found out something.

If I use 1.5.0 (release) consumption value default is `power_decimals: 2`.
If I use 1.6.0b9 consumption default value is `power_decimals: 0`. This results in much lower change of the value.

I now set `power_decimals: 1` in 1.6.0b9. This resolves the issue for me.

**Comment by chemelli74** [comment]
> This entitiy is not updated anymore because until the 18W is changed... this result in wrong calculation of kWh:
> sensor.shelly_shsw_pm_c12345_consumption

This is a old sensor, new one is "current_consumption".

Simone

**Comment by vistalba** [comment]
@chemelli74 

There is no sensor with `current_consumption` in 1.6.0b9.

Here you can see all the senaors I've in developer tools:
![image](https://user-images.githubusercontent.com/12324196/73662003-5d744e80-469b-11ea-837f-ce2be499309a.png)

Current config:

```
shelly:
  discovery: false
  show_id_in_name: false
  igmp_fix: true
  additional_information: true
  power_decimals: 1
  sensors:
#  - all
  - power
  - battery
  - switch
  - over_temp
  - over_power
  - current_consumption
  - total_consumption
  attributes:
  - default
  devices: 
```

**Comment by chemelli74** [comment]
> There is no sensor with current_consumption in 1.6.0b9.

[https://github.com/StyraHem/ShellyForHASS/releases
](url)

Simone

**Comment by vistalba** [comment]
Sorry, but I don't get the point with this release page you linked.

**Comment by chemelli74** [comment]
@morph027 , @vistalba please recheck with final 0.1.6 release.

Simone

**Comment by vistalba** [comment]
Added "power_decimals: 1" to configuration and this works fine for me.
May the issue has something to do with 1.5.0 which had always 2 decimals.

**Comment by hakana** [comment]
Yes, we changed the power_decimals to 0 as default in 0.1.6 so it not fill/flood the database.

**Comment by vistalba** [comment]
I think this is the problem we facing in.
I've very constant load and this results in that the value sometimes is not updated for multiple hours. This results in not calculate kWh in utility_meter.

**Comment by hakana** [comment]
But the total_consumption will be updated even if not the consumption updates

**Comment by vistalba** [comment]
> But the total_consumption will be updated even if not the current_consumption updates

Do you have an good example how to calculate consumed energy with utility_meter in kWh with `total_consumption`? As I know after a shelly reboot `total_consumption` value will be 0.

**Comment by hakana** [comment]
No, total_consumption is from the Shelly and is only reset when you doing a factory-reset of the Shelly.

**Comment by vistalba** [comment]
> No, total_consumption is from the Shelly and is only reset when you doing a factory-reset of the Shelly.

Which parameter do you use for `total_consumption`? 

http://ip/status total value?

`{"wifi_sta":{"connected":true,"ssid":"vistalba-iot","ip":"192.168.1.235","rssi":-52},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"14:18","serial":5,"has_update":false,"mac":"ECFABCC45728","relays" :[{"ison":true, "has_timer":false,"overpower":false}],"meters":[{"power":180.25,"is_valid":true,"timestamp":1580998722,"counters":[0.000, 0.000, 0.000],"total":0}],"inputs":[{"input":0}],"ext_temperature":{},"temperature":40.46,"overtemperature":false,"tmp":{"tC":40.46,"tF":104.83, "is_valid":"true"},"update":{"status":"idle","has_update":false,"new_version":"20200206-083604/v1.5.10@e6a4205e","old_version":"20200206-083604/v1.5.10@e6a4205e"},"ram_total":50664,"ram_free":36612,"fs_size":233681,"fs_free":167919,"uptime":66}`

after a FW upgrade of the shelly total value is 0.

**Comment by ggraziotti** [comment]
current consumption values are energy, so Wh or power, so Watt? I assume that are WATT, so is not correct consumption, but POWER is correct.... Otherwise miss understanding...

**Comment by vistalba** [comment]
@ggraziotti 
As described here: https://shelly-api-docs.shelly.cloud/#shelly1-1pm-status

power = Current power in Watt
total =  Total energy consumed by the attached electrical appliance in W/min

So as I understand:

power = current_consumption
total = total_consumption

Problem is that "total" value is 0 after reboot/firmware upgrade. So you may have to do some extra work on HA that consumption counter is not reset. 

@hakana How is it solved that the total consumption isn't resetted? Do you check if new value is smaller thant the last and add it automaticly?

**Comment by hakana** [comment]
Yes that is correct

We don't have any logic around total_consumption, just showing the value from the Shelly.

**Comment by ggraziotti** [comment]
Power is not consumption, I do not understand why watt as consumption and not instant power...

**Comment by hakana** [comment]
@ggraziotti Can you please explain what you don't understand?

**Comment by JANogueira** [comment]
Hi All,

Not sure if this is the right place to post this, but I am finding data inconsistency regarding the current_consumption sensor when comparing lovelace history graphs and InfluxDB/Grafana.

Here is an example taken from the Lovelace history graph:
![image](https://user-images.githubusercontent.com/22750391/74339725-8e8c0780-4d9c-11ea-8d61-e6ca0c58d475.png)

and a graph built with Grafana for the same sensor:
![image](https://user-images.githubusercontent.com/22750391/74339804-b24f4d80-4d9c-11ea-982b-8b5e1c777ea1.png)

Not sure if the sensor only reports instant consumption variations (and does not send data if no change is seen).
Do you know what can this be?

Thanks in advance.

**Comment by hakana** [comment]
Try change fill (null) to something else (don't remember)

![image](https://user-images.githubusercontent.com/1168654/74340956-37d7fb00-4da7-11ea-9320-40ccf60b1bef.png)

**Comment by JANogueira** [comment]
Many thanks @hakana. Changing to fill(previous) now shows it correctly.
Cheers

**Comment by hakana** [comment]
Perfect!
