### ISSUE TITLE
Shelly Door/Window sensor state (open, close) cannot see

### ISSUE THREAD

**Issue by balagev** [StyraHem/ShellyForHASS#170]
Hello team,
I'm working on integrating Shelly DW into HASS. The first problem is that I see a lot of information from the DW (battery, mqtt connection, lux status ... etc) but I haven't seen the sensor status (open, closed).
Can you add this sensor ... or update the documentation, how do I set up this sensor?
Thanks,
Balazs

**Comment by hakana** [comment]
What version of ShellyForHass do you use? Should work in latest beta release.

**Comment by balagev** [comment]
Installed version: 0.1.5

**Comment by hakana** [comment]
Yes, it will work in latest beta
