### ISSUE TITLE
How to use the proxy.py python script?

### ISSUE THREAD

**Issue by jponte85** [StyraHem/ShellyForHASS#172]
I'm running HASSIO, I tried to execute the script on the same server where I have the HASSIO but without success, what I did was:
 python3  proxy.py

after execute the command I didn't receive any ouput.

**Comment by chemelli74** [comment]
Script is used to forward CoAP messages from Shelly's network to HA network; I don't expect any output on the script itself, even if I didn't tested it.

Simone

**Comment by jponte85** [comment]
I was not able to use the python script. What I did was create a static route for multicast. It is working. Thanks.

**Comment by jponte85** [comment]
I was not able to use the script. What I did was create a static route for multicast communication. It is working.
