### ISSUE TITLE
problem to upgrade from 0.16 beta to 0.16 stable using HACS

### ISSUE THREAD

**Issue by pilot1981** [StyraHem/ShellyForHASS#174]
Hi,
I have HACS 0.20.9 on HASSIO 0.104.3, I tried to upgrade from 0.16 beta to 0.16 stable using HACS but it remain at 0.16 beta 10...I always have restart HA message on HACS...

**Comment by chemelli74** [comment]
Hi,

worked fine here.
Can you post debug log please ?

Simone

**Comment by pilot1981** [comment]
Hi,
in HACS I always have same problem...Shelly isn't updated correctly...

where I can take debug logs?

**Comment by pilot1981** [comment]
solved, a problem in configuration.yaml create a stop in upgrade process of HACS when it have to restart home assistant!
