### ISSUE TITLE
Version 0.1.6 - issue with device FW display after update 

### ISSUE THREAD

**Issue by rParslow** [StyraHem/ShellyForHASS#177]
Hi 

_First Thank's a lot for this release, has I'm switching from JDom to HA I'm able to do it with less pain with the Integration support :)_ 

I've noticed an issue after updating the Shelly's Firmware (from HA and from the Shelly web acces) 

ShellyForHass tells me the actual FW version of my devices and that a new one is available, so I've updated the FW from HA. It works fine, but no I've on the lovelace device display : 
`Entité non disponible: switch.shelly_shplg_s_******_firmware_update`

My versions
HA 0.105.1 / HACS: 0.20.9 / ShellyForHass 0.1.6
Shelly's 1 / 2.5PM /  PlugS v1.5.10

**Comment by hakana** [comment]
Yes the update switch is removed when there is no update. You can use the custom component auto-entities to show a list of update switches.
https://github.com/StyraHem/ShellyForHASS/blob/master/README.md#need-firmware-update-click-on-the-switch-to-update

**Comment by chemelli74** [comment]
@rParslow, did you got the point ? Can you close the issue ?

Thank you,

Simone

**Comment by rParslow** [comment]
Hello 
Sorry for the delay to answer 

My point was more like to the new cards when there is no Firmware update there is en yellow warning message  
![image](https://user-images.githubusercontent.com/1121777/74595075-b77ef780-503d-11ea-9dd8-8edf6b6c7f26.png)

I've installed the auto-entity with a dedicated card for firmware update it's great 

Thanks

**Comment by chemelli74** [comment]
@rParslow , so if I got it right you solve dusing auto-entities card. 
If so can you close the issue ?

Simone
