### ISSUE TITLE
0.1.6 - Total consumption sensor / persistance 

### ISSUE THREAD

**Issue by rParslow** [StyraHem/ShellyForHASS#178]
Hi 

The **Total consumption sensor** is a great thing, but unfortunatly when the Shelly restart the value to 0 

Do you think it will be possible to keep the value to avoif this ? 
![TotConsump](https://user-images.githubusercontent.com/1121777/73967336-fa432000-4917-11ea-8b1f-82fffbf42fc2.jpg)

**Comment by catalinbordan** [comment]
It related to the firmware of shelly.
if you want a persistent values, you can use this sensor as a source for utility meters in HA

**Comment by rParslow** [comment]
Thanks
this is what I was looking for
