### ISSUE TITLE
0.1.6 Default config outputs a lot of data in log

### ISSUE THREAD

**Issue by TASSDevon** [StyraHem/ShellyForHASS#179]
After updating to 0.1.6 it seems ShellyForHASS outputs quite a bit more into the logs. Could this be lowered a bit?

If not by default, is there a way for me to make the plugin more silent?

Thanks

Example:

_values:{'current_consumption': 0, 'switch': False}
2020-02-07 18:16:16 INFO (CoAP) [pyShelly] Update id:7718D1 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B9377F state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B9377F-1 state:0.0 stateValue:None values:None info_values:None
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B9377F-1 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B9377F-2 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B944CD state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B944CD-1 state:0.0 stateValue:None values:None info_values:None
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B944CD-1 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B944CD-2 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:24 INFO (CoAP) [pyShelly] Update id:8CAAB505E877 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'switch': False}
2020-02-07 18:16:24 INFO (CoAP) [pyShelly] Update id:8CAAB505E877 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:28 INFO (CoAP) [pyShelly] Update id:68ECF2 state:False stateValue:None values:None info_values:{'current_consumption': 0.0}
2020-02-07 18:16:28 INFO (CoAP) [pyShelly] Update id:68ECF2-1 state:0.0 stateValue:None values:None info_values:None
2020-02-07 18:16:28 INFO (CoAP) [pyShelly] Update id:68ECF2-1 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:28 INFO (CoAP) [pyShelly] Update id:68ECF2-2 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:31 INFO (CoAP) [pyShelly] Update id:7718D1 state:False stateValue:None values:None info_values:{'current_consumption': 0, 'switch': False}
2020-02-07 18:16:31 INFO (CoAP) [pyShelly] Update id:7718D1 state:False stateValue:None values:None info_values:None
2020-02-07 18:16:34 INFO (CoAP) [pyShelly] Update id:B9377F state:True stateValue:None values:None info_

**Comment by Misiu** [comment]
What is your log level in config (in home assistant)?

**Comment by emilp333** [comment]
Same here. Default log level in HA.

**Comment by chemelli74** [comment]
@TASSDevon , @emilp333 please set log level to warn or higher:

```
logger:
 pyshelly: warn

```
Simone

**Comment by TASSDevon** [comment]
@Misiu default, I don't have a log level specified in my configuration yaml file.

@chemelli74 Thanks, I'll update that :-)

**Comment by emilp333** [comment]
I still think this issue is an issue. Default log level is too high.

**Comment by emilp333** [comment]
Non of the above examples seems to have any affect on this component though. And be careful if you have not set any default level in logger component.

**Comment by chemelli74** [comment]
> I still think this issue is an issue. Default log level is too high.

Default level is your HA default level ;-)

Simone

**Comment by chemelli74** [comment]
> Non of the above examples seems to have any affect on this component though. And be careful if you have not set any default level in logger component.

Post your configuration.yaml, I expect something wrong there as Shelly respect HA level since so long time.

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by emilp333** [comment]
What's your question @chemelli74. I think the information provided is perfectly clear. Default logging of this component outputs this just like the example from first post.
> 2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B9377F state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
This started in version 0.1.6. So you tell us if that is your desired "default" log level.

And this does not change anything either.
`logger:
     logs:
         pyshelly: warn`

**Comment by chemelli74** [comment]
> What's your question @chemelli74. I think the information provided is perfectly clear. Default logging of this component outputs this just like the example from first post.

If you want to fix the issue you nee dto change your logger config.
Here is working just fine.


> ```
> logger:
>   default: info
>   logs:
>     homeassistant.components.yamaha: critical
>     custom_components.my_integration: critical
> ```

If you have default info and wrong component name, it won't work.
Please try using:

```
logger:
  default: warn
```

Simone

**Comment by emilp333** [comment]
Ok, I still think you misunderstand my question and I can see it got missed in the formating in my previous post. This is fixed now.
```
2020-02-07 18:16:19 INFO (CoAP) [pyShelly] Update id:B9377F state:True stateValue:None values:None info_values:{'current_consumption': 0.0}
```
This started in version 0.1.6. So you tell us if that is your desired "default" log level?
And for the record the default log level in Home Assistant is "info" if you do not specify anything else.

> If you have default info and wrong component name, it won't work.
Please try using:
logger:
  default: warn

The above would change even Home Assistant Core default log level which is info by default. So how would I specify the log level of only the Shelly component?

**Comment by chemelli74** [comment]
> This started in version 0.1.6. So you tell us if that is your desired "default" log level?

If you have info as default for HA, Shelly honors it and thus you get the above message.
You have only 2 options:

- change the log level for HA to "warn" or anything you like. ShellyForHASS will honor it.
- change the log level only for this plugin using:

` pyShelly: warn
`

> And for the record the default log level in Home Assistant is "info" if you do not specify anything else.

Indeed, it is.

> > If you have default info and wrong component name, it won't work.
> > Please try using:
> > logger:
> > default: warn
> 
> The above would change even Home Assistant Core default log level which is info by default. So how would I specify the log level of only the Shelly component?

See above comments and or few lines in this comment ;-)

Simone

**Comment by emilp333** [comment]
Ok. I still think you are avoiding the question. 
> After updating to 0.1.6 it seems ShellyForHASS outputs quite a bit more into the logs. Could this be lowered a bit?

So you have added more information in the "info" log level for 0.1.6 and this is intentionally?

This component will by default output one of these for every Shelly device channel every 3 seconds.
```home-assistant   | 2020-02-24 20:52:00 INFO (CoAP) [pyShelly] Update id:007***-1 state:0.0 stateValue:None values:None info_values:None```

So my point is that I think this is too much logging by default. I understand there is a workaround and this is only my opinion and its up to you to do whatever with that feedback. 
I only have 13 devices but its still 13 logs lines every 3 seconds by default...

**Comment by emilp333** [comment]
And as I stated above this does not work either.
```
logger:
  default: info
  logs:
    pyshelly: warn
```

**Comment by TASSDevon** [comment]
The code I pasted some time ago works fine. No clue why it would not work for you (have you triple checked?)

True some additional logging has been added at the Info level that, in my opinion, might be a bit verbose and it is debatable if it should be debug or info level. Thing is chemelli74 has given plenty of info on how to make sure these new loglines do not appear in your log when using info as a default. If he thinks this should be info level, that's his good right as the developer. Clearly from the answers posted it looks like he judges it like that and now debug, and I respect his opinion and decision on that.

It's his code, his plugin and his own time, we haven't paid him a dime for it, please don't take it for granted and be happy with what you get.

If you don't like it, I've seen a Shellies Discovery script topic on the HA forum which looks like an alternative to this.

If you still have issues with different levels of logging for default HA and specific plugins such as ShellyForHass, I suggest you open a topic on the HA community forum so more people can have a look at why this is happening for you.

**Comment by TASSDevon** [comment]
And with that, let's close the issue, it has been resolved.

**Comment by emilp333** [comment]
Hey. 
Dont take me wrong but issues in an open Github repo is partly for the community to help find bugs and improvements.
Just like I'm stated above "This is only my opinion."

Then next I'm trying to point out the syntax of logger. This is again to improve the code. It's not criticism. 
https://www.home-assistant.io/integrations/logger/

**Comment by chemelli74** [comment]
> And as I stated above this does not work either.
> 
> ```
> logger:
>   default: info
>   logs:
>     pyshelly: warn
> ```

Again, works here.
Did you mind posting your configuration.yaml to check ?
Otherwise I have no other input to give you.

Simone

**Comment by emilp333** [comment]
Yes, this is from my configuration.yaml.

**Comment by emilp333** [comment]
And this is the shelly part of my configuration.yaml.
```

shelly:
  discovery: true  #add all devices (default)
  additional_information: True
  sensors:
    - current_consumption
    - total_consumption
  attributes:
    - ip_address
    - shelly_type
    - shelly_id
    - firmware_version
    - cloud_status
    - switch
    - current_consumption
    - total_consumption
    - over_power
    - device_temp
    - over_temp
    - payload
```

**Comment by chemelli74** [comment]
> Yes, this is from my configuration.yaml.

As you aren't posting the whole configuration.yaml for a check I have no other choice than locking this thread.
Sorry,

Simone
