### ISSUE TITLE
0.1.6 No Total Consumption for Shelly Plug S

### ISSUE THREAD

**Issue by VooZ2** [StyraHem/ShellyForHASS#180]
I installed yo Shelly Plug S but can't get total consumption. My config:

```
shelly:
  discover_by_ip:
    - '192.168.9.11'
    - '192.168.9.25'
    - '192.168.9.2'
```

where I make a mistake?
<img width="376" alt="Screenshot 2020-02-08 at 10 47 49" src="https://user-images.githubusercontent.com/58629422/74082240-c4f61980-4a60-11ea-9c60-026ef3cf485a.png">
<img width="505" alt="Screenshot 2020-02-08 at 10 47 39" src="https://user-images.githubusercontent.com/58629422/74082244-c6bfdd00-4a60-11ea-88f4-5088e3b05523.png">

**Comment by chemelli74** [comment]
Confirmed also on my installation.

Simone

**Comment by VooZ2** [comment]
Case closed. Problem was with a time. Shelly Plug S must have time to calculate total consumption.
