### ISSUE TITLE
Shelly EM sensor value missing

### ISSUE THREAD

**Issue by danygi79** [StyraHem/ShellyForHASS#181]
hello,
the shelly EM sensor does not show the voltage, apparent power and cosfi values, for me they are very important

**Comment by chemelli74** [comment]
> hello,
> the shelly EM sensor does not show the voltage, apparent power and cosfi values, for me they are very important

Hi @danygi79, can you share your configuration.yaml ?

Simone

**Comment by danygi79** [comment]
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

cloud:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   base_url: casa45234.duckdns.org
   server_port: 8123
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem

homeassistant:
  customize: !include customize.yaml

telegram_bot:
  - platform: polling
    api_key: 101807dasd6:AAEcwBt6sURFsrDIxgE8z1RBpan65T5zOuo
    allowed_chat_ids:
      - 76145633

notify:
  - name: Daniele
    platform: telegram
    chat_id: 76145633
  - platform: alexa_media
    name: alexa_media
    
shelly:
  cloud_auth_key: YzA4YnVpZADA3AAER45648274244FEB1F6DA4C26DDC86B2C739D2CD3DD79ED2FF7894C245C053AEA0A910F5BB8EDDWEQEQWD
  cloud_server: https://shelly-2-eu.shelly.cloud
  discovery: true  #add all devices (default)
  sensors: #sensors to show, can be override on each device
    - all

# Text to speech
tts:
  - platform: google_translate

hacs:
  token: ef1a7b5f6a8b21312345149a8ba0826e98c332152d

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

fritzbox_tools:
  host: "192.168.4.1"
  username: "offinf"  # create one at `System > FRITZ!Box Benutzer` on your router
  password: "D13gXSWW"

group: 
  famiglia:
    entities:
      - device_tracker.sm_g975f
      - device_tracker.iphone_di_deborah
    
  allarme:
    entities:
      - alarm_control_panel.casa
      - alarm_control_panel.garage

  luci_interne:
      - switch.shelly_shsw_1_b9dac1
      - switch.shelly_shsw_1_b9d875
      - switch.shelly_shsw_25_690251_1
      - witch.shelly_shsw_1_68c51a
      - switch.shelly_shsw_25_690251_2
      - switch.luce_divano

automation: !include automations.yaml
script: !include scripts.yaml

switch :
  - platform: broadlink
    host: 192.168.4.34
    mac: '34EA34BD3A01'
    friendly_name: "Luce Divano"
    type: sp2
  
  - platform: broadlink
    host: 192.168.4.32
    mac: '34EA344086F1'
    timeout: 15
    switches:
      condizionatore:
        friendly_name: "Condizionatore"
        command_on: 'JgAGAWw1Dg4PDA8nDw0OKA8MDw8MDg8nDycODQ8NDg4OKA4oDg4ODg4NDg8ODQ0ODg0ODQ4PDgwODg8MDw0PJw8MDw0ODg4ODwwPDQ4NDigPDA8NDg0PDg0pDSkOKA4oDycOKA4pDSkODQ4ODikODQ4ODg0ODg0NDw8MDQ8ODyYOKBAMDg8NKA8MDg4ODQ4pDwwOKQ8MDg4NDw4nDw4NDQ8MDw4NDw4NDQ8NDQ4ODg0ODg4NDw0ODQ4ODg0ODg4PDgwODg8NDw0NDg8MDg0ODg8ODA8NDRAMDwwODg4ODg0ODw0NDg8NDRAMDg4NDg8MDioODA4ODigPJw8NDSgPKA8NDSgQDQ0ADQUAAA==' 
        command_off: 'JgB2AGw2Dg0NDg8oDwsPKA8ODA4ODQ4qDCkODQ4OEAsOKA8pDQ0ODw8MDg0PDA4PDQ4ODQ4NDw0ODQ4PDw0OKA0PDQ0PDBAMEAsQDA4PDSgODg8MDg0QDA8nDw0PDQ0NDw4ODQ4NDikNDw4nDikOKA8nDigOKA8ADQUAAA=='

  - platform: mqtt
    name: "Portone Ingresso"
    state_topic: "paradox/control/outputs/Portone_Ingresso"
    command_topic: "paradox/control/outputs/Portone_Ingresso"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    retain: false

  - platform: mqtt
    name: "Garage"
    state_topic: "paradox/control/outputs/Garage"
    command_topic: "paradox/control/outputs/Garage"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    retain: false

  - platform: mqtt
    name: "Allarme Perimetrale"
    state_topic: "paradox/control/partitions/all"
    command_topic: "paradox/control/partitions/all"
    qos: 0
    payload_on: "arm_stay"
    payload_off: "disarm"
    optimistic: false
    retain: false

  - platform: mqtt
    name: "Allarme Totale"
    state_topic: "paradox/control/partitions/all"
    command_topic: "paradox/control/partitions/all"
    qos: 0
    payload_on: "arm"
    payload_off: "disarm"
    optimistic: false
    retain: false

tuya:
  username: ASDASD@gmail.com
  password: ASDASDASD
  country_code: 39
  platform: smart_life

sensor:
  - platform: mqtt
    name: "Tensione Alim. Allarme"
    state_topic: "paradox/states/system/power/vdc"
    qos: 1
    unit_of_measurement: "V"
    
  - platform: mqtt
    name: "Tensione Batteria. Allarme"
    state_topic: "paradox/states/system/power/battery"
    qos: 1
    unit_of_measurement: "V"

  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

  - platform: systemmonitor
    resources:
      - type: processor_use 
      - type: memory_use_percent

  - platform: template
    sensors: 
      cosfi:
        friendly_name: "Fattore di Potenza"
        value_template: "{{ ((states.sensor.shelly_shem_b9e456_1_current_consumption.state|float) / sqrt(((states.sensor.shelly_shem_b9e456_1_current_consumption.state|float) ** 2) + ((states.sensor.potenza_apparente_appartamento.state|float) ** 2)))|round(2) }}"

  - platform: template
    sensors:
      temperatura_esterna:
        friendly_name: "Temperatura Esterna"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.casa', 'temperature') }}"

  - platform: template
    sensors:
      temperatura_salotto:
        friendly_name: "Temperatura Salotto"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.30308510bcddc2bf6301', 'current_temperature') }}"
          
  - platform: broadlink
    scan_interval: 10
    host: 192.168.4.33
    mac: '34EA34B2C3DA'
    monitored_conditions:
      - temperature
      - humidity
      - air_quality
      - light
      - noise

  - platform: mold_indicator
    indoor_temp_sensor: sensor.broadlink_sensor_temperature
    indoor_humidity_sensor: sensor.broadlink_sensor_humidity
    outdoor_temp_sensor: sensor.temperatura_esterna
    calibration_factor: 2.0

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
      
  - platform: fritzbox_netmonitor
    host: 192.168.4.1

camera:
  - platform: ffmpeg
    name: "Cam Terrazzo"
    input: -rtsp_transport tcp -i rtsp://admin:ASDASD@192.168.4.6:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  
  - platform: ffmpeg
    name: "Cam Esterno"
    input: -rtsp_transport tcp -i rtsp://admin:ASDASD@192.168.4.6:554/cam/realmonitor?channel=2&subtype=0&unicast=true&proto=Onvif
  
  - platform: ffmpeg
    name: "Cam Ingresso"
    input: -rtsp_transport tcp -i rtsp://admin:ASDASD@192.168.4.6:554/cam/realmonitor?channel=3&subtype=0&unicast=true&proto=Onvif

  - platform: ffmpeg
    name: "Cam Garage"
    input: -rtsp_transport tcp -i rtsp://admin:ASDASD@192.168.4.6:554/cam/realmonitor?channel=4&subtype=0&unicast=true&proto=Onvif

**Comment by danygi79** [comment]
in the previous post there is the iterus file, of course all the passwords and the api key have been changed

**Comment by chemelli74** [comment]
> in the previous post there is the iterus file, of course all the passwords and the api key have been changed

I suggest you use "secrets.yaml" for all sensitive data (api key, ip addresses, users, password, etc.

Simone

**Comment by danygi79** [comment]
> > in the previous post there is the iterus file, of course all the passwords and the api key have been changed
> 
> I suggest you use "secrets.yaml" for all sensitive data (api key, ip addresses, users, password, etc.)
> 
> Simone



thank you for your suggestion

**Comment by hakana** [comment]
@danygi79 

How should the values be presented in HA?

This is the info I got from my Shelly EM:
{"power":-28.97,"reactive":2.15,"voltage":122.10,"is_valid":true,"total":781.7,"total_returned":9.2}

voltage = 122.10 V
current_consumption = -28.97 W
current_reactive = 2.15 W
total_consumption = 781.7 Wh
total_reactive = 9.2 Wh

Should I also add power factor like this?
power_factor = cos(arctan(2.15/-28.97))

**Comment by danygi79** [comment]
all value is correct excetp this:
current_reactive = 2.15 VAr  (no W)

The values ​​presented in my opinion should be:

voltage = 122.10 V
current_consumption = 28.97 W > if value is positive
current_returned = -28.97 W > if current_consumption value is negative
current_reactive = 2.15 VAr > Positive value = inductive load; Negative value = capacitive load
total_consumption = 781.7 Wh
total_returned = 9.2 Wh
power_factor = 1

The values ​​of current_consumption and current_returned are mutually exclusive and one of the two must always have a 0 value.

**Comment by JamesT42** [comment]
In the recent firmware they switched from showing reactive power to power factor.  Did they change the API also?

**Comment by chemelli74** [comment]
Please upgrade to 0.1.7b1 and recheck.

Simone

**Comment by danygi79** [comment]
With this version the voltage measurement is displayed, all the other values ​​are still missing.
On the other hand, the operation of all the switches has a delay in the display of about 10 seconds.

Daniele

**Comment by chemelli74** [comment]
@danygi79 please update to b2 and take a screenshot if something is still missing.

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone
