### ISSUE TITLE
Slow update of current consumption

### ISSUE THREAD

**Issue by dodg3r** [StyraHem/ShellyForHASS#182]
Hi.

My dev installation is on beta 8 and my prod installation is on 0.1.6.

In my prod installation current consumption is delayd with about 50 seconds when I turn on/off lights/switches.
In my dev installation its almost instant.
When I updated my dev to 0.1.6 the same delays occured

What to do ?

Someone else with same issue ?

**Comment by catalinbordan** [comment]
Same issue here too. the update is for every minute.

**Comment by chemelli74** [comment]
Should we continue on #158 ?

Simone

**Comment by dodg3r** [comment]
Why continue in 158 ?
Everything works except for power consumption as I descriped above.
In 158 state updates of lovelace is slow ? That works for me.

**Comment by chemelli74** [comment]
Sorry, didn't get that is only power slow.
Can you all check on http://x.x.x.x/status if it's refreshed more often than once per minute ?

Simone

**Comment by dodg3r** [comment]
Hi.
If I check the status of the plugs power consumption it changes instant.
But it takes exactly 1 minute for lovelace to change.

**Comment by chemelli74** [comment]
> Hi.
> If I check the status of the plugs power consumption it changes instant.
> But it takes exactly 1 minute for lovelace to change.

Can you please try enabling debug log and check if CoAP message is received istantly or is delayed ?

Simone

**Comment by chemelli74** [comment]
Shelly's official support informed me that current consumption is updated as follow:

- every 30 seconds
- immediatly if there is a 10% delta value

At this point, I'm going to close this issue.

Simone
