### ISSUE TITLE
0.1.6 Broke Shelly 1 devices

### ISSUE THREAD

**Issue by cjramseyer** [StyraHem/ShellyForHASS#183]
Following an upgrade from 0.1.5 to 0.1.6 the three Shelly1 devices I have, no longer appear in home assistant.

I have shelly: in the configuration.yaml

When checking the configuration (after complete removal and reinstall via HACS), the following error is received: 
Component error: shelly - cannot import name 'ATTR_RESTORED' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

Adding via the integrations page instead of the configuration.yaml also does not work

HA 0.102.3 running on rPi 3 B+

**Comment by cjramseyer** [comment]
Following numerous attempts at going back to version 0.1.5 via HACS and many reboots, have manually installed 0.1.5 (and rebooted).  Added "shelly:" back to the configuration.yaml.
This is the only way I could restore the shelly devices.

**Comment by chemelli74** [comment]
> HA 0.102.3 running on rPi 3 B+

You need HA >= 0.104.0 for 0.1.6

Simone

**Comment by cjramseyer** [comment]
Good to know.  That would be a good thing to include in the documentation.

Thanx for letting me know.

Regards,
CJ

CJ Ramseyer
(203) 690-4969
consult<at>techdesk.org

**Comment by chemelli74** [comment]
Please confirm it works after upgrade so we can close this issue.

Simone

**Comment by weltmeyer** [comment]
Works for me with 105. Had to update the shelly1 with latest firmware.

**Comment by chemelli74** [comment]
@cjramseyer , did you manage to get it working ? If so can you close the issue ?

Thank you,

Simone

**Comment by rgutialo** [comment]
What version of this component I need for Home Assistant 0.97.2?.
Thanks.

**Comment by cjramseyer** [comment]
0.1.5 is working for me on HA 0.102.3

CJ Ramseyer
(203) 690-4969
consult<at>techdesk.org

**Comment by hakana** [comment]
@cjramseyer 
You need HA 0.104.0 or greater for latest (0.1.6) release of ShellyForHASS

I close this issue for now
