### ISSUE TITLE
Massive amount of events and state entries on DB

### ISSUE THREAD

**Issue by pedrobsm** [StyraHem/ShellyForHASS#186]
I have about 10 shelly devices connected to my HASS and eveything working properly so far, but they are generating an enormous amount of events when compared to other devices.
Even without changing any state (button or relay) each device is sending between 1000 and 8000 events per day to HASS. This leads to a huge DB size (>2GB for 7 days retention) and a very slow graph performance on Lovelace.
The shellies configured as cover are the most active, reporting pos=-1 and pos=255 alternatively every second!!!
Any idea why I'm getting this amount of events?

**Comment by chemelli74** [comment]
About "pos" you mean roller position ?
If so can you check on http://x.x.x.x/status the values ?

Simone

**Comment by pedrobsm** [comment]
Those vaules are correct, meaning 100 when open. Some are higher than 100, but I'm assuming that it needs a calibration.

**Comment by chemelli74** [comment]
> 
> 
> Those vaules are correct, meaning 100 when open. Some are higher than 100, but I'm assuming that it needs a calibration.

If higher than 100 then you have a issue with calibration.
Please redo it and let us know if this fixes both the value and the DB activity.

Simone

**Comment by pedrobsm** [comment]
Hi again,

Thanks chemelli. That was actually the issue. 
So, when the blind, even after a correct callibration, goes over 100% open (which may hapen because calibration is based on time, not real position), the shelly logs 2 state changes per second! One says position >100, the other one position = -1.
So, this was using 30% of my DB!!!

Is it possible to fix this behaviour? Maybe add a new attribute "pos_out_of_range"? :)

**Comment by chemelli74** [comment]
Hi @pedrobsm,

it's a calibrating issue we cannot fix in code; mainly because there is a reason for this kind of error:
https://github.com/StyraHem/ShellyForHASS/issues/156#issuecomment-580421791

**Comment by chemelli74** [comment]
Opened a ER: #190 

Closing this one, discussion can continue on the other thread.

Simone
