### ISSUE TITLE
Shelly 4 Pro no State for Switch

### ISSUE THREAD

**Issue by helmi1987** [StyraHem/ShellyForHASS#187]
Connectet Shelly 4 Pro in hass.io have no switch_state entity
(Switch sensors to show status of switch button (0.0.16))

**Comment by chemelli74** [comment]
Is your config including:

```
sensors:
  -all

```
?

Simone

**Comment by helmi1987** [comment]
i have this in the configuration.yaml 

`shelly:
  discovery: true  #add all devices (default)
  discover_by_ip:
    - '192.168.100.107'
  sensors:
    - all #show all sensors
  devices:  #configure devices
    - id: "CC95EF-1"
      name: "Heizstrang 1"
    - id: "CC95EF-2"
      name: "Heizstrang 2"
    - id: "CC95EF-3"
      name: "Steckdose"
    - id: "CC95EF-4"
      name: "Heizungsschalter"`

but i have only this entitys for shelly 4Pro
![image](https://user-images.githubusercontent.com/20250408/74414133-1af00600-4e41-11ea-829d-0c8ec6219b5e.png)
![image](https://user-images.githubusercontent.com/20250408/74414164-2ba07c00-4e41-11ea-9c31-d74d99718e20.png)
![image](https://user-images.githubusercontent.com/20250408/74414191-36f3a780-4e41-11ea-8013-da338a3bcf0b.png)

**Comment by chemelli74** [comment]
Sorry I may be wrong as I don't have a Shelly 4 PRO, but in your screenshto I see 4 entities that have a switch (Heitzstrang 1, Heitzstrang 2, Heizungsshalter, Stechdose).
Some are on, some are off.

Simone

**Comment by hakana** [comment]
Fixed in 0.1.7.B1

@chemelli74, it is the physical switch (input) sensor missing

**Comment by helmi1987** [comment]
Thanks for fixing
There i will wait for next release Update.
Greate Job.

**Comment by chemelli74** [comment]
Please upgrade to 0.1.7b1 and recheck.

Simone

**Comment by helmi1987** [comment]
Hello Simone

ich will test it this weekend.

Thanks for fixing

**Comment by helmi1987** [comment]
Switch is showing but only in state on. Switch change will not triggert

**Comment by chemelli74** [comment]
> Switch is showing but only in state on. Switch change will not triggert

Please close this issue and open a new one.
Don't forget to attach debug log.

Thank you,

Simone
