### ISSUE TITLE
Claims to support integration flow but it actually fails

### ISSUE THREAD

**Issue by superm1** [StyraHem/ShellyForHASS#188]
Hi,

I just installed from HACS and it told me I could go to integrations to configure it.  I found it there:
![image](https://user-images.githubusercontent.com/494526/74206540-7bb0f000-4c41-11ea-913e-267eac4c6a75.png)

However after clicking through I'm brought to a rather confusing dialog.
![image](https://user-images.githubusercontent.com/494526/74206556-8bc8cf80-4c41-11ea-922d-53dbd1a76aab.png)

**Comment by hakana** [comment]
It can only be setup/configured in config.yaml for the moment

**Comment by superm1** [comment]
Yes, I configured it via yaml afterwards successfully. I just wanted to report it so you knew the bug it was offering integration flow even though not functioning.

**Comment by chemelli74** [comment]
Please update to 0.1.7b1 and recheck.

Simone

**Comment by Misiu** [comment]
@chemelli74 I was able to successfully add integration using config flow, but I'm unable to change any options. More info here: https://github.com/StyraHem/ShellyForHASS/issues/210

**Comment by chemelli74** [comment]
I would say that we can close this issue and track bugs in new issues.

Simone
