### ISSUE TITLE
Shelly 3EM support

### ISSUE THREAD

**Issue by jarnojlaine** [StyraHem/ShellyForHASS#191]
Hello,
First of all LOVE your work and thank you so much for your input for all of us Shelly fanatics.

2nd, 3EM's have started to roll out, just got mine hooked up and would love to see integration for this :)

**Comment by hakana** [comment]
To help ypu can enable attribute payload in config.yaml and post the result from 3em. Also post result http://xxxx/status and /settings where xxx is ip address of 3em.

**Comment by kuradi** [comment]
> To help ypu can enable attribute payload in config.yaml and post the result from 3em. Also post result http://xxxx/status and /settings where xxx is ip address of 3em.

please
`{"wifi_sta":{"connected":true,"ssid":"name","ip":"xxx. xxx. xxx. xxx ","rssi":3},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":true},"time":"01:44","serial":1,"has_update":false,"mac":" xxx","relays":[{"ison":false,"has_timer":false,"overpower":false,"is_valid":true}],"emeters":[{"power":3269.48,"pf":1.00,"current":14.35,"voltage":227.90,"is_valid":true,"total":7589.6,"total_returned":17706.2},{"power":147.60,"pf":0.56,"current":1.12,"voltage":234.34,"is_valid":true,"total":469.4,"total_returned":3188.7},{"power":193.11,"pf":0.74,"current":1.12,"voltage":231.52,"is_valid":true,"total":435.7,"total_returned":943.7}],"fs_mounted":true,"update":{"status":"idle","has_update":false,"new_version":"20200205-183800/master@fa9ba943","old_version":"20200205-183800/master@fa9ba943"},"ram_total":48704,"ram_free":31096,"fs_size":233681,"fs_free":162146,"uptime":930}

`

**Comment by chemelli74** [comment]
@kuradi,thx for the "status" page.

 Can you please post also "settings" ? 

Finally, please add "payload" to your configuration.yaml under shelly: Section and post home-assistant.log with CoAP message.

Thank you,

Simone

**Comment by emilp333** [comment]
/settings

`{"device":{"type":"SHEM-3","mac":"*****48C6","hostname":"shellyem3-****227648C6","num_outputs":1, "num_meters": 0, "num_emeters":3},"wifi_ap":{"enabled":false,"ssid":"shellyem3-****227648C6","key":""},"wifi_sta":{"enabled":true,"ssid":"****","ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"wifi_sta1":{"enabled":false,"ssid":null,"ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"mqtt": {"enable":false,"server":"x.x.x.x:1883","user":"","id":"shellyem3-****227648C6","reconnect_timeout_max":60.000000,"reconnect_timeout_min":2.000000,"clean_session":true,"keep_alive":60,"max_qos":0,"retain":false,"update_period":30},"coiot": {"update_period":15},"sntp":{"server":"time.google.com","enabled":true},"login":{"enabled":false,"unprotected":false,"username":"***","password":"***"},"pin_code":"****","name":"","fw":"20200205-183800/master@fa9ba943","discoverable":true,"build_info":{"build_id":"20200205-183800/master@fa9ba943","build_timestamp":"2020-02-05T18:38:00Z","build_version":"1.0"},"cloud":{"enabled":true,"connected":true},"timezone":"Europe/Stockholm","lat":52,"lng":11.191000,"tzautodetect":true,"tz_utc_offset":3600,"tz_dst":false,"tz_dst_auto":true,"time":"13:41","hwinfo":{"hw_revision":"prod-2020-1", "batch_id":1},"max_power":0,"relays":[{"name":null,"ison":false,"has_timer":false,"overpower":false,"default_state":"off","auto_on":0.00,"auto_off":0.00,"max_power":0,"out_on_url":null,"out_off_url":null,"schedule":false,"schedule_rules":[]}],"emeters":[{"ctraf_type":50},{"ctraf_type":50},{"ctraf_type":0}]}`

**Comment by emilp333** [comment]
I do not see any payload in the log after enabling payload attribute. I do see that attribute in created entities but the 3EM does not get created. I'll check and see if I can adjust log level or something.

**Comment by emilp333** [comment]
Any progress on this? Do you need any other input?

**Comment by petergebruers** [comment]
I can see COAP messages by using Wireshark... This is the decode... does this help?

`{"G":[[0,112,0],[0,111,47.360000],[0,114,0.312814],[0,115,0.640570],[0,116,236.125200],[0,121,5.220000],[0,124,0.399388],[0,125,0.055230],[0,126,236.817000],[0,131,53.000000],[0,134,0.952381],[0,135,0.236290],[0,136,235.659600]]}`

I cannot get 100% identical numbers from status page, my guess is the internal sample rate is rather high so I cannot get status and COAP at the exact same time.

```json
{
  "wifi_sta": {
    "connected": true,
    "ssid": "telenet-****",
    "ip": "*****",
    "rssi": -59
  },
  "cloud": {
    "enabled": true,
    "connected": true
  },
  "mqtt": {
    "connected": false
  },
  "time": "14:35",
  "serial": 158,
  "has_update": false,
  "mac": "****",
  "relays": [
    {
      "ison": false,
      "has_timer": false,
      "overpower": false,
      "is_valid": true
    }
  ],
  "emeters": [
    {
      "power": 47.15,
      "pf": 0.31,
      "current": 0.64,
      "voltage": 236.39,
      "is_valid": true,
      "total": 5819.2,
      "total_returned": 0
    },
    {
      "power": 5.18,
      "pf": 0.4,
      "current": 0.05,
      "voltage": 236.93,
      "is_valid": true,
      "total": 953.2,
      "total_returned": 0
    },
    {
      "power": 53.02,
      "pf": 0.95,
      "current": 0.24,
      "voltage": 235.59,
      "is_valid": true,
      "total": 2823,
      "total_returned": 0
    }
  ],
  "fs_mounted": true,
  "update": {
    "status": "idle",
    "has_update": false,
    "new_version": "20200205-183800/master@fa9ba943",
    "old_version": "20200205-183800/master@fa9ba943"
  },
  "ram_total": 48704,
  "ram_free": 31260,
  "fs_size": 233681,
  "fs_free": 162146,
  "uptime": 15400
}
```

**Comment by iz3man** [comment]
I got this installed a week ago as well. Can I do anything to support?
It would be especially helpful to get the "used energy" from the device (last 24h, day, week, month, year ..). Everything else can be seen over MQTT already, still it's nice to have this installed via "integrations."

**Comment by JamesT42** [comment]
The Shelly EM has used energy etc. available via MQTT, so I think this is an oversight that it is missing from the 3EM MQTT data...

**Comment by iz3man** [comment]
So maybe we can expect this in a update from Shelly.

**Comment by chemelli74** [comment]
Please upgrade to 0.1.7b1 and recheck.

Simone

**Comment by petergebruers** [comment]
@chemelli74 big thanks! CoAP discovered these devices (see screenshot), the values make sense and match... I would, however, name the phases A, B and C instead of 1,2,3 to be consistent with the Shelly docs and (web) interface

<img width="458" alt="Screenshot 2020-03-06 at 09 21 49" src="https://user-images.githubusercontent.com/5297547/76065556-2e981380-5f8c-11ea-8689-a5cbc54c3956.png">

The switch is working "more or less" but I think that is not a 3EM issue but a 1.7 beta problem, in the BUI the switch "jumps" between on and off. It will settle on the right state eventually and does control the output as expected. I have no other Shelly devices on this particular network only a Shelly 3EM, so nothing to compare with.

**Comment by iz3man** [comment]
I'm still waiting for the 0.1.7 release before I install, so is it possible to not only see total consumption but also "last 24h". weekly. monthly and so? Or needs this to be handled by a counting automation?

**Comment by petergebruers** [comment]
@iz3man 
> is it possible to not only see total consumption but also "last 24h". weekly. monthly and so? Or needs this to be handled by a counting automation?

AFAIK what you want is a feature of the Shelly Cloud, the device itself does not report day/week/...

See https://github.com/StyraHem/ShellyForHASS/issues/191#issuecomment-590870669 for output in JSON and coap, there is no such thing as day/week/...

So yeah, need to store the Wh values with timestamp and do the math.

Unless there is some (hidden) feature to get the numbers from the device... I don't know.

This is a bit tangential, but you can download timestamped data from the device by calling "em_data.csv" like this

`http://192.168.1.177/emeter/0/em_data.csv`

It is not documented for the 3EM, I guess the 0 means phase A, but I did not thoroughly check this.

```
Date/time UTC,Active energy Wh,Returned energy Wh
2020-03-06 09:50,3.1,0.0
2020-03-06 09:55,3.1,0.0
2020-03-06 10:00,3.2,0.0
2020-03-06 10:05,3.1,0.0
...
```

**Comment by chemelli74** [comment]
> I'm still waiting for the 0.1.7 release before I install, so is it possible to not only see total consumption but also "last 24h". weekly. monthly and so? Or needs this to be handled by a counting automation?

You need to use "utility_meter" from HA ;-)

Simone

**Comment by iz3man** [comment]
@chemelli74 Could you please enlighten me? Never heard of. I will need to google it immediately. At the moment I'm using self written automation which is far from comfortable, and I'm not sure they are 100% correct either.

**Comment by hakana** [comment]
https://www.home-assistant.io/integrations/utility_meter/

**Comment by iz3man** [comment]
WOW. You're quicker than google :)
Thank you all. This totally went past me. Much appreciated ...

**Comment by chemelli74** [comment]
@jarnojlaine, @petergebruers, @iz3man please confirm issue is fixed in latest beta.

Thank you,

Simone

**Comment by petergebruers** [comment]
3EM power reporting is working on 0.1.7b2, I don' see any change with respect to naming of the devices (I suggested... I would, name the phases A, B and C instead of 1,2,3 to be consistent with the Shelly docs and (web) interface) but that is not too important and the switch still "jumps" between on and off of but I don't care about that bug. The main thing is I get power and energy reporting :)

**Comment by hakana** [comment]
0.1.7.b2 is not released, see releases in github for latest release if not using HACS!

**Comment by petergebruers** [comment]
I did notice something else but it might be related to hass 0.106.5 (but I don't see a similar report on their forum), I upgraded to this version a few days ago... Sometimes, briefly, all shelly 3EM sensors show "Unavailable". It looks a bit like the problem described in https://github.com/StyraHem/ShellyForHASS/issues/207 but in my case it only goes to Unavailable "in the blink of an eye", it took me quite a while to notice it...

**Comment by petergebruers** [comment]
> 0.1.7.b2 is not released, see releases in github for latest release if not using HACS!

I already told you it was working on 0.1.7.b1 3 days ago, so I naturally assumed you were talking about the 0.1.7.b2 you mentioned on 'master' branch...

Don't you appreciate my feedback here?

**Comment by iz3man** [comment]
> @jarnojlaine, @petergebruers, @iz3man please confirm issue is fixed in latest beta.

Hi Simone I wish I could. I'm using HACS, so don't see a way to test beta versions.

**Comment by chemelli74** [comment]
> > @jarnojlaine, @petergebruers, @iz3man please confirm issue is fixed in latest beta.
> 
> Hi Simone I wish I could. I'm using HACS, so don't see a way to test beta versions.

https://github.com/StyraHem/ShellyForHASS/wiki/FAQ5:-Enable-beta-in-HACS

Simone

**Comment by iz3man** [comment]
Thanks Simone. You learn every day :)

After upgrading to 0.1.7b1 the 3EM showed up in integrations instantly. Added all to Lovelace, customized the naming, and this is what it looks like:

![image](https://user-images.githubusercontent.com/11553674/76223278-a16aee00-621b-11ea-93c8-c353780cdfa8.png)

Seems to work fine. Now I need to find out how to make it show kWh and then sum it all up and add the hourly, daily, weekly, monthly numbers, and I'm happy. 

Great work!!!

**Comment by chemelli74** [comment]
> Seems to work fine. Now I need to find out how to make it show kWh and then sum it all up and add the hourly, daily, weekly, monthly numbers, and I'm happy.

Go with “utility_meter”

> Great work!!!

The author is really great!

Simone
