### ISSUE TITLE
[Question/FR] Too many attributes

### ISSUE THREAD

**Issue by GoNzCiD** [StyraHem/ShellyForHASS#194]
Hi, I have a question about attibutes showed in a light entity.

When `additional_information` is set to True it shows a lot of attributes into the light entity. It's fantastic, but when record is enable for this entity, it's writting continously a lot of entries to database, maybe the signal or temperature changes a lot of times and HA detects a change and write to database.

It should be possible to choose the attributes you want to use?

Thanks

**Comment by hakana** [comment]
Please see readme file, there is a config for this (attributes).
