### ISSUE TITLE
Password request during integration

### ISSUE THREAD

**Issue by claustro** [StyraHem/ShellyForHASS#197]
Hi all , excuse me for this dumb question .  But when I try to integrate Shelly smart home in home assistant it ask me for a password. Which password is it? I tried the shelly cloud one but it doesn't work

My device is discovered using simply 
` shelly:
discovery: true`
but I would like to link the names of devices to the cloud one so I tried to use 

```
shelly:
  cloud_auth_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  cloud_server: "shelly-XXXXX.shelly.cloud"
```
but is doesn't work.
No errors on log

thank you

![pass](https://user-images.githubusercontent.com/11670954/75031938-a7d13a00-54a7-11ea-8eb5-9d9006150794.jpg)

**Comment by hakana** [comment]
The integration only working by adding it using config.yaml. The dialog you have in the picture is not working.
Did you found the auth-key in my shelly cloud?

**Comment by chemelli74** [comment]
Please upgrade to 0.1.7b1 and recheck.

Simone

**Comment by chemelli74** [comment]
No update for 21 days from the user, closing.

Simone
