### ISSUE TITLE
Shelly 1 - No response to On/Off commands

### ISSUE THREAD

**Issue by ameennihad** [StyraHem/ShellyForHASS#198]
Home Assistant 0.105.4
Release 0.1.6

Some of my Shelly 1 devices report the status normally but I can't switch them on/off, following are some screenshots for working not working devices, any idea what can be the reason?

Note that all Shelly 1 device are running  latest firmware and not connected to cloud:
_**The current Firmware version of your Shelly device is 20200206-083100/v1.5.10@e6a4205e No newer firmware available.**_

While pasting the screenshots I notices that all not working devices are Version 1, the working ones are V3. Could that be the reason!

**Comment by ameennihad** [comment]
I figured out the cause of this issue, on my first batch of Shelly 1 devices I enabled RESTRICT LOGIN, I removed that from one of the devices and I can control it normally now form HA.
What would be the solution if I want to keep RESTRICT LOGIN enabled?

**Comment by chemelli74** [comment]
@ameennihad, currently you have to set the same login to all devices (or to none of them).

Simone

**Comment by hakana** [comment]
You can also mix devices with none and restricted login, but all restricted need same user/password
