### ISSUE TITLE
Shelly EM total consumption

### ISSUE THREAD

**Issue by NateLogan** [StyraHem/ShellyForHASS#202]
Hello,

I am trying to set up Shelly EM power meter, but recieved value for total_consumption_attr is wrong. In fact, it is 60 times lower than what I get from REST command or from Shelly cloud.

This seems to be an issue only with EM, other Shellies looks OK. 
 
In this screenshot, first and third values are from ShellyForHASS, second and fourth are from REST sensor.  

![Screenshot_20200224_223221_com android calculator2](https://user-images.githubusercontent.com/442064/75195175-c0687b00-5759-11ea-8cbb-4e329277fa85.jpg)

Edit:
Sorry for a duplicit post, same issue here: [Issue 200](https://github.com/StyraHem/ShellyForHASS/issues/200)

**Comment by chemelli74** [comment]
Known issue, fixed in upcoming 0.1.7b1

Simone
