### ISSUE TITLE
Write current_consumption at least every hour 

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#204]
Feature Request:

Write current_consumption value at least every hour to DB so that utility_meter can measure energy correctly.

If you've very static load like a heater which is using eg. 18W for 10h a day utility_meter stays at 0 kWh because there is no change of the load (W) in current_consumption. This results in inaccurate values because kWh values are not updated for 10h.

**Comment by chemelli74** [comment]
Why are you using utility meter for current consumption ? 
I use it for historical data (daily, monthly) but for current I just sum all sensors.

Simone

**Comment by vistalba** [comment]
No... I think you don't understand.

`current_consumption` is the value of now. It results in kWh (W/min) if you add the "time" dimention.  Utility_meter does this. It looks on the `current_consumption` value and the time and does show you how much energy you used in a period of month/week/day/year... or whatever you define. If the value is 10h old... it doesn't calculate the kWh value.

`total_consumption` isn't a solution because `total_consumption` is 0 after reboot/firmware upgrade of shelly. So in this case you have to recalculate the usage everytime the `total_consumption` value retunred is smaller than the last value. If this happen you have to calculate old_value + new_value.
And also this doesn't cover the time-based thing (daily, monthly..)

**Comment by chemelli74** [comment]
Hi, sorry but this is not the intented usage.

I'm on "current_consumption" for istant values; and as such I don't care to store them.

I use instead total_consumption for your use case. As utility_meter does the math: store the difference between current and previous value. Not the absolute value.
So even if you reboot the Shelly, it will store the sum of all consumptions based on total (from CoAP and previous period).

If you need any more info on my setup, I'll share.

Simone

**Comment by emilp333** [comment]
I think you got it wrong Vistalba. I did the same mistake with the utility meter in the past.
`current_consumption`will give you the value of the energy right now in W. Not Wh or kWh.
Utility meter calculates the differences between the values but operates in kWh or Wh whatever you send in to it.
But to make a proper energy consumption calculation you need to take the current consumption and do the time based calculation. This is done by the `integration` component, https://www.home-assistant.io/integrations/integration/.

Then you use that sensor to feed your utility meter.

**Comment by emilp333** [comment]
This is an example:
In your sensor component configuration:
```
- platform: integration
  source: sensor.shelly_shsw_pm_current_consumption
  name: myshelly_consumption
  unit_prefix: k
  round: 2
```
In your utlity_meter configuration:
```
shelly_pm_daily_consumption:
  source: myshelly_consumption
  cycle: daily
whelly_pm_monthly_consumption:
  source: myshelly_consumption
  cycle: monthly
shelly_pm_yearly_consumption:
  source: myshelly_consumption
  cycle: yearly
```
If the `totalt_consumption` attribute was not reset then you could use that to feed utility meter instead. But you cant use the current_consumption to feed utility meter.

**Comment by emilp333** [comment]
Or maybe it even works like @chemelli74 said if Utility meter handles the reset of totalt consumption. I was unaware of that. I was afraid it would count back if that was the case.

**Comment by vistalba** [comment]
> But to make a proper energy consumption calculation you need to take the current consumption and do the time based calculation. This is done by the `integration` component, https://www.home-assistant.io/integrations/integration/.

This is exactly what I'm doing.
I use `current_consumption` and use integration and utility_meter to calculate kWh from W.

But... why I open this issue is... if you have static load that uses constant 18W for 10h then after 59 minutes the kWh from utility_meter is still 0 because there is no new value (what is wrong, it is just the same as before). This results in wrong calculation.

**Comment by vistalba** [comment]
> Or maybe it even works like @chemelli74 said if, Utility meter handles the reset of totalt consumption. I was unaware of that. I was afraid it would count back if that was the case.

Didn't tried that and I also don't see why I should try and loos all of my history. That is not the sense of my energy monitoring.

**Comment by emilp333** [comment]
> But... why I open this issue is... if you have static load that uses constant 18W for 10h then after 59 minutes the kWh from utility_meter is still 0 because there is no new value (what is wrong, it is just the same as before). This results in wrong calculation.

Do you mean that your integration sensor is also 0? That sounds strange. 
> Didn't tried that and I also don't see why I should try and loos all of my history. That is not the sense of my energy monitoring.

I do not think the utlity meter is reseted when you change the source.

**Comment by vistalba** [comment]
> Do you mean that your integration sensor is also 0? That sounds strange.
> 
> >

Yes. Until next value change the utility_meter value is 0. Everything is working fine as long as the `current_consumption` value changes often enought (so, at least one time a hour) to calculate hourly kWh usage.

**Comment by chemelli74** [comment]
> > Or maybe it even works like @chemelli74 said if, Utility meter handles the reset of totalt consumption. I was unaware of that. I was afraid it would count back if that was the case.
> 
> Didn't tried that and I also don't see why I should try and loos all of my history. That is not the sense of my energy monitoring.

@vistalba you can create a new sensor, and only once it's working remove the old one. So you don't risk your data.

Simone

**Comment by chemelli74** [comment]
> > Do you mean that your integration sensor is also 0? That sounds strange.
> > >
> 
> Yes. Until next value change the utility_meter value is 0. Everything is working fine as long as the `current_consumption` value changes often enought (so, at least one time a hour) to calculate hourly kWh usage.

Definitly a issue somewhere, doesn't work like this here.
Can you enable debug lof for "pyShelly" and see if the coAP incoming message is wrong ?

Simone

**Comment by vistalba** [comment]
> Can you enable debug lof for "pyShelly" and see if the coAP incoming message is wrong ?

Is there a how to?

**Comment by chemelli74** [comment]
> > Can you enable debug lof for "pyShelly" and see if the coAP incoming message is wrong ?
> 
> Is there a how to?

https://github.com/StyraHem/ShellyForHASS/wiki/FAQ4:-Enable-debug-log

Simone

**Comment by vistalba** [comment]
>  @vistalba you can create a new sensor, and only once it's working remove the old one. So you don't risk your data.


I just created a new one to test.
I've to convert Wh to kWh (because shelly is reporting Wh. To show big values and calculate cost I need kWh).

This looks like it is working and I've just to switch the entity in utility_meter config.
But I want to show acual consumption too (as value & graph).

Like this:
![image](https://user-images.githubusercontent.com/12324196/75672872-f473fc80-5c81-11ea-8242-31ae22b2db39.png)

In this case I now need to use both values and record both values :( Because I can't show just "current_consumption" and use "total_consumption" for the graph.

Any ideas how to solve that?

**Comment by chemelli74** [comment]
@vistalba, can you post the related part of your current config ?

Simone

**Comment by chemelli74** [comment]
> @vistalba, can you post the related part of your current config ?
> 
> Simone

@vistalba can you share your config ?

Simone

**Comment by vistalba** [comment]
For me it looks line it works now with 0.1.7b3 as the value update is now much faster also if the load is very similar.
