### ISSUE TITLE
Settings panel is too long in 0.1.7 beta 1

### ISSUE THREAD

**Issue by Misiu** [StyraHem/ShellyForHASS#209]
The setting window is too long:
![image](https://user-images.githubusercontent.com/1741838/76040035-7ef08080-5f4e-11ea-8fe9-70565536d16f.png)
I had to zoom out to be able to see the `Submit` button

**Comment by chemelli74** [comment]
Confirmed.

Simone

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.7.b2) and recheck.

Simone

**Comment by Misiu** [comment]
@chemelli74 I just updated to 0.1.7.b2 and I have the exact same bug (the panel is still too long).
I have screen resolution 1680x1050.
If I change the zoom to 80% (in Chrome I see the submit button).

**Comment by hakana** [comment]
Fixed in 0.1.7.b3

**Comment by Misiu** [comment]
Now it looks great!
Thank you.
@chemelli74 you can close this issue now.

**Comment by hakana** [comment]
👍

**Comment by Misiu** [comment]
@hakana ideally config dialog should allow scrolling if there are large number of options.
There are scrollable containers in Lovelace, I'll create a feature request for adding this to config flow.

**Comment by hakana** [comment]
This os controlled by HA so you need to add FR to HA.

**Comment by Misiu** [comment]
FR created: https://github.com/home-assistant/frontend/issues/5253

**Comment by bramkragten** [comment]
Why not use a multiselect input for this?

**Comment by hakana** [comment]
Because HA not supporting that for settings

**Comment by Misiu** [comment]
@hakana check for example plex: https://github.com/home-assistant/core/blob/dev/homeassistant/components/plex/config_flow.py#L287 or Unifi https://github.com/home-assistant/core/blob/dev/homeassistant/components/unifi/config_flow.py#L210

**Comment by chemelli74** [comment]
With 0.2.0 milestone author will design a completly new GUI for settings so this issue will be superseded.

Closing.

Simone
