### ISSUE TITLE
[Feature] Option for exposing overtemperature and overpower sensor

### ISSUE THREAD

**Issue by rufik** [StyraHem/ShellyForHASS#21]
It would be nice to have an options for exposing:
- overtemperature as binary sensor
- overpower as binary sensor

**Comment by hakana** [comment]
You can do that easy with the sensor template. I will add an example of it to the doc shortly.

**Comment by rufik** [comment]
Yes, I know. But it requires more configuration than just a single line in shelly config section...maybe should I code it myself and send you PR? :)

**Comment by astrandb** [comment]
If you are considering to make the component official it might be better be a bit restrictive with exposing all attributers as sensors. If you have e.g. 25 shellies with 4-5 sensors each, the UI would be cluttered for those that just want to see the switch in the UI.
An alternative is to make a configuration option which attributes to expose as sensors.

**Comment by hakana** [comment]
@rufik , the coding is not the problem it is to keep it simple. But I will look if we can do it in a nice way in next release.

**Comment by hakana** [comment]
Fixed in latest release, 0.0.15!
