### ISSUE TITLE
Can't edit settings in the integrations menu in 0.1.7 beta 1

### ISSUE THREAD

**Issue by Misiu** [StyraHem/ShellyForHASS#210]
When adding ShellyForHass via Integration panel I can't update the setting (using cog icon in top right)
![image](https://user-images.githubusercontent.com/1741838/76040115-c8d96680-5f4e-11ea-96c3-78982f3d32d0.png)

After putting new values and hitting `Submit` the values aren't getting saved.

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.7.b2) and recheck.

Simone

**Comment by Misiu** [comment]
Sadly this still isn't working.
I've updated to the latest beta (0.1.7.b2), restarted Home Assistant couple of times, cleared the cache in the browser, even tried in Incognito mode, but I always get the same results.

**Comment by hakana** [comment]
Have you checked if you can see any error in log?

**Comment by Misiu** [comment]
@hakana I have this in my config:
```
logger:
  default: critical
  logs:
    custom_components.shelly: debug
    pyShelly: debug
    shelly: debug
```

nothing unusual in logs.

I've noticed this behavior:
 when I edit settings (using gear icon) I get a success message:
![image](https://user-images.githubusercontent.com/1741838/76795684-1f099d80-67ca-11ea-870f-e3b9fe033a6f.png)
when I click the same edit button I get old values (it looks like they didn't save),
but after a restart, the settings are stored.
The setting button is saving the config, but we must restart Home Assistant to have them applied.
Edit settings fo shelly (gear icon) is always showing the old config.

Could you check that on your side?

**Comment by Misiu** [comment]
Same with 0.1.7-beta.3

**Comment by hakana** [comment]
You need to restart HA after changing settings. What is not working?

**Comment by Misiu** [comment]
@hakana I was thinking that I don't need to restart HA.
It would be awesome if integration could reload with new config, but I think that's a feature request for HA.

**Comment by hakana** [comment]
Yes I agree, it can be fixed in the component also but it is a big change because it not build for that from the beginning.

**Comment by Misiu** [comment]
So maybe let's leave this as a feature request? Or I can create a new issue for that.
That's not very important, but would be a great addition.
For now, I think this should be documented that changing integration settings requires HA restart to apply them.

**Comment by hakana** [comment]
I have that on my todo but never wrong to put an FR on it.

**Comment by chemelli74** [comment]
> For now, I think this should be documented that changing integration settings requires HA restart to apply them.

I would say we can add to the  "Option successfully saved" also a "Remember to restart HA to make the changes active" or something similar.

Simone

**Comment by chemelli74** [comment]
> I would say we can add to the "Option successfully saved" also a "Remember to restart HA to make the changes active" or something similar.
> 

Unfortunately we cannot edit the message from HA, it's embedded.

Simone

**Comment by chemelli74** [comment]
Nothing we can do more than documenting the need of restart.
Closing.

Simone
