### ISSUE TITLE
Rgbw2 doesnt work in 0.1.7 beta1

### ISSUE THREAD

**Issue by dodg3r** [StyraHem/ShellyForHASS#211]
Hi.
My hassio can´t find my rgbw2 shellys after upgrading to 0.1.7 beta1.

Do you want logfiles ?

**Comment by chemelli74** [comment]
> Do you want logfiles ?

Yes please, but with debug enabled.

Simone

**Comment by dodg3r** [comment]
HI.

All of a sudden my rgbw2 units shows up and works. I dont know why.

Sorry for wasting your time :(

**Comment by chemelli74** [comment]
> HI.
> 
> All of a sudden my rgbw2 units shows up and works. I dont know why.
> 
> Sorry for wasting your time :(

No problem, please close the issue

Simone
