### ISSUE TITLE
Status delay 

### ISSUE THREAD

**Issue by ishalem** [StyraHem/ShellyForHASS#213]
I have shelly 1 installed and working perfectly, the problem with the Homeassistantconnection is that there is a delay (more than 30 sec) until the state is updated
this is a new issue, I didn't have it in the past

I use:
ShellyForHASS: 0.1.6
Home Assistant release with the issue: 0.106.5
Operating environment : docker on linux (ubuntu)

**Comment by gaggio** [comment]
I can confirm the same behaviour, same versions as above, rasberry pi 3 (hass.io)

**Comment by chemelli74** [comment]
Please report how your devices are discovered

Simone

**Comment by ishalem** [comment]
not sure what you mean.
all devices were added through the Shelly mobile app
and were discovered automatically by Homeassistantafter installing the ShellyForHass from HACS

**Comment by chemelli74** [comment]
> not sure what you mean.
> all devices were added through the Shelly mobile app
> and were discovered automatically by Homeassistant after installing the ShellyForHass from HACS

Please check HA identities and there you'll find the discovery method I'm interested in.

Simone

**Comment by gaggio** [comment]
mine has CoAP-discovery

**Comment by ishalem** [comment]
CoAP-discovery

**Comment by gaggio** [comment]
> mine has CoAP-discovery

Actually I just connected another shelly (it is a 2.5) that shows the same behaviour but has been discovered by mDns.

**Comment by me1299** [comment]
Same problem here with discover_by_ip mode.

**Comment by chemelli74** [comment]
Confimed on 0.1.7.b1 with CoAP Discovery.

Simone

**Comment by me1299** [comment]
If you need any more information please let me know. Right now my door sensor isn't working because toggle.light isn't working correctly because HA thinks the light status hasn't changed.

**Comment by chemelli74** [comment]
@ishalem , @gaggio, @me1299 please update to latest beta (0.1.7.b2) and recheck.

Simone

**Comment by ishalem** [comment]
Is there a way to do it from HACS? or do I have to manually install?

**Comment by chemelli74** [comment]
> Is there a way to do it from HACS? or do I have to manually install?

https://github.com/StyraHem/ShellyForHASS/wiki/FAQ5:-Enable-beta-in-HACS

Simone

**Comment by ishalem** [comment]
not fixes yet still not updated immediately - took ~1 min
I checked the discovery and now it says "CoAP-discovery, poll"

**Comment by ishalem** [comment]
also when I click on the on/off inside HA its changing stage for a sec and
go back to the previous state but the actual state changes
e.g. turn on the light from off state in HA will turn the light on and the
button in Homeassistantwill move for a sec to on and get back to off for a
min until synced

**Comment by gaggio** [comment]
> @ishalem , @gaggio, @me1299 please update to latest beta (0.1.7.b2) and recheck.

Confirmed the same behaviour on 0.1.7.b2, approx. 1min to get status update.

**Comment by me1299** [comment]
> also when I click on the on/off inside HA its changing stage for a sec and go back to the previous state but the actual state changes e.g. turn on the light from off state in HA will turn the light on and the button in Homeassistantwill move for a sec to on and get back to off for a min until synced
> […](#)

I experience the same behavior. Switch a light and the status will revert until after some time HA catches up to the actual status.

**Comment by chemelli74** [comment]
@ishalem, @gaggio, @me1299 if you miss "CoAP-msg" this is the reason of the delay as it will fall back to "poll". 

Simone

**Comment by ishalem** [comment]
this issue started before the latest firmware
Let wait for Shelly to release the fix and well check again.

**Comment by chemelli74** [comment]
> this issue started before the latest firmware
> Let wait for Shelly to release the fix and well check again.

Sorry, ca you explain better what you mean ?
Thank you,

Simone

**Comment by ishalem** [comment]
I mean that I'm not sure the problem is with the Shelly firmware as I opened this issue before it was released
If you think it's related we can wait for the new firmware and check again if the problem still exists

**Comment by chemelli74** [comment]
> I mean that I'm not sure the problem is with the Shelly firmware as I opened this issue before it was released
> If you think it's related we can wait for the new firmware and check again if the problem still exists

Absolutely not a firmware issue, I'm 99% convinced it's a network problem.
As you don't receive "CoAP-msg", this is the reason of the delay.

Please try adding "scan_interval" to your config as low as 5 seconds and report back.

Simone

**Comment by ishalem** [comment]
update, after changing scan_interval to 5 its now working. but the strange thing is that when I changed back to 60 it kept working..
(I did restart the HA after every change)

**Comment by gaggio** [comment]
Update:
After upgrade to 0.1.7.b2, both devices show: "CoAP-discovery, poll, mDns, CoAP-msg".
But the behavior is still the same. Additionally, the device becomes briefly unavailable every few minutes.
Now set scan_interval to 5, devices react much faster as expected. But now, after restart, on protocols I can only see "CoAP-discovery, poll, mDns".

**Comment by chemelli74** [comment]
https://github.com/StyraHem/ShellyForHASS/wiki/FAQ2:-Slow-updates-of-lovelave-UI

Simone

**Comment by gaggio** [comment]
> Now set scan_interval to 5, devices react much faster as expected. But now, after restart, on protocols I can only see "CoAP-discovery, poll, mDns".

Further update: 
- CoAP-msg has reappeared
- removed scan_interval: 5 for testing, restarted
- CoAP-msg disappeared again, behavior back to large delay in status response
I'll leave it running as is, to see if CoAP-msg appears again.

(I live in Italy, as I believe you are Simone, so have plenty of time to spend at home for testing...)

**Comment by chemelli74** [comment]
> Further update:
> 
> [...]

Please continue discussion in a post inside the Facebook group.
Thank you,

Simone
