### ISSUE TITLE
[FR] allow to configure decimals in device config for other devices

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#215]
As described here with `power_decimals`: https://github.com/StyraHem/ShellyForHASS/issues/203

I like to "round" also the decimals of my temperature sensor to prevent from storing unnecessary values like this:

![image](https://user-images.githubusercontent.com/12324196/76307882-f5341080-62c9-11ea-8bdc-5b50ca69d114.png)

This is the teperature from my Shelly H&T. As you can see, it has a lot of different values in the last 24h. But the differences between this valus are not really important as the lowest value is 11.50 °C and the highest is 11.80 °C.

All measured valus in 24 are:
- 11.50
- 11.60
- 11.62
- 11.75
- 11.80

So may it would be helpful to round to:

a) 1 °C (without decimals)
b) x.1 °C
c) x.0 and x.5 °C values

Would that be possbile?

**Comment by chemelli74** [comment]
Added to 0.1.7b6. See release notes.

Simone

**Comment by vistalba** [comment]
Tested. Works for me. Thx.
