### ISSUE TITLE
0.1.7b1: Plug-S unconnected but still seen as active

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#217]
Seems that with latest beta, on top of the flip ( #207 ), when I unplug my Shelly's Plug-S system doesn't recognize that action.

Been attached to an iron, can happen that it is detached while there is still some consumption; this is reported as active after 1 hour, but obviously it's not:

![image](https://user-images.githubusercontent.com/57354320/76331121-00e5fe00-62ef-11ea-8adb-fd2e948781d8.png)

Simone

**Comment by hakana** [comment]
Fixed in 0.1.7.b3

**Comment by chemelli74** [comment]
Confirmed to be fixed. Thx!
