### ISSUE TITLE
How to get position value on shelly 2.5 as roller

### ISSUE THREAD

**Issue by Sailorsbe** [StyraHem/ShellyForHASS#220]
Hello
I'm newbie in hassio and ready to learn the system.
I have 3 Shelly 2.5 installed on different rollers. I can operate all of them with MQTT but prefer to do it with this user component.
For automation issues I want to have a value for the position of each of the rollers so I can use it as a condition in an automation rule. How can i do that? Thanks for the answer

**Comment by hakana** [comment]
Have you tried, it should work like this.

**Comment by Sailorsbe** [comment]
I tought to do it that way
<sensor:
  - platform: Shelly
    entity_id: "voletch"
    name: "Position"
    position_topic:??????????????
    unit_of_measurement: "%"
    icon: mdi:percent>
But I Don't know what to put on ????

**Comment by hakana** [comment]
Please have a look at the readme file.
https://github.com/StyraHem/ShellyForHASS/blob/master/README.md

You should only add the shelly platform to config.yaml,
shelly:
