### ISSUE TITLE
Shelly Duo - can't change color temperature

### ISSUE THREAD

**Issue by Misiu** [StyraHem/ShellyForHASS#221]
When trying to change color temperature I get this error:
![image](https://user-images.githubusercontent.com/1741838/76685361-5124cf00-6613-11ea-853c-014b57624346.png)

I'm using ShellyForHass 0.1.7 beta 2

![image](https://user-images.githubusercontent.com/1741838/76685438-e45e0480-6613-11ea-9232-36955890bf0d.png)

**Comment by me1299** [comment]
Could very well be a bug in the firmware. The same problem is present when using MQTT.

**Comment by Misiu** [comment]
@me1299 this is possible. Did you report this problem to Shelly via their Facebook profile? Maybe they don't know about this bug.

**Comment by me1299** [comment]
Their Facebook page says they are aware of the problem and will release a new firmware. They just released one a few days ago, but I don't think it fixed the issue.

**Comment by Misiu** [comment]
could you post a link to that post? It will be useful.

**Comment by hakana** [comment]
Fixed, will be available in 0.1.7.b3

**Comment by Misiu** [comment]
@hakana any plans to release a new beta soon? 🤞

**Comment by hakana** [comment]
Yes, now!

**Comment by Misiu** [comment]
This works fine now 🎉 , but I got confused a bit at first.
In Shelly app warm white (yellow) is on left, but is HA it is on right. Is this configurable?

**Comment by hakana** [comment]
No, it can't be changed from our component.

**Comment by hakana** [comment]
I close this issue as it is fixed in 0.1.7.b3.

**Comment by Misiu** [comment]
@hakana thanks for the reply!
