### ISSUE TITLE
0.1.7.b2: I can't see the 'protocols' attribute in any of my devices

### ISSUE THREAD

**Issue by pablitofernandez** [StyraHem/ShellyForHASS#224]
Home Assistant 0.106.6 running inside a Docker Container. Using 0.1.7.b2 with config migrated to integration database. I can't see any protocols attribute, I can only see this:

![image](https://user-images.githubusercontent.com/5592837/76999827-96206c80-6957-11ea-944f-569ee4e03dff.png)

BTW Coap is working correctly.

**Comment by chemelli74** [comment]
Please update to 0.1.7.b3 and report back.

Simone

**Comment by pablitofernandez** [comment]
Just installed it:

![image](https://user-images.githubusercontent.com/5592837/77015860-6339a100-6976-11ea-8b7c-1e93206ce00c.png)

Same behaviour of Beta2:

![image](https://user-images.githubusercontent.com/5592837/77015904-7cdae880-6976-11ea-9d23-eaac42582ccf.png)

![image](https://user-images.githubusercontent.com/5592837/77015920-882e1400-6976-11ea-9e78-4b274d9499b5.png)

**Comment by chemelli74** [comment]
Click on one entity, like the switch.

Simone

**Comment by pablitofernandez** [comment]
> Click on one entity, like the switch.
> "Protocols" is an attribute, not an entity.
> 
> Simone

And now I can see it, thanks!!
