### ISSUE TITLE
UI integration from HACS

### ISSUE THREAD

**Issue by koldogut** [StyraHem/ShellyForHASS#225]
What's supposed to be typed here??
![Shelly_UI_integration](https://user-images.githubusercontent.com/43078880/77059354-1508ba00-69d7-11ea-8bbd-285bdd4c7108.GIF)

**Comment by chemelli74** [comment]
which build are you using ?

If not 0.1.7 beta3, please update.
If you don't know how to show betas in HACS, follow our wiki: [https://github.com/StyraHem/ShellyForHASS/wiki/FAQ5:-Enable-beta-in-HACS](url)

Simone

**Comment by koldogut** [comment]
Thanx! The link doesn't work but i've found the way to show betas (click on the 3 dots on the right - enable beta)
