### ISSUE TITLE
How to setup to have realtime state update instead of polling ?

### ISSUE THREAD

**Issue by palinf** [StyraHem/ShellyForHASS#229]
I need a bit of help to configure my network to ensure ShellyForHASS will not use polling but CoAP for state update.

My current setup is the following:
[Lots of Shellies - latest firmware]
<WIFI>
[Ubiquiti UniFi-AC-LITE with openwrt OpenWrt 19.07.2 - interfaces are bridged]
<WIRE> 
Ubuntu 18.04.4 LTS - Docker 19.03.8 - Hassio 209 - Home Assistant 0.107.5 network mode is "host" - ShellyForHASS 0.1.7-beta3 aa29cd8

The devices are all displaying CoAP-discovery, poll

My configuration 
```
shelly:
  host_ip: 10.90.1.1        
  sensors:
    - all
  devices:      #devices to be added
    - id: "3DC4AE"
      entity_id: BulbLiving
      name: BulbLiving
...
```

So my problem is that the shellies states are polled instead of immediately updated.

When I run test.py within the hass instance in docker I get immediately get the states of the devices:
Like for example:
```
'P\x1e\xce\xcf\xb3cit\x01s\xed\x0b\xec\tSHSW-25#E028038C4D59#1\xd2C\x96\x00\x82 \x00\xff{"G":[[0,112,1],[0,122,0],[0,111,0.000000],[0,121,0.000000],[0,118,1],[0,128,0],[0,115,57.74],[0,116,135.94],[0,117,0]]}'
```

So at first I would say my network is not in cause, isn't this correct ?
What would be the next step to diagnose ?

This is related to [issue] (https://github.com/StyraHem/ShellyForHASS/issues/158)

**Comment by hakana** [comment]
Did you update test.py? If test.py working without change, try to remove host_ip in confog.yaml and see if that works.

**Comment by palinf** [comment]
I updated test.py
test.py does not show any value if host_ip is not there
test.py does show all states change if host_ip is set to the host machine ip.

**Comment by hakana** [comment]
Can you post your test.py that working for you?

**Comment by palinf** [comment]
You mean the result ?
The test.py I am using is the one in the git one.

**Comment by hakana** [comment]
What version are you use of HA and ShellyForHASS?

**Comment by palinf** [comment]
Home Assistant 0.107.5 network mode is "host" - ShellyForHASS 0.1.7-beta3 aa29cd8

**Comment by hakana** [comment]
Strange, it should work if you remove host_ip in config and restart HA.

**Comment by palinf** [comment]
When I remove host_ip (and of course restart HA) no messages are received by test.py.

As HA instance receive coap messages (using test.py we see it) could you give me an insight of how the coap messages are dealt ? Directly by ShellyForHASS or is it another component ?
I suppose at some point something has to say it wants to receive information from Shellies using CoAP. I am struggling finding information on this and would need to have a small pointer to start to investigate more in depth.

**Comment by hakana** [comment]
Try to update test.py like this (mreq row):

```yaml
import socket
import struct

UDP_IP = "224.0.1.187"
UDP_PORT = 5683

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(('', UDP_PORT))
#mreq = struct.pack("=4sl", socket.inet_aton(UDP_IP), socket.INADDR_ANY)
mreq = struct.pack("=4s4s", socket.inet_aton(UDP_IP), socket.inet_aton("10.90.1.1"))
sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)

while True:
  data = sock.recv(10240)
  print(data)
```

The part receiving the CoAP is in pyShelly, https://github.com/StyraHem/pyShelly/blob/master/pyShelly/coap.py

**Comment by hakana** [comment]
Here is some information about CoAP:
https://github.com/StyraHem/ShellyForHASS/wiki/FAQ6:-Troubleshoot-CoAP-messages

**Comment by palinf** [comment]
Result of test.py while using switches in shelly 2.5 . Those lines are displayed in real time.
```
b'P\x1e\x00\xaa\xb3cit\x01s\xed\x0b\xec\tSHSW-25#E098068D4D59#1\xd2C\x96\x00\x82\x9f\x00\xff{"G":[[0,112,1],[0,122,0],[0,111,6.774169],[0,121,0.000000],[0,118,0],[0,128,1],[0,115,51.33],[0,116,124.39],[0,117,0]]}'
b'P\x1e\x00\xab\xb3cit\x01s\xed\x0b\xec\tSHSW-25#E098068D4D59#1\xd2C\x96\x00\x82\xa0\x00\xff{"G":[[0,112,1],[0,122,0],[0,111,6.875663],[0,121,0.000000],[0,118,0],[0,128,0],[0,115,51.33],[0,116,124.39],[0,117,0]]}'
b'P\x1e\x01\xbb\xb3cit\x01s\xed\x0b\xec\x03SHBLB-1#3CC4EE#1\xd2C\x96\x00\x82\x1b\x00\xff{"G":[[0,111, 255],[0,121, 255],[0,131, 0],[0,141, 0],[0,151, 100],[0,161, 3000],[0,171, 100],[0,181, 1]]}'
b'P\x1e\x00\xac\xb3cit\x01s\xed\x0b\xec\tSHSW-25#E098068D4D59#1\xd2C\x96\x00\x82\xa1\x00\xff{"G":[[0,112,0],[0,122,0],[0,111,6.838685],[0,121,0.000000],[0,118,1],[0,128,0],[0,115,51.33],[0,116,124.39],[0,117,0]]}'
b'P\x1e\x00\xad\xb3cit\x01s\xed\x0b\xec\tSHSW-25#E098068D4D59#1\xd2C\x96\x00\x82\xa2\x00\xff{"G":[[0,112,0],[0,122,0],[0,111,0.000000],[0,121,0.000000],[0,118,0],[0,128,0],[0,115,51.33],[0,116,124.39],[0,117,0]]}'
```

**Comment by hakana** [comment]
Is it working in HA now after you run the test.py?

**Comment by palinf** [comment]
Yes, it is working in HA **while** test.py is running.

To be clear:
HA does not get realtime changes.
I start test.py: HA gets realtime changes.
I stop test.py then HA does not work anymore.

**Comment by palinf** [comment]
Before running test.py:
protocols displayed in shelly lovelace card: mDns, poll
after:
protocols displayed in shelly lovelace card: mDns, poll, CoAP-msg

**Comment by hakana** [comment]
That is very interesting! 

Don't do this, just check if! Do you have the possibility to select master version of ShellyForHASS in HACS?

**Comment by hakana** [comment]
Do you have chat (whatsapp, skype etc?)

**Comment by palinf** [comment]
You can use whatsapp +352691914450

In HACS I have the possibility to select the following versions:
0.1.6
0.1.5
0.1.0
0.0.14
master

**master** is selected currently and the following is displayed:

Last updated: 7 hours ago
Installed: 2b660e6
 
Available: (newest: 0.1.6)
master

**Comment by hakana** [comment]
Try install the latest master

**Comment by palinf** [comment]
e9b55e0 fix the issue
thanks a lot !

**Comment by hakana** [comment]
Fixed in 0.1.7.b5

**Comment by pablitofernandez** [comment]
I have a quite similar setup as you @palinf , just for clarification. What is your final configuration?

> To be clear:
HA does not get realtime changes.
I start test.py: HA gets realtime changes.
I stop test.py then HA does not work anymore.

I had a similar problem in 0.1.7.b3, I think I fixed it using host_ip: 0.0.0.0 and the igmp_fix: true. But I'm interested if in 0.1.7.b5 and your config I can fix it too.

Thanks!

**Comment by palinf** [comment]
@pablitofernandez 
host_ip: 
Is set with the ip of the network interface where my shellies are connected.
Version installed: e9b55e0 - 0.1.7.b5

It would be nice if you could post your network setup if this work for you as there are many solutions for a common problem (realtime state update not working / CoAP-msg not working)

To a certain extent this may also solved issues:
https://github.com/StyraHem/ShellyForHASS/issues/158

**Comment by pablitofernandez** [comment]
Yes this is something I have been fighting with for a few weeks and all help is welcome. This is my current setup:

Macmini (Mid 2011) running Ubuntu server with Docker.
Home Assistant 0.107.5 running in a container in Host mode.
ShellyForHass 0.1.7.b5
Router: Asus RT-AC68U with MerlinWRT (IGMP enabled in Wifi settings)
Docker Host IP is: 192.168.1.6 and the shellys (15 of them) are in the same range between 192.168.1.130 and 192.168.1.150.

Right now my working (tested for some hours) config is this one:

host_ip: 192.168.1.6
igmp_fix: true

The interesting thing is that if I disable the IGMP fix and I restart HASS I can see COAP messages flowing in my network with Wireshark. But after some time, like maybe between 3 - 10 minutes those COAP messages stop flowing, 0 network COAP activity and therefore there is no real time updating in HASS switches. In that moment if I start test.py in any computer of my network (for example in my desktop gaming computer) magically the COAP messages start flowing again and I can see real time updating in my HASS frontend.

So in my specific case, and I dont know why I had to set the igmp_fix: true so every minute the COAP network is somehow "woken up"?

I hope this helps anybody and I would like to thank this integration authors and all the community for the great job they did!

**Comment by hakana** [comment]
> So in my specific case, and I don't know why I had to set the igmp_fix: true so every minute the COAP network is somehow "woken up"?

Yes, igmp_fix sending the IP_ADD_MEMBERSHIP regular. Normal that should not be needed but for me and some other, it is needed to keep the CoAP-msg flowing.

**Comment by chemelli74** [comment]
I think that we can close this issue as 0.1.7b5 is released.
@palinf  can you proceed please ?

Simone
