### ISSUE TITLE
Missing Consumption value Shelly 3EM

### ISSUE THREAD

**Issue by bmwm69** [StyraHem/ShellyForHASS#234]
Hello,

I bought one shelly 3EM and try integrated that with HA but dont have any consumption information :

My Configuration:

shelly:
  username: xxxx
  password: xxxx
  discovery: true
  additional_information: True
  sensors:
    - all #show all sensors

HA sensors:

![image](https://user-images.githubusercontent.com/33760373/77677163-3b09fd80-6f87-11ea-90af-872128af0752.png)

Using Hacs:

![image](https://user-images.githubusercontent.com/33760373/77678386-fbdcac00-6f88-11ea-9e05-2b8f3f6422af.png)

HASSIO Version : 0.107.5

**Comment by hakana** [comment]
Only available in latest beta. You can enable show beta in HACS to see it.

**Comment by bmwm69** [comment]
Tks @hakana already show all information !
