### ISSUE TITLE
Comment: "CoAP message" works only with latest firmware

### ISSUE THREAD

**Issue by palinf** [StyraHem/ShellyForHASS#235]
Sorry I had to open an issue for this but regarding the issue https://github.com/StyraHem/ShellyForHASS/issues/229
The solution described still works.

But for one device it did not. Most probably because the firmware was not up to date.
After updating the firmware everything was fine.
This could be interesting to add in the troubleshooting section.

**Comment by chemelli74** [comment]
When you have a issue, you should always update to latest firmware and latest beta build of this plugin before reporting.

Thank yu for you cooperation.

Simone
