### ISSUE TITLE
update of current consumption (W) shelly 2.5 to fast

### ISSUE THREAD

**Issue by catalinbordan** [StyraHem/ShellyForHASS#236]
Hello,

I have a strange behavior of power consumption atribute of a shelly 2.5 device type. how to explain?
I have placed my power source of laptop on it, and in the HA the state changes between 2-4 per second, something like this 1 sec = 13,14,15,12 W. Is flipping like crazy between numbers.
I restart the shelly, I have made a cold restart. the same behavior.
I have changed the shelly 2.5. the same behavior on this too.
On app not sow much update, very slow update compared to this.
I am on the last beta6.
This is funny because I was complaining about slow update before(before 1 min because I have problems with coap protocol). but now it is to much, because it is hammering my HA CPU. I observe an increase of CPU activity in HA host. 
Looking in Glances add-on I saw that phyton3 is taking 60% cpu usage in conjunction with another sensor "template"(this also change 4 times per seconds) witch is making a math difference between for almost 10 sensors(this Shelly also).  I have HA in VM on windows. Here I can see an increase of CPU usage from 8% to 25% when Shelly starting to act like this(has this power source of laptop plugged )

What it could be? so many messages(COAP) per seconds send by shelly 2.5? integration does not know/decide what value to put?

Do you experiences this too also?

thanks.
PS I have 2 power source for this laptop (same brand HP) so I changed between them also. Same behavior.

**Comment by chemelli74** [comment]
Enable debug logging and check how often you receive CoAP messages.
Maybe for this specific load you can change the unit to KW and round to 1 decimal so it won't flip so much.

Simone

**Comment by catalinbordan** [comment]
> Enable debug logging and check how often you receive CoAP messages.
> Maybe for this specific load you can change the unit to KW and round to 1 decimal so it won't flip so much.
> 
> Simone

Hi,
1. please tell me how to enable debug logging. I also am curios to see what messages are coming and why the hell with this power supply of laptop is going crazy.
2. Not reasonable in this case. right now I Have 85 w relay 2 and 10-20 w in relay 1. so if I convert to KW it will be: 85/1000=0.0W and 20/1000= 0.0w. Yes it will fix :)  but ...

PS. Off topic:
1. the fields in integration for user and pass restriction do not save on restart if you try to remove them.
2. I try to put more decimals for power consumption 2 -> 4. To do that, I understand that I have to put settings in configuration.yaml, witch I did it, but the integration will not take the settings from configuration.yaml. So this must to be moved it to the integration. If option for logging also here in configuration.yaml I will not have the possibility to activate the logging.

**Comment by catalinbordan** [comment]
Update after analyse the logs;
I can confirm. for 600 seconds I have for this shelly 2.5 aprox 2617 messages=4.4/sec. my laptop charger it is like viagra for power meter :) for other 1PM I have 56 messages, for another shelly 2.5 (power source of a modem and a router) 61 messages.
Here it is the logs exported in excel.
Almost 28.000 lines for 10minutes. this is insane. :-O 

[shelly coap.xlsx](https://github.com/StyraHem/ShellyForHASS/files/4402196/shelly.coap.xlsx)

**Comment by chemelli74** [comment]
> Update after analyse the logs;
> I can confirm. for 600 seconds I have for this shelly 2.5 aprox 2617 messages=4.4/sec. 

Please post on Shelly's English support group on Facebook about this issue.
Something for Allterco to check and fix.

Closing this issue.

Simone

**Comment by catalinbordan** [comment]
I sent a private message to Dimitar with my excel file and he said that he will send to developer to check, but until now no response. Tomorrow I will try to ask about it.
