### ISSUE TITLE
Renaming strategies for devices and entities

### ISSUE THREAD

**Issue by palinf** [StyraHem/ShellyForHASS#237]
I am struggling with the good approach to have in term of naming the devices to correctly identify them.

```
  **devices:**  #configure devices
    - id: "ABCDEF-1"
      name: bathroom switch left **#set friendly name**
    - id: "ABCDEF-2"
      name: bathroom switch right #set friendly name
```

1. This applies the renaming on the entity, not on the device. Is this the expected behaviour for a configuration under `devices:` ?
2. Also, the line on `#set friendly name`  changes not only the friendly name but also the entity_id.

The main device is not renamed when using for example:
    - id: "ABCDEF"
      name: bathroom double switch
3. Is this the correct behaviour ?

_So far, users seem to have two solutions:_
**4. Rename in HA:** first rename the device and apply to all entities (friendly name only, this does not change the entity id) and all entity id have to be manually changed.

**5. Rename in shellyforhass configuration:**
Only apply on entities, then the devices name have to be updated in HA. Using a mix of configuration (both HA and shellyforhass configuration) seems to me a bit cumbersome.

6. Is there a third way I am not aware of ?

**Comment by chemelli74** [comment]
>
> 6. Is there a third way I am not aware of ?

Use cloud integration for getting names and stay in sync with app.
Anyway plugin takes care of single entities more that the whole device.
So for Shelly 2.5 used for 2 different load, the device is named as input first input.

Simone

**Comment by palinf** [comment]
6. Interesting. Thanks.

> So for Shelly 2.5 used for 2 different load, the device is named as input first input.
I did not notice this behaviour. I will check it again.
