### ISSUE TITLE
UniFi USG-3P proxy.py issue

### ISSUE THREAD

**Issue by stich86** [StyraHem/ShellyForHASS#238]
Hi all,

I’m running various Shellys on different VLAN. So to make CoAP working, I’ve installed proxy.py script on my USG-3P (which is routing VLAN),but it looks like that the program doesn’t routing Multicast packets between VLAN. Doing a TCPDUMP there is no trace of forwarding packet (so my HA doesn’t update immediately on change status).

Any hints how to debug python scripts?

Thanks

**Comment by hakana** [comment]
Can you see the packages if you run test.py?

**Comment by stich86** [comment]
No :(

**Comment by chemelli74** [comment]
@stich86, please contact UniFi support and ask them the right way to route multicast.
There is anything we can do unfortunately.

Simone

**Comment by wltng** [comment]
@stich86 What you need is an IGMP proxy. All my Shellies are on the same VLAN (666)
Instead of using the proxy.py, I added the following to my config.gateway.json to get things to work:

```
{	
	"protocols": {
		"igmp-proxy": {			
			"interface": {				
				"eth1": {
					"alt-subnet": [
						"224.0.1.187/0"
					],
					"role": "downstream",
					"threshold": "1"
				},
				"eth1.666": {
					"alt-subnet": [
						"224.0.1.187/0"
					],
					"role": "upstream",
					"threshold": "1"
				}
			}
		}
	}
}

```

**Comment by stich86** [comment]
i cannot use IGMP-Proxy because already used to SSDP for other device on the IoT subnet :(
same issue that I had in the past using Xiaomi Gateway..

**Comment by hakana** [comment]
Can you just use our proxy.py?

**Comment by stich86** [comment]
the problem is that on my USG, the multicast join is  done only on main interface (eth1) and not on the VLAN interface (eth1.2), so the Multicast messages sent on the VLAN2 are not received by the proxy.py :(

**Comment by chemelli74** [comment]
@stich86, I think there is anything we can do. Am I wrong ?

Simone

**Comment by stich86** [comment]
I don’t think. I’ll try to find another solution, otherwise I’ll stick with 30s scan interval..
