### ISSUE TITLE
Shelly RGBW2 White Color and Brightness control inverted 

### ISSUE THREAD

**Issue by claustro** [StyraHem/ShellyForHASS#239]
Hi , I have installed shellyForHASS and everything works fine except the Shelly RGBW2 that has brightenss and color inverted.
I use the shelly to control a simple white led strip connected on the W pin of the shelly RGBW2. I switch on and off the leds by another shelly1.
Always works correctly with the exception of brightness control.
Any idea

**Comment by hakana** [comment]
I have tested and it working for me.

Are you using color or white as device type?

If you use color you should use the white value control to change the brightness on the white channel.

If you use white you should use the switch named 4.

**Comment by claustro** [comment]
Thank you very much this was the problem.
Solved
Thank you for taking time to answering me !

Andrea

Il giorno lun 13 apr 2020 alle ore 16:08 hakana <notifications@github.com>
ha scritto:
