### ISSUE TITLE
Shelly1 doesn't work from within hassio

### ISSUE THREAD

**Issue by carameljm** [StyraHem/ShellyForHASS#242]
It does switch, both with the Shelly app and with a connected switch, but not with autodiscovered switch in hassio. It just waits a few seconds and then switches back.
Another shelly1 works great.

I must say, the shelly1 with the issue is a gen 1.

**Comment by chemelli74** [comment]
Please post debug log ( see wiki in order to enable ) along with some details ( es. time when you switched ).

Simone

**Comment by carameljm** [comment]
My bad. Restricted login in the shelly app for this shelly1.
Before I used it as a rest switch, with login.
SOLVED
