### ISSUE TITLE
How to setup USG pro 4 to work with CoAP

### ISSUE THREAD

**Issue by Surgikill** [StyraHem/ShellyForHASS#243]
Hey all,

I'm trying to get my network to work with CoAP messages. I'm running a USG pro 4, USW 24, and UAP AC Pro. All the shellies are on an IOT vlan, and my Home Assistant is on a docker inside a proxmox VM, on my LAN network. I've read the troubleshooting guides and haven't had any luck. The tcpdump doesn't show anything, and the python test script only shows one message, which is home assistant. I've tried the IGMP fix, and that didn't do anything. I've also tried enabling and disabling IGMP snooping.

I want this to update in real time.

I forgot to mention, but the only way the shellies are discovered is if I discover by IP. This is very slow though.

**Comment by chemelli74** [comment]
@Surgikill, some questions

- do you have tcpdump on board of your router ?
- is your router Linux based ?
- did you try contacting vendor support for getting info about UDP multicast for CoAP ?

Simone

**Comment by palinf** [comment]
I went through this problem on several installation so I would add my two cents:

- Update everything - docker, hassio, ha, shellyforhass but more importantly the shelly devices.
- Start from inside the ha docker container. If you are using the standard hassio install it should be ` homeassistant/qemux86-64-homeassistant:0.107.7` and run test.py 
- https://github.com/tefinger/StyraHem-ShellyForHASS/blob/master/util/test.py
- Use one of your device with physical input. If you see immediate updates = message is displayed in test.py, as soon as you act on the device then your network is probably not in cause.

**Comment by Surgikill** [comment]
Not sure if I have tcpdump on my router, I can ssh in and check. Yes it's linux based. I saw some other posts on here with ubiquiti stuff. It's pretty powerful. I think my issue is I'm running it across vlans, so I might have to run proxy.py, or put hass on the IOT vlan, and I don't want to do either of those.

**Comment by chemelli74** [comment]
> I think my issue is I'm running it across vlans, so I might have to run proxy.py, or put hass on the IOT vlan, and I don't want to do either of those.

Your choice, issue closed.

Simone

**Comment by Surgikill** [comment]
> 
> 
> > I think my issue is I'm running it across vlans, so I might have to run proxy.py, or put hass on the IOT vlan, and I don't want to do either of those.
> 
> Your choice, issue closed.
> 
> Simone

Thanks. This makes my choice to run MQTT very clear.
