### ISSUE TITLE
Integrations - asking for password

### ISSUE THREAD

**Issue by wormscoffer** [StyraHem/ShellyForHASS#246]
Hello all

I hope I've not missed anything obvious but I've installed HAC on my HASS (Supervisor on Ubuntu) and managed to add ShellyForHass and it appears as "installed".

However, when I "GO TO INTEGRATIONS" it's not listed so I click "+" and find it but it pops up with a password request and no indication why, what password or any sort of explanation.

Have I done something wrong?

**Comment by chemelli74** [comment]
@wormscoffer, you are using 0.1.6 that has a incomplete flow handling.
Please upgrade to 0.1.7b6.

Simone

**Comment by wormscoffer** [comment]
I was only offered 0.1.6 as "newest" but having explored the ellipses I found a "show beta" option.

Then I have uninstalled 0.1.6 and then installed 0.1.7b6 but alas, the same thing.

Nothing is shown in configured integrations and after trying to add it from the "Set up a new integration" button it prompts me for something, such as a password.

TIA.

Andrew

**Comment by wormscoffer** [comment]
Ah ha! A restart of Home  Assistant and then it asked for a prefix and told me configuration was complete. Phew.

Thanks for the reply.
