### ISSUE TITLE
Set device entity_id and name from DNS reverse lookup (PTR)

### ISSUE THREAD

**Issue by robinsmidsrod** [StyraHem/ShellyForHASS#251]
The **name** and **entity_id** of a shelly device can be fetched from the cloud or defined directly in the HA configuration. I try to avoid connecting my devices to the cloud (for security), but it would be nice to only have to "name" my devices in one location. For me that location is DHCP/DNS. I use static IPs for all of my devices, and for the shellies I name them `shelly-dishwasher.local.domain`, `shelly-washing-machine.local.domain`, etc.

It would be really nice if the **entity_id** and **name** of each device (during discovery) could try to do a DNS PTR lookup to find the name of the IP, then use that as the base for calculating per-device entity_id and friendly name.

In my case, you'd strip the `.local.domain` (which is commonly found in /etc/resolv.conf) or just use the first part of the full PTR record, split the name on hyphens (or underscores), check that the first (or last) entry of the array matches the defined prefix (which defaults to `shelly`), and if it does, combine it together with underscores to form the **entity_id**. For the **name** you'd remove the prefix from the array, title case each word (usually uppercase first letter), and combine them together with space.

With this feature implemented people that give static IP/name to their devices in their network would get automatic naming that makes sense instead of just names based on MAC address of the device. Overall, I'd think that would be better default behavior.

What do you think? Is this something that could be implemented without too much refactoring and code changes?

I imagine this would be a breaking change if it was introduced as something on by default, but hiding it behind a config.yaml toggle (off by default) could be a way to introduce it without breaking anyone's existing setup.

**Comment by chemelli74** [comment]
I would says that majority doesn't name devices in DHCP but leave the name as is.

Anyway, I would say your porposal can be taken into account on a more general approach; something like:

- DNS PRT query
- substring at first "."

IMHO other solutions would be too linked to the specific environment thus making this plugin too complicate to be mantained without a real benefits.

It will be a fallback: if no "name" in cfg, then use cloud. If no "cloud" then use DNS PTR".
 
Simone

**Comment by robinsmidsrod** [comment]
@chemelli74 My suggestions for doing the changes to the name retrieved from the PTR record was just to make it more in line with Home Assistant conventions (lowercase and underscores between words in entity IDs, and name of entities with first letter uppercased. Since underscores at some point was not allowed in DNS records (not sure if this really has changed, or is just misused) most people still use hyphens in DNS entries to name things. That's why my suggestion to change them into underscores.

I think this approach would make sense to anyone that like to give their devices static IPs, although that might not be the majority of users.

The overall intent is to not have to rename Shelly entities at all in HA, and just use DNS for naming them, instead of having to either rely on Shelly Cloud or the HA configuration file to manually name them.

I agree with you that this is just another fallback before going to the generic naming template.

**Comment by palinf** [comment]
@robinsmidsrod What is the generic naming template you are talking about ?

> It would be really nice if the entity_id and name of each device (during discovery) could try to do a DNS PTR lookup to find the name of the IP, then use that as the base for calculating per-device entity_id and friendly name.
I would also be really interested by this feature. I am organising my network devices through DHCP naming too, in the case of shellies I use valuable information within the hostname and having the entity_id and device_id in home assistant renamed with this would be a golden solution. 
Having to use HA gui to rename device is a bit cumbersome.
This would make https://github.com/StyraHem/ShellyForHASS/issues/245 useless.

**Comment by hakana** [comment]
You can still get the name from Shelly Cloud even if the device not is connected to cloud. Are you using the Shelly app?

I think this feature will be used just by a few users an will make the component to complex.

Right now Im building a configuration GUI for shelly, so I think it is better to do the naming there.

**Comment by robinsmidsrod** [comment]
@hakana No, I'm not using the Shelly app at all, because I assumed it meant the devices would have to be connected to the cloud to use it. All of my shellies have been configured manually using the web server on 192.168.33.1 on the factory default SSID.

How will this new configuration GUI be used? Do you have a description of your plans for this new feature?

**Comment by chemelli74** [comment]
> Right now Im building a configuration GUI for shelly, so I think it is better to do the naming there.

Issue should be addressed with the new GUI.
Once released, if not solved please open a new issue.
For now I close this one.

Simone
