### ISSUE TITLE
[FR] Add DHT Humidity support for temperature add-on for Shelly 1(PM)

### ISSUE THREAD

**Issue by acirtautas** [StyraHem/ShellyForHASS#252]
Since (fw 1.6) shelly 1 and PM supports DHT sensor with temperature add-on, it gives readings for temperature and humidity. Temperature is already displayed as it was supported earlier with up to three dallas temperature sensors. 

This is how external sensor state json piece looks like.

```json
{
    "ext_sensors": {
        "temperature_unit": "C"
    },
    "ext_temperature": {
        "0": {
            "tC": 23.30,
            "tF": 73.94
        }
    },
    "ext_humidity": {
        "0": {
            "hum": 53.20
        }
    }
}
```

It would be nice see the humidity sensor value in ShellyForHass.

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.8.b2) and report back.

Simone

**Comment by acirtautas** [comment]
Thanks, I see the humidity now!

<img width="376" alt="dht22_humidity_graph" src="https://user-images.githubusercontent.com/1830639/80857667-766dab00-8c5c-11ea-9402-b2d40b6b7593.png">
