### ISSUE TITLE
[FR] Shelly Flood battery % sensor

### ISSUE THREAD

**Issue by jsBlackBelt** [StyraHem/ShellyForHASS#253]
Hello,

Shelly Flood is battery powered, and the battery percent is reported back to HA:
<img width="384" alt="Screen Shot 2020-04-07 at 9 06 47 PM" src="https://user-images.githubusercontent.com/7566666/78704142-15c8a800-7914-11ea-9bca-04ba1110b542.png">

It would be nice to get a sensor for the battery level, to be able to support automations to notify to replace the battery when drops below a % level.

**Comment by acirtautas** [comment]
But there alredy is a battery % provided, have you enabled all the sensors?

**Comment by jsBlackBelt** [comment]
I see it to in the details (see screenshot above) however it is not exposed in automation under device or state.

**Comment by acirtautas** [comment]
In my case I see it under sensor name:

**sensor.shelly_shwt_1_######_battery**

And can use it in automations if needed.

**Comment by chompy18** [comment]
Ok, then maybe this is a problem on my side. How can I enable all sensors?

**Comment by jsBlackBelt** [comment]
Ok, then maybe this is a problem on my side. How can I enable all sensors?

**Comment by acirtautas** [comment]
You can enable individual or all sensors and attributes is shelly yaml config:

```yaml
shelly:
  sensors:
    - all
  attributes:
    - all
```

**Comment by jsBlackBelt** [comment]
Right. I see it now. Thanks. I'll close this FR now.
