### ISSUE TITLE
Repeated Disconnects logged

### ISSUE THREAD

**Issue by blkpanther5** [StyraHem/ShellyForHASS#256]
Running 0.1.7 of ShellyForHASS

After installing the integration, I'm getting repeated disconnects and reconnects of any Shelly devices. They have good wifi strength (-55 dBm), but I'm getting thousands of unavailable/off entries per day like this:
![Annotation 2020-04-09 083509](https://user-images.githubusercontent.com/1998538/78906833-1741bf80-7a3d-11ea-98f5-a739cc2602eb.jpg)

The only thing I've noticed is that, using a rapid ping (.2 sec intervals), the devices exhibit a 4-ish second gap in response every 6-10 seconds. I don't know if this is the expected behavior for Shelly's or not.
![Annotation 2020-04-09 083550](https://user-images.githubusercontent.com/1998538/78907002-55d77a00-7a3d-11ea-9603-688a28cd531f.jpg)

Any help is appreciated, as these things are littering my logs like crazy.

**Comment by hakana** [comment]
Try to set unavailable_after_sec to a higher value, like 300. Look like you have a problem with your WiFi, pinging my Shellys have no delays. 

What values do you see on the protocols attribute?

**Comment by chemelli74** [comment]
Please check also http://<shelly ip>/status for the "uptime" value immediatly after the disconnect.

Simone

**Comment by blkpanther5** [comment]
> Please check also http:///status for the "uptime" value immediatly after the disconnect.
> 
> Simone

Directly after the disconnect, the uptime is just incremented by 4 or 5 seconds. If I try while it's d/c'd it hangs for a few seconds and then loads the JSON.

**Comment by chemelli74** [comment]
> Directly after the disconnect, the uptime is just incremented by 4 or 5 seconds.

Ok then it's not a device reboot. Must be a network issue.

Simone

**Comment by blkpanther5** [comment]
> Try to set unavailable_after_sec to a higher value, like 300. Look like you have a problem with your WiFi, pinging my Shellys have no delays.
> 
> What values do you see on the protocols attribute?

Ok, so the protocols attribute has: IP-addr, poll

I've adjusted the unavailable_after_sec to 300. I haven't seen any events in the HA logbook for about 10 minutes, so... maybe solved! I'll check back in a couple hours and verify. Thank you.

**Comment by blkpanther5** [comment]
Ok, it's been hours, and I'm not seeing those entries any more. My WiFi must simply not like the Shelly's or visa-versa. Either way the suggestion seems to have resolved the issue. Thanks!
