### ISSUE TITLE
Renaming power entity via Integrations page not persistent after restart

### ISSUE THREAD

**Issue by samvanh** [StyraHem/ShellyForHASS#257]
When renaming `current_consumption` entities (Name Override & Entity ID) via Integrations Page, everything seems to save correctly, but after a restart reverts again to standard name & Entity ID

Issue seems to happen to both `current_consumption` (Wattage) entities of my Shelly EM and not to any other sensors on Shelly EM or Shelly 2.5

After naming:
<img width="408" alt="Screenshot 2020-04-10 at 11 02 30" src="https://user-images.githubusercontent.com/13184388/78978888-fc457d00-7b1a-11ea-8695-85edf5e302a2.png">

After HA-core restart:
<img width="406" alt="Screenshot 2020-04-10 at 11 02 40" src="https://user-images.githubusercontent.com/13184388/78978928-141d0100-7b1b-11ea-9de6-cf4e04a33fc1.png">

FYI:
Home Assistant 0.108.1
Supervisor v 214
ShellyForHASS v 0.1.7
All settings via Integrations Page

**Comment by chemelli74** [comment]
Do you have discovery enabled and/or shelly cloud integrated ?

Simone

**Comment by samvanh** [comment]
Hi,
-Discovery: enabled
-Shelly Cloud: not connected
I have tested some more and only the `current_consumption` entity of the shelly EM seems to be affected. Renaming other entities of Shelly EM or 2.5 do persist after HA Core restart.  Maybe the problem is in the HA storage rather than your component?

**Comment by chemelli74** [comment]
> I have tested some more and only the `current_consumption` entity of the shelly EM seems to be affected. Renaming other entities of Shelly EM or 2.5 do persist after HA Core restart. Maybe the problem is in the HA storage rather than your component?

Thank you for investigating.
Unfortunately I don't have yet a Shelly EM to test myself.

Anyway list of fixes/enanchement for 0.1.8 is already closed.
Once released, we'll check this as well.

Simone

**Comment by hakana** [comment]
ShellyForHass does not support the renaming of entity_id from integration. I need to have a look at that and see if it can be solved.

You can rename the entity_id in config.yaml until fixed.

**Comment by vevexus** [comment]
renaming the entity_id in yaml will affect all entities coming from that device correct?  
I have am having the same issue with my power sensors being renamed on two shelly 2.5's.

One of my shelly devices controls couch lights via automation but is actually powering my entertainment center (relay disabled).  If I edit the name in yaml it will affect both but I want to specify them separately to sensor level not device level.

**Comment by ericvitale** [comment]
I'm having the same issue with the Shelly 1PM. The switch & total_consumption entities stay renamed but the power sensor goes back to default when restarting HA.

**Comment by ericvitale** [comment]
This is just a note for anyone new experiencing this issue. Upgrading to 0.1.8 does not fix this issue, it was never expected to. I hope the developers include it in the next release.

This issue is preventing me from adding a bunch of sensors, shelly or not. Not the end of the world in the short term.

**Comment by mandelflanders** [comment]
Using the entity_id still will not solve the issue for suffixes. 
I have for instance been using a set nomenclature with _power for all power monitoring sensors (since that is the standard for most other integrations, and would like to continue doing so in order to avoid confusion and/or need to join several id:s in the long term data in influxDB/Grafana.

**Comment by ericvitale** [comment]
@mandelflanders - Same here. Renaming the power entity each time I restart is getting annoying. I've had to turn off a few automations that are expecting these devices to be working.

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.9.b1) and recheck.

Simone

**Comment by ericvitale** [comment]
I'm installed through HACS, but I downloaded the beta release...

https://github.com/StyraHem/ShellyForHASS/releases/download/0.1.9.beta.1/shelly4hass.zip

Extracted into the /custom_components/shelly directory, restarted. Entities changed back to the default names. I updated them again, restarted HA, same result. They changed back to default.

**Comment by chemelli74** [comment]
> I'm installed through HACS, but I downloaded the beta release...
> 

Please install, upgrade and downgrade always via HACS: [FAQ5:-Enable-beta-in-HACS](https://github.com/StyraHem/ShellyForHASS/wiki/FAQ5:-Enable-beta-in-HACS)

Simone

**Comment by ericvitale** [comment]
Yea, as soon as I posted my message I remembered I could do the beta via HACS. Ok, I've restored back to previous version and I can confirm the previous version is functioning. Will update via HACs.

**Comment by ericvitale** [comment]
After upgrading to the beta, I changed the entity id and name of the sensor. Restarted, it still got set back to the default. Maybe I'll uninstall the integration and start from scratch.

**Comment by ericvitale** [comment]
1 - Uninstalled Integration
2 - Confirmed the "shelly" folder was gone
3 - Restarted Home Assistant
4 - Installed 19.1 beta from HACS
5 - Added the integration.

At that point it started to slowly discover my devices. Doesn't have them all yet, but I can't configure the integration. It doesn't show any text.

<img width="426" alt="shelly" src="https://user-images.githubusercontent.com/8474048/81436176-087f2300-9137-11ea-91d6-c63f2b459319.png">

**Comment by ericvitale** [comment]
Also, for the devices it did find they didn't retain their entity names or names after restarting HACS. Is there a better way to uninstall? I did it from HACS. Seems like something is cached somewhere.

**Comment by hakana** [comment]
@ericvitale Delete the Shelly integration from HA gui and all entries will be removed.

**Comment by ericvitale** [comment]
Yes, I just tried that. I deleted the latest install via HACS and deleted the integration via "Integrations" page. When I click add integration without installing via HACS, shelly shows up in the integration list. Should that be there?

**Comment by ericvitale** [comment]
Also do you recommend installing 1.8 before upgrading 1.9?

**Comment by hakana** [comment]
Yes Shelly should always show up under integrations.

It does not matter if you install 0.1.8 before installing 0.1.9.

**Comment by ericvitale** [comment]
Same result, setup screens don't have any text.

**Comment by ericvitale** [comment]
Uninstalled, went back to 0.1.8, same thing. Blank text on setup screens.

**Comment by ericvitale** [comment]
I took a backup of my shelly folder before all this started (or I started it). I noticed that the new shelly install does not have a __pycache__ folder. Not sure if that matters or not.

**Comment by hakana** [comment]
Do you have the translations folder including en.json? It is strange the pycache is not created. Check permissions on files and folders.

**Comment by ericvitale** [comment]
en.json exists. It was the first thing I checked. I also restored the old shelly folder, same issue. 

Permissions look like they did before. Here is a screenshot. Also, going to try restarting the whole machine. The other thing that is weird is that it hasn't discovered all of my shelly devices yet. And for the couple it did find, some of them it "remembered" the device names, not the entities and others it didn't. See the other image. I didn't have to rename the Garage Door and Miner08. But the other shelly should should Miner03.

<img width="270" alt="devices" src="https://user-images.githubusercontent.com/8474048/81439966-467f4580-913d-11ea-98a7-033a0f137a34.png">


<img width="654" alt="files" src="https://user-images.githubusercontent.com/8474048/81439780-e9838f80-913c-11ea-8955-538ba973a36e.png">

**Comment by ericvitale** [comment]
Restarting didn't help.

**Comment by ericvitale** [comment]
Progress...
1 - Uninstalled Integration
2 - Removed integration from "integrations" page.
3 - Confirmed the "shelly" folder was gone
4 - Restarted Server
5 - Installed via HACs (1.8)
6 - Added via "Integrations" page.

---Text on the setup page, yay!---

7 - Setup ran fine.

---Still missing a device---

8 - Upgraded to 1.9 via HACs
9 - Restarted Home Assistant
10 - Renamed a power entity
11 - Restarted Home Assistant

--- Entity rename worked, yay!
--- Found the rest of the devices, yay!

12 - Renaming the rest now

--- I hope for the last time!!!

**Comment by hakana** [comment]
Im glad it working for you now!

**Comment by ericvitale** [comment]
Thank you for making the changes.
