### ISSUE TITLE
Add brand images to home assistant

### ISSUE THREAD

**Issue by Misiu** [StyraHem/ShellyForHASS#258]
In the recent version of Home Assistant brands (logos) of integrations are shown when adding new or view details - https://github.com/home-assistant/frontend/pull/5500
It would be awesome to see SHelly logo there.
Consider adding brands to https://github.com/home-assistant/brands.
Not sure about the name, it should be "shelly", but this integration is named `ShellyForHASS`?
Maybe it should be renamed?

**Comment by chemelli74** [comment]
Will check with Dimitar if and how we can proceed.

Simone

**Comment by chemelli74** [comment]
Dimitar gave green light.

Need to find the right formats now. Maybe we can try to ask their marketing, but they are rather busy lately.

Simone

**Comment by hakana** [comment]
I have the Shelly logo in vector format so I can fix that!
________________________________

**Comment by Misiu** [comment]
@hakana I can prepare images if You share the vector logo.

**Comment by hakana** [comment]
I have created the images, if someone can help to do a pull request it will help a lot!

<img width="922" alt="logo@2x" src="https://user-images.githubusercontent.com/1168654/79461718-d62a4c00-7ff6-11ea-99e4-0f3e114c2b70.png">
![icon](https://user-images.githubusercontent.com/1168654/79461723-d75b7900-7ff6-11ea-8508-c0824bd8039c.png)
<img width="256" alt="icon@2x" src="https://user-images.githubusercontent.com/1168654/79461727-d7f40f80-7ff6-11ea-935d-9bd6ee322a14.png">
![logo](https://user-images.githubusercontent.com/1168654/79461730-d88ca600-7ff6-11ea-8e6c-8be0f57b3a8b.png)

**Comment by Misiu** [comment]
@hakana I can do PR, but what will be the name of integration? I must place images in a folder.
How should I call that folder? `shelly`?

**Comment by chemelli74** [comment]
> Ok, got it. Icon name is based on domain, and it is `shelly`

Yes please, go for "Shelly" if the name is the product or "Allterco" if it's the brand.

Simone

**Comment by Misiu** [comment]
@chemelli74 I'm waiting for reply on community forum because ShellyForHASS is a custom integration and I'm not sure if this is allowed (sorry for not asking HA devs before)
I'll get back with results and I'll link PR if I get approval.

**Comment by hakana** [comment]
Must be the domain name used in plugin and that is shelly

**Comment by hakana** [comment]
@misiu Any news?

**Comment by Misiu** [comment]
@hakana I've created a thread on forum (https://community.home-assistant.io/t/brands-images-for-custom-integrations/187363) but sadly I didn't get any response.
Sadly custom integrations icons and logos can't be added to brands repo.
Let's wait a bit more. Maybe Home Assistant team will propose a solution

**Comment by chemelli74** [comment]
> @hakana I've created a thread on forum (https://community.home-assistant.io/t/brands-images-for-custom-integrations/187363) but sadly I didn't get any response.
> Sadly custom integrations icons and logos can't be added to brands repo.
> Let's wait a bit more. Maybe Home Assistant team will propose a solution

Replied to the community thread with my proposal, let's see if they notice it ;-)

Simone

**Comment by denniswham** [comment]
🎉 https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/

**Comment by Misiu** [comment]
https://github.com/home-assistant/brands/pull/1563

**Comment by Misiu** [comment]
I've noticed that custom components should be added to wheels - https://github.com/home-assistant/wheels-custom-integrations
@chemelli74 could you create PR for that?

**Comment by hakana** [comment]
What will wheels-custom-integration do?

**Comment by Misiu** [comment]
> What will wheels-custom-integration do?

To be honest I have no ideas :smile: but I see HACS is added there.

**Comment by hakana** [comment]
@misiu, thanks for adding the PR!

**Comment by hakana** [comment]
I have added it to Wheels now, can't hurt ;)

**Comment by Misiu** [comment]
My PR got merged so I think we can close this issue.
Took long but finally the integration will look fine :)

**Comment by hakana** [comment]
Do you know when will working, guess it will need a build?

**Comment by chemelli74** [comment]
> Do you know when will working, guess it will need a build?

Next release is expected for Wednesday.

Simone

**Comment by Misiu** [comment]
@hakana @chemelli74 I think images don't require a new release as they are served from a separate repo.

**Comment by chemelli74** [comment]
> @hakana @chemelli74 I think images don't require a new release as they are served from a separate repo.

Let's see it that way: even if I did a reboot of my 0.110.x HA test environment, I still don't see the images.

Simone

**Comment by chemelli74** [comment]
Works on 0.110.0.dev20200510

![image](https://user-images.githubusercontent.com/57354320/81513654-36788900-932a-11ea-9569-126589fd1601.png)

**Comment by hakana** [comment]
Works in 0.109.x also!

**Comment by Misiu** [comment]
Awesome 🎉🎉🎉

**Comment by hakana** [comment]
Thanks @Misiu for the help!
