### ISSUE TITLE
Question regarding shelly_switch_click event

### ISSUE THREAD

**Issue by TASSDevon** [StyraHem/ShellyForHASS#260]
I'm using v0.1.7 with HA version 0.108.3

First time trying to use click events, somehow I'm not receiving click events, when I go to the dev tools page and listen for "shelly_switch_click", nothing is incoming when I toggle the physical buttons to which a Shelly1 is connected. The switch entity does show that it is turned on/off as well as what the physical button state is (in the attributes).

Any ideas why I'm not getting anything?

**Comment by hakana** [comment]
You need to enable switch sensor. Also check what protocols the device list in HA.

**Comment by Stephan296** [comment]
@TASSDevon:
```
shelly:
  discovery: true
  version: true #add version sensor
  devices:      #devices to be added
    - id: "PUTHERESHELLYID"
      sensors: #overide global (all)
         - switch
```

**Comment by TASSDevon** [comment]
Thanks, didn't know the binary sensor was required.
