### ISSUE TITLE
[pyShelly] mDNS error, 502 Bad Gateway

### ISSUE THREAD

**Issue by fitim7** [StyraHem/ShellyForHASS#261]
Hi, Im getting this warning since update to 0.108.3.
This is spamming my whole log:
`
Logger: pyShelly
Source: /usr/local/lib/python3.7/site-packages/pyShelly/utils.py:68 
First occurred: 19:39:51 (54 occurrences) 
Last logged: 20:32:56

Error, 502 Bad Gateway
`

**Comment by chemelli74** [comment]
Bad gateway is a network issue, basically HA cannot connect to the shelly trough the router.
Can you connect using ssh and do some test ?

Simone

**Comment by fitim7** [comment]
Debugging pyShelly showed me that this is happening every minute after this:
`2020-04-13 00:06:27 DEBUG (Poll) [pyShelly] http://172.30.32.1/settings`

Yes, I can if you tell me what to do. Everything is working fine in HA btw, its just the error in the logs...

**Comment by hakana** [comment]
Try to turn off mDns in the plugin.

**Comment by fitim7** [comment]
> Try to turn off mDns in the plugin.

Just did it. Looks like this solves the issue. Weird, that this didn't happen before.
Is there any disadvantage turning mDns off?

**Comment by hakana** [comment]
If CoAP not working mdns can be used to discover devices. But there is a bug in mdns that get the address to the router instead of the device.

**Comment by fitim7** [comment]
Okay. Hope this will be fixed. It's still a backdoor, if CoAP has issues.

**Comment by chemelli74** [comment]
mDNS reworked in 0.1.8.b1. Please test and report back.

Simone

**Comment by fitim7** [comment]
Is it possible to install the beta with HACS?

**Comment by chemelli74** [comment]
> Is it possible to install the beta with HACS?

Indeed, check our wiki

Simone

**Comment by fitim7** [comment]
I'm running the beta since approx 24 hours now and can report, that there is no issue with mDNS logged in this time. Looks like your fix did the job!
