### ISSUE TITLE
Icon shows wrong direction if SWAP INPUTS is enabled son Shelly 2.5

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#262]
I found a bug since 0.108 I can see this issue on my covers.

On some of my Shelly 2.5 I've enabled the option in "SWAP INPUTS":
`If you enable this option, the buttons Open/Close behaviour will be swapped.`

![image](https://user-images.githubusercontent.com/12324196/79114475-ac1d2380-7d83-11ea-8b3e-30c70fd8edbd.png)

The result is that the arrow shows the wrong direction on this devices.
In example above I press "Down" on both covers. But the upper one shows the "opening" icon.
On this devices the SWAP INPUTS is enabled (because it is wired this way).

**Comment by chemelli74** [comment]
Swap is available only in the app, not in MQTT or CoAP.
I suggest to rewire correctly.

Simone

**Comment by vistalba** [comment]
Oh noooo :( 

May you could add a deivce setting for this case? Like `swap_input: true`?

**Comment by chemelli74** [comment]
Please rewire, is a really easy task and you will have it clean and working on all applications current and future 😉

We don’t want to make the plugin unnecessary complicate.

Thank you for understanding,

Simone

**Comment by chemelli74** [comment]
As stated above, user needs to fix wiring.

Simone
