### ISSUE TITLE
[FR] Support for Shelly Eye

### ISSUE THREAD

**Issue by gardart** [StyraHem/ShellyForHASS#263]
Hi, is this product supported?
https://shelly.cloud/shelly-eye/

**Comment by chemelli74** [comment]
Not yet: [https://github.com/StyraHem/ShellyForHASS/blob/master/README.md](https://github.com/StyraHem/ShellyForHASS/blob/master/README.md)

Simone

**Comment by chemelli74** [comment]
@gardart, do you own it ?

Simone

**Comment by gardart** [comment]
@chemelli74 no, not yet :)

**Comment by chemelli74** [comment]
Sorry no way to integrate; I was going to buy one to test but I discovered there the o lot way to access data is proprietary app.
No api, no RTSP streaming, no way for third party to access data.

Closing,

Simone
