### ISSUE TITLE
[FR] Support for shelly vintage bulbs

### ISSUE THREAD

**Issue by skrutt** [StyraHem/ShellyForHASS#264]
I just got a shelly vintage bulb a60 delivered, and was surprised that it didn't show up in home assistant! 

I'm guessing that it's too new to have gotten support yet? So there should be a topic for this then :) 

I saw that there was an issue that included these devices, but it was closed and supposedly split into two? However none of those two mentions the vintage bulbs what i saw?

Also, i want to say great work so far, the shelly integration is top-notch and i'm pretty much only buying from shelly because of your hard work!

Very impressed with the last update as well.

Thanks!

**Comment by hakana** [comment]
I received A60 today and will add support shortly.

**Comment by chemelli74** [comment]
Added in 0.1.8.b1. Please test and report back.

Simone

**Comment by skrutt** [comment]
Seems to work, just installed the beta and the A60 bulb showed up and could
be controlled!

Great work, i'll report if i discover any quirks the next days :)

Den fre 17 apr. 2020 17:06Simone Chemelli <notifications@github.com> skrev:

**Comment by chemelli74** [comment]
If you find problems, please open a new issue.

Support correctly added, so job for this is completed.
Closing.

Simone
