### ISSUE TITLE
Missing Cover Position 

### ISSUE THREAD

**Issue by rtirelli** [StyraHem/ShellyForHASS#266]
Hi I’ve noticed that the entity cover position is missing. I didn’t notice since when, HA version is 0.108.4. Thanks

**Comment by hakana** [comment]
Can you post http://ip-address/status and http://ip-address/settings for your Shelly

(Check so you not post any sensitive information like passwords)

**Comment by rtirelli** [comment]
![85146133-5131-474B-88E3-C45F1F4ADF30](https://user-images.githubusercontent.com/60747807/79394015-c703b980-7f76-11ea-8a2d-22e64ad99114.jpeg)
![19DA1346-30E6-4AC3-B179-22FE95BDD636](https://user-images.githubusercontent.com/60747807/79394021-cb2fd700-7f76-11ea-9711-91e8c709fa94.jpeg)
![C296FE7F-16A9-4115-A0C3-C433946915E8](https://user-images.githubusercontent.com/60747807/79394024-cc610400-7f76-11ea-9472-9bb8bd17af0d.jpeg)

**Comment by chemelli74** [comment]
@rtirelli, seems all fine to my eyes. What are you missing ?

Simone

**Comment by rtirelli** [comment]
That's really strange. It could be only a problem of mine. The cover percentage in the entity cards is missing (both on iPhone/iPad and Firefox) as in the screenshot above. 
If I use the slider-entity-row there is also here no % of the covers (only with iphone/iPad, with firefox everything is ok). I will try to uninstall the integration a reinstall it again to see if something will change.

**Comment by rtirelli** [comment]
It looks like a problem of the slider entity row card. So I close here the topic. Thanks for the support!
