### ISSUE TITLE
[pyShelly] mDNS error, 404 Not Found

### ISSUE THREAD

**Issue by vampywiz17** [StyraHem/ShellyForHASS#267]
Hello there,

this message is spam my log: WARNING (Poll) [pyShelly] Error, 404 Not Found

i use 3 shelly device, all of them is working well (in hassio) i dont know why get this.

**Comment by hakana** [comment]
Try to disable mdns  under shelly settings

**Comment by hakana** [comment]
Do you have a restricted login on any Shelly?

**Comment by vampywiz17** [comment]
> Do you have a restricted login on any Shelly?

Yes, all of them.

**Comment by hakana** [comment]
Have you entered the username and password in config for shelly ?

**Comment by vampywiz17** [comment]
> Have you entered the username and password in config for shelly ?

Yes, set it (i able to controll my Shellys with hass, i only get this my log)

**Comment by hakana** [comment]
Can you see for example rssi, uptime etc?

**Comment by vampywiz17** [comment]
I see this:

```
shelly_type: Shelly 1
shelly_id: *******
ip_address: 192.168.31.110
protocols:
  - CoAP-discovery
  - CoAP-msg
  - poll
has_firmware_update: false
cloud_status: disabled
switch: true
friendly_name: Törölközőszárító - Fürdő

```

**Comment by hakana** [comment]
Did you try to disable mdns?

In the next release, I will add more info to the working so we can see where it trying to connect when receiving the error. It will be a beta available this week.

**Comment by Vitosant** [comment]
I have the same problem.
when I disable the mdns the error is no longer generated.

**Comment by chemelli74** [comment]
Can be related to #261 somehow

Simone

**Comment by chemelli74** [comment]
mDNS reworked in 0.1.8.b1. Please test and report back.

Simone

**Comment by chemelli74** [comment]
@vampywiz17, @Vitosant, any feedback on this topic ?

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by ronschaeffer** [comment]
I've been waiting actually to check in a non-beta version. Has it been merged, or should I bit the bullet and try the beta?

**Comment by chemelli74** [comment]
> I've been waiting actually to check in a non-beta version. Has it been merged, or should I bit the bullet and try the beta?

Please try the beta are report back.
Thank you,

Simone

**Comment by ronschaeffer** [comment]
I installed the beta and removed and commented out `mdns: false` in `configuration.yam`l.

I can confirm that after an HA restart, there have been no 404 errors for and hour and a half. Before I'd added `mdns: false` with previous version of ShellyForHass, the 404 errors appeared almost immediately after restart and fairly frequently thereafter.

**Comment by chemelli74** [comment]
Thx for your feedback.
Closing.

Simone
