### ISSUE TITLE
Random Unavaible

### ISSUE THREAD

**Issue by Vitosant** [StyraHem/ShellyForHASS#268]
Shellys often go into unavailable. I have tested the 2.5 that a plugs.
![unavaible](https://user-images.githubusercontent.com/62880910/79443586-4c6c8580-7fda-11ea-959b-914a14662269.JPG)

**Comment by fitim7** [comment]
I also have this issue. I've noticed this behavior since I had to turn mDNS off because of https://github.com/StyraHem/ShellyForHASS/issues/267

**Comment by hakana** [comment]
Try igmp fix option

**Comment by chemelli74** [comment]
Please check also uptime trough http://<device ip>/status.

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.8.b2) and report back.

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
