### ISSUE TITLE
Shelly unavailable via google assistant voice

### ISSUE THREAD

**Issue by ShaunAndersonAZ** [StyraHem/ShellyForHASS#269]
I have two Shelly devices.  Both are integrated using the Shelly HACS Integration and have worked great until about 2 days ago.  They still appear in the interface and work manually.  They also appear in the 'Configuration -> Home Assistant Cloud -> Google Assistant' in the 'Manage Entities' section.

When I ask Google to modify one of the devices, I get an error stating "Sorry, I couldn't reach HASS.IO".  Google voice control works for all other devices except for the two Shelly devices.

Status on the devices both show online, I'm just having trouble figuring out why ONLY the Shelly devices are giving me issues, and ONLY with voice control.

Any logs I can review or any particular reason why only the Shelly devices would be affected?

**Comment by chemelli74** [comment]
Please enable debug log (see wiki for details) and post it.

Simone

**Comment by ShaunAndersonAZ** [comment]
[halog.tar.gz](https://github.com/StyraHem/ShellyForHASS/files/4488177/halog.tar.gz)

Doesn't appear to be much helpful in there. I have been randomly using Google to turn things on and off to verify that nothing else is seeing the same condition.  Only thing affected is the Shelly

**Comment by hakana** [comment]
How do you have Google home integration set up?

**Comment by ShaunAndersonAZ** [comment]
All through the Google Assistant integration for Home Assistant Cloud.

**Comment by hakana** [comment]
I just tried to set up Google Home with HA cloud and for me, it worked without any problems.

Have you checked in HA/Config/HomeAssistantCloud/GoogleAssistant/ManageDevices so they are enabled?

Have you synched Google Home by saying "Sync devices"?

**Comment by ShaunAndersonAZ** [comment]
So I'm not sure where the breakdown was.  Likely some hidden cruft that only the few devices that didn't have a HA native integration were experiencing.  I basically unlinked HASSIO from Google Assistant, cleaned up any orphaned devices in HA and rediscovered everything and all seems to be good now.  Appreciate the help. I'll close this out.
