### ISSUE TITLE
Shelly 1 Activation Switch

### ISSUE THREAD

**Issue by Sajivve** [StyraHem/ShellyForHASS#274]
Could someone please guide me on what would be the configuration for Shelly as an Activation Switch.

I can only find the following config but it has no reference to Activation Switch with Motion Sensor which is there in the Shelly GUI.

Parameter | Description
-- | --
click_cnt | Number of clicks, 2 = turn back and forth quickly, 4 = double click on the momentary switch.
state | Current state of the switch can be used to distinct on-off-on from off-on-off for example.

Regards
Sajive

**Comment by chemelli74** [comment]
Sorry to have overlooked this for so long.

Motion sensor is not supported: https://github.com/StyraHem/ShellyForHASS#devices-supported
Please open a FR and remember to add debug log with all CoAP-msg received by the device.

Simone

**Comment by chemelli74** [comment]
I'm going to close this issue.
If you want you can open a new FR.
Simone
