### ISSUE TITLE
timed out error messages

### ISSUE THREAD

**Issue by zsbobbob** [StyraHem/ShellyForHASS#276]
Hello,

HA 0.108.8
ShellyForHASS 0.1.8 beta1

Since I updated to 0.1.7 ShellyForHass I have timed out error messages at different devices and after HA restart the devices unavailable randomly:
This is the error message:

```log
2020-04-23 08:31:00 ERROR (CoAP) [pyShelly] Error http GET: http://10.0.1.48/settings, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```
This is my config:

> 
```yaml
discovery: true
mdns: false
igmp_fix: true
# unavailable_after_sec: 120
version: true #add version sensor
# discover_by_ip:
#     - '10.0.1.5'
#     - '10.0.1.13'
#     - '10.0.1.31'
#     - '10.0.1.48'
#     - '10.0.1.73'
#     - '10.0.1.81'
#     - '10.0.1.111'
#     - '10.0.1.161'
#     - '10.0.1.176'
#     - '10.0.1.181'
#     - '10.0.1.186'
#     - '10.0.1.188'
#     - '10.0.1.189'
sensors:
  - rssi
  - uptime
  - over_power
  - device_temp
  - over_temp
  # - power_factor
  - total_consumption
  - current_consumption
settings:
 total_consumption: { decimals: 2, div: 1000, unit: 'kWh' }
attributes:
  - default
devices:
  - id: 004574
    name: Redőny dolgozó
  - id: 00C77F
    name: Redőny étkező
  - id: 0083B0
    name: Redőny vendég
  - id: 00836f
    name: Redőny konyha
  - id: 0082AD
    name: Redőny fürdő benti
  - id: 00484C
    name: Redőny gyerekszoba
  - id: 0045AA
    name: Redőny terasz
  - id: 004579
    name: Redőny nappali
  - id: 68713D
    name: Redőny fürdő kinti
  - id: E09f8C
    light_switch: true
    name: Light switch garage
  - id: E2D878
    light_switch: true
    name: Light switch spájz
  - id: 76FB0B
    light_switch: true
    name: Light switch előszoba
    sensors:
      - switch
  - id: E0E632
    # light_switch: true
    name: Switch WC előszoba
    sensors:
      - switch
  - id: 041176
    name: Rack konnektor
    sensors:
      - consumption
      - current_consumption
      - total_consumption
  - id: 2677DA
    name: Fűtés benti fürdő
  - id: 79D1F8
    name: Fűtés hálószoba
  - id: 0418d8
    name: Fűtés gyerekszoba
  - id: 267AED
    name: Fűtés vendégszoba
  - id: 765bA1
    name: Fűtés Pongó
  - id: E61D9B
    light_switch: true
    name: Light switch külső kazán ajtó
  - id: 76BD8C
    name: Klíma
  - id: 376bf3
    name: Fűtés dolgozószoba
  - id: 76718A
    name: Switch folyosó
    sensors:
      - switch
  - id: 767CC4
    name: Switch WC benti
    sensors:
      - switch
  - id: 76FB0D
    light_switch: true
    name: Light gardrob
    sensors:
      - switch
  - id: DB451A
    name: Mosó szárítógép konnektor
  - id: 7657E9
    name: Flood kazán
    sensors:
      - battery
  - id: 76526C
    name: Flood konyha
    sensors:
      - battery
  - id: 765969
    name: Flood benti fürdő
    sensors:
      - battery
  - id: 765361
    name: Flood kinti fürdő
    sensors:
      - battery
  - id: 76620b
    light_switch: true
    name: Light ház körül
  - id: 26752A
    name: Kiosk konyha
  - id: 76dd1A
    name: Szivattyú
  - id: B8E0CC
    light_switch: true
    name: Light faház külső
  - id: 267DAA
    name: Mendy öntöző
  - id: F437F3
    light_switch: true
    name: Nappali LED RGB
  - id: F4332D
    light_switch: true
    name: Étkező ablak LED RGB
  - id: F43875
    light_switch: true
    name: Étkező LED RGB
  - id: 8CAAB505720C
    light_switch: true
    name: Konyha LED
  - id: 004757
    name: Redőny hálószoba
```
>

**Comment by chemelli74** [comment]
Are you able to connect to the web page when you receive the timeout in HA log ?

Simone

**Comment by zsbobbob** [comment]
Yes, I had a timed out error in the log http://10.0.1.186/color/0 at 09:02:17, I tried the link few seconds later in the browser and it worked.

Zsolt

**Comment by chemelli74** [comment]
Please try accessing the same URL, we already found users that have content blocking rules on router/AP and the page was blocked ;-)

Also if you can connect to your HA bash, try to run "curl -s http://10.0.1.186/settings" right after the timeout in.

Simone

**Comment by zsbobbob** [comment]
I tried with HA webterminal, it looks work:
<img width="1602" alt="Képernyőfotó 2020-04-23 - 9 18 05" src="https://user-images.githubusercontent.com/52219709/80070767-cef9c580-8543-11ea-9275-b3de59eb1844.png">
I do not have any content blocking on the router, I am using Pi-hole, but I guess it should not be an issue.
Here is the log from HA, I have random timed out error from different devices.
[home-assistant.log](https://github.com/StyraHem/ShellyForHASS/files/4520848/home-assistant.log)

I have this experience since the 0.1.7 version. This HA is running on an Intel NUC, but I have another HA (just to play with it) on an Raspberry PI, I have the same issue on it, the times of the error message is different.
This is the error message from the RPI HA log:
[home-assistant.log](https://github.com/StyraHem/ShellyForHASS/files/4520866/home-assistant.log)
I really appreciate if you have any idea what can be wrong.

Thanks in advance.
Zsolt

**Comment by chemelli74** [comment]
Issue is network related:

`socket.timeout: timed out`

I'm 99% convinced that what I'm going to ask doesn't change anything, but try to downgrade to 0.1.6 version of ShellyForHASS.
And maybe later on, upgrade to 0.1.8b1.

Simone

**Comment by zsbobbob** [comment]
Yes, looks like you are right. I tried roll back to 0.1.6 or 0.1.7, but still I have randomly unavailable. I tried to remove the shelly components and remove from the config add again only the covers, but still I have the same issue. Two cover continuously entity not available and some other randomly unavailable.

I tried to googling to understand what is wrong, understand, multicast, igmp etc. Still it is not clear where I should start.

I have a Snyology RT2600AC router with two MR2200AC in mesh. I can not find any settings what can cause the issue. The primery DNS is a Pi-hole, but I guess it should not be an issue.

The HA is running on a NUC in a docker with Ubuntu 18.04 host.

Can I have a suggestion, where to start the investigation.
1. on the Ubuntu host or
2. on the Synology router?
Thanks

**Comment by hakana** [comment]
What happens if you set igmp_fix to false (need restart HA)?
Can you see CoAP-msg under protocols on the main entity?
Do you have any error about shelly in the logs (under development)?
Try to set unavilable_after_sec to 120

**Comment by zsbobbob** [comment]
Still I have random unavailable devices.
Some lights and switch domains has protocols: CoAP-discovery, poll, some others:protocols: CoAP-discovery, CoAP-msg, poll.

Randomly I have the following error log:
`Logger: pyShelly
Source: /usr/local/lib/python3.7/site-packages/pyShelly/utils.py:37 
First occurred: 3:21:55 PM (6 occurrences) 
Last logged: 3:22:29 PM

Error http GET: http://10.0.1.181/settings, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Error http GET: http://10.0.1.65/settings, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Error http GET: http://10.0.1.127/settings, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Error http GET: http://10.0.1.6/settings, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Error http GET: http://10.0.1.58/settings, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out`

This is the current config:
`
discovery: true
mdns: false
igmp_fix: false
host_ip: '10.0.1.55'
unavailable_after_sec: 120
scan_interval: 50
version: true #add version sensor
# discover_by_ip:
    # - '10.0.1.5'
#     - '10.0.1.13'
#     - '10.0.1.31'
#     - '10.0.1.48'
#     - '10.0.1.73'
#     - '10.0.1.81'
#     - '10.0.1.111'
#     - '10.0.1.161'
    # - '10.0.1.176'
#     - '10.0.1.181'
#     - '10.0.1.186'
#     - '10.0.1.188'
#     - '10.0.1.189'
sensors:
  - rssi
  # - uptime
  - over_power
  - device_temp
  - over_temp
  # - power_factor
  - total_consumption
  - current_consumption
settings:
 total_consumption: { decimals: 2, div: 1000, unit: 'kWh' }
attributes:
  - default
devices:

#Cover
  - id: 004574
    name: Redőny dolgozó
  - id: 00C77F
    name: Redőny étkező
  - id: 0083B0
    name: Redőny vendég
  - id: 00836f
    name: Redőny konyha
  - id: 0082AD
    name: Redőny fürdő benti
  - id: 00484C
    name: Redőny gyerekszoba
  - id: 0045AA
    name: Redőny terasz
  - id: 004579
    name: Redőny nappali
  - id: 68713D
    name: Redőny fürdő kinti
  - id: 004757
    name: Redőny hálószoba


#Lights
  - id: E09f8C
    light_switch: true
    name: Garázs lámpa
  - id: E2D878 #nincs
    light_switch: true
    name: Spájz lámpa
  - id: 76FB0B
    light_switch: true
    name: Előszoba lámpa
    sensors:
      - switch
  - id: E0E632
    name: Switch WC előszoba
    sensors:
      - switch
  - id: E61D9B
    light_switch: true
    name: Light switch külső kazán ajtó
  - id: 76718A
    name: Switch folyosó
    sensors:
      - switch
  - id: 767CC4
    name: Switch WC benti
    sensors:
      - switch
  - id: 76FB0D
    light_switch: true
    name: Light gardrob
    sensors:
      - switch
  - id: 76620b
    light_switch: true
    name: Light ház körül
  - id: F437F3
    light_switch: true
    name: Nappali LED RGB
  - id: F4332D
    light_switch: true
    name: Étkező ablak LED RGB
  - id: F43875
    light_switch: true
    name: Étkező LED RGB
  - id: 8CAAB505720C
    light_switch: true
    name: Konyha LED
  - id: B8E0CC
    light_switch: true
    name: Light faház külső



#Switch
  - id: 041176
    name: Rack konnektor
    sensors:
      - consumption
      - current_consumption
      - total_consumption
  - id: 76BD8C
    name: Klíma
  - id: 26752A
    name: Kiosk konyha
  - id: 76DD1A
    name: Szivattyú
  - id: 267DAA
    name: Mendy öntöző
  - id: DB451A
    name: Mosó szárítógép konnektor


#Fűtés
  - id: 2677DA
    name: Fűtés benti fürdő
  - id: 79D1F8
    name: Fűtés hálószoba
  - id: 0418d8
    name: Fűtés gyerekszoba
  - id: 267AED
    name: Fűtés vendégszoba
  - id: 765bA1
    name: Fűtés Pongó
  - id: 376bf3
    name: Fűtés dolgozószoba


#Flood
  - id: 7657E9
    name: Flood kazán
    sensors:
      - battery
  - id: 76526C
    name: Flood konyha
    sensors:
      - battery
  - id: 765969
    name: Flood benti fürdő
    sensors:
      - battery
  - id: 765361
    name: Flood kinti fürdő
    sensors:
      - battery
`

**Comment by chemelli74** [comment]
> I have a Snyology RT2600AC router with two MR2200AC in mesh. I can not find any settings what can cause the issue. The primery DNS is a Pi-hole, but I guess it should not be an issue.
> 
> The HA is running on a NUC in a docker with Ubuntu 18.04 host.
> 
> Can I have a suggestion, where to start the investigation.
> 
> 1. on the Ubuntu host or
> 2. on the Synology router?

As it's a network issue, I would investigate with Synology how to configure correctly the router for multicast. They have a great support ( I use their NAS ) so I think they will be able to help.

> Some lights and switch domains has protocols: CoAP-discovery, poll, some others:protocols: CoAP-discovery, CoAP-msg, poll.

This sound a really strange.
Please compare firmware and every setting of a working Shelly ( CoAP-msg) vs a non working one. Also verify if they are connected to the same AP and if they have the same ip-class.

Simone

**Comment by zsbobbob** [comment]
Ticket opened at Synology support. I am looking forward what will they suggest.

Unfortunately I can not find any deviation in the settings of Shelly devices.
All they have the same ip range which is fixed in the router.

It can be a problem if some of them connected directly to RT2600 router and some of them one of the MR2200 wifi extender, which is working in mesh mode?

**Comment by chemelli74** [comment]
> It can be a problem if some of them connected directly to RT2600 router and some of them one of the MR2200 wifi extender, which is working in mesh mode?

I bet one of them doesn't support multicast and this is why you don't have CoAP-msg.
Can you check if all devices on RT2600 have the same behaviour ? What about devices on MR2200 ?

Simone

**Comment by zsbobbob** [comment]
Unfortunately I can not see connection. Ex.: I have 3 RGBW2 Shelly relay. Two of them connected to RT2600 and one of them to an MR2200. 3 restart of HA and some times 2, sometimes 1 RGBW2 relay was not available, does not matter which synology wifi point is used.

Is it ok, if the shelly devices with cover domain has no protocol attributes?
<img width="790" alt="Képernyőfotó 2020-04-26 - 11 59 06" src="https://user-images.githubusercontent.com/52219709/80304335-5863fe80-87b5-11ea-84d5-568b3a5e8e90.png">

**Comment by chemelli74** [comment]
Did you get any feedback from Synology support ?
Can you test connecting all devices on a single AP ?

Simone

**Comment by zsbobbob** [comment]
No, I do not received any feedback from Synology. After upgrade to 0.109 seems less unavailability, but still I have some random error:

Tomorrow I will check with one AP, but some of them will not be able to connect, because there will be no signal, let see. I come back to you tomorrow.

```log
 Log Details (ERROR)
Logger: pyShelly
Source: /usr/local/lib/python3.7/site-packages/pyShelly/utils.py:37 
First occurred: 7:12:13 PM (12 occurrences) 
Last logged: 7:48:49 PM

Error http GET: http://10.0.1.73/color/0, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Error http GET: http://10.0.1.186/color/0, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Error http GET: http://10.0.1.189/color/0, timed out, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get conn.request("GET", url, None, headers) File "/usr/local/lib/python3.7/http/client.py", line 1252, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 966, in send self.connect() File "/usr/local/lib/python3.7/http/client.py", line 938, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection raise err File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection sock.connect(sa) socket.timeout: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

**Comment by chemelli74** [comment]
@zsbobbob, any news ?

Simone

**Comment by zsbobbob** [comment]
I tried  with one AP only with RT2600 without the MR2200repeater. The result is the same, randomly I had not available devices.
I have also received answer from Synology:


Support ticket #2510494 has been updated by Synology Technical Support. Please go to your Synology Account to respond to this ticket or receive further assistance. A preview of the updated ticket is shown below:
Dear customer,

please excuse the late check-in.
Due to the current situation and order situation our support is a bit limited.

Many thanks for your understanding.


If you should connect the devices via WLAN, I have a few points here that I would like you to check.
These was theirsuggestion

● Move the device next to the router and check if the issue still persists.

● (5GHz) Change channel to band 1(CH 36-48) or band 4(CH 149-161) to avoid radar issue. (DFS channel uses the same frequency with radar.)

(When a router detects the radar signal, it will changes to another channel which causing the Wi-Fi interruption. You will see the radar detect in /var/log/messages)

11207: May 27 07:30:05 SynologyRouter kernel: [12571.440000] WL1: DFS: UNCLASSIFIED ########## RADAR DETECTED ON CHANNEL 100/80 ########## Intv=12164, min_pw=13, AT 11650500MS
● (2.4GHz) Change the channel to 1.6.11 and check if the issue still persists.

● IoT or smart device please set the key rotation=0, DTIM=1, Disable PMF and check if the issue still persists.



● Turn off Smart Connect and check the issue is only happen on the specific band or both 2.4GHz and 5GHz band.

I did not see any radar detection message, so I guess the first part is not an issue. After change the key rotation to 0 and DTIM to 1 and turn off Smart Connect, seems I have less devices unavailable.

After I changed the mdns to true and the igmp_fix to true, looks all devices are available. Currently the scan interval is 5, the unavailable_after_sec is 120.

Still the protocolls are mixed, I have the following version of protocols:
1. CoAP-discovery, poll
2. CoAP-discovery, CoAP-msg, mDns, poll
3. CoAP-discovery, CoAP-msg, poll
4. CoAP-msg, poll
5. CoAP-msg, mDns, poll

If I understand well one of your previous comment, it should be the same for all shelly devices?

**Comment by chemelli74** [comment]
Yes, should be the same for all devices in the same network.

Based on the 5 point above, I would say that multicast is still not working as it should affecting both mDns and CoAP-msg.
Please update the ticket reporting this details to Synology support.

Simone

**Comment by zsbobbob** [comment]
Is is it normal if I do not see protocols attributes at the cover domains?

**Comment by chemelli74** [comment]
> Is is it normal if I do not see protocols attributes at the cover domains?

> I found this description on the synology support site:

Shelly's are configured as cover, so yes the domain is correct.
 
> Multicast translation: Enable this option to translate multicast packets into unicast packets for better performance regarding streaming services.
> Note: This option is always set as Enabled when the Synology product joins a mesh network.
> 
> RT2600 and MR2200 are in a mesh network, do you think that the above description cause the issue?

Yes this is a good point to investigate, HA needs the multicast CoAP packets without translation of any kind.

Simone

**Comment by zsbobbob** [comment]
I mean that the cover domains has no protocol attributes:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/52219709/82148498-ac15b500-9854-11ea-9ac6-7f0bf50da90c.png">

**Comment by chemelli74** [comment]
> I mean that the cover domains has no protocol attributes:

oh, you are right.
Let's ask @hakana to check ;-)

Simone

**Comment by hakana** [comment]
On the devices missing mDns and CoAP-msg the multi casts not working.

This must be a network issue. I can't help you with more than that.

**Comment by chemelli74** [comment]
@zsbobbob, we are going to close this issue about the "timeout" as we can't help more that what we already did.

About the protocols missing for domain covers, I'm going to open a new issue.

Simone

**Comment by zsbobbob** [comment]
Ok, thanks, I will check the mqtt implementation in 0.1.9 beta 2.
