### ISSUE TITLE
Discovery only happens if on same Wifi network

### ISSUE THREAD

**Issue by DarrenRatcliffe** [StyraHem/ShellyForHASS#28]
Is it possible to have Shelly devices discovered if they are on a different WiFi network to Home Assistant?

My devices are on a separate WiFi to HA and discovery doesn't work, when I move them to the same WiFi they discover fine. It is becoming a more common to have IoT devices on a separate network so it would be great if this would work

**Comment by hakana** [comment]
@DarrenRatcliffe 
CoAP protocol is used by Shelly to communicate with this plugin (multicast UDP packages). They use the group address 224.0.1.187 on port 5683.

How does your network look like? Do you have different sub-nets with routers between? It is possible to setup a route for multicast messages also. Let me know a bit more about your setup.

**Comment by ohadlevy** [comment]
I have a separate vlan between my shellies and my haas, I guess some multicast iptables forwarding is required.

**Comment by hakana** [comment]
Will it help if I wrote a proxy in python that forward it from other lan/subnet to the HASS plugin? This require you can run the proxy on a computer in the other lan/subnet. The proxy catch the CoAP message from te Shelly devices and send them to the Plugin by specifying the IP address for the HASS server.

Another option may be to setup a IGMP-proxy (upstream+downstream). I tried that in my setup without any success, so for me the python proxy will be lot easier to set up.

**Comment by hakana** [comment]
Added to latest release, 0.0.15. Use the proxy script under util.
