### ISSUE TITLE
Unable to read setting screens in HA (GUI integration)

### ISSUE THREAD

**Issue by teknikpappan** [StyraHem/ShellyForHASS#281]
My system versions:
Home Assistant 0.108.9 and Release 0.1.8 (Beta 1)
HA language is swedish.

I'm unable to read the setting pages (GUI) in HA for Shelly integration. I see the checkboxes and can check them. I also see SEND button on the setting screen 1,2 and 5. There seems to be NEXT button on 3 and 4 which I can't see but is able to click to proceed (tab-ing from last checkbox puts you in the invisible NEXT).

Changing HA language to english makes no diff. Removing the integration, restarting HA and adding the integration makes no diff. as well.

Let's hope someone has a solution.

![IMG_2690](https://user-images.githubusercontent.com/64425082/80391391-f5a25e00-88ad-11ea-8861-3c90e27a1221.JPG)
![IMG_2691](https://user-images.githubusercontent.com/64425082/80391396-f76c2180-88ad-11ea-8b50-a0e8d4e5509f.JPG)
![IMG_2692](https://user-images.githubusercontent.com/64425082/80391398-f89d4e80-88ad-11ea-8cb9-62fbba37ecc6.JPG)
![IMG_2693](https://user-images.githubusercontent.com/64425082/80391403-f9ce7b80-88ad-11ea-947f-3188ca69cef4.JPG)
![IMG_2694](https://user-images.githubusercontent.com/64425082/80391410-fa671200-88ad-11ea-8deb-26e7dfa203a0.JPG)
![IMG_2695](https://user-images.githubusercontent.com/64425082/80391413-fb983f00-88ad-11ea-87b5-62d86976d788.JPG)

**Comment by chemelli74** [comment]
One question I didn't ask on FB: are you using built-in theme or not ?

Also please post home-assistant.log.

Simone

**Comment by teknikpappan** [comment]
I use the built-in Lovelace.

Not sure what log you need: here is the overall one from Developer tools:

Config entry for ipp not ready yet. Retrying in 5 seconds.
11:25:35 – config_entries.py (WARNING) - Meddelandet inträffade först 27 april 2020 14:44:48 och har hänt 890 gånger
Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
11:25:35 – ipp (ERROR) - Meddelandet inträffade först 27 april 2020 14:44:48 och har hänt 890 gånger
socket.send() raised exception.
11:23:45 – components/websocket_api/http.py (WARNING)
socket.send() raised exception.
11:23:45 – components/websocket_api/http.py (WARNING) - Meddelandet inträffade först 11:23:45 och har hänt 16 gånger
Error on retrieving data: empty response
9:33:36 – waze_travel_time (WARNING) - Meddelandet inträffade först 27 april 2020 15:05:04 och har hänt 26 gånger
[Philips TV Vardagsrum:8009] Failed to connect to service TPM171E-396af488298de5e35782145f2a0cc7e9._googlecast._tcp.local., retrying in 5.0s
6:05:54 – /usr/local/lib/python3.7/site-packages/pychromecast/socket_client.py (ERROR) - Meddelandet inträffade först 27 april 2020 18:26:49 och har hänt 5 gånger
[HOME Mini Källare:8009] Heartbeat timeout, resetting connection
6:05:44 – /usr/local/lib/python3.7/site-packages/pychromecast/socket_client.py (WARNING) - Meddelandet inträffade först 27 april 2020 18:26:19 och har hänt 11 gånger
[MUSIK HOME Alla:42344] Error communicating with socket, resetting connection
4:39:35 – /usr/local/lib/python3.7/site-packages/pychromecast/socket_client.py (WARNING) - Meddelandet inträffade först 2:57:22 och har hänt 6 gånger
[MUSIK HOME Alla:42344] Error reading from socket.
4:39:35 – /usr/local/lib/python3.7/site-packages/pychromecast/socket_client.py (ERROR) - Meddelandet inträffade först 2:57:22 och har hänt 6 gånger
Update of sensor.trv_vastberga_humidity is taking over 10 seconds
4:30:10 – __main__.py (WARNING) - Meddelandet inträffade först 27 april 2020 15:04:59 och har hänt 24 gånger
Failed request
27 april 2020 21:28:09 – tellduslive (WARNING) - Meddelandet inträffade först 27 april 2020 21:10:36 och har hänt 14 gånger
Failed request: HTTPSConnectionPool(host='api.telldus.com', port=443): Max retries exceeded with url: /json/sensors/list?includeValues=1&includeScale=1&includeIgnored=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa8c2e910>, 'Connection to api.telldus.com timed out. (connect timeout=10)'))
27 april 2020 21:28:09 – /usr/local/lib/python3.7/site-packages/tellduslive.py (WARNING) - Meddelandet inträffade först 27 april 2020 21:10:26 och har hänt 28 gånger
Could not fetch weather data: Cannot connect to host api.trafikinfo.trafikverket.se:80 ssl:None [Connect call failed ('188.121.79.138', 80)]
27 april 2020 21:26:38 – trafikverket_weatherstation (ERROR) - Meddelandet inträffade först 27 april 2020 21:06:34 och har hänt 18 gånger
Host timeout.
27 april 2020 20:18:46 – components/asuswrt/device_tracker.py (ERROR)
Setup of binary_sensor platform ping is taking over 10 seconds.
27 april 2020 14:44:54 – Binär sensor (WARNING)
Error setting up entry patrick@arkley.se for icloud
27 april 2020 14:44:44 – components/icloud/__init__.py (ERROR)

**Comment by chemelli74** [comment]
> I use the built-in Lovelace.

I would like to know if you use the default theme of HA or not.
 
> Not sure what log you need: here is the overall one from Developer tools:
> 

Please enable debug log: [https://github.com/StyraHem/ShellyForHASS/wiki/FAQ4:-Enable-debug-log](https://github.com/StyraHem/ShellyForHASS/wiki/FAQ4:-Enable-debug-log)

Simone

**Comment by teknikpappan** [comment]
Default theme it is.

Will get back to you on the log

**Comment by teknikpappan** [comment]
Hi.

This is done. How do I pull the nec. log details from HA then? I guess that
is not so easy for a novis like me.

/Patrick

Den tis 28 apr. 2020 kl 11:54 skrev Simone Chemelli <
notifications@github.com>:

**Comment by chemelli74** [comment]
> Hi. This is done. How do I pull the nec. log details from HA then? I guess that is not so easy for a novis like me.

First you need to update your configuration.yaml as per our wiki.
Then to read the log just look at "home-assistant.log" or if you prefer, install "uilogs" from HACS.

Simone

**Comment by hakana** [comment]
Have you tried to upgrade to the latest HA 109.3? 
You can also try to upgrade ShellyForHass to 0.1.8.

I can't reproduce this problem, so it is very strange.

You can contact me on info@styrahem.se or call us if you need more help and we can do it in Swedish.

**Comment by teknikpappan** [comment]
Hi.

Will update all. However, I think my SD card is starting to fail on me so I
need to get HA up and running on a USB instead. I'll be back.

May the force be with you!

Den mån 4 maj 2020 kl 10:45 skrev hakana <notifications@github.com>:

**Comment by teknikpappan** [comment]
With latest versions I do see the text.

Thanks.

Den mån 4 maj 2020 kl 13:11 skrev Patrick Arkley <patrick@arkley.se>:
