### ISSUE TITLE
error in report

### ISSUE THREAD

**Issue by davide-rhw** [StyraHem/ShellyForHASS#284]
new hassio 109:

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:206
First occurred: 10:48:44 (12 occurrences)
Last logged: 10:48:47

shelly: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

**Comment by chemelli74** [comment]
Duplicate #279 

Simone
