### ISSUE TITLE
Error in log when starting HA 0.109.1

### ISSUE THREAD

**Issue by TASSDevon** [StyraHem/ShellyForHASS#285]
I just updated to the newest HA version and when monitoring the log I noticed the following errors:

`2020-04-30 10:51:24 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_8caab505e877_firmware_update. Platform shelly does not generate unique IDs
2020-04-30 10:51:25 ERROR (MainThread) [homeassistant.components.switch] Entity id already exists - ignoring: switch.shelly_shsw_1_8caab505e38b_firmware_update. Platform shelly does not generate unique IDs`

I know there are 2 shelly's in my network that have a firmware upgrade available. Is this something that HA 0.109 broke with the integration?

**Comment by chemelli74** [comment]
Same issue here as well.
I close this one as there is already one similar: #228 

Simone
