### ISSUE TITLE
Shelly 2.5, cover display wrong

### ISSUE THREAD

**Issue by toby17780** [StyraHem/ShellyForHASS#286]
HA 0.109.1 (but I don't know if it was better in older releases - i don't think so)

Hello, I think a little bug:
I use the "REVERSE DIRECTIONS" Option "Enable if the directions of movement do not match the directions in the interface."

And now, the cover works correct! But when I klick on "down", the icon changes to "up" and vice versa. Anybody the same?

**Comment by chemelli74** [comment]
Please rewire your Shelly in the correct way.
We don't want to make this plugin too much complicated adding all sort of options.

Thank you for your understanding,

Simone
