### ISSUE TITLE
polling attemps to add HA docker container IP

### ISSUE THREAD

**Issue by 0n3man** [StyraHem/ShellyForHASS#287]
I get the following error "INFO (Poll) [pyShelly] Error adding device, 172.30.32.1" at the polling interval.  This IP is the IP for hassio as seen from ifconfig:

hassio: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.30.32.1  netmask 255.255.254.0  broadcast 172.30.33.255

I removed shellyforhass and re-installed and now I get this error twice every polling interval.  Any idea how get this IP out of the polling process?

**Comment by chemelli74** [comment]
Please update to 0.1.8b2 an dreport back.

Simone

**Comment by 0n3man** [comment]
Polling message is gone, so looks good.
