### ISSUE TITLE
switches wait until polling interval to update state

### ISSUE THREAD

**Issue by 0n3man** [StyraHem/ShellyForHASS#288]
I'm using shelly 1 switches.  I just stared using them a couple of days ago.  When I us the lovelace "Picture Elements Card" with an entity on the my floor plan I can click on the light and the real switch immediately turns on.  The GUI however doesn't get indication of the state change until the next polling cycle.  The default is 60 seconds so the switches appear to be very non-responsive.  Since the GUI state doesn't change, clicking the element again will not change the state.  So in other words I can not turn a light on and then back off before the polling cycle.  Watching the database state_change events the database record is also updated on this polling cycle.  Ideally the state of the switch would update when the switch is toggelled and not wait until the next polling cycle.  I also use a different brands of switches and the shelly is the only that works in this fashion.

**Comment by chemelli74** [comment]
Please check wiki: your network doesn’t play well with CoAP-msg due to some restrictions on multicast packets.

Simone

**Comment by 0n3man** [comment]
tcpdump only shows outbound packets from HA to the multicast address 224.0.1.187 as identified in the wiki.  Multi case from the switch is to 244.0.0.251.  From tcpdump:

15:25:28.723151 IP 192.168.10.81.5353 > 224.0.0.251.5353: 0*- [0q] 6/0/0 PTR _http._tcp., PTR shelly1-98F4ABD0B919._http._tcp.local., (Cache flush) SRV shelly1-98F4ABD0B919.local.:80 0 0, (Cache flush) TXT "id=shelly1-98F4ABD0B919" "fw_id=20200320-123430/v1.6.2@514044b4" "arch=esp8266", (Cache flush) A 192.168.10.81, (Cache flush) NSEC (449)

Any chance this is the CoAP message?

**Comment by 0n3man** [comment]
I update firmware in my wifi router and now I at least get the following

16:29:17.693402 IP 192.168.10.81 > 224.0.1.187: igmp v2 report 224.0.1.187

but this still doesn't seem to get the messages desired.  I tried using the mqtt capability of the switch and that works great.  I'll probably just switch to using that until I hit a need to upgrade the wifi.

Thanks for the information on this.

**Comment by chemelli74** [comment]
Please check our wiki:

[FAQ2:-Slow-updates-of-lovelave-UI](https://github.com/StyraHem/ShellyForHASS/wiki/FAQ2:-Slow-updates-of-lovelave-UI)

[FAQ6:-Troubleshoot-CoAP-messages](https://github.com/StyraHem/ShellyForHASS/wiki/FAQ6:-Troubleshoot-CoAP-messages)

Simone

**Comment by 0n3man** [comment]
I never got this to work, but I buy the fact that it's probably a problem with my wifi router not passing the messages.
