### ISSUE TITLE
[Feature] Double press recognition

### ISSUE THREAD

**Issue by GregoryKowalik** [StyraHem/ShellyForHASS#29]
Hi, it's Greg. 
I'm extremely interested in ability to use double press or long press actions using original Shelly firmware. Since the stock FW supports only long press I'd like to implement not supported actions by Shelly in Home Assistant. So knowing that relay can be detached from the physical button the status of the switch can be controlled by your awesome component so I can recognize double press in HA and send a command to another relay for instance. Would it be possible any when?

Thanks

**Comment by hakana** [comment]
Yes, we hope that. We need support in fw for this and it will be implemented. I just asked Shelly for the road map for this.

**Comment by hakana** [comment]
Fixed in latest release
