### ISSUE TITLE
[FR] better temperature resolution for Shelly H&T

### ISSUE THREAD

**Issue by halecivo** [StyraHem/ShellyForHASS#292]
## Is your feature request related to a problem? Please describe.

My Shelly H&T is configured to report a 0.5 °C temperature change, but graph is always shown in 1 °C resolution. We are very sensitive for a temperature in bedroom and 1 °C difference is quite notable.

See the attached image. MQTT data providing unrounded result is in red, while rounded data from Shelly integration component is green.

![image](https://user-images.githubusercontent.com/11456331/80956491-a1ddca80-8e01-11ea-87d1-c3ef4b88d51d.png)

## Describe the solution you'd like
I would like to be able to configure rounding of the temperature, having rounding to 0.1°C rather than 1°C would solve the problem for me.

**Comment by chemelli74** [comment]
This plugin is not using MQTT, are you sure you have ShellyforHASS configured ?

Simone

**Comment by hakana** [comment]
You can configure number of decimals in config.yaml

**Comment by halecivo** [comment]
@chemelli74 I know it does not use MQTT - I just put data from same sensor using MQTT to show what I would like to achieve.

@hakana thanks for advice, I tried to add
```
shelly:
  settings:
    temperature: { decimals: 1 }
```
into `configuration.yaml` and restarted server. Integration page now shows two shelly integrations (see the image), Shelly H&T appears in both of them, but none shows 1 decimal number - it is still rounded to °C.  Am I still doing something wrong?
![image](https://user-images.githubusercontent.com/11456331/80967735-225af600-8e17-11ea-80fd-4ce0dc073200.png)

**Comment by hakana** [comment]
Yes, now you have two different instances. One created from config.yaml and one from UI. You can remove the one from UI and only use it by config.yaml. If you have changed settings in UI you need to add them to config.yaml.

If you use same prefix (default) in both configurations they will overwrite same sensor. Try to remove the one from UI or add another prefix in config.yaml.

**Comment by halecivo** [comment]
@hakana thanks for the tip with prefix, it helped me to test the solution without using the old configuration.

It would be nice to have this configuration available without config.yaml, but issue can be closed, if you are not going to implement it, as I'm okay to switch to yaml config in that case.

**Comment by hakana** [comment]
Yes, it will come but it lots of work so it will take some time.

II will close this issue now.
