### ISSUE TITLE
[BUG] ShellyForHASS does not detect Shelly

### ISSUE THREAD

**Issue by WirelessMind** [StyraHem/ShellyForHASS#294]
## Environment

- ShellyForHASS release with the issue: 1.8
- Last working ShellyForHASS release (if known):  1.7
- Home Assistant Core release with the issue: 0.109.4
- Operating environment (Home Assistant/Supervised/Docker/venv): HASSIO on Docker

## Describe the bug
I had ShellyForHASS 1.7. When I installed it, it worked.
I upgraded to 1.8 All Shelly (3 Shelly 1PM) were unavailable, even after restarting.
I tried to remove ShellyForHASS and he rejoined it, but now he doesn't see anyone Shelly anymore. The same as trying to reinstall version 1.7

## Steps to Reproduce
I added (and then updated) ShellyForHASS via HACS and configured via GUI

## Expected behavior
It should detect 3 Shelly 1 PM

**Comment by WirelessMind** [comment]
Suddenly they reappeared, but always "unavailable"

**Comment by hakana** [comment]
Do you have any Shelly errors in the log (/developer-tools/logs)?

**Comment by WirelessMind** [comment]
> Do you have any Shelly errors in the log (/developer-tools/logs)?

no.
I have no idea to resolve...

**Comment by hakana** [comment]
Do you use config.yaml or GUI?

**Comment by WirelessMind** [comment]
I use GUI

**Comment by bastiaanterhorst** [comment]
I have the same issue with my 1pm. Disappeared after the update and I cant get it back. I'm configuring using configuration.yml (not GUI). I have also tried adding the device by ip (discover_by_ip) but also no luck.

**Comment by hakana** [comment]
@bastiaanterhorst Any errors in log?
Have you tried to downgrade ShellyForHass?

**Comment by WirelessMind** [comment]
I had tried with the downgrade, but nothing, so I went back to the latest version.
Today one of the 3 Shelly 1 PM magically started seeing him again!
I'm waiting for the other 2 to decide! :D

**Comment by hakana** [comment]
@WirelessMind 
What do your protocol attribute show?

**Comment by bastiaanterhorst** [comment]
> @bastiaanterhorst Any errors in log?
> Have you tried to downgrade ShellyForHass?

I just tried the downgrade, but still no Shelly devices showing up… Very strange. I have tried uninstalling via HACS and reinstalling as well, but no entities show up. No errors in the log either.

**Comment by WirelessMind** [comment]
> What do your protocol attribute show?

Which attribute protocol? Where do I see it?

**Comment by hakana** [comment]
@WirelessMind 
If you click on the visible device switch there will be a protocols row.
![image](https://user-images.githubusercontent.com/1168654/81399898-327f1800-912c-11ea-8fc4-8738fbf74017.png)

**Comment by WirelessMind** [comment]
ah ok! 
protocols: CoAP-discovery, CoAP-msg, poll, mDns
![1](https://user-images.githubusercontent.com/18408814/81400347-221b6d00-912d-11ea-9dd9-952ad3bcdcc3.png)

**Comment by hakana** [comment]
@WirelessMind Ok, then everything working for that device and the other devices should also be detected.
Do you use multiple AP in a mesh?

**Comment by WirelessMind** [comment]
I have a mesh network (google Wifi)

**Comment by WirelessMind** [comment]
I tried to turn off the google wifi and they all came back online.
But why don't they work with the mesh network?
With Alexa and through the app they have no problems!

**Comment by hakana** [comment]
I think Google Mesh not support mDns, multicast etc that it used for discovery. App and Alexa using the Shelly Cloud for communication. We will try to add that option to ShellyForHass later.

Do you have latest firmware for Google Mesh, maybe that helps to update.

**Comment by bastiaanterhorst** [comment]
I ended up trying a hard reset of the Shelly, and after that it got picked
up by HA. Pretty strange, but at least it works again.

For me, the entity shows CoAP-discovery, poll for protocols, even though
multicast is on. Could that be why I had issues before?

**Comment by chemelli74** [comment]
> I think Google Mesh not support mDns, multicast etc that it used for discovery. 
> [...]
> Do you have latest firmware for Google Mesh, maybe that helps to update.

Seems mDNS is not well supported and latest firmware doesn't fix.
Also Google did not acknoledge the problem.
Reference (a bit old maybe): [https://support.google.com/googlenest/thread/11386387?hl=en](https://support.google.com/googlenest/thread/11386387?hl=en)

Simone

**Comment by chemelli74** [comment]
@WirelessMind, @bastiaanterhorst , can we close this issue ?

Simone

**Comment by WirelessMind** [comment]
> @WirelessMind, @bastiaanterhorst , can we close this issue ?
> 
> Simone

Ok for me 

Thanks!
