### ISSUE TITLE
Shelly dimmer keep wrong status in ha

### ISSUE THREAD

**Issue by alkesander** [StyraHem/ShellyForHASS#296]
Hi, 

I have successfully installed and added new shelly dimmer. It turns on/off when I interact with the switch in ha and changes brightness. The only problem is that the status is not properly updated after the switch action is executed. 

What I mean is the situation, when after switching the light on the status reverts back to being off in home assistant and the only way to switch off the light is to press the switch twice (force switch to be turned on and then quickly to turn it off before the status dissynchronize). 

What is weird, this situation is not present when using shelly app. 

Can someone help me, I am stuck and don't know how to fix this... Please let me know if you need more details. 

Cheers,
Alek

**Comment by hakana** [comment]
It will be a fix for this in the next release until then you can turn down scan_interval to 5 sec so it updates faster.

**Comment by alkesander** [comment]
Ok, great to hear that! Thanks!

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.9.b1) and recheck.

Simone

**Comment by alkesander** [comment]
Hi Simone, 
I can confirm the problem is no longer there when using the new beta. Thanks a lot!
BR, 
Alek
