### ISSUE TITLE
Timeout for actions.

### ISSUE THREAD

**Issue by Puntoboy** [StyraHem/ShellyForHASS#297]
I recently added this to my Home Assistant setup. It mostly works as I would expect but I'm having an issue when trying to control the shelly from a Zigbee switch. It's like there is a timeout period set in so that I can only control the shelly once each minute. I press the switch, shelly turns on, then if I press the switch again, nothing happens. If I wait a minute and press it again the shelly turns off instantly.

**Comment by chemelli74** [comment]
Please report back witch protocols are shown in the entity details page.

Simone

**Comment by chemelli74** [comment]
And fill the issue template please

Simone

**Comment by hakana** [comment]
Tees 0.1.9-beta 1, think this is fixed there.

**Comment by Puntoboy** [comment]
> 
> 
> And fill the issue template please
> 
> Simone

Where do I find the template?

**Comment by Puntoboy** [comment]
> 
> 
> Please report back witch protocols are shown in the entity details page.
> 
> Simone

Not sure what you mean? I can't see any protocols.

![image](https://user-images.githubusercontent.com/11718878/81498610-ce8c5900-92bd-11ea-9c33-8b69a6cc1ca5.png)

**Comment by chemelli74** [comment]
> > And fill the issue template please
> > Simone
> 
> Where do I find the template?

When you open a issue, there is a template to fill.
We need it filled.
Thank you,

Simone

**Comment by Puntoboy** [comment]
> 
> 
> > > And fill the issue template please
> > > Simone
> > 
> > 
> > Where do I find the template?
> 
> When you open a issue, there is a template to fill.
> We need it filled.
> Thank you,
> 
> Simone

Ah I was on my phone when I did it and didn't see that option sorry.
