### ISSUE TITLE
[BUG] Timeout for one minute after first operation

### ISSUE THREAD

**Issue by Puntoboy** [StyraHem/ShellyForHASS#298]
## Environment

- ShellyForHASS release with the issue:   0.1.8
- Last working ShellyForHASS release (if known): First install
- Home Assistant Core release with the issue: 0.109.0
- Operating environment (Home Assistant/Supervised/Docker/venv):  Docker on Synology

## Describe the bug

Operating the Shelly switch from a Zigbee button works, but there seems to be a timeout when trying more often than once a minute. So first button press instant operation, second press nothing, keep trying for under a minute still nothing, try after one minute and the switch operates. 

## Steps to Reproduce

first button press instant operation, second press nothing, keep trying for under a minute still nothing, try after one minute and the switch operates. 

## Expected behaviour

Shelly should react to every button press

## Traceback/Error logs

```txt

```

## Additional context

My Zigbee buttons operate all other devices every press, with no timeout.

**Comment by chemelli74** [comment]
Please double click on an affected entity and report attribute "protocols".

Simone

**Comment by Puntoboy** [comment]
![image](https://user-images.githubusercontent.com/11718878/81502940-e9b89200-92d8-11ea-8aba-2ab0d35ec54e.png)

**Comment by chemelli74** [comment]
> Protocols: IP-addr, poll

This is why you have slow updates.
Please see our wiki for more informations: [FAQ2:-Slow-updates-of-lovelave-UI](https://github.com/StyraHem/ShellyForHASS/wiki/FAQ2:-Slow-updates-of-lovelave-UI)

Simone

**Comment by Puntoboy** [comment]
> 
> 
> > Protocols: IP-addr, poll
> 
> This is why you have slow updates.
> Please see our wiki for more informations: [FAQ2:-Slow-updates-of-lovelave-UI](https://github.com/StyraHem/ShellyForHASS/wiki/FAQ2:-Slow-updates-of-lovelave-UI)
> 
> Simone

Why is the first press almost instant but I have to wait exactly 1 minute to operate it again?

**Comment by chemelli74** [comment]
> > > Protocols: IP-addr, poll
> > 
> > 
> > This is why you have slow updates.
> > Please see our wiki for more informations: [FAQ2:-Slow-updates-of-lovelave-UI](https://github.com/StyraHem/ShellyForHASS/wiki/FAQ2:-Slow-updates-of-lovelave-UI)
> > Simone
> 
> Why is the first press almost instant but I have to wait exactly 1 minute to operate it again?

Enable debug mode and check logs. See wiki for details on how to proceed.

Simone

**Comment by Puntoboy** [comment]
I'm using a UniFi router. I don't think it's easy to fix. I may have to move the Shelly to my LAN network.

**Comment by Puntoboy** [comment]
OK so I've enabled mDNS in the UniFi software that has changed the protocol in the entity.

![image](https://user-images.githubusercontent.com/11718878/81505963-0f4e9700-92eb-11ea-8d0e-29046bf8e49d.png)

That didn't fix it, however I then changed my Node-Red automation to rather than toggle the Shelly Switch, it just turn it on, then another one to turn it off. Both of those works instantly it just means I have to have both switches operated by each button press together rather than on their own. The button only have limited press options.

**Comment by Puntoboy** [comment]
It's changed again now. 

![image](https://user-images.githubusercontent.com/11718878/81508355-8429cd00-92fb-11ea-8df7-81cd830a1163.png)

**Comment by chemelli74** [comment]
Until you don't have "CoAP-msg" you cannot get instant fedback.

This is well explained in the wifi.
Unfortunately, nothing we can do about it.

If there are no new infos, I'm going to close this issue.

Simone

**Comment by chemelli74** [comment]
No additional info received.
Closing.

Simone
