### ISSUE TITLE
Exclude Enity

### ISSUE THREAD

**Issue by AngelofromTurin** [StyraHem/ShellyForHASS#30]
Hi, 
How to exclude entity? 
thise my example:
shelly:
  discovery: false
  version: true
  wifi_sensor: true
  devices:  #configure devices
    - id: 66167A
      name: Luce Led Soggiorno #set friendly name
    - id: 66167A-4
      name: Luce Led Soggiorno #set friendly name
now i have the name for the channel that i use and for the shelly's device for give name at the sensor (rssi , update, etc) 
but ha show me the channel 1,2,3 i dont want thise because dont have real light
thanks

**Comment by hakana** [comment]
Remove:
- id: 66167A
name: Luce Led Soggiorno #set friendly name
That line include all 1,2,3,4 devices
