### ISSUE TITLE
[FR] Add decimal to Shelly Flood Temperature Sensor

### ISSUE THREAD

**Issue by mattia480** [StyraHem/ShellyForHASS#300]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
It would be helpful to add decimals to the Shelly Flood temperature sensor value.

## Describe alternatives you've considered
If is not possible to add decimal to value is it possible to add the complete value with decimal as attribute state?

## Additional context
![image](https://user-images.githubusercontent.com/29857651/81568363-f18e3a00-939d-11ea-82fa-6ff2cb8ed3bd.png)

Thank you!

**Comment by chemelli74** [comment]
Please fill the template when opening a FR.

Simone

**Comment by mattia480** [comment]
@chemelli74 Fixed

**Comment by chemelli74** [comment]
Did you check [documentation ](https://github.com/StyraHem/ShellyForHASS#decimal-and-unit-settings) ?

Simone

**Comment by mattia480** [comment]
> Did you check [documentation ](https://github.com/StyraHem/ShellyForHASS#decimal-and-unit-settings) ?
> 
> Simone

Sure! As says [here](https://github.com/StyraHem/ShellyForHASS#types-decimal-units-and-default-settings-017) temperature has 0 decimals, but in the [schreenshots](https://github.com/StyraHem/ShellyForHASS#screenshots) is cleary visible that Shelly H&T has 1 decimal. It's a quite strange that for H&T decimal is 1 and for Shelly flood is 0 (for both in the docs it says 0). I can confirm you that in the original Shelly Android App i can see decimals also for  ther temperature sensor of ther Shelly Flood Sensor.

**Comment by mattia480** [comment]
I saw the [paragraph](https://github.com/StyraHem/ShellyForHASS#decimal-and-unit-settings) now.
Sorry for my mistake! =(
