### ISSUE TITLE
[FR] Limit the movement of cover device (Shelly Roller 2.5)

### ISSUE THREAD

**Issue by boocko** [StyraHem/ShellyForHASS#301]
## Is your feature request related to a problem? Please describe.

  I have curtains (Shelly 2.5 as a HA cover device) that I don't want to move from totally opened to totally closed.

## Describe the solution you'd like

  It would be nice to have the upper and lower limit of position configurable per device. Then, "close" means "go to lower limit", and similarly "open" means "go to upper limit". The same with status: "closed" means "position == lower limit", open means "position == upper limit".

## Describe alternatives you've considered

I know it's achievable in HA scripting, but this would be much cleaner at the device level.

**Comment by chemelli74** [comment]
We would like to keep the plugin's code as easy as possible.

I also think that such behavior will be used by very few users as you can always stop at the desired limit by app/web or use the % if controlling trough voice.

Simone
