### ISSUE TITLE
[FR] Introduce vibration and tilt angle as sensor values 

### ISSUE THREAD

**Issue by miljume** [StyraHem/ShellyForHASS#309]
## Is your feature request related to a problem? Please describe.
No, but I am missing being able to use vibration and tilt values in automations like alarm automations

## Describe the solution you'd like
  Collect and report vibration and tilt angle as sensor values to HA

## Describe alternatives you've considered
  Stop using ShellyForHass and only use cloud or native MQTT

**Comment by markblokpoel** [comment]
I would also really appreciate this addition too.

**Comment by chemelli74** [comment]
Please check 0.1.9 and report back.
 
Simone

**Comment by markblokpoel** [comment]
I updated to 0.1.9 before I added the DW2 to my home network. It was detected, the open/close sensor was added automatically to HA. I then realized the angle measurement needed to be activated and calibrated, so I proceeded doing so via the built

**Comment by markblokpoel** [comment]
Apologies, turns out in 0.1.9 there were new device options in ShellyForHASS integration settings. I've added the tilt sensors to be created, but still it does not show up for the DW2. Other sensors (e.g. switch state which is also new) were added after turned on. I restarted HA several times.

**Comment by markblokpoel** [comment]
Ok, for some reason the sensors were added after an hour or so, I guess it took some time to update? For anyone else as impatient as myself, please give it some time after you've added the sensor options in the shellyforhass integration.

**Comment by chemelli74** [comment]
So are both tilt and vibration working ? Can we close this issue ?

Simone

**Comment by markblokpoel** [comment]
Tilt is working. I haven't tested vibration, will try to do that tomorrow.

**Comment by chemelli74** [comment]
@markblokpoel did you have time to test vibration ?

Simone

**Comment by markblokpoel** [comment]
@chemelli74 thanks for the reminder, I did have some time now. I've enabled the vibration sensor on the DW2, not waiting for it to show up in HA. I'll keep an eye on the time.

**Comment by markblokpoel** [comment]
Hmm, it hasn't shown up for about 12 hours. I tried several restarts and tried to trigger updates by giving the DW2 input. Any ideas where to look for more info to help you?

**Comment by chemelli74** [comment]
> Hmm, it hasn't shown up for about 12 hours. I tried several restarts and tried to trigger updates by giving the DW2 input. Any ideas where to look for more info to help you?

Humm, any error/warning in the log ?

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
