### ISSUE TITLE
Use Shelly as "Detached Button"

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#31]
I have a couple of Shelly switches (both the Shelly1 and Shelly2.5) controlling smart bulbs in my home setup (home-assistant) and I want to be able to control the bulbs with the Shelly Switch. Therefore I need to set the Button to 'detached mode' so I don't actually cut power to the bulbs. Now I would like to know if I can forward the toggling of the switch to the smart bulbs so they would actually turn on and off when pressed.
I tried to configure this via MQTT but I can't seem to configure a 'state' change when using an MQTT command as trigger for an automation. So every time an MQTT state gets published the switch gets a 'light.toggle' command...
Is this possible with this component? Is there a sensor that I can monitor for switch toggles?

**Comment by hakana** [comment]
Fixed in latest release
