### ISSUE TITLE
[BUG] BinarySensorDevice and SwitchDevice are deprecated

### ISSUE THREAD

**Issue by Schrikt** [StyraHem/ShellyForHASS#310]
## Environment

- ShellyForHASS release with the issue:  0.1.8
- Last working ShellyForHASS release (if known): - 
- Home Assistant Core release with the issue: 0.110.0
- Operating environment (Home Assistant/Supervised/Docker/venv): hass.io

## Describe the bug
BinarySensorDevice is deprecated, modify ShellySwitch to extend BinarySensorEntity
SwitchDevice is deprecated, modify ShellySwitch to extend SwitchEntity

## Steps to Reproduce
message appears in log after restart

## Expected behavior
use of BinarySensorEntity and SwitchEntity

## Traceback/Error logs
```txt
BinarySensorDevice is deprecated, modify ShellySwitch to extend BinarySensorEntity
17:52:13 – Binary Sensor (WARNING) - message first occurred at 17:52:13 and shows up 3 times
SwitchDevice is deprecated, modify ShellySwitch to extend SwitchEntity
17:52:13 – Switch (WARNING) - message first occurred at 17:52:12 and shows up 2 times
```

**Comment by chemelli74** [comment]
Please always update to latest beta before reporting a issue.

This is already fixed.

Simone
