### ISSUE TITLE
[BUG] I/O inside the event loop when updating firmware

### ISSUE THREAD

**Issue by chmielowiec** [StyraHem/ShellyForHASS#312]
## Environment

- ShellyForHASS release with the issue: 0.1.8
- Last working ShellyForHASS release (if known): -
- Home Assistant Core release with the issue: 0.110.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

I/O inside the event loop.

## Steps to Reproduce

Update Shelly to latest version

## Traceback/Error logs

```txt
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for shelly doing I/O at custom_components/shelly/switch.py, line 115: self._block.update_firmware()
```

**Comment by chemelli74** [comment]
Please update to 0.1.9b2, issue is already fixed.

BTW, if you check [release notes](https://github.com/StyraHem/ShellyForHASS/releases) you get many info.

Simone

**Comment by chmielowiec** [comment]
I will wait for stable release.

Btw, In release notes there is no information about this bug.

**Comment by chemelli74** [comment]
> Btw, In release notes there is no information about this bug.

Sorry, my fault. I was pretty sure info was there.

Simone
