### ISSUE TITLE
[FR] Shelly 1 power sensors

### ISSUE THREAD

**Issue by NelsonFrancisco** [StyraHem/ShellyForHASS#318]
## Is your feature request related to a problem? Please describe.
I cannot see the current power consumption and total power consumption for Shelly1

## Describe the solution you'd like
Just like Shelly2.5. We already have current and total power consumption

## Describe alternatives you've considered
None

## Additional context

Following picture is from a Shelly2.5. Would be nice to have similar sensor for Shelly1
![image](https://user-images.githubusercontent.com/31771519/83965121-36c45f80-a8a9-11ea-8827-5db82eb44ecb.png)

**Comment by chemelli74** [comment]
Shelly1 doesn't have those sensors; you need to buy Shelly 1PM instead.

Simone

**Comment by NelsonFrancisco** [comment]
Oh, that's right!
Sorry for bothering you with such a request.
Thanks
