### ISSUE TITLE
[FR] Username and password for accessing local shelly devices

### ISSUE THREAD

**Issue by markblokpoel** [StyraHem/ShellyForHASS#321]
First of, thanks for the great work on this plugin! Here's a feature suggestion relating to security, if I may.

## Is your feature request related to a problem?
When setting a username and password in the Shelly device webserver, ShellyForHA cannot find the device anymore.

## Describe the solution you'd like
Have the option to set a username and password that ShellyForHA can use to access the devices.

## Describe alternatives you've considered
None, I assume the password locks out the protocols used by ShellyForHA and I wouldn't know what to do about this.

**Comment by hakana** [comment]
You have to set the same username and passwords in the Shelly4Hass. You can do that in config.yaml or the options for the integration in the HA GUI.

**Comment by markblokpoel** [comment]
Oh that's great! I'm really sorry I missed that feature! It is working perfectly now (after the required HA restart).
