### ISSUE TITLE
not allowing control with restricted login

### ISSUE THREAD

**Issue by rotcop4u2** [StyraHem/ShellyForHASS#322]
I have been trying to figure out why i should not contact my shellys or control when having a restricted login via the shellys themselves. When I use a restricted login the shelly cannot be controlled but with restricted login turned off, I am able to control.

**Comment by chemelli74** [comment]
Did you configure username and password in configuration.yaml?

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by ruandy12** [comment]
Hello.
Can you give an example of providing a username and password in configuration.yaml
I`ve tried to apply it in few different ways, but HASS allways shows an error in username tag
this is my current config, I had to comment user/pass to allow hass to work.
shelly:
  # settings:
  #  username: !secret shelly_username
  #  password: !secret shelly_password
   
  # devices:
  #  - id: 800F44
  #    settings:
  #     username: !secret shelly_username
  #     password: !secret shelly_password

**Comment by ruandy12** [comment]
`shelly:
  # settings:
  #  username: !secret shelly_username
  #  password: !secret shelly_password
   
  # devices:
  #  - id: 800F44
  #    settings:
  #     username: !secret shelly_username
  #     password: !secret shelly_password`

**Comment by ruandy12** [comment]
```
shelly:
  # settings:
  #  username: !secret shelly_username
  #  password: !secret shelly_password
   
  # devices:
  #  - id: 800F44
  #    settings:
  #     username: !secret shelly_username
  #     password: !secret shelly_password`
```

**Comment by chemelli74** [comment]
Hi, please take care that in YAML indentation is very important.

username and password should be at the same level as "devices:" like:

```
devices:
  - id: XXXX
username: !secret shelly_username
password: !secret shelly_password
```

Remember also that all devices needs the same username and password.

Simone

**Comment by ruandy12** [comment]
Thanks, that worked!
