### ISSUE TITLE
New MQTT Feature Fails After Some Time

### ISSUE THREAD

**Issue by ericvitale** [StyraHem/ShellyForHASS#324]
I had been using the proxy for a while now with no issues. I switched over to the new MQTT feature and took down my proxy. After HA restart everything works fine. After some time... Could be a couple hours, could be a couple days all of my Shelly devices show disconnected. Restarting HA fixes it every time. Not sure what exactly is happening or how to give you more details (logs) to see what is causing it.

Currently running 0.1.9 Beta 2 / HA 0.111.2

**Comment by chemelli74** [comment]
Please use the template to one a issue

Thank you,

Simone

**Comment by chemelli74** [comment]
Template not filled. Closed.

Simone
