### ISSUE TITLE
[BUG] no discovery for shellyswitch25 (Shelly 2.5)

### ISSUE THREAD

**Issue by quammy** [StyraHem/ShellyForHASS#328]
## Environment

- ShellyForHASS release with the issue: 0.1.8
- Last working ShellyForHASS release (if known): (first time testing your integration)
- Home Assistant Core release with the issue: 0.111.2
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant (HassOS 4.10)

## Describe the bug

I have 4 Shelly devices on my network, 3 X Shelly 1 and 1 X Shelly 2.5. All are working with MQTT, no cloud, each protected by user/pass of its own.

No matter which method, the Shelly 2.5 doe snot become available. I've tried:
the auto discovery through Integrations.
auto discovery through configuration.yaml
define the devices by ID like: - id: "112772-1" and - id: "112772-2" and also only - id: "112772"
set the IP on 'discover_by_ip' (not in parallel to the devices id).
None worked, while the Shelly 1 devices were discovered correctly as far as I can tell.

While at, I think I also get the Error, 401 Unauthorized http://192.168.1.x/settings and /status on each of the deices (including the IP of the 2.5 due to the lack of user/password (make sense?) on your docs there is no place for user/pass per device, only on the higher level...

I hope it's enough as I don't have much more than that to help with the bug description...

Thanks.

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
You need to have same user/password for all devices and configure it in ShellyForHass

**Comment by quammy** [comment]
> You need to have same user/password for all devices and configure it in ShellyForHass

Once done, all reported issues disappeared. Thank you very much.
