### ISSUE TITLE
Devices listed under integration?

### ISSUE THREAD

**Issue by fredrikbaberg** [StyraHem/ShellyForHASS#33]
I just started using this component, received my first Shelly products today (2 Shelly Plug S), and the plugs appeared when I had connected them to the network.

I'd love if the discovered devices were visible under Integrations, as is the case for deCONZ, TP-Link and some other integrations I'm using.

It may be the case that only official components supports that, but I saw that you are at least considering to get it included (#23). Hope you are able to include that feature in the future.

**Comment by hakana** [comment]
Yes we will look at this!
