### ISSUE TITLE
[FR] Add decimals to integration UI

### ISSUE THREAD

**Issue by jandrop** [StyraHem/ShellyForHASS#334]
## Is your feature request related to a problem? Please describe.

  Actually there´s no way to add decimals in the integrations UI and all the config in the configuration yaml is ignored if the integration is enabled

## Describe the solution you'd like

  Be able to add decimals configuration in the UI like in the yaml  (current_consumption: { decimals: 2 })
    

## Describe alternatives you've considered

  If there´s no way to integrate this in the integrations UI then not ignore the configuration yaml

## Additional context

![image](https://user-images.githubusercontent.com/8020875/85516950-10b7f280-b5ff-11ea-8c9a-c2a521d87b66.png)

![image](https://user-images.githubusercontent.com/8020875/85517179-4d83e980-b5ff-11ea-9cba-949906ec473f.png)

**Comment by gokuro** [comment]
I am looking to get the full 2 decimals of accuracy from the ADC voltage in my shelly uni.

Shelly Uni shows 2 decimals places of accuracy but HA shows just 2

https://community.home-assistant.io/t/shelly-uni-adc-voltage-at-2-decimals/304997

**Comment by apedance** [comment]
I would love too see this too, please.
Migrating to a custom config.yaml can be quite a hassle.

**Comment by cfgroenewald** [comment]
Has this been changed to include 2 decimals?

**Comment by hakana** [comment]
I will check this for next release comming soon

**Comment by dapowl** [comment]
Have it working with 2 decimals and shellyforhass (shelly - settings - voltage *attribute, deicmals)  but it sporadically comes back to zero decimals after a restart. Then I have to restart until i get the 2 decimal readings back. Weird....
