### ISSUE TITLE
[BUG] Shelly Device lose connection to HASSIO but remain on the network.

### ISSUE THREAD

**Issue by smallrebelarmy** [StyraHem/ShellyForHASS#345]
## Environment

HassOS 4.11
rpi4
--

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Describe the bug

I have several Shelly EMs connected to Home Assistant. Randomly two will disconnect and never return. The one is connected to the main router. The two that are absent are connected to the satellite. 

I am running an Orbi mesh network. Multicasting is enabled. 
I've run the test.py and can only see one of three devices. 
When I run proxy.py nothing seems to change. 
I have igmp_fix: true in the configuration yaml. nothing seems to change. 
When I run "tcpdump -A udp port 5683" I only see the one of three shellies.
All shellies can be seen by the router and the shelly app. 

## Traceback/Error logs

```txt

```

**Comment by chemelli74** [comment]
If tcpdump is not able to show the package, unfortunately is a network issue.
Please check out wiki to see if you find any helpful information to fix it.

Simone

**Comment by filmgarage** [comment]
It's a very common problem related to firmware version 1.7.0 of the Shellies...

You could downgrade the Shellies using the procedure found on http://archive.shelly-faq.de

**Comment by smallrebelarmy** [comment]
Thanks. I'll try it. I've been calling out the shellies specifically by IP with a little better results, but they still vanish from the to time for extended periods.

**Comment by jeepotvin** [comment]
I've been also having problem with my Shellies reporting back to HA recently.
The devices are all accessible through their respective web interface.
I've decided to downgrade the firmware back to 1.6.1 and 1.6.2 and data has been instantly reporting back to HA afterwards.
Just sharing in case someone else want to go down that route.

**Comment by chemelli74** [comment]
Take care that there are 3 different protocols on Shelly’s:

- Web interface (tcp)
- CoAP (usp multicast)
- MQTT (tcp)

Changing firmware is not solving any issue as far as we know.

When ShellyforHASS, that uses CoAP, doesn’t work 99% is a network issue that you can verify with tcpdump.

Simone

**Comment by jeepotvin** [comment]
You're probably right. One of the Shelly has stopped reporting to HA the same day its firmware was downgraded. I guess it is a networking issue after all.

**Comment by chemelli74** [comment]
As there is no news, I would close this issue in a couple of days.

Simone
