### ISSUE TITLE
[BUG] Roller shutter changed to "Closing" in the logs but in reality it is "Opening"

### ISSUE THREAD

**Issue by giovesoft** [StyraHem/ShellyForHASS#346]
## Environment

- ShellyForHASS release with the issue: 0.1.8
- Last working ShellyForHASS release (if known): no one
- Home Assistant Core release with the issue: 0.112.3
- Operating environment (Home Assistant/Supervised/Docker/venv): HassOS 4.11

## Describe the bug
When the roller shutter is Opening I see in the log that is Closing.
Also the automations are not working for this bug, if I set a trigger on Opening it is triggered on Closing.

## Steps to Reproduce
Set this settings on Shelly 2.5:
INPUT BUTTOS MODE: Open & Close Buttons...
BUTTON TYPE: Momentary
SWAP INPUTS: checked 
REVERSE DIRECTIONS: checked **(probably this is the main reason of the bug)**

## Expected behavior
Support the REVERSE DIRECTIONS setting.

## Traceback/Error logs

```txt

```

**Comment by chemelli74** [comment]
Reverse direction is not part of the CoAp message the plugin is based on.
Please rewire the device and all will be fine.

Simone

**Comment by giovesoft** [comment]
> Reverse direction is not part of the CoAp message the plugin is based on.
> Please rewire the device and all will be fine.
> 
> Simone

Can you share the link to the CoAP documentation?

**Comment by chemelli74** [comment]
Sorry but current version in not documented by Allterco; but we are working on it.

As this is not a fixable, I'll proceed to close this issue.
Support discussion can go on on our Facebook user group.

Simone

**Comment by giovesoft** [comment]
Due to space problems, the motors were mounted upside down on all the shutters.
I don't think it changes anything by reversing the cables on the shelly. I have 8 shutters and I had to enable reverse on all. Was I so "lucky" and put all the cables in the wrong position?

**Comment by chemelli74** [comment]
> Was I so "lucky" and put all the cables in the wrong position?

Unfortunately yes.

Simone

**Comment by juanpa669** [comment]
I have the same problem. This is not a wire issue cause I had test all possibilities and it still inverted in HA

**Comment by giovesoft** [comment]
For me it was a wire issue.
Inverted the wires and removed the "reverse" setting and it works as
expected

Il giorno mar 4 ago 2020 alle ore 11:53 Juanpa <notifications@github.com>
ha scritto:
