### ISSUE TITLE
HA Warning: Light is deprecated, modify ShellyLightRelay to extend LightEntity

### ISSUE THREAD

**Issue by synoniem** [StyraHem/ShellyForHASS#351]
Since today i get the following warning in Home Assistant 0.112.4:

Log Details (WARNING)

Logger: homeassistant.components.light
Source: components/light/__init__.py:280
Integration: Light (documentation, issues)
First occurred: July 18, 2020, 9:47:39 PM (3 occurrences)
Last logged: July 18, 2020, 9:47:39 PM

    Light is deprecated, modify ShellyLightRelay to extend LightEntity
    Light is deprecated, modify ShellyDimmer to extend LightEntity
    Light is deprecated, modify ShellyRGB to extend LightEntity

**Comment by chemelli74** [comment]
Please be so kind to full-fil the issue template.

Simone

**Comment by synoniem** [comment]
Sure where do i find this issue template?

**Comment by chemelli74** [comment]
It's proposed when you open the issue

Simone

**Comment by synoniem** [comment]
Sure but i did not and do not see anything what looks like a template when opening a issue. Supposing that it means that nothing is gonna happen with my issue i close it myself.

**Comment by chemelli74** [comment]
Hi @synoniem, when you click on "new issue" you should get something like:

![image](https://user-images.githubusercontent.com/57354320/88061406-beb7ad80-cb67-11ea-88d0-14ca46d2a305.png)

The request is just to fill all the info.
Thank you for your understanding,

Simone
