### ISSUE TITLE
[FR] Dimmer2 integration

### ISSUE THREAD

**Issue by Balou067** [StyraHem/ShellyForHASS#352]
## Is your feature request related to a problem? Please describe.
I received my Shelly [Dimmer 2](https://shelly.cloud/products/shelly-dimmer-2-smart-home-light-contoller/) yesterday and could not integrate it with ShellyForHASS (the Dimmer is recognized as a device but without any actual functionality)
## Describe the solution you'd like
Supporting Shelly Dimmer 2 in ShellyForHASS

## Describe alternatives you've considered
Trying to integrate via MQTT

**Comment by chemelli74** [comment]
Hi, please update to 0.1.9.b3

Simone

**Comment by mrulke** [comment]
I have updated and it works really well.
set the dimmer to edge in the shelly app and the dimmer functions appear in  HA
