### ISSUE TITLE
No separate switches for RGB and White channel

### ISSUE THREAD

**Issue by uspino2** [StyraHem/ShellyForHASS#353]
## Environment

- ShellyForHASS 0.1.9
- Home Assistant 0.113
- Home Assistant running in Hyper-V

## Describe the bug

I use one RGB strip connected to the RGB pins and a separate White strip connected to the W pin in the same RGBW2 Shelly. I want to have two separate switches, one for the RGB strip, another one for the white strip. I thought this was possible by using -1 & -2 at the end of `id:`

Any way to achieve this? Thanks.

**Comment by hakana** [comment]
You can set the level of white stripe in same entity as color.

![image](https://user-images.githubusercontent.com/1168654/88377666-de391b00-cd9f-11ea-84ab-fa4313de9706.png)

**Comment by uspino2** [comment]
Yes, thanks, but is it possible to turn on/off the white strip while keeping the rgb strip off?

**Comment by hakana** [comment]
Yes, if you just set the white value to 0% it will be turned off.

I close this as it is old, please open a new if still needed changes.
