### ISSUE TITLE
[FR] Change behavior of white_value (Shelly RGBW2)

### ISSUE THREAD

**Issue by david-kalbermatten** [StyraHem/ShellyForHASS#355]
## Is your feature request related to a problem? Please describe.

Not really since this is more of an idea I had. If I had to name a problem, it'd be the fact that you can't turn off the RGB part completely since the `brightness-slider` turns off the light when set to 0.

### How `white_value` & `brightness` work right now:
`white_value` controls the brightness of the white channel of a Shelly RGBW
`brightness` controls the brightness of the RGB channels

### How I would like `white_value` & `brightness` to work instead:
Instead of having `white_value` control the brightness of white, I'd propose it controling the mixture between RGB and W.

#### Examples
Values: `white_value` is set to 50% and `brightness` is set to 100%
Result: RGB and W are both on and set to 100% brightness

Values:  `white_value` is set to 25% and `brightness` is set to 100%
Result: RGB-brightness is 100% W-brightness is 50%

Values:  `white_value` is set to 75% and `brightness` is set to 100%
Result: RGB-brightness is 50% W-brightness is 100%

Values:  `white_value` is set to 75% and `brightness` is set to 50%
Result: RGB-brightness is 25% W-brightness is 50%
## Describe alternatives you've considered

Just setting the brightness to something low.
## Additional context

The motivation behind this FR is me trying to make a `light group` with LIFX and Shelly. Since those two handle white color/light differently, I can't really make the work in one group.
![image](https://user-images.githubusercontent.com/45201085/88455821-fb8de800-ce78-11ea-9897-9504de1b0a79.png)

## Related Issue(s)
This would also provide a neat solution for this issue #353

**Comment by hakana** [comment]
I think you can do this by using a light template in HA

**Comment by david-kalbermatten** [comment]
> I think you can do this by using a light template in HA

I don't see how, since I'd need to be able to set brightness to 100% on the LIFX bulb while having `brightness` as low as possible for the Shelly RGBW2 (otherwise it creates an ugly white mix of `white_value` and the RGB-LEDs)

My FR-Idea would solve this problem since it makes the `brightness` value control the brightness of the white channel as well.

But sure, if you @hakana have a concrete idea on how to achieve this differently I'm all ears :D

**Comment by david-kalbermatten** [comment]
**Disclaimer:**
I don't think this should necessarily be the default behavior. However, I'd find it cool if you could define the behavior I described above in the configuration:
```yaml
# shelly.yaml
[...]
devices:
  - id: "6d2xxx"
    alternate_white_mode: true
[...]
```

**Comment by hakana** [comment]
I can't implement all different possible requirements because then ShellyForHass will grow to big. I also want to keep the settings as few as possible.

**Comment by chemelli74** [comment]
As per the statement above, I'm going to close this issue.
