### ISSUE TITLE
Shelly HT

### ISSUE THREAD

**Issue by JoaquimLopes1980** [StyraHem/ShellyForHASS#36]
Hello everyone.

I have a issue. Sometimes it fails to detect shelly ht. They are unavailable. Any way to fix this?

**Comment by hakana** [comment]
It will take some time for H&T as it is in sleeping mode. You can wake it by click on the button and it should show up in a few seconds or next time it send some data.



On Mon, Jul 22, 2019 at 11:25 PM +0200, "JoaquimLopes1980" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello everyone.

I have a issue. Sometimes it fails to detect shelly ht. They are unavailable. Any way to fix this?

**Comment by krom54** [comment]
is it possible to prevent it from falling asleep? with an external power supply maybe? it's very annoying because I can't configure it with http unless I'm next door and mine is in another room on a repeater so I can't get it out without losing the connection.
