### ISSUE TITLE
Can't get Shelly dimmer brightness

### ISSUE THREAD

**Issue by szamq** [StyraHem/ShellyForHASS#364]
Hi, to there any special way to get the brightness from dimmer? I can see the brightness displayed correctly on the slider when dimmer properties are displayed. But how to get it to use in automation?

**Comment by chemelli74** [comment]
Hi there @szamq!

Thanks for opening an issue. When you create an issue, an issue template is presented. Could you please update your issue description to have that template and provide as much as the requested data as possible?

Without it, we won't be able to help you.

Thanks!

**Comment by szamq** [comment]
Sorry, here is the info
- ShellyForHASS release with the issue:  0.1.9
- Home Assistant Core release with the issue:  0.113.3
- Operating environment: Home Assistant image on raspberry pi 4

Expected behavior
I wish, I could be able to get the brightness by some sensor or attribute of the device. But I can't see anything like this in my shelly dimmers entities (but home assistant is somehow showing the actual brightness when viewing all properties of the light on the slider)

config:

shelly:
  discovery: true
  id_prefix: ""
  sensors:
    - all
  devices:
    - id: "XXXXXX"
      light_switch: true
      name: "Kantorek światlo"
      entity_id: kantorek_swiatlo

**Comment by chemelli74** [comment]
When the light is on, you have attribute "brightness" on your device.

Simone

**Comment by szamq** [comment]
Thank you very much, great work
