### ISSUE TITLE
[FR] Contribute integration to Home Assistant

### ISSUE THREAD

**Issue by balloob** [StyraHem/ShellyForHASS#368]
## Is your feature request related to a problem? Please describe.

It's difficult for Home Assistant users to get started integrating Shelly. A new user will need to first find this integration, then install HACS and then install this integration. 

## Describe the solution you'd like

Contribute this integration to Home Assistant so that it's bundled with each release. This will also allow discovery of Shelly on the network to automatically suggest setting up this integration.

**Comment by chemelli74** [comment]
@balloob, at this stage we think that the integration needs to be updated too frequently to be bundled with HA.

Once firmware 1.8 with completely reviewed CoAP protocol is released and all known bugs squashed, we may reconsider above statement.

thank you for your comprehension.

Simone

**Comment by Mincka** [comment]
Looks like it's already in progress:
https://github.com/home-assistant/core/pull/39178
https://github.com/home-assistant/core/pull/39209

I don't know what to think. From the outside, looks like a bold move for a very limited support compared to this component.
However I understand that we have to start with something. If the core team can help with the support of the latest firmware, it should help in the end.

**Comment by balloob** [comment]
The journey of a thousand miles starts with a single step :) 

This custom integration will always be more powerful than what will be in core. Core will just do the bare minimum to give a good experience with local APIs. No cloud user/pass to fetch names etc. 

Users of this integration won't be impacted by the core integration. Having this one installed will override the built-in one.
