### ISSUE TITLE
Is the new Shelly EM already supported?

### ISSUE THREAD

**Issue by PeteHassio** [StyraHem/ShellyForHASS#37]
My Shelly EM should be arriving in the next few days. 
So my question is: Is this device already supported?

Thank you for your time

**Comment by hakana** [comment]
Hi,

No it is not supported right now. We can probably solve it if I got some help from you when you receive it.

/Håkan, StyraHem

Från: PeteHassio <notifications@github.com>
Skickat: den 24 juli 2019 21:31
Till: StyraHem/ShellyForHASS <ShellyForHASS@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [StyraHem/ShellyForHASS] Is the new Shelly EM already supported? (#37)


My Shelly EM should be arriving in the next few days.
So my question is: Is this device already supported?

Thank you for your time

**Comment by PeteHassio** [comment]
Sorry for my late response. But now I have the Shelly-EM up and running.
How can I help you to integrate the device in your application?

**Comment by hakana** [comment]
Can you run this python script and send me some rows showing the CoAP messages for the EM device.

https://github.com/StyraHem/ShellyForHASS/blob/master/util/test.py

**Comment by monsterciattolo** [comment]
Below my output

b'P\x1e\x08\x99\xb3cit\x01s\xed\x0b\xec\x00SHEM#B9E4AB#1\xd2C\x96\x00\x82\x01\x00\xff{"G":[[0,112,0],[0,111,241.619527],[0,121,0.000000]]}'

**Comment by PeteHassio** [comment]
It looks a little bit strange (or I did something wrong) , but this is my output:
P▒ĳcits▒
        ▒SHEM#B9EF4A#1▒C▒▒▒{"G":[[0,112,0],[0,111,-3.968063],[0,121,0.000000]]}

**Comment by hakana** [comment]
Thanks, @PeteHassio and @monsterciattolo  !

I will add EM in some days.

**Comment by bizzottogary** [comment]
This is my result: 
b'P\x1e7\xef\xb3cit\x01s\xed\x0b\xec\x00SHEM#B9E855#1\xd2C\x96\x00\x82\x01\x00\xff{"G":[[0,112,0],[0,111,4116.749592],[0,121,344.171568]]}'

**Comment by estefanogoncalves** [comment]
It is working like a charm!!! :) Thank you @hakana 

![image](https://user-images.githubusercontent.com/6942795/63509883-26d3be80-c4d5-11e9-950e-4a08a5f12774.png)

**Comment by hakana** [comment]
Great!

**Comment by GoNzCiD** [comment]
What are the available sensors for shelly EM?
