### ISSUE TITLE
[BUG]  Invalid config for [shelly]: expected a dictionary @ data['shelly']['devices'][0]. 

### ISSUE THREAD

**Issue by Soylor** [StyraHem/ShellyForHASS#377]
configuration.yaml

![image](https://user-images.githubusercontent.com/9199475/90284037-945cc580-de71-11ea-84f6-5b443d8fe148.png)

Invalid config for [shelly]: expected a dictionary @ data['shelly']['devices'][0]. 

Allways error if using **devices**:

**Comment by chemelli74** [comment]
Hi,

if you don't add any specific config for each specified devices, for sure you get an error ;-)

Simone

**Comment by Soylor** [comment]
In the example page of this project there is an example with this:

![image](https://user-images.githubusercontent.com/9199475/90308597-0ae4dc00-dee1-11ea-8dbc-1a613fbd7113.png)

Tested with filling name does not work. Same error

**Comment by david-kalbermatten** [comment]
@Soylor I think you need to add a name to each device if you intend to define every Shelly manually...
(also please use code brackets when you share code, so people can show you more easily what you need to change ;D)
```
/```yaml
 #your config ....
/```
```

without the `/` before the ```

**Comment by hakana** [comment]
You missing : after id

**Comment by Soylor** [comment]
Tht's right, with : it worked. No names added.
Thank you.
