### ISSUE TITLE
Make entity ID customisable per device

### ISSUE THREAD

**Issue by inforsgit** [StyraHem/ShellyForHASS#38]
The entity ID contains something along the lines of shelly_shsw_1_9999f9 to describe the device. It should be possible to override this or at least add some text to it to make it easier to identify a device by entity ID.

Therefore there would be three options to choose from for implementation:

1. Allow a "suffix" to be added, e.g. `suffix: "friendlyname"` results in **`shelly_shsw_1_9999f9_friendlyname`**
2. Allow full override of entity id , e.g. `entityid: "friendlyname"` results in **`friendlyname`**
3. Use existing `name` to auto-generate friendly name,  e.g. `name: "Friendly Name"` results in **`shelly_shsw_1_9999f9_friendly_name`**

**Comment by hakana** [comment]
Good point, I will fix this for next release. I think option 1 is the best...

**Comment by filmgarage** [comment]
Strange, I like this function and I want to use it. But unfortunately it does not get added to the names or replaced by the default names as before... I tried adding the suffix, with or without quotes around the suffix. Nothing works... And no my HomeKit setup is completely messed up too... :-D Apparently the lights are considered as new every time this internal HA name changes...

**Comment by hakana** [comment]
I'm not understand if it is problem or not... Home Assistant is using the entity id to identify the entity and will create  a new if it change.

**Comment by filmgarage** [comment]
I have it working now: I added the following to the general settings:
```
show_id_in_name: true
id_prefix: ""
```
Now I can set a custom name for every device:
`entity_id: "custom_name"`
Results in:
`light.custom_name`

**Comment by hakana** [comment]
Yes, the id_prefix is always added so if you don't want it you can do like you do. I think the prefix is good so I can filter out all shellies easly with for example monster cards.
