### ISSUE TITLE
[BUG] Shelly 2.5 in cover mode. There is no "current position" attribute any more. It happened after the last update. 

### ISSUE THREAD

**Issue by tiberius25** [StyraHem/ShellyForHASS#382]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known): unknown
- Home Assistant Core release with the issue: 0.114.0
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker version	19.03.5

## Describe the bug

Shelly 2.5 in cover mode. There is no "current position" attribute any more. It happened after the last update

## Traceback/Error logs

```txt

```

**Comment by chemelli74** [comment]
Hi there @tiberius25!

Thanks for opening an issue. When you create an issue, an issue template is presented. Could you please update your issue description to have that template and provide as much as the requested data as possible?

Without it, we won't be able to help you.

Thanks!

**Comment by tiberius25** [comment]
![Annotation 2020-08-18 203527](https://user-images.githubusercontent.com/54347519/90546415-b7011e00-e192-11ea-8f01-e6996c830549.png)
![Annotation 2020-08-18 203556](https://user-images.githubusercontent.com/54347519/90546417-b799b480-e192-11ea-86c8-9ae5c5e4e3f7.png)

**Comment by tiberius25** [comment]
![Annotation 2020-08-18 203902](https://user-images.githubusercontent.com/54347519/90546529-e0ba4500-e192-11ea-8aca-082644ac3ad6.png)

**Comment by scherer42** [comment]
I have the exact same issue. All my shelly 2.5 cover entities are showing in position 0.

**Comment by KidA90** [comment]
Same here. After the last firmware upgrade, all my Shelly 2.5's won't show the "current position" attribute or any other attribute except the ones tiberius25 posted in HA.

**Comment by chemelli74** [comment]
Firmware 1.8 is no supported.

Please check #366 

Simone
