### ISSUE TITLE
[BUG] Unavailable after firmware update

### ISSUE THREAD

**Issue by OmegaKill** [StyraHem/ShellyForHASS#384]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known): 0.1.9 before Shelly Plug S Firmware Update to version 20200812-091824/v1.8.0@8acf41b0
- Home Assistant Core release with the issue: 0.114.2
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant OS

## Describe the bug

The Devices are no longer working at all. They are all grayed out and unavailable. This happened after i updated the firmware of the plugs to the newest available (20200812-091824/v1.8.0@8acf41b0)

## Steps to Reproduce

Just update the Plugs to the newest firmware. I tried it with 5 devices and all are now unavailable.

## Expected behavior

Be able to turn them on and off. Read out total consumption

## Screenshots

![Shelly_Plugs](https://user-images.githubusercontent.com/17964130/90552757-9a191a80-e193-11ea-9955-f7db8f37dd5d.PNG)
![Shelly_Plugs_Device](https://user-images.githubusercontent.com/17964130/90552759-9b4a4780-e193-11ea-8208-54b8d3bc1625.PNG)
![Shelly_Plugs_Device_2](https://user-images.githubusercontent.com/17964130/90552760-9b4a4780-e193-11ea-920a-26678e0f0271.PNG)
![Shelly_Plugs_Webpage](https://user-images.githubusercontent.com/17964130/90552761-9be2de00-e193-11ea-8c25-a90f11af14d4.PNG)

## Traceback/Error logs

```txt

```

## Additional context

The plugs work if you use the integrated webinterface

**Comment by chemelli74** [comment]
Please check #366 

Simone
