### ISSUE TITLE
[BUG] Removing `discover_by_ip` from parameters still polls from ip resulting in warning.

### ISSUE THREAD

**Issue by timvancann** [StyraHem/ShellyForHASS#386]
## Environment

- ShellyForHASS release with the issue: `0.1.9`, possible also earlier versions.
- Last working ShellyForHASS release (if known): none during my time with ShellyForHass
- Home Assistant Core release with the issue: `0.114` and earlier versions up to at least `0.110`
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

Removing `discover_by_ip` from parameters still polls from ip resulting in warning.

## Steps to Reproduce

- Run home assistant core in docker using `network_mode=bridge`. 
- In the configuration for ShellyForHass set `discover_by_ip` to shelly IPs in local network.
- Stop home assistant core, set `network_mode=host`
- Remove all `discover_by_ip` settings.
- Restart home assistant core

Note: home assistant config is a persistent volume in docker container.

ShellyForHass still polls for given ip addresses and yields warning:

```
2020-08-21 21:09:35 WARNING (Poll) [pyShelly] Error, 404 Not Found http://192.168.1.155/settings
2020-08-21 21:09:35 INFO (Poll) [pyShelly] Error adding device, 192.168.1.155 mDns
```

## Expected behavior

Removing `discover_by_ip` should not poll for ip addresses anymore.

## Additional context

There might be other steps to reproduce. These were my steps.

I tried removing all entries for these IP addresses from `.storage/core.restore_state`. This did not solve it.

**Comment by hakana** [comment]
This is because the devices is detected by mDns, you can turn of mDns discovery

**Comment by timvancann** [comment]
Thanks for your support @hakana . Regarding your comment I have two additional quesions:

1. How can I turn off mDns discovery for ShellyForHASS since this is the only component causing these issues? I don't want to disable discovery globally.
2. If it is caused by mDns, why don't the other shelly's (that were not manually added to the `discover_by_ip` setting) show up in the warning logs? Only the shelly's for which I manually entered the IP addresses show up as warning logs. (perhaps my knowledge mDns is lacking 😅)

**Comment by hakana** [comment]
As you can see the device is polled because it is discobvered by mDns.

See readme about mDns setting

2020-08-21 21:09:35 WARNING (Poll) [pyShelly] Error, 404 Not Found http://192.168.1.155/settings
2020-08-21 21:09:35 INFO (Poll) [pyShelly] Error adding device, 192.168.1.155 **mDns**

**Comment by hakana** [comment]
No updates, we closing this issue.
