### ISSUE TITLE
[BUG] Shelly dimmer 1 and 2 doesn't return its state to HA after upgrade

### ISSUE THREAD

**Issue by frkos** [StyraHem/ShellyForHASS#387]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known): NA
- Home Assistant Core release with the issue: 0.114.3
- Operating environment (Home Assistant/Supervised/Docker/venv): HassIO @ rpi

## Describe the bug

I can switch the dimmer on and off, I can set brightness, but the toggle is always off in the interface
I guess it's caused by the error below

## Steps to Reproduce

try to switch toggle from HA interface

## Expected behavior

Toggle shows actual state

## Traceback/Error logs

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 439, in state_attributes
    data[ATTR_BRIGHTNESS] = self.brightness
  File "/config/custom_components/shelly/light.py", line 147, in brightness
    return int(self._brightness * 2.55)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by frkos** [comment]
I tried with another dimmer 2 which were not upgraded... and it works well.
After upgrading its firmware I received the same issue(

![20200824_142112](https://user-images.githubusercontent.com/47523946/91039398-2b194700-e615-11ea-8421-14efaec3e3d6.jpg)

**Comment by frkos** [comment]
I have tried to upgrade my **1gen** Dimmer from 20200122-090747/v1.5.9@4b657c90 to the new version 20200812-092126/v1.8.0@8acf41b0
And reproduced the issue. So it's definitely caused by changes on Shelly side

**Comment by brubaked** [comment]
I am having the same issue described here with shelly component version 0.1.9 and shelly dimmer 2 firmware version 20200812-092126/v1.8.0@8acf41b0.

**Comment by dborsnich** [comment]
Problem with dimmer version: 20200812-092126/v1.8.0@8acf41b0
Driving with  'custom:slider-entity-row'  take a long time to refresh or directly dont change the state in Hassio version 0.112.1, with Ubuntu 18.04 with unsupported Supervisor version 235. The key works well and the command made by Hassio is do it but not reflexed in Hassio
With shelly soft through web interface or app works well.
Thanks!

**Comment by chemelli74** [comment]
Firmware 1.8 is currently not supported.

Please follow #366
