### ISSUE TITLE
[BUG] Temperature updates

### ISSUE THREAD

**Issue by ignaciosala** [StyraHem/ShellyForHASS#391]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known): N/A 
- Home Assistant Core release with the issue: 0.114.3
- Operating environment (Home Assistant/Supervised/Docker/venv): 
Docker_version | 19.03.11
   HassOS | 4.12
   LinuxOS | 4.19.127-v7
   python_version | 3.8.3

## Describe the bug
I using ShellyForHASS (Using CoAP and REST for communication) with Shelly 1 Add-On to measure temperature. For some reason the values are not updated frequently during some periods (see image). Set a static IP address, and sensor next to the router to avoid posible network issues. Thanks for your support!

## Steps to Reproduce
New installation on Raspberry Pi 3

## Expected behavior
More frequent updates on temperature measures.

## Screenshots
<img width="502" alt="Screen Shot 2020-08-24 at 10 58 56 AM" src="https://user-images.githubusercontent.com/69985807/91079797-885fc900-e612-11ea-94dc-1a941312a426.png">

## Traceback/Error logs

Maybe this error is related:
Error receive CoAP
1:52:03 PM – /usr/local/lib/python3.8/site-packages/pyShelly/coap.py (ERROR) - message first occurred at 1:14:10 PM and shows up 149 times

## Additional context
Downgraded Shelly firmware to 1.7.7 and now it's updating every minute.

**Comment by chemelli74** [comment]
Hi there @ignaciosala!

Thanks for opening an issue. When you create an issue, an issue template is presented. Could you please update your issue description to have that template and provide as much as the requested data as possible?

Without it, we won't be able to help you.

Thanks!

**Comment by ignaciosala** [comment]
It's firmware, nothing to do with Shellyforhass.
