### ISSUE TITLE
[BUG] Firmware 1.8 is NOT supported

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#392]
Currently the only option is to downgrade to 1.7.x

We are working hard for updating the integration.
Thank you for your understanding.

ShellyforHASS Team

**Comment by fitim7** [comment]
Since when is this happening?
Is the update expected in the near future? 
Do you know the problem, or still searching?

**Comment by dedepene** [comment]
How do I go back to 1.7 on a Shelly Duo?...anyone knows?

**Comment by MajoV** [comment]
@dedepene 
http://1.2.3.4/ota?url=http://archive.shelly-support.eu/v1.7.0/SHBDUO-1_build.zip
Majo

**Comment by dedepene** [comment]
> @dedepene
> 
> http://1.2.3.4/ota?url=http://archive.shelly-support.eu/v1.7.0/SHBDUO-1_build.zip
> 1.2.3.4 - IP address of the bulb
> Majo

Thanks, man! I can now confirm the DUO works fine on 1.7 FW

**Comment by JSteunou** [comment]
folders are not readable :( Is anyone know the path / url for Shelly 1 & Shelly Dimmer 2 last 1.7 FW in order to rollback?

**Comment by fitim7** [comment]
> folders are not readable :( Is anyone know the path / url for Shelly 1 & Shelly Dimmer 2 last 1.7 FW in order to rollback?

Here you go: http://YOUR-SHELLY1-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHSW-1_build.zip

**Comment by fitim7** [comment]
> folders are not readable :( Is anyone know the path / url for Shelly 1 & Shelly Dimmer 2 last 1.7 FW in order to rollback?

Here you go for Shelly Dimmer 2: http://YOUR-SHELLYDIMMER2-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHDM-2_build.zip

**Comment by JSteunou** [comment]
thanks a lot :pray:

**Comment by lwYeo** [comment]
Anyone have any idea how to downgrade RGBW2 to 1.7.x? The OTA method flicker the light once and stops downgrading. 
Other devices seem to be able to downgrade with no issues using OTA.

**Comment by paavo** [comment]
@fitim7 It would be nice to have a list of Shelly Devices and the corresponding 1.7  firmware. 
What about Shelly 1PM and 2.5?

- **Shelly 1** http://YOUR-SHELLY1-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHSW-1_build.zip
- **Shelly Dimmer 2** http://YOUR-SHELLYDIMMER2-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHDM-2_build.zip

**Comment by lwYeo** [comment]
What works for me

- Shelly 1PM http://YOUR-SHELLY-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHSW-PM_build.zip
- Shelly Duo http://YOUR-SHELLY-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHBDUO-1_build.zip

**Comment by fitim7** [comment]
> @fitim7 It would be nice to have a list of Shelly Devices and the corresponding 1.7 firmware.
> What about Shelly 1PM and 2.5?
> 
> * **Shelly 1** http://YOUR-SHELLY1-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHSW-1_build.zip
> * **Shelly Dimmer 2** http://YOUR-SHELLYDIMMER2-IP-HERE/ota?url=http://archive.shelly-support.eu/v1.7.7/SHDM-2_build.zip

I could make a list with all devices, but this wouldn't be fair. https://www.shelly-support.eu made a great feature for this. You just select your device and your firmware (you can choose between all possible firmwares) and then it generates the link. They invested a lot in this. Thats why it wouldn't be fair.

Go to https://www.shelly-support.eu and create an account. Its free.

**Comment by paavo** [comment]
Didn't knew about that @fitim7 

**Direct Link to the Firmware Archive** (_you need to be logged in_)
https://www.shelly-support.eu/index.php?shelly-firmware-archive/

**Comment by JSteunou** [comment]
Didn't know either :/

**Comment by micdis** [comment]
do we know when 0.2 beta will be published?

**Comment by bigboban** [comment]
I see tag 0.2.0 beta 1.

**Comment by tigers75** [comment]
I can confirm it's out and seems to work.

**Comment by bigboban** [comment]
Shelly 1 status is good and fast now. BUT. Shelly H&T broken. 99% of time unavaliable, temp graph is not line but some dots. I have USB powered H&T so it should not sleep. MQTT graph on same device is fine.

Integration on older version was bad (see my post here: https://github.com/StyraHem/ShellyForHASS/issues/388) but now it is totally broken.

**Comment by chemelli74** [comment]
Use latest beta
