### ISSUE TITLE
Shelly EM get 0 Watt [BUG]

### ISSUE THREAD

**Issue by gobbe87** [StyraHem/ShellyForHASS#393]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known):  0.1.7
- Home Assistant Core release with the issue: HassOS 4.12
--

- Operating environment (Home Assistant/Supervised/Docker/venv): HassOS

## Describe the bug
After integration with shelly EM with 1.8 firmware i see 0 Watt in a lot of samples 

![image](https://user-images.githubusercontent.com/50985428/91193859-e74b3e00-e6f7-11ea-9775-22ba35c2b71f.png)
![image](https://user-images.githubusercontent.com/50985428/91194206-3b562280-e6f8-11ea-9e27-03686cb5b3dd.png)

## Steps to Reproduce
Add Shelly EM device on ha configuration

## Expected behavior
see the expected Watt on current_consumption sensor

## Traceback/Error logs

```txt

```

**Comment by chemelli74** [comment]
Firmware 1.8 is not supported

Please see #366
