### ISSUE TITLE
[BUG] Shelly 2.5 in roller shutter mode doesn't update properly (fw 1.8)

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#399]
## Environment

- ShellyForHASS release with the issue: 0.2.0.beta.2
- Last working ShellyForHASS release (if known): 0.1.9
- Home Assistant Core release with the issue: 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised

## Describe the bug
After updateing ShellyforHASS from 0.1.9 to 0.2.0.beta.2 and updating Shelly 2.5 from FW 1.7.x to 1.8.3 the status in HA doesn't updating if roller shutter is moving.

If roller is opend (100%) and I press "down" button roller starts moving but there is no indication in the HA GUI.
It doesn't update "last changed" and it does not propper show the "current_position" while moving. It is still showing 100%.
This leads to that I can not open the roller shutter anymore in HA GUI until I fully close it as HA is thinking it is still at 100%.

## Steps to Reproduce
Shelly 2.5 in roller shutter mode.
Lovelace UI to open/stop/close roller
Shelly FW 1.8.3
ShellyforHASS 0.2.0.beta.2

Full open roller shutter. Let roller shutter close and stop after a few seconds (depends on roller shuter how long)
While moving check HA GUI. There is no indication and it doen't update the "current_position".

## Expected behavior
- Update "current_position" while moving
- Button up/down should be available if "current_position" is >0% or <100% as in this case the roller is not fully open/closed.

## Screenshots
Shows "fully open" / `current_position` = 100%:
![image](https://user-images.githubusercontent.com/12324196/91535750-ef7fc500-e913-11ea-9856-3debcbe5196f.png)
Show real position at 24% in Shelly cloud:
![image](https://user-images.githubusercontent.com/12324196/91535880-235aea80-e914-11ea-9200-f618ef34802e.png)

## Traceback/Error logs
-

## Additional context
-

**Comment by lh14576** [comment]
same issue for me

**Comment by vistalba** [comment]
Update Info:
Shelly 2.5 with FW 1.7.7 and ShellyforHASS 0.2.0.beta.2 is working fine. So it looke like an issue with new CoAP Protocol.

**Comment by tigers75** [comment]
I experience the same bug but for me the position is oscillating between 0 and 100% every 4 or 5 seconds, not showing the real position. 
I upgraded to 1.8 only one shelly, that gave me connectivity problems, and that's the only one with this behaviour, the others on 1.7 FW run just fine like before.

**Comment by Ligio** [comment]
Same problem!
This is the error I have in HA logs:

`
Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/coap.py:191
First occurred: 27 agosto 2020, 21:34:20 (5181 occurrences)
Last logged: 19:12:41

Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 53, in update
    self.info_values[INFO_VALUE_SWITCH] = switch_state > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'`

**Comment by tigers75** [comment]
I guess my issue is unrelated then, because I'm getting no errors in log. Should I open a new one? My cover status keeps oscillating between the real state and 0%.

**Comment by thecem** [comment]
@tigers75: I have the same with 2.5 in shutter mode fw 1.8.0 and fw 1.8.3.

@chemelli74: if you need more logs let me know...

**Comment by tal2420** [comment]
Same issue with Shelly fw 1.8.3

**Comment by hakana** [comment]
Working on that to next release

**Comment by vistalba** [comment]
Look like it is solved for me in 0.2.0.beta.3.
