### ISSUE TITLE
Capturing Shelly1 Switch Status

### ISSUE THREAD

**Issue by gitnubee** [StyraHem/ShellyForHASS#40]
Is it possible to capture the Shelly1 switch status?
The Shelly 1 is used to open and close our garage door.
When polled via MQTT: shellies/shelly1-E0XXXX/input/0/#
1= Garage door is closed
0=Garage door is open

What I want to do is create an automation that runs at say 21:30 and checks the status of the garage door: If its open, send a command to close it; if it's closed do nothing.

I've set additional_information: true but the switch status doesn't come through

**Comment by hakana** [comment]
We waiting for Shelly to add input status in CoAP messages in coming fw. Please ask when it will be available in Shelly forum or support to remind them user asking for this feature. I will try to fix a work around until it will be in fw.

**Comment by hakana** [comment]
Fixed in latest release
