### ISSUE TITLE
[BUG] Shelly H&T state unknown for all sensors with FW 1.8.0

### ISSUE THREAD

**Issue by vistalba** [StyraHem/ShellyForHASS#400]
## Environment

- ShellyForHASS release with the issue: 0.2.0.beta.2
- Last working ShellyForHASS release (if known): 0.1.9
- Home Assistant Core release with the issue: 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised

## Describe the bug
With ShellyforHASS 0.2.0.beta.2 and Shelly H&T on FW 1.8.0 all states (temperature/humidity/battery) shows as `unknown`.
Shelly H&T with Firmware 1.7.7 with ShellyforHASS 0.2.0.beta.2 is working fine. So there seems to be an CoAP translation issue as HA shows "last change 2 min ago" but state is still "unknown".

## Steps to Reproduce
Use Shelly H&T with Firmware 1.8.0 and ShellyforHASS 0.2.0.beta.2.

## Expected behavior
Show correct temperature/humidity/battery values as state of the sensor.

## Screenshots
![image](https://user-images.githubusercontent.com/12324196/91536846-aa5c9280-e915-11ea-9b40-d85c42897f85.png)

## Traceback/Error logs
-

## Additional context
-

**Comment by bigboban** [comment]
Yes, i confirm this. Last version 0.1.9 was working but precision was 1 whole degree celsius as i wrote here: https://github.com/StyraHem/ShellyForHASS/issues/388
Now only some little dots are on graph - so in some very little time it works:
![image](https://user-images.githubusercontent.com/7159224/91595327-a3f50780-e963-11ea-96b8-1ab25f165e47.png)

**Comment by hakana** [comment]
Working on that!

**Comment by vistalba** [comment]
Testing 0.2.0.beta.3 at this time. Will report back.

**Comment by n3tkiller** [comment]
beta 3 seems to fix it in my setup.

**Comment by vistalba** [comment]
For me it looks like it is fixed too. No issues for a few hours now. I will close the issue.
