### ISSUE TITLE
RGBW2 index out of range (FW 1.8)

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#405]
## Environment

- ShellyForHASS release with the issue: 2.0 beta 2
- Last working ShellyForHASS release (if known): 1.9.0
- Home Assistant Core release with the issue: 4.12
- Operating environment (Home Assistant/Supervised/Docker/venv): HASSIO Raspberry Pi 4

## Describe the bug

The config of a Shelly RGBW2 throws an error

## Steps to Reproduce

Configure Shelly RGBW2 in setup

## Expected behavior

No errors in log

## Traceback/Error logs

```
Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/utils.py:38 
First occurred: 13:44:30 (36 occurrences) 
Last logged: 13:55:37

Error update device status: 123ABC-2 SHRGBW2, list index out of range, Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 169, in update_status_information dev._update_info_value(name, status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 79, in _update_info_value value = self._get_status_value(status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 64, in _get_status_value value = value[ch] IndexError: list index out of range
Error update device status: 123ABC-3 SHRGBW2, list index out of range, Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 169, in update_status_information dev._update_info_value(name, status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 79, in _update_info_value value = self._get_status_value(status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 64, in _get_status_value value = value[ch] IndexError: list index out of range
Error update device status: 123ABC-4 SHRGBW2, list index out of range, Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 169, in update_status_information dev._update_info_value(name, status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 79, in _update_info_value value = self._get_status_value(status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 64, in _get_status_value value = value[ch] IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 169, in update_status_information
    dev._update_info_value(name, status, cfg)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 79, in _update_info_value
    value = self._get_status_value(status, cfg)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 64, in _get_status_value
    value = value[ch]
IndexError: list index out of range
```

**Comment by marcob79** [comment]
still present in beta3 as well

Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/utils.py:38
First occurred: 4:55:12 PM (93 occurrences)
Last logged: 5:25:12 PM

Error update device status: XXXXXX-2 SHRGBW2, list index out of range, Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 166, in update_status_information dev._update_info_value(name, status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 94, in _update_info_value value = self._get_status_value(status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 77, in _get_status_value value = value[ch] IndexError: list index out of range
Error update device status: XXXXXX-3 SHRGBW2, list index out of range, Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 166, in update_status_information dev._update_info_value(name, status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 94, in _update_info_value value = self._get_status_value(status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 77, in _get_status_value value = value[ch] IndexError: list index out of range
Error update device status: XXXXXX-4 SHRGBW2, list index out of range, Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 166, in update_status_information dev._update_info_value(name, status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 94, in _update_info_value value = self._get_status_value(status, cfg) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 77, in _get_status_value value = value[ch] IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 166, in update_status_information
    dev._update_info_value(name, status, cfg)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 94, in _update_info_value
    value = self._get_status_value(status, cfg)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 77, in _get_status_value
    value = value[ch]
IndexError: list index out of range
