### ISSUE TITLE
[BUG] Shelly 1 shellyforhass.click only reporting single and long (FW 1.8.3)

### ISSUE THREAD

**Issue by david-kalbermatten** [StyraHem/ShellyForHASS#409]
## Environment

- ShellyForHASS release with the issue: 0.2.0.beta3 also present in beta4
- Last working ShellyForHASS release (if known): 1.9
- Home Assistant Core release with the issue: 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

After upgrading the `shellyforhass.click` event doesn't have lag anymore like I previously described in issue #356, however with the new firmware the old `shelly_switch_click` event doesn't fire anymore for the Shelly 1.

This wouldn't be an issue if it weren't for the missing double and triple clicks which both show up as single clicks in the `shellyforhass.click` event.

## Steps to Reproduce

1. Update shelly 1 to the newest firmware (1.8.3 at the time of writing)
2. Use event listener on `shellyforhass.click`

## Expected behavior

It should work like the Shelly Button i.e. single, double, triple, long

**Comment by hakana** [comment]
Try beta 4

**Comment by david-kalbermatten** [comment]
Still the same. Also because I forgot to mention it in the initial bug report, I'm using the Shelly Button enclosure for the Shelly 1 which uses a momentary switch i.e. `press down => On | release => Off`.

## Example output from debugging tab:
__When pressing the button 2x and 3x, they each show up as single__
```json
{
    "event_type": "shellyforhass.click",
    "data": {
        "entity_id": "binary_sensor.shelly_shsw_1_xxxxxxxxxxxxxxx_switch",
        "click_type": "single"  <--- This should be triple
    },
    "origin": "LOCAL",
    "time_fired": "2020-09-02T05:05:51.063136+00:00",
    "context": {
        "id": "f8928468ecd911eab818393c23c6e7a9",
        "parent_id": null,
        "user_id": null
    }
}
{
    "event_type": "shellyforhass.click",
    "data": {
        "entity_id": "binary_sensor.shelly_shsw_1_xxxxxxxxxxxxx_switch",
        "click_type": "single"  <--- This should be double
    },
    "origin": "LOCAL",
    "time_fired": "2020-09-02T05:05:49.164075+00:00",
    "context": {
        "id": "f770be7decd911eab839af5c8c99617f",
        "parent_id": null,
        "user_id": null
    }
}
{
    "event_type": "shellyforhass.click",
    "data": {
        "entity_id": "binary_sensor.shelly_shsw_1_xxxxxxxxxxx_switch",
        "click_type": "single"
    },
    "origin": "LOCAL",
    "time_fired": "2020-09-02T04:59:47.529996+00:00",
    "context": {
        "id": "1fe3c30aecd911ea96cbb912dec9d4ee",
        "parent_id": null,
        "user_id": null
    }
}

{
    "event_type": "shellyforhass.click",
    "data": {
        "entity_id": "binary_sensor.shelly_shsw_1_xxxxxxxxxxxxx_switch",
        "click_type": "long"
    },
    "origin": "LOCAL",
    "time_fired": "2020-09-02T04:59:43.226908+00:00",
    "context": {
        "id": "1d5329edecd911ea965e7f7b9b1bc3a9",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by hakana** [comment]
Shelly firmware only support long and short click for Shelly You can request an update for this on Shelly Support forum.

**Comment by david-kalbermatten** [comment]
@hakana `shelly_switch_click` doesn't fire when using a Shelly 1 with the new firmware (1.8.3). So if Shelly 1 doesn't provide double and triple click with `shellyforhass.click`, it should at least still work with the old event (`shelly_switch_click`) which unfortunately isn't the case at the moment with the beta D:

**Comment by hakana** [comment]
This is because shelly fw limitations and nothing we can do anything about. If you click to fast shelly device not sending this info for example. Fw also only support single and double click for some devices.

**Comment by Kinglias** [comment]
Same issue with Shelly dimmer 2. Shelly only reporting single and long click and events are not relîable,
