### ISSUE TITLE
Shelly 1PM - add power sensor

### ISSUE THREAD

**Issue by trommegutten** [StyraHem/ShellyForHASS#41]
Implement power sensor for Shelly 1 PM, please.
They are missing right now in component version: 0.0.15. Shelly's status page has them already, example:
```
"time": "09:43",
  "serial": 1,
  "has_update": false,
  [...cut...]
  "relays": [
    {
      "ison": true,
      "has_timer": false,
      "overpower": false
    }
  ],
  "meters": [
    {
      "power": 241.01,
      "is_valid": true,
      "timestamp": 1564479811,
      "counters": [
        0.000,
        0.000,
        0.000
      ],
      "total": 14689
    }
  ],
  "temperature": 29.41,
  "overtemperature": false,
  [...cut...]
```

**Comment by hakana** [comment]
Hi, it is already implemented in 0.0.15. How is you config for shelly look like? It appear as a sensor named like this, sensor.shelly_shsw_pm_1a3b3c_consumtion.

**Comment by trommegutten** [comment]
Yes, you are right. I did not have the latest home assistant release and that was causing my problems with the component. 

After making the core up to date, the component works like a charm👍🏻

**Comment by hakana** [comment]
Perfekt!
