### ISSUE TITLE
[BUG] Shelly Button 1 click_type null (0.2.0.beta3)

### ISSUE THREAD

**Issue by david-kalbermatten** [StyraHem/ShellyForHASS#410]
## Environment

- ShellyForHASS release with the issue: 0.2.0.beta3
- Last working ShellyForHASS release (if known): 1.9
- Home Assistant Core release with the issue: 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

The Shelly Button 1 still causes the `shellyforhass.click` event to fire, however the `click_type` reports as `null` instead of single, double, triple or long.

## Steps to Reproduce

1. use Shelly Button 1
2. observe the event output from `shellyforhass.click`

## Expected behavior

It should work as it did in ShellyForHass 1.9 since the firmware didn't change (1.7.3)

**Comment by hakana** [comment]
Check beta 4

**Comment by david-kalbermatten** [comment]
Works as expected now. Using it with external power supply. Haven't tested it on battery mode

**Comment by hakana** [comment]
There is a bug in firmware for Button1 when running on battery. I have implemented a workaround, but this has a limit that it not allow detecting clicks more frequently than 10 sec.

**Comment by david-kalbermatten** [comment]
I updated the Firmware to 1.8.3 and now it's showing the same On/Off behavior from issue #408 

```json
{
    "event_type": "shelly_switch_click",
    "data": {
        "entity_id": "binary_sensor.shelly_shbtn_1_xxxxxxxxxxxx_switch",
        "click_cnt": 2,
        "state": false
    },
    "origin": "LOCAL",
    "time_fired": "2020-09-02T18:54:18.612672+00:00",
    "context": {
        "id": "b494a688ed4d11eaa194931cf3280e22",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by david-kalbermatten** [comment]
beta5 fixed the resurgence of this issue :+1
