### ISSUE TITLE
[BUG] name 'new_val' is not defined

### ISSUE THREAD

**Issue by azriele** [StyraHem/ShellyForHASS#420]
Home Assistant version (docker) : 0.114.4
HACS Version: 1.5.2
Shelly integration version: 2.0.0.beta.6

This update has fixed some of the issues I had (#403) but now the integration raises the same exception few times in a second and cause the all system to crash (high Cpu and 100% Memory )
This is the exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 289, in _update_loop
    block.loop()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 107, in loop
    if value != new_val:
NameError: name 'new_val' is not defined
2020-09-04 15:40:19 ERROR (Update loop) [pyShelly] Error update loop, name 'new_val' is not defined, Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 289, in _update_loop
    block.loop()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 107, in loop
    if value != new_val:
NameError: name 'new_val' is not defined

**Comment by n3tkiller** [comment]
@azriele this issues is actually in pyShelly(https://github.com/StyraHem/pyShelly/blob/master/pyShelly/block.py)
temporary fix:
edit the file "/usr/local/lib/python3.8/site-packages/pyShelly/block.py" on line 107, as following:

`if value != new_val:` to become `if value != new_value:`

**Comment by galex80** [comment]
Hy @n3tkiller 
I want to do the temporary fix, unfortunately i cannot find the path for.
I'm running Hassio on a Rasperrry PI, the only path i found was /config/custom_components/shelly/block.py 
But on line 107 i didn't found the specific line. 
Can you point me to the right direction.
Any help here appreciate

**Comment by lwYeo** [comment]
@galex80 the issue is at the pyShelly repo, not ShellyForHASS repo.

**Comment by galex80** [comment]
@lwYeo Understood, but I'm wondering if there is a way to fix it manually In the ShellyForHASS as well until there is a official fix available.

**Comment by n3tkiller** [comment]
@galex80 you can by editing the file block.py as stated above. In my setup, the file is located at `/srv/homeassistant/lib/python3.7/site-packages/pyShelly/block.py`. You need to look where is yours. The best is to look at the log file of hass.io to see where the error is discovered.
By the way, I am running HASS without a virtual environment, so the file is probably at a slightly different location.

**Comment by galex80** [comment]
Unfortunately i wasn't able to figure out, how to find the correct path in a HASSIO Installation (I guess a Newbie-Issue :-S ) .
The weird thing is, that i got exactly the same error with the same file path "/usr/local/lib/python3.8/site-packages/pyShelly/block.py". But this path doesn't exist or i'm to stupid to access it.

**Comment by azriele** [comment]
Looks like the bug is fixed on pyShelly
