### ISSUE TITLE
[BUG] Shelly Door/Window2 (DW2) status not updated or incorrect

### ISSUE THREAD

**Issue by TheGroundZero** [StyraHem/ShellyForHASS#421]
## Environment

- ShellyForHASS release with the issue: 0.2.0-b6
- Last working ShellyForHASS release (if known):  /
- Home Assistant Core release with the issue: HassOS 4.12 / Home Assistant 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant VM

```yaml
shelly: 0.2.0-b6
pyShelly: 0.2.8
developed_by: StyraHem.se
friendly_name: ShellyForHass
```

Supervisor | -
-- | --
Version | 235
Latest version | 235

Host system | -
-- | --
Hostname | homeassistant
System | HassOS 4.12
Deployment | production

Shelly firmware: 20200818-120407/v1.8.2@36539b0b

## Describe the bug

The status of my Shelly DW2 in Home Assistant, doesn't match the physical status of my doors.  
They are correct in the Shelly app, so it's not an issue with the sensors.

Status in HA is _usually_ the status of the sensor when Home Assistant is rebooted.

State changes aren't captured, so automations using the DW2 as trigger don't work.

## Steps to Reproduce

- Install ShellyForHASS
- Have one or more Shelly Door/Window2 sensors installed in your house and configured in the app

## Expected behavior

- Have Home Assistant correctly display the current state of the DW2.
- Be able to build automations using the DW2 state change as trigger

## Screenshots

![image](https://user-images.githubusercontent.com/2406013/92304565-ae6c5e00-ef6e-11ea-8dff-cda1b6ca2b61.png)
![image](https://user-images.githubusercontent.com/2406013/92304578-c04e0100-ef6e-11ea-8b4c-143fb419eadb.png)
![image](https://user-images.githubusercontent.com/2406013/92304580-c80da580-ef6e-11ea-9db5-2ab1a80a1225.png)

Currently, my "Achterdeur" is open and my "Voordeur" is closed.
Notice how "Voordeur" has been unavailable as some moments.

## Traceback/Error logs

```txt

```

**Comment by msekoranja** [comment]
I have problem with DW2 too. The door is closed, cloud reports closed to (cloud is always correct), but HA reports open.
Using the latest HA and integration. HA shows that the door were closed but then couple of minutes later (delay not constant) it reports open again! If I check the HA logbook, I see only closed event.

**Comment by msekoranja** [comment]
Another thing I have noticed. The door were closed and correctly reported by HA. Then I have restarted HA (entire host computer). After the restart the status changed to open. I guess this state will remain "wrong" until the sensors wakes up, right? Therefore can I make a conclusion that "battery powered Shelly devices" are flawed. Maybe not a big issue with temp.&hum. devices, but with door/window sensor this is very inconvenient.

**Comment by msekoranja** [comment]
Basically the only thing that can be done here is to query Shelly Cloud (if used) for the most recent state.
Or introduce periodic wakeups in FW and sacrifice a battery.

**Comment by TheGroundZero** [comment]
Rebooted HA yesterday for an update of ShellyForHASS (0.2.0 coming out of beta).  
Since then, both DW2 are unavailable, even though I have opened and closed both doors multiple times since.

Lights are detected without any problem, so there's no issue on the network side.  
H&T (#422) are still not discovered either.

![image](https://user-images.githubusercontent.com/2406013/92574651-e200fe00-f276-11ea-92f3-19c2cc619463.png)

**Comment by hakana** [comment]
What say the protocol attributes under the lights?

**Comment by hakana** [comment]
I will have a closer look at this later. I have tested with my H&T and it is working.

**Comment by TheGroundZero** [comment]
> What say the protocol attributes under the lights?

Is this what you mean?
![image](https://user-images.githubusercontent.com/2406013/92586748-365faa00-f286-11ea-844e-5ed5096e7836.png)
![image](https://user-images.githubusercontent.com/2406013/92586795-44adc600-f286-11ea-923e-14cb561b525d.png)

**Comment by TheGroundZero** [comment]
I have the igmp_fix enabled
![image](https://user-images.githubusercontent.com/2406013/92587300-fcdb6e80-f286-11ea-8c8c-13f13e191801.png)

**Comment by thechorba** [comment]
did you managed to get it working correctly? 
I am having the same issue. 
the status doesn't change

**Comment by TheGroundZero** [comment]
> did you managed to get it working correctly?
> I am having the same issue.
> the status doesn't change

My HA still doesn't connect to the DW2 over CoAP.  
DW2 still shows as Unavailable for most of the time.

I'm planning to switch to MQTT, since this seems to work well with my H&T (I'm also having issues with ShellyForHASS and H&T)

**Comment by thechorba** [comment]
my dw2 over coap any the unit is always available.
my problem is that the status doesn't change. 
is there anything i can try?

**Comment by hakana** [comment]
U will have a look on this and see if I can reproduce

**Comment by ichesworth** [comment]
I have this same issue on DW2 (currently running 0.2.1 on Hassio 118.4 but the problem has been there for a while). My sensor updates straight away (on both cloud and in HA) when our garage door is opened i.e. device has been asleep for a long time but when the door is closed, the cloud updates straight away but HA doesn't get updated which means my automation based on the door being left open doesn't work! The sensor seems to update itself much later (can be up to 4-5 hours). I don't want to move over to MQTT as I want to keep cloud functionality!

**Comment by davidjac** [comment]
I also have same issue with DW2. All fine in Shelley app but showing unavailable in v2020.12.0. Only installed yesterday and appeared to be ok until update/reboot.

**Comment by arofarn** [comment]
Same issue here with Shelly DW2 out-of-the-box and after firmware update (current version: 20210115-103411/v1.9.4@e2732e05 ).

Notes : 
 - on the sensor's own webinterface, data are correct
 - correct data are sent (and received) over MQTT protocol (I don't use Shelly cloud) but no update in HA
 - user auth is enable on sensor.
 - Home Assistant version : 2021.1.5 (rebooted several times for this issue and others configuration tweaks not related to Shelly integration).

**Comment by davidjac** [comment]
Doesn't seem this is being fixed. I switched to Mqtt (tick retain) and all ok now.

**Comment by TheGroundZero** [comment]
> 
> 
> Doesn't seem this is being fixed. I switched to Mqtt (tick retain) and all ok now.

You most likely don't want to tick Retain.
This will cause the Shelly to resend its latest messages each time it reconnects to WiFi or reboots.
This may cause ghost switching.

The Shelly also resends its state every 30 seconds by default.
See https://shelly-api-docs.shelly.cloud/#availability-and-announces

**Comment by davidjac** [comment]
THis is what someone advised on a blog a few weeks ago - I also raised the question on "killing battery" all appears to be ok since I did it - here's response. 
"retain" flag sets a field in the MQTT message that instructs the broker to save the message and whoever asks for it (homeassistant) receives it on start. This is functionality of the MQTT protocol. The shelly will keep operating normaly (no increase in power drain). And yes if using MQTT is as simple as just ticking the box.

**Comment by Raphael99-99** [comment]
Same issue here. Shelly DW out of the box working flawlessy with shelly app but not in homeassistant. I updated and then downgraded shellyforhass with no joy at all.  It never updates. It has worked for few after shelly DW installation. Now is stuck on open

**Comment by Raphael99-99** [comment]
![B7B9F360-34BA-4361-BAC7-A71DE38DB9E1](https://user-images.githubusercontent.com/46441468/119490001-98046d80-bd5c-11eb-89cb-04c888be41d0.png)

**Comment by pepjo** [comment]
I am having the same issue with a brand-new sensor, that state is correct in the web-ui of the sensor but not on home assistant

**Comment by davidjac** [comment]
Its a bit of a pain. Kind of working ok most of the time. Just replaced batteries following inconsistent results - now much improved. Definitely not perfect. Batteries lasted about 8 months BTW.

**Comment by tgg-wellhive** [comment]
I have an HA automation that monotors the Shelly dw2 mounted on my patio slider door. It turns my AC off if the is left open for some period of time. It turns the AC back on when the door is closed. And of the automation has shut off the AC it monotors the humidity in the house. If the it reaches a given % (as measured by my Ecobee) then it triggers my Echo devices to suggest I close the door.  

I am also seeing intermittent issues with the door not reporting closed to HA (over MQTT). 

My automation now works like this:

If the Door is left open, the AC is turned off. The door is closed and if the 'door closed' event is not received, my AC doesn't get turned back on. 
If my AC stays off.  My Temp sensor monitor in my Computer Closet is triggered which sends an HA notify to me letting me know my computers are gonna fry. I then  manually turn the AC back on.

I GUESS this is an automation of a sort....

I was hoping there was some wakeup timer setting on the Shelly dw2 that would wake it up so it would send it's sensor states at a defined interval like my Shelly1 devices.

**Comment by apedance** [comment]
I have this issue too.
not using mqtt. updates takes ages or doesn't happen at all.

**Comment by sroettering** [comment]
I'm having the same issue with newest integration version and a brand new shelly door/window 2. States of any sensor did not change since the initial setup 3 hours ago. I don't want to use mqtt and stick with coap.

**Comment by mARTin-B78** [comment]
Got the same issue - 
the sensor works with shelly cloud or on the web interface over the ip
but the status  (door open / closed) does not change in home assistant. 

Any Fix for it?

**Comment by Aka1962** [comment]
Bei mir das Gleiche.
Statusänderungen über die Shelly AP
aber über Home Assistant werden immer die Werte und der Status zum Zeitpunkt der Einbindung angezeigt.

Hat jemand eine Lösung ?

**Comment by mARTin-B78** [comment]
Got into a conversation with Shelly Support..
here is the last message:

> You have to subscribe to the topic shellies/shellydw-<deviceid>/sensor/state, it's where the open/close status appears. 
Check again the documentation: https://shelly-api-docs.shelly.cloud/gen1/#shelly-door-window-1-2-mqtt
The forum you sent us is from 2020, with last update of February this year. It is not a relevant topic anymore.
You are confusing something with the configuration.
Kind regards,
Shelly Support Team

It did not help me much so I went through the hassle to set up a Mosquitto MQTT Server just for that one device.

**Comment by raemsey** [comment]
Same issue here. MQTT did not solve the issue for me.

**Comment by madAndroid** [comment]
I was experiencing the same symptoms, until I configured `ColoT` in the Shelly configuration, following the steps in the HA docs, here: https://www.home-assistant.io/integrations/shelly/#shelly-device-configuration-generation-1

Once this was configured to point to my HA instance on the Shelly settings side, the device is reporting open/close properly.

**Comment by Meyer3** [comment]
> ... I configured `CoIoT ` in the Shelly configuration, 

That is the solution. RTFM. I almost threw away my DW2 that was not reporting to HA most of the time. Also helps with RGBW2 that reacts to dashboard now at first click.

In detail:
> We recommend using `unicast` for communication. To enable this, enter the local IP address of the Home Assistant server and port `5683` into the CoIoT peer field [of web interface, not app] and push SAVE button.

**Comment by TheGroundZero** [comment]
There's no more reason to use ShellyForHass as Home Assistant supports Shelly out of the box.
Set up CoIoT for the best results.

If you don't want to use the built-in integration, use MQTT.

**Comment by MarkusHempel** [comment]
Hallo zusammen,
Statusänderungen über die Shelly APP funktionieren.
aber über Home Assistant 2022.12.5 werden immer die Werte und der Status zum Zeitpunkt der Einbindung angezeigt.
Bis Home Assistant Version 2022.12.4 funktionierte es noch. 
Hat jemand eine Lösung ?

**Comment by Misenkooo** [comment]
2023 and this is still not fixed. Via mcast it reports only very randomly and with unicast it's tad better but not 100% reliable. I was trying to use tcdump to monitor communication for the device and sometimes packet was lost. UDP protocol is not very good for these kind of things since it's simply unreliable. You must have really good wifi connection this works as much reliable as possible. MQTT is out of scope since I need the status also in cloud. Cloud works always OK so I wonder if it would be possible to re-send events from shelly cloud to HA. Maybe this would be a solution but I don't know if they offer this service and if so, then it's probably a paid service.

**Comment by TheGroundZero** [comment]
> 2023 and this is still not fixed. Via mcast it reports only very randomly and with unicast it's tad better but not 100% reliable. I was trying to use tcdump to monitor communication for the device and sometimes packet was lost. UDP protocol is not very good for these kind of things since it's simply unreliable. You must have really good wifi connection this works as much reliable as possible. MQTT is out of scope since I need the status also in cloud. Cloud works always OK so I wonder if it would be possible to re-send events from shelly cloud to HA. Maybe this would be a solution but I don't know if they offer this service and if so, then it's probably a paid service.

Have you tried the built-in Shelly integration?
Combined with CoIoT unicast it works perfectly fine for me
https://www.home-assistant.io/integrations/shelly/

**Comment by TheGroundZero** [comment]
> 2023 and this is still not fixed. Via mcast it reports only very randomly and with unicast it's tad better but not 100% reliable. I was trying to use tcdump to monitor communication for the device and sometimes packet was lost. UDP protocol is not very good for these kind of things since it's simply unreliable. You must have really good wifi connection this works as much reliable as possible. MQTT is out of scope since I need the status also in cloud. Cloud works always OK so I wonder if it would be possible to re-send events from shelly cloud to HA. Maybe this would be a solution but I don't know if they offer this service and if so, then it's probably a paid service.

Use built-in integration https://www.home-assistant.io/integrations/shelly/ and CoIoT.
If you still have issues then, pick it up with the HA devs.

**Comment by Meyer3** [comment]
Same issue here. The built-in integration works great for all other Shellys but the DW2 becomes "unavailable" every few days. I just need to reload integration to immediately see it again.
 
During this "unavailable" time the sensor is not reporting any status change.
