### ISSUE TITLE
[FR] Shelly Plug US support

### ISSUE THREAD

**Issue by Shnoobins** [StyraHem/ShellyForHASS#429]
## Is your feature request related to a problem? Please describe.

Discovering Shelly Plug US does not appear to be supported

## Describe the solution you'd like

To be able to use the new Shelly Plug US with home assistant

## Additional context

I saw a post on the facebook group to gather the CoAP Messages related to the plug, so I enabled the logging. I've been trying to get mine added for a few days without luck, hoping someone can help with getting this functionality added. I didn't want to remove anything from the log that might be needed, so I started HA and let it run for a while to gather the logs, saw the CoAP run a few times, then shut it down and gathered what I have. Here are the logs for review: 
[home-assistant.log](https://github.com/StyraHem/ShellyForHASS/files/5191394/home-assistant.log)

Let me know what other data might be needed, if I've missed anything: 

HA: 0.114.4
Shelly Plug Firmware: 20200827-070340/v1.8.3
ShellyForHas: 0.1.9
Shelly Plug IP: 10.10.14.58 (I think this MIGHT make it easier to sort through the logs since there are several shelly devices in my configuration.

**Comment by hakana** [comment]
I need a /status /settings from REST API and also if you can collect the CoAP message sent from it. Also need the mDns signature and MQTT signature,

**Comment by Shnoobins** [comment]
Happy to grab them, though I am not sure how. The logs I gathered above were gathered with logger and shelly set to debug, Is there something beyond that needed? How do I gather them for ya? 

Thanks for the help!

**Comment by jasonwilk** [comment]
$ curl http://<ip-address>/status | jq
{
  "wifi_sta": {
    "connected": true,
    "ssid": "<SSID>",
    "ip": "<ip-address>",
    "rssi": -79
  },
  "cloud": {
    "enabled": false,
    "connected": false
  },
  "mqtt": {
    "connected": false
  },
  "time": "22:59",
  "unixtime": 1599605997,
  "serial": 206,
  "has_update": false,
  "mac": "<MAC>",
  "cfg_changed_cnt": 6,
  "actions_stats": {
    "skipped": 0
  },
  "relays": [
    {
      "ison": false,
      "has_timer": false,
      "timer_started": 0,
      "timer_duration": 0,
      "timer_remaining": 0,
      "overpower": false,
      "source": "http"
    }
  ],
  "meters": [
    {
      "power": 0,
      "overpower": 0,
      "is_valid": true,
      "timestamp": 1599605997,
      "counters": [
        0,
        0,
        0
      ],
      "total": 0
    }
  ],
  "update": {
    "status": "idle",
    "has_update": false,
    "new_version": "20200827-070340/v1.8.3@4a8bc427",
    "old_version": "20200827-070340/v1.8.3@4a8bc427"
  },
  "ram_total": 51112,
  "ram_free": 39304,
  "fs_size": 233681,
  "fs_free": 162648,
  "uptime": 11895
}

**Comment by jasonwilk** [comment]
@hakana Here is the requested REST API output

$ curl /settings | jq

```
{
  "device": {
    "type": "SHPLG-U1",
    "mac": "<MAC>",
    "hostname": "shellyplugu1-<ID>",
    "num_outputs": 1,
    "num_meters": 1
  },
  "wifi_ap": {
    "enabled": false,
    "ssid": "shellyplugu1-<ID>",
    "key": ""
  },
  "wifi_sta": {
    "enabled": true,
    "ssid": "<SSID>",
    "ipv4_method": "dhcp",
    "ip": null,
    "gw": null,
    "mask": null,
    "dns": null
  },
  "wifi_sta1": {
    "enabled": false,
    "ssid": null,
    "ipv4_method": "dhcp",
    "ip": null,
    "gw": null,
    "mask": null,
    "dns": null
  },
  "mqtt": {
    "enable": false,
    "server": "",
    "user": "",
    "id": "shellyplugu1-<ID>",
    "reconnect_timeout_max": 60,
    "reconnect_timeout_min": 2,
    "clean_session": true,
    "keep_alive": 60,
    "max_qos": 0,
    "retain": false,
    "update_period": 30
  },
  "coiot": {
    "update_period": 15
  },
  "sntp": {
    "server": "time.google.com",
    "enabled": true
  },
  "login": {
    "enabled": false,
    "unprotected": false,
    "username": "admin"
  },
  "pin_code": "",
  "name": null,
  "fw": "20200827-070340/v1.8.3@4a8bc427",
  "discoverable": true,
  "build_info": {
    "build_id": "20200827-070340/v1.8.3@4a8bc427",
    "build_timestamp": "2020-08-27T07:03:40Z",
    "build_version": "1.0"
  },
  "cloud": {
    "enabled": false,
    "connected": false
  },
  "timezone": "America/Chicago",
  "lat": <lat>,
  "lng": <lon>,
  "tzautodetect": true,
  "tz_utc_offset": -18000,
  "tz_dst": true,
  "tz_dst_auto": true,
  "time": "23:04",
  "unixtime": 1599606259,
  "led_status_disable": false,
  "actions": {
    "active": false,
    "names": [
      "btn_on_url",
      "out_on_url",
      "out_off_url"
    ]
  },
  "hwinfo": {
    "hw_revision": "prod-2020-04-14",
    "batch_id": 1
  },
  "max_power": 2500,
  "led_power_disable": false,
  "relays": [
    {
      "name": null,
      "ison": false,
      "has_timer": false,
      "default_state": "off",
      "auto_on": 0,
      "auto_off": 0,
      "btn_on_url": "",
      "out_on_url": "",
      "out_off_url": "",
      "schedule": false,
      "schedule_rules": [],
      "max_power": 2500
    }
  ]
}
```

**Comment by jasonwilk** [comment]
@hakana Is this what you're looking for with regard to MQTT signature?

```
Message 5 received on shellies/shellyplugu1-AA1234/relay/0 at 12:00 AM:
off
QoS: 0 - Retain: false
Message 4 received on shellies/shellyplugu1-AA1234/relay/0/energy at 12:00 AM:
0
QoS: 0 - Retain: false
Message 3 received on shellies/shellyplugu1-AA1234/relay/0/power at 12:00 AM:
0
QoS: 0 - Retain: false
Message 2 received on shellies/shellyplugu1-AA1234/relay/0/energy at 12:00 AM:
0
QoS: 0 - Retain: true
Message 1 received on shellies/shellyplugu1-AA1234/relay/0/power at 12:00 AM:
0
QoS: 0 - Retain: true
Message 0 received on shellies/shellyplugu1-AA1234/relay/0 at 12:00 AM:
off
QoS: 0 - Retain: true
```

**Comment by mklight** [comment]
I downloaded https://github.com/StyraHem/ShellyForHASS/tree/0.2.1.beta.1 and restarted home assistant, but did not see my Shelly Plug US show up.
I looked at https://github.com/StyraHem/pyShelly/commit/48d7ccc6ffffc17f90b005f5a4aaf7d67136f756 and saw some typos that when corrected allow it to work.
In block.py:
SHPLG-US -> SHPLG-U1
In const.py:
SHPLUG-U1 -> SHPLG-U1

**Comment by hakana** [comment]
Ok, I will check that!

**Comment by Shnoobins** [comment]
@jasonwilk @hakana @mklight Thanks for all you've done to make this a reality, I really appreciate it!

**Comment by slomanl1** [comment]
> Ok, I will check that!

What is the status of the fix from mklight above?
Thanks

**Comment by slomanl1** [comment]
> Ok, I will check that!

What is the status of the fix from mklight above?
Thanks

**Comment by dlarrick** [comment]
I made https://github.com/StyraHem/pyShelly/pull/45 for this issue

**Comment by dlarrick** [comment]
You asked in the release notes for 0.2.1b3 if Shelly Plus US works there. It does not. It's still pulling a version of pyShelly that doesn't include the changes mentioned in the previous few comments here.

**Comment by hakana** [comment]
Yes you are right, I have created Beta 4 now that should include the changes for US plug.

Från: dlarrick <notifications@github.com>
Skickat: den 25 november 2020 21:42
Till: StyraHem/ShellyForHASS <ShellyForHASS@noreply.github.com>
Kopia: Håkan Åkerberg <hakan@tarra.se>; Mention <mention@noreply.github.com>
Ämne: Re: [StyraHem/ShellyForHASS] [FR] Shelly Plug US support (#429)


You asked in the release notes for 0.2.1b3 if Shelly Plus US works there. It does not. It's still pulling a version of pyShelly that doesn't include the changes mentioned in the previous few comments here.

**Comment by dlarrick** [comment]
Beta 4 seems to be working fine for Shelly Plug US. Thanks!
