### ISSUE TITLE
[BUG] Shelly 2.5 'Status switch' and 'Voltage' "Unavailable" after update

### ISSUE THREAD

**Issue by LupoCri** [StyraHem/ShellyForHASS#430]
Hi.

After update ShellyForHASS to 0.2.0 **ALL** Shelly 2.5 (roller/shutter mode with fw 1.8.3) in my net report:

- _Status switch_
- _Voltage_

as "**Unavailable**".

Home Assistant are up to date.

Thanks for the wonderful work.
LupoCri

**Comment by hakana** [comment]
Yes, you are right. Will be fixed in next release.

**Comment by ppato79** [comment]
The issue seems to be applicable also to Shelly EM. Power is unavailable.
Thanks
P

**Comment by hakana** [comment]
Fixed in 0.2.1 beta 1
