### ISSUE TITLE
[BUG] Shelly 3EM does not show current consumption

### ISSUE THREAD

**Issue by TomasSeven** [StyraHem/ShellyForHASS#431]
## Environment

- ShellyForHASS release with the issue: 2.0.0
- Last working ShellyForHASS release (if known): 1.9.0
- Home Assistant Core release with the issue: 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv):  Supervised

## Describe the bug

  The current comsumption is shown as unavailable/unknown on all three emeters.

## Steps to Reproduce

  Updated to 2.0.0

## Expected behavior
 
  Should show the current consumption (from emeters":[{"power":XXX,")..},{"power":YYY,")..},{"power":ZZZ,")..},..]

## Screenshots

 
![image](https://user-images.githubusercontent.com/30586945/92565798-8d13b680-f27b-11ea-93ed-1ea2c3685663.png)
![image](https://user-images.githubusercontent.com/30586945/92565833-9b61d280-f27b-11ea-90a1-2f2548693e3c.png)
![image](https://user-images.githubusercontent.com/30586945/92568389-65265200-f27f-11ea-9e7b-b5d16998c172.png)

## Traceback/Error logs

```txt

```

## Additional context

from the /status of the 3em device.
  {"wifi_sta":{"connected":true,"ssid":"IOT","ip":"10.10.10.13","rssi":-46},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":false},"time":"08:55","unixtime":1599641744,"serial":XXXXX,"has_update":false,"mac":"D8BFXXXXXX","cfg_changed_cnt":9,"actions_stats":{"skipped":0},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"is_valid":true,"source":"http"}],"emeters":[{"power":0.00,"pf":0.01,"current":0.32,"voltage":232.59,"is_valid":true,"total":555.2,"total_returned":0.0},{"power":-18.27,"pf":-0.08,"current":1.02,"voltage":231.58,"is_valid":true,"total":1472.1,"total_returned":3238.2},{"power":225.91,"pf":0.88,"current":1.11,"voltage":231.99,"is_valid":true,"total":30561.0,"total_returned":0.0}],"fs_mounted":true,"update":{"status":"idle","has_update":false,"new_version":"20200813-140420/v1.8.1@1b2a49be","old_version":"20200813-140420/v1.8.1@1b2a49be"},"ram_total":49432,"ram_free":28296,"fs_size":233681,"fs_free":154365,"uptime":569708}

From 1.9.0
![image](https://user-images.githubusercontent.com/30586945/92569767-4c1ea080-f281-11ea-8685-70389fbe37ae.png)

**Comment by gerliczky** [comment]
Just a guess: Did you try to remove and install the addon?
I had a similar issue. Remove and install helped me at that time.

**Comment by marcob79** [comment]
Same problem with Shelly EM.
Rollback to shellyforhass 1.9.0 keeping latest 1.8.1 Shelly firmware, the current consumption is reported correctly

**Comment by hakana** [comment]
I found the bug, it working when CoAP working as in my setup but not when only polling /status for updates. Will be fixed in next release.

**Comment by TomasSeven** [comment]
> I found the bug, it working when CoAP working as in my setup but not when only polling /status for updates. Will be fixed in next release.

Ty for your great work!

**Comment by marcob79** [comment]
Good job.
Thanks

**Comment by hakana** [comment]
Thanks, I will close this issue.
