### ISSUE TITLE
[BUG] Entity firmware_update disappear after update

### ISSUE THREAD

**Issue by LupoCri** [StyraHem/ShellyForHASS#432]
Hi.

After i update the shelly firmware by update switch, the entity _firmware_update_ **disappear**. 

![Schermata del 2020-09-09 10-54-53](https://user-images.githubusercontent.com/66326247/92577635-25fdfe00-f28b-11ea-920c-228c2e610e9c.png)

Same situation for 1v3, 2.5 and i3.
Bug still on ShellyForHASS 0.1.9 and 0.2.0.
Home Assistant are up to date.

Tnx.
LupoCri

**Comment by hakana** [comment]
That is by design if nothing to update the switch are removed, see readme file,

**Comment by LupoCri** [comment]
Tnx.
