### ISSUE TITLE
INFO: default Shelly Integration in 0.115

### ISSUE THREAD

**Issue by JonahKr** [StyraHem/ShellyForHASS#433]
## New Additions in 0.115

With the new Version 0.115, a new integration named shelly has been integrated by ballob.
You can find the beta docs here: https://rc.home-assistant.io/integrations/shelly/

This is just to make you guys aware. I really like your project! 👍 

Maybe some kind of collaboration is possible? I haven't taken a look into the nitty gritty stuff yet...

**Comment by hakana** [comment]
Yes we know that ;)

We have been in lots of meeting with Paulus (ballob) and others regarding this. They decided to start developing a new integration from scratch. I think their plan is to do a simple plugin without any extra features as in ShellyForHass.

We will continue the development of ShellyForHass and add new nice features. Next in our plan is to add a nice GUI for config and management of Shelly devices.

**Comment by Cyberfighter** [comment]
I also love the project and am glad you will be continuing to develop it.

I am currently on 0.115 and noticed that I cannot add the new 1st party integration. I wanted to do some testing with the new one. I had to delete your integration and added the 1st party one. I immediately saw that it was a much more simple integration so I switched back.

I would like to have the option to check in on the progress of the first party one though. I am assuming I cannot add both due to them both being named "Shelly". Is there any plans for changing the name of your integration so that we can have a hybrid approach of the two?

**Comment by blackbit47** [comment]
I'm glad to know ShellyForHass will go on.
Perhaps in the future, they'll reconsider and switch or merge.
A GUI will be awesome :-)
Also please sync the name property on shelly config and integrate device actions in the GUI.

Thank you so much for your work.

**Comment by jrkoiter** [comment]
Is there anything that can be shared as to why ShellyForHASS is not the starting point for the new default Shelly integration? ShellyForHASS is working great for me and will continue to use it.

**Comment by hakana** [comment]
I have been open to using ShellyForHass but of some unknown reason, they start over. Maybe they want to have a simpler solution with lower functionality.

**Comment by JonahKr** [comment]
As far as I know they started a cooperation with Shelly as a company. (source: home assistant Podcast 0.115)Maybe it has something to do with this. -------- Original message --------From: Håkan Åkerberg <notifications@github.com>Date: Thu, 8 Oct 2020, 14:54To: StyraHem/ShellyForHASS <ShellyForHASS@noreply.github.com>Cc: JonahKr <jonah.kraushaar@gmx.net>, Author <author@noreply.github.com>Subject: Re: [StyraHem/ShellyForHASS] INFO: default Shelly Integration in 0.115 (#433)
I have been open to using ShellyForHass but of some unknown reason, they start over. Maybe they want to have a simpler solution with lower functionality.

**Comment by chemelli74** [comment]
> I have been open to using ShellyForHass but of some unknown reason, they start over. Maybe they want to have a simpler solution with lower functionality.

Is not completely unknown the reason ;-)

Simone
