### ISSUE TITLE
Shelly EM current_consumption lost

### ISSUE THREAD

**Issue by koldogut** [StyraHem/ShellyForHASS#434]
Hi All,

With the new version 2.0 I've lost the current_consumption sensor for Shelly EM; just total_consumption is available. I've checked the Shelly and real-time consumption is displayed on Shelly's web interface. Some details:

ShellyForHass version: 2.0.0
Device: Shelly EM
Firmware: 1.8.1

No errors found in HA logs, the rest of the device sensors works fine (total consumption, voltage, etc..)

**Comment by nunogia** [comment]
+1

**Comment by nelsnels** [comment]
I got the same issue with a Shelly 3EM.

**Comment by ploppythekangaroo** [comment]
Have you tried going back to Firmware 1.7?  This worked for me.
You can use the Shelly firware tool to do this:
https://www.shelly-support.eu/index.php?shelly-firmware-archive/

**Comment by hakana** [comment]
Should work in 0.2.1 beta 1

**Comment by koldogut** [comment]
Upgraded to 0.2.1 beta 1 and working, thanks!
