### ISSUE TITLE
[BUG]does not show power factor

### ISSUE THREAD

**Issue by archi071** [StyraHem/ShellyForHASS#439]
## Environment

- ShellyForHASS release with the issue: 0.2.1 beta 1
- Last working ShellyForHASS release (if known): 1.7.7
- Home Assistant Core release with the issue: Home Assistant 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant 0.114.4

## Traceback/Error logs

```txt

```

**Comment by Tensorr** [comment]
Power factor is not enabled by default as one of the items it scrapes/receives from the Shellys, you need to enable it from Options in Integrations. 

![image](https://user-images.githubusercontent.com/2848441/96444792-4bb0e800-11e5-11eb-92eb-82f2c94fb029.png)

**Comment by Tensorr** [comment]
PowerFactor is not recieved by default. you need to select in Integrations / Shelly Options 

![image](https://user-images.githubusercontent.com/2848441/96444827-5cf9f480-11e5-11eb-9955-82010e7f7816.png)

**Comment by hakana** [comment]
Solved, closing this issue
