### ISSUE TITLE
Plugin fails to find Shelly 2.5 relays after router reboot

### ISSUE THREAD

**Issue by Delph1** [StyraHem/ShellyForHASS#44]
I installed 8 Shelly 2.5 a few days ago. Installed the plugin and all 8 popped up as expected and worked like a charm. 

Unfortunately I had to reboot my router earlier today after it crippled WiFi speeds to around 1Mbit/s and after reboot I can't get this to work anymore. The entities all showed as "Unavailable" (Ej tillgänglig) no matter what I did. 

I then removed the plugin from HACS, commented out shelly: from configuration.yaml and manually deleted all entries from the Entity registry as well as the known_devices.yaml. 

I then rebooted, reinstalled the plugin via HACS, enabled shelly: and rebooted again. No devices shows. 

All relays show up fine in the Shelly app. I can find all of them by scanning the network and I can reach the web interface just fine via the local IP. 

I'd really like to get this to work instead of having to create switch templates for each relay...

Also, the relays are in the known_devices.yaml now but the namnes are the mac-addresses instead of the host name if that matter.

**Comment by hakana** [comment]
Run the test python script under utils and see if you can see the network traffic from the Shellies.

https://github.com/StyraHem/ShellyForHASS/blob/master/util/test.py

**Comment by Delph1** [comment]
Ran it on the RPi. Nothing prints in the terminal.

**Comment by Delph1** [comment]
I can successfully send rest-commands and control them though and as stated above, the Shelly app sees and controls all relays just fine.

**Comment by hakana** [comment]
Test run "netstat -g" on your RPi and send the result

**Comment by Delph1** [comment]
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      224.0.0.251
lo              1      all-systems.mcast.net
eth0            2      224.0.0.251
eth0            1      all-systems.mcast.net
wlan0           1      all-systems.mcast.net
hassio          2      224.0.0.251
hassio          1      all-systems.mcast.net
docker0         2      224.0.0.251
docker0         1      all-systems.mcast.net
vethbdc625      1      all-systems.mcast.net
veth6c5311      1      all-systems.mcast.net
veth7fbe3b      1      all-systems.mcast.net
veth41b3d3      1      all-systems.mcast.net
vethd97d16      1      all-systems.mcast.net
vethf93377      1      all-systems.mcast.net
lo              1      ip6-allnodes
lo              1      ff01::1
eth0            1      ff02::fb
eth0            1      ff02::1:ff1e:475e
eth0            1      ff02::1:fff5:d78a
eth0            1      ip6-allnodes
eth0            1      ff01::1
wlan0           1      ip6-allnodes
wlan0           1      ff01::1
hassio          1      ff02::fb
hassio          1      ff02::1:ffa7:bf52
hassio          1      ip6-allnodes
hassio          1      ff01::1
docker0         1      ff02::fb
docker0         1      ff02::1:ff86:fba
docker0         1      ip6-allnodes
docker0         1      ff01::1
vethbdc6256     1      ff02::fb
vethbdc6256     1      ff02::1:ff3e:be41
vethbdc6256     1      ip6-allnodes
vethbdc6256     1      ff01::1
veth6c53117     1      ff02::fb
veth6c53117     1      ff02::1:ffc6:63f1
veth6c53117     1      ip6-allnodes
veth6c53117     1      ff01::1
veth7fbe3bd     1      ff02::fb
veth7fbe3bd     1      ff02::1:ff79:4174
veth7fbe3bd     1      ip6-allnodes
veth7fbe3bd     1      ff01::1
veth41b3d32     1      ff02::fb
veth41b3d32     1      ff02::1:ff9e:da0
veth41b3d32     1      ip6-allnodes
veth41b3d32     1      ff01::1
vethd97d161     1      ff02::fb
vethd97d161     1      ff02::1:ffef:6ae4
vethd97d161     1      ip6-allnodes
vethd97d161     1      ff01::1
vethf93377d     1      ff02::fb
vethf93377d     1      ff02::1:ffb9:2c89
vethf93377d     1      ip6-allnodes
vethf93377d     1      ff01::1

**Comment by hakana** [comment]
How are you running HASS, does not look like HassIO on RPi?

**Comment by Delph1** [comment]
It is. 

arch | armv7l
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | Europe/Stockholm
version | 0.97.1
virtualenv | false

I ran netstat inside the docker container, becuase netstat in the docker environment doesn't accept the -g option.

**Comment by hakana** [comment]
Ok, this is outside my scope. My advice is to find a place where you can receive the CoAP messages the Shelly devices. You can try to run the test.py script outside the docker or another computer. Then you can ether try to open up for the messages one step at the time. You can also run the proxy.py script from there to forward them to the HASS ip. You do that by updating the proxy.py with your HA ip.
