### ISSUE TITLE
shows wrong current value

### ISSUE THREAD

**Issue by archi071** [StyraHem/ShellyForHASS#440]
## Environment

- ShellyForHASS release with the issue: Release 0.2.1 Beta 1
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue:  Home Assistant 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv):

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
Please describe the bug, I will close this until updated with more information.
