### ISSUE TITLE
[BUG] 0.2.0 shelly EM not returning current_consumption

### ISSUE THREAD

**Issue by poofyteddy** [StyraHem/ShellyForHASS#441]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): 0.1.9
- Home Assistant Core release with the issue: 0.114.3
- Operating environment (Home Assistant/Supervised/Docker/venv): venv

## Describe the bug

`Have a report about problems with current consumption in EM and 3EM. Here it working as it should so I need more input about this. Please let me know if it working or not. Please report on the issue in GitHub.`

Well, i do have this issue with a shelly EM ... rolling back fixed it. happy to help but don't quite know how :)
shelly EM with a single 50A prob do display total_consumption, but not current_consumption
tested with Shelly v1.6.0 and 1.8.1

## Traceback/Error logs

```txt

```

**Comment by poofyteddy** [comment]
didn't look at closed issue :(

**Comment by robinostlund** [comment]
i have the same issue
