### ISSUE TITLE
[BUG] shelly shutter roller percentage isn't correct in HomeKit.

### ISSUE THREAD

**Issue by HawkUser** [StyraHem/ShellyForHASS#449]
## Environment

ShellyForHASS 0.2.0
HA 0.114 and 0.115
HassOS.

## Describe the bug
Shelly 2.5 shutter roller, Homekit Integration isn't act as expected, when using partial opening/closing while using the HA directly it seems just fine, but while using HomeKit on variant iOS devices the percentage option in opening or closing the cover in the HomeKit is messed up, it shows completely open or closed.

## Steps to Reproduce
Using HA shutters operate as expected, using the homekit the problem exists.

## Expected behavior
Insert a brief description of the expected behavior is

## Screenshots

![IMG_2766](https://user-images.githubusercontent.com/39925630/93557811-9e984500-f984-11ea-993b-ee1972818c30.PNG)
![IMG_E4C90A6E8662-1](https://user-images.githubusercontent.com/39925630/93557816-a22bcc00-f984-11ea-8726-c865bbe96fe2.jpeg)

## Traceback/Error logs

```txt

```

## Additional context
I already tried few times to (de-include) the cover domain in homekit, and reinclude it.

**Comment by PabloAriza** [comment]
I have the exact same problem. ¿Can anyone review it?

Regards

**Comment by PabloAriza** [comment]
I’ve managed to fix it. Just delete HomeKit integration on both homeassistant and iOS and reconfigure everything again 

Regards.

**Comment by asherungar** [comment]
> I’ve managed to fix it. Just delete HomeKit integration on both homeassistant and iOS and reconfigure everything again
> 
> Regards.

by me this is a temporary fix, within less than a day it's back to no percentage.

**Comment by asherungar** [comment]
Also, I'm not sure but I think this happens only after HA restarts.

**Comment by benji1703** [comment]
Indeed, happening after restart.

**Comment by HawkUser** [comment]
just noting, I tried:

Removing completely the ShellyForHass plugin and Homekit bridge, rebooting the host, adding ShellyForHass plugin from scratch, verifies the all shelly devices discovery successful.
At this point shelly devices working correctly from HA and as excepted, then I reinstall HomeKit Bridge plugin, just including the cover domain.
Then the control for the cover in the HomeKit worked just fine (like the HA), BUT I reboot the HA, since then the same behavior occurs. Still in the HA working just great BUT in HomeKit the cover has only "open or closed" status no percentage display and no percentage control

**Comment by PabloAriza** [comment]
Yes. You’re right.  I updated to the last version which as you all know requieres a automatic restart and everything related to covers is broken 

How can we proceed?

Regards

**Comment by HawkUser** [comment]
Hi,
I hope someone will pick the issue, it was fine before 0.2.0, so I tried to investigate, and there were a lot of changes specific in the cover.py in the 0.2.0, I guess they broke something.

**Comment by PabloAriza** [comment]
Morning @hakana 

What could be causing this issue? How can I help?

Regards

**Comment by HawkUser** [comment]
Hi @hakana

as far as i saw, most of the change happened in the 3rd beta of 0.2.0
i don't know if this helping, just keep in mind cover is working fine in HA directly, and the problem exists in the homekit only, BUT this started in 0.2.0, also the same shelly device working just fine in the new built-in integration or when switching to MQTT.

**Comment by HawkUser** [comment]
UPDATE:
I tried to debug homekit in both environments (ShellyForHass and Shelly built-in integration)
Shelly Built-in new integration:
2020-10-07 17:10:54 DEBUG (MainThread) [homeassistant.components.homekit.accessories] New_state: <state cover.shellyswitch25_68c63af92df5_roller_0=open; current_position=85, friendly_name=***********2DF5 roller 0, supported_features=15 @ 2020-10-07T17:10:53.625974+03:00>
ShellyForHass:
2020-10-07 16:17:15 DEBUG (MainThread) [homeassistant.components.homekit.accessories] New_state: <state cover.*************2df5=open; current_position=85, shelly_type=Shelly 2.5 (Roller), shelly_id=******2DF5, ip_address=192.168.***.***, room=LivingRoom, protocols=['CoAP-discovery', 'CoAP-msg', 'poll'], over_temp=0, has_firmware_update=False, cloud_status=connected, total_consumption=0.38 kWh, friendly_name=WestCover, supported_features=15 @ 2020-10-07T15:47:05.839585+03:00>

**Comment by HawkUser** [comment]
> Yes. You’re right. I updated to the last version which as you all know requieres a automatic restart and everything related to covers is broken
> 
> How can we proceed?
> 
> Regards

I believe i found a workaround:
A. I created a separate homekit bridge for the cover domain, and excluded from the original one.
B. try to reload the homekit integration that configured for the cover domain only 1-2 minutes after the HA completed the restart.

can yo

**Comment by hakana** [comment]
I will try to install homekit bridge and see if I can reproduce this.

**Comment by HawkUser** [comment]
Summarize my workaround:
A. create a separate HomeKit bridge include only cover Domain.
B. exclude a cover domain from the other homekit bridge

To handle server restarts, i added automation:
`- id: '123123123123123123'
  alias: Reload Homekit
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay: '120'
  - service: homekit.reload
    data: {}
  - service: persistent_notification.create
    data:
      message: Reload homekit successed
      title: Reload Homekit
  mode: single
`

**Comment by elazarit** [comment]
> Summarize my workaround:
> A. create a separate HomeKit bridge include only cover Domain.
> B. exclude a cover domain from the other homekit bridge
> 
> To handle server restarts, i added automation:
> `- id: '123123123123123123'
> alias: Reload Homekit
> description: ''
> trigger:
> 
>     * platform: homeassistant
>       event: start
>       condition: []
>       action:
> 
>     * delay: '120'
> 
>     * service: homekit.reload
>       data: {}
> 
>     * service: persistent_notification.create
>       data:
>       message: Reload homekit successed
>       title: Reload Homekit
>       mode: single
>       `

im having the same issue, tried your workaround and now it randomly working.
it looks like the roller randomly stops responding, and it only functional when i fully open or close.

**Comment by HawkUser** [comment]
> > Summarize my workaround:
> > A. create a separate HomeKit bridge include only cover Domain.
> > B. exclude a cover domain from the other homekit bridge
> > To handle server restarts, I added automation:
> > `- id: '123123123123123123'
> > alias: Reload Homekit
> > description: ''
> > trigger:
> > ```
> > * platform: homeassistant
> >   event: start
> >   condition: []
> >   action:
> > 
> > * delay: '120'
> > 
> > * service: homekit.reload
> >   data: {}
> > 
> > * service: persistent_notification.create
> >   data:
> >   message: Reload homekit successed
> >   title: Reload Homekit
> >   mode: single
> >   `
> > ```
> 
> I'm having the same issue, tried your workaround, and now it randomly working.
> it looks like the roller randomly stops responding, and it only functional when I fully open or close.

Hi,
did you separate the cover domain to a different homekit bridge?
how many covers do you have?

**Comment by lopesdasilva** [comment]
I see the same issue, and started after the 0.2.0.
How can we help?

**Comment by apmosss** [comment]
Any news on this?

**Comment by vinimaz** [comment]
I have the same problem, I think it started after I connected the Shellys to the Cloud. Controlling them with Alexa directly from the cloud works properly, but going through Home Assistant (I use it for iOS HomeKit support) brings up the described problem with the percentage.

**Comment by Dodoooh** [comment]
have exactly the same problem, 

in Home Assistant and on the Shelly interface itself everything works. but in HomeKit only works completely open or closed. 

But never connected it to Shelly Cloud.

**Comment by thechorba** [comment]
> have exactly the same problem,
> 
> in Home Assistant and on the Shelly interface itself everything works. but in HomeKit only works completely open or closed.
> 
> But never connected it to Shelly Cloud.

I have the same problem.
any solution?

**Comment by HawkUser** [comment]
> > have exactly the same problem,
> 
> > 
> 
> > in Home Assistant and on the Shelly interface itself everything works. but in HomeKit only works completely open or closed.
> 
> > 
> 
> > But never connected it to Shelly Cloud.
> 
> 
> 
> I have the same problem.
> 
> any solution? 
> 
> 
> 
> 
Not so sophisticated solution.. I added HomeKit integration restart 2 minutes after home assistant loaded.

**Comment by thechorba** [comment]
Thanks. 
Maybe you can tell me how to restart this service? 
תודה אחי 😀

**Comment by HawkUser** [comment]
> Thanks. 
> 
> Maybe you can tell me how to restart this service? 
> 
> תודה אחי 😀

Just add simple automation 

alias: Reload Homekit
description: ''
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay: '120'
  - service: homekit.reload
    data: {}
  - service: notify.mo
    data:
      message: Reload homekit successed
mode: single
