### ISSUE TITLE
Shelly not available after a couple of minutes

### ISSUE THREAD

**Issue by tantararin** [StyraHem/ShellyForHASS#45]
Hello:

After many tests, he decided to be sure if they can help me.
 I have installed hass.io version 96.5 and after many tests on the yaml with shelly discovery, without discovery, ... after a couple of minutes it appears as unavailable. 
Why is it? What do I do wrong? I've tried with Shelly 1 for now.
 a greeting

**Comment by hakana** [comment]
Something is wrong with the CoAP messages in the network. They use UDP multicast, maybe you have some settings in your router about igmp. You can also try enable the flag for Shelly in HASS config, 
igmp_fix = True 
and see if that helps.

**Comment by hakana** [comment]
Any news?

**Comment by tantararin** [comment]
Including in yaml "igmp_fix = true" everything works perfectly.
 Anyway I have commissioned a new modem / router. The supplied one of my internet company gives a lot of problems. I bought a free router.
Congratulations on your work. Perfect!!!!.

I have not been able to continue with my home automation project these days because of my work. Sorry for answering so late.

**Comment by hakana** [comment]
Great!

**Comment by carlos83cc** [comment]
> Including in yaml "igmp_fix = true" everything works perfectly.
>  Anyway I have commissioned a new modem / router. The supplied one of my internet company gives a lot of problems. I bought a free router.
> Congratulations on your work. Perfect!!!!.
> 
> I have not been able to continue with my home automation project these days because of my work. Sorry for answering so late.

Hi, but exactly where did you enter the change? Thanks

**Comment by chemelli74** [comment]
> Hi, but exactly where did you enter the change? Thanks

Please check documentation: https://github.com/StyraHem/ShellyForHASS/blob/master/README.md

If you need further support, open a new issue with all details ( HA version, plugin version, configuration, etc.).

Simone
