### ISSUE TITLE
[BUG] Remove of orphan devices 

### ISSUE THREAD

**Issue by HawkUser** [StyraHem/ShellyForHASS#452]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): N/A
- Home Assistant Core release with the issue: 0.115.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Asssistant HassIO

## Describe the bug
Shelly devices that been automatically added, cannot be removed, even if I remove all the sub-entities the devices stay orphan without any option to remove it, the only workaround is to uninstall the ShellyForHass and reinstall it.

## Steps to Reproduce
Described in the bug.

## Expected behavior
Devices that removed in Shelly Cloud should be automatic removed.

## Screenshots
N/A

## Traceback/Error logs
N/A

## Additional context
N/A

**Comment by hakana** [comment]
Entities are not removed as they can be temporarily unavailable. That the device can't be removed is more an issue for Home Assistant. I don't see how we can solve this in this plugin.

**Comment by energywave** [comment]
Hello, in reality there must be a way for plugins to add commands buttons for every device. ZHA is doing that and there is a "Remove device" button link that is doing what would be wonderful to be able to do with ShellyForHass: remove the device (and all sub entitites)!
Please check it out:
![image](https://user-images.githubusercontent.com/2051567/105651493-58656c00-5eb7-11eb-9fdd-ee31292bcb1a.png)

I'm also in the state of having host devices that I don't have anymore but I cannot remove from Home Assistant. That's a pity.

**Comment by ricarva** [comment]
I also would like to see an option to remove devices from the integration. I've had a device replaced by Shelly, and now have an orphan that I cannot delete from my Shellyforhass integration.

**Comment by kiila22** [comment]
foscam integration makes it easy to remove cameras
![image](https://user-images.githubusercontent.com/77587080/156198847-dd43f3da-18b6-4e1c-bd6a-b6d7efa81b93.png)

**Comment by hakana** [comment]
I will check this and try to add to ShellyForHass also.

**Comment by kiila22** [comment]
problem fixed
I switched to home Assistant for native integration and now Shelly pro2 also works :)

**Comment by hakana** [comment]
We will add this to next release.
