### ISSUE TITLE
[BUG] Shelly 1, Failed to call service switch/turn_on and off

### ISSUE THREAD

**Issue by mmkrysiak** [StyraHem/ShellyForHASS#457]
## Environment

- ShellyForHASS release with the issue:  1.6.0
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 0.115.5
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant on hassio RP

## Describe the bug
 Failed to call service switch/turn_on and off after click on entity button. external sensors and rrsi reported OK

## Steps to Reproduce
No idea

## Traceback/Error logs
Logger: homeassistant.components.websocket_api.http.connection.2853667408
Source: helpers/service.py:424
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:55:41 (2 occurrences)
Last logged: 18:55:42

'switch.shelly_shsw_1_e098068d0393'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 424, in entity_service_call
    entity_ids.remove(entity.entity_id)
KeyError: 'switch.shelly_shsw_1_e098068d0393'

```txt

```

**Comment by Partovic** [comment]
I've just started with Homeassistant and discovered my Shellys with this integration. Values will be displayed correctly (if I switch on/off a dimmer via Shelly app). 

But if i try to set a value via homeassistant I get: 

`Failed to call service light/turn_on.`

This happens with all of my Shelly devices (2.5, Dimmer 1).

**Comment by hakana** [comment]
The name of the service should be light.turn_on (with a dot, not dash)
Also make sure the device is configured as a light and not a switch. If it is a switch use switch.turn_on

The log is not related to this and should have been fixed in the latest beta release.
