### ISSUE TITLE
Possible bugfix for power consumption ?

### ISSUE THREAD

**Issue by nicolasvac** [StyraHem/ShellyForHASS#46]
https://github.com/StyraHem/ShellyForHASS/blob/d4ce33134c80357c3c7589198acef3a4aeb45c38/custom_components/shelly/sensor.py#L79

Shouldn't this be 'consumption' ?

**Comment by hakana** [comment]
Yes, I saw that too, will be fixed in next release

**Comment by hakana** [comment]
Fixed in latest release
