### ISSUE TITLE
[BUG] Multiple log entries : ERROR (FirmwareManage) [pyShelly] Error http GET: http://https://repo.shell

### ISSUE THREAD

**Issue by fatt0ny** [StyraHem/ShellyForHASS#477]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 0.118
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant/Docker (un-supervised)

## Describe the bug
Logs are filling up with the below errors

## Steps to Reproduce

  journalctl -p err..alert --since "1 day ago"

## Traceback/Error logs

   2020-11-22 01:38:02 ERROR (FirmwareManage) [pyShelly] Error http GET: http://https://repo.shell>
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     h.request(req.get_method(), req.selector, req.data, headers,
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     self._send_request(method, url, body, headers, encode_chunked)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     self.endheaders(body, encode_chunked=encode_chunked)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     self._send_output(message_body, encode_chunked=encode_chunked)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     self.send(msg)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/http/client.py", line 950, in send
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     self.connect()
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/http/client.py", line 1417, in connect
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     super().connect()
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/http/client.py", line 921, in connect
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     self.sock = self._create_connection(
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     raise err
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     sock.connect(sa)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]: TimeoutError: [Errno 110] Operation timed out
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:
Nov 22 01:38:02 Xserve 6b7568aaea15[585]: During handling of the above exception, another exception occurred:
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:
Nov 22 01:38:02 Xserve 6b7568aaea15[585]: Traceback (most recent call last):
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/site-packages/pyShelly/firmware.py", line 29, in _http_get
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     f = urllib.request.urlopen(url)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     return opener.open(url, data, timeout)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     response = self._open(req, data)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     result = self._call_chain(self.handle_open, protocol, protocol +
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     result = func(*args)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/urllib/request.py", line 1393, in https_open
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     return self.do_open(http.client.HTTPSConnection, req,
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:   File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
Nov 22 01:38:02 Xserve 6b7568aaea15[585]:     raise URLError(err)
Nov 22 01:38:02 Xserve 6b7568aaea15[585]: urllib.error.URLError: <urlopen error [Errno 110] Operation timed out>

```txt

```

**Comment by david-kalbermatten** [comment]
possibly duplicate of #460

**Comment by fatt0ny** [comment]
@david-kalbermatten Thanks, i missed that one

**Comment by fatt0ny** [comment]
duplicate of #460
