### ISSUE TITLE
[BUG] Shelly 3EM not working in latest beta

### ISSUE THREAD

**Issue by robinostlund** [StyraHem/ShellyForHASS#479]
## Environment

- ShellyForHASS release with the issue: Release 0.2.1 Beta 2
- Last working ShellyForHASS release (if known): Release 0.2.1 Beta 1
- Home Assistant Core release with the issue: 118.2
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Describe the bug
Shelly 3em current_consumption stopped working in latest beta version.

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
Strange, for me it works. Is it the sensor or attribute that is not working?

**Comment by hakana** [comment]
What firmware are you using on 3EM?

**Comment by ericfesta** [comment]
Same for me, the attribute current_consumption is now unknown on my Shelly 3EM (firmware 1.8.1) and on all my Shelly 1PM (firmware 1.8.3).

**Comment by tobbensoft** [comment]
Same situation here.. (multiple 3EM and 1PM)

3EM: Current version: 20200813-140420/v1.8.1@1b2a49be

1PM: Current version: 20200827-070450/v1.8.3@4a8bc427

**Comment by hakana** [comment]
No action, I will close this issue now.
