### ISSUE TITLE
[BUG] Shelly 3EM loses connection, every few Minutes

### ISSUE THREAD

**Issue by lebherz** [StyraHem/ShellyForHASS#480]
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known):  0.2.0
- Home Assistant Core release with the issue: 0.118.2
```txt
Version: 0.118.2
Installation Type: Home Assistant Container
Docker: true
Virtual Environment: false
Python Version: 3.8.6
Operating System Family: Linux
Operating System Version: 4.4.59+
CPU Architecture: x86_64
Timezone: Europe/Berlin
```

- Operating environment (Home Assistant/Supervised/Docker/venv): 
  Docker in Synology

## Describe the bug
I think since HA 0.118
I have interruptions/dropps at all shelly 3EM sensors. see pics below.

So I am not sure if this great Plugin have the problem

## Steps to Reproduce
all other Sensors are online and shows 

## Screenshots
![grafik](https://user-images.githubusercontent.com/11904931/99992416-9a3e3d00-2db6-11eb-9a43-fbcfb71c30fc.png)
Sometime.... ok...
![grafik](https://user-images.githubusercontent.com/11904931/99993602-2ef56a80-2db8-11eb-9a26-803c725d1308.png)
a view Minutes later:
![grafik](https://user-images.githubusercontent.com/11904931/99994006-bf33af80-2db8-11eb-8fd7-230750ff54d2.png)

## Traceback/Error logs
no Error in Log
```txt

```

**Comment by stevearmitage** [comment]
Can you access the device using a browser? I have been having intermittent issues with devices going offline and not available directly or ShellyForHASS. Shelly asked me to set static IP's in the devices rather than DHCP. I'm sill waiting, but the devices have been 100% available for the last 2 days....

**Comment by lebherz** [comment]
Hi @stevearmitage 
 
> Can you access the device using a browser?

yes I can:


> I have been having intermittent issues with devices going offline and not available directly or ShellyForHASS. Shelly asked me to set static IP's in the devices rather than DHCP. I'm sill waiting, but the devices have been 100% available for the last 2 days....

**Comment by lebherz** [comment]
Another interesting observation:
the entities : 
sensor.shelly_shem_3_xxxx_1_current
sensor.shelly_shem_3_xxxx_2_current
sensor.shelly_shem_3_xxxx_3_current 
shows all the time, without interruption values:
![grafik](https://user-images.githubusercontent.com/11904931/100157150-604e6300-2eaa-11eb-8595-b5e046eaeb64.png)
```txt
here phase1 
shelly_type: Shelly 3EM
shelly_id: xxx
ip_address: 192.168.x.y
voltage: 236 V
power_factor: 0.4
total_consumption: 308.19 kWh
total_returned: 0.0 kWh
unit_of_measurement: W
friendly_name: Shelly 3EM - xxx-1
icon: mdi:flash-outline
```

so maybe I can use this value? But why values here an not in the Entity-Values:
![grafik](https://user-images.githubusercontent.com/11904931/100158556-a60c2b00-2eac-11eb-99ac-047956a9ec2c.png)

**Comment by lebherz** [comment]
Thanks a lot! Your the best 👍 🥇
