### ISSUE TITLE
[BUG] Shelly 3EM, Shelly 1PM and Shelly Dimmer current_consumption unknown after updating to latest beta

### ISSUE THREAD

**Issue by ericfesta** [StyraHem/ShellyForHASS#482]
## Environment

- ShellyForHASS release with the issue: 0.2.1-b2
- Last working ShellyForHASS release (if known): 0.2.1-b1
- Home Assistant Core release with the issue: 0.118.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised

## Describe the bug

After updating to the latest beta the value of current_consumption on all my Shelly 3EM, Shelly 1PM and Shelly Dimmer is unknown. Shelly 3EM has firmware 1.8.1, Shelly 1PM has firmware 1.8.3 and Shelly Dimmer has firmware 1.8.5.

## Expected behavior

Showing current_consumption value on all Shelly devices.

## Traceback/Error logs

```txt

```

**Comment by scooper1** [comment]
+1 for this

**Comment by hakana** [comment]
Is it the sensor or attribute that is missing?

**Comment by scooper1** [comment]
some Attributes

**Comment by scooper1** [comment]
power unknown 
totals are zero for power

**Comment by ericfesta** [comment]
> Is it the sensor or attribute that is missing?

Attribute.

**Comment by scooper1** [comment]
a single reading of the current values appears to be put into the databases on startup of home assistant

**Comment by hakana** [comment]
Fixed in beta 3

**Comment by scooper1** [comment]
confirm fixed ok 👍 
thanks
