### ISSUE TITLE
[FR] Support for external switch on shelly 1 addon

### ISSUE THREAD

**Issue by mamrai1** [StyraHem/ShellyForHASS#485]
## Is your feature request related to a problem? Please describe.

  External magnetic sensor on shelly1 addon (yellow&black wire) is not shown as switch in HA.
On shelly wengui is shown and working as expected after enabling under settings - Enable external switch add-on

## Describe the solution you'd like

  new feature of shelly 1.9.0 firmware- Supoort of External switch add-on

**Comment by gerva3** [comment]
Hello!
Is there any solution for this?
Is it already possible to add the external switch into HA?

**Comment by nunogako** [comment]
Same problem here. Magnetic Sensor do not update on HA. On Shelly App works perfectly..
Someone found the solution?

**Comment by hakana** [comment]
It is implemented in latest beta (2)
