### ISSUE TITLE
Power Consumption not shown for Shelly Plug S

### ISSUE THREAD

**Issue by inforsgit** [StyraHem/ShellyForHASS#49]
I've recently added a Shelly Plug S to my network and it was picked up properly by ShellyForHASS and the relevant sensors added (I've got a global `sensors: - all` in my config). However, the sensor for power consumption does not appear. The same config is used for some Shelly 2.5s and a Shelly 2 and those correctly display the power consumption sensor.

If there's some troubleshooting or debug I can do to localise the problem please let me know.

**Comment by hakana** [comment]
Om running 10+ Shelly plug S and it working fine. Do you have latest version of HASS?

Check if you see some errors in log? You can alao go to http://shelly-ip/status and see if you can see the consumption there.

**Comment by inforsgit** [comment]
So original problem is definitely with the idiot (me) between the chair and the computer - my utmost apologies ;) I had `discovery: false` set in my config (on purpose) so of course it was not setting the new Shelly Plug S up properly because I had not specified it in my `devices:` list. Once I added it then it showed the consumption correctly.

However, what confused me was that even with `discovery: false` set in the configuration, sensors relating to the plug still appeared when it connected to the network. I'll open a second issue to track that so things are clean.
