### ISSUE TITLE
Shelly EM1 -  voltage is unavailable after upgrade - [BUG]

### ISSUE THREAD

**Issue by Vards0** [StyraHem/ShellyForHASS#491]
## Environment

- ShellyForHASS release 0.2.1.  Voltage on both channels is showing  as "unavailable" after upgrade.
- HACore 0.118.4
- Operating environment (Home Assistant/Rpi 4
- Shelly EM1 FW version:- 20201124-092817/v1.9.0@57ac4ad8

## Describe the bug

Voltage on both channels is showing  as "unavailable" after upgrade.  Voltage is enabled on the device.  
I cannot see voltage as a property of the current consumption sensor ....  This workaround was referred to in issue #444 but does not appear as a property on my sensor.

## Steps to Reproduce

  N/A

**Comment by Vards0** [comment]
Uninstalled and re-installed from scratch

**Comment by hakana** [comment]
Was it working in any earlier version?

**Comment by DeviousPenguin** [comment]
How did you fix this?
