### ISSUE TITLE
[BUG] shelly activates immediately and then freezes for 40 seconds

### ISSUE THREAD

**Issue by flavioporro** [StyraHem/ShellyForHASS#501]
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Traceback/Error logs

```txt

```

**Comment by flavioporro** [comment]
Hello
i ran the shellys and everything works but when i click to turn on eg. the light, it turns on immediately but the bulb changes state only after 30-40 seconds and in that period of time it cannot be turned off by hassio while it turns off immediately from the shelly app. I also have Merosses and those are immediate. it only happens with Shelly. Come to solve? thanks

**Comment by davidino** [comment]
I've experienced the same behaviour described by above. Any news or suggestion on how to troubleshoot ?
Thanks.

**Comment by hakana** [comment]
This is because you not have CoAP working in your network, please see Wiki for more information.

When CoAP not working it will see the change of status when polling, default interval is 30 sec.
