### ISSUE TITLE
[FR]Decreace the polling time for the Shelly RGBW2

### ISSUE THREAD

**Issue by Chaosflori25** [StyraHem/ShellyForHASS#506]
## Is your feature request related to a problem? Please describe.
Yes, my feature request is a bit related to this problem(https://github.com/StyraHem/ShellyForHASS/issues/347). It takes ages for Homeassistant to recognize that my Shelly RGBW2 has connected to the network. I have an old house in which my only possibility to power my shelly is to directly wire it to the switch. So power gets directly cut every time I use the switch. I want to turn my LED Strips on with a white color when I've turned them on(2-5s later is also ok.). So I increased the polling time of the plugin what worked for my Shelly dimmers but not for my RGBW2. I'm new to this plugin so I haven't tried MQTT or something like this. Any Ideas how I could decrease this time(takes about 3-5min)?

## Describe the solution you'd like

So I'd like to decrease the polling time of my RGBW2 so I can trigger the automation to switch colors quicker.
## Describe alternatives you've considered

The standard Homeassistant integration which did not work at all.
## Additional context

I'm using a Docker Container on my Nas, with Hassio(0.118.4) and the latest version of this plugin(0.2.1).

**Comment by hakana** [comment]
This is because of problems with your setup, when CoAP or mDns is working it finds the device in a few seconds.
