### ISSUE TITLE
[BUG] Coap Address already in use

### ISSUE THREAD

**Issue by asherungar** [StyraHem/ShellyForHASS#507]
## Environment

- ShellyForHASS release with the issue:  Release 0.2.2 Beta 1
- Last working ShellyForHASS release (if known): N/A - I just installed latest after a long time 
- Home Assistant Core release with the issue: 2020.12.2
- Operating environment (Home Assistant/Supervised/Docker/venv): venv

## Describe the bug

ShellyForHASS cannot connect to the shelly devices via Coap, I'm getting error that the address is already in use.
but - no other process on the machine is using the port, if I run:
lsof -t -i:5683

I only get back the pid of the python process running the home assistant in venv.

## Expected behavior

Coap connection instead of mdns,polling for instant updates

## Traceback/Error logs

```txt
Traceback (most recent call last):
  File "/Users/asherungar/.homeassistant/custom_components/shelly/__init__.py", line 199, in start_up
    pys.start()
  File "/Users/asherungar/homeassistant/lib/python3.8/site-packages/pyShelly/__init__.py", line 147, in start
    self._coap.start()
  File "/Users/asherungar/homeassistant/lib/python3.8/site-packages/pyShelly/coap.py", line 27, in start
    self._init_socket()
  File "/Users/asherungar/homeassistant/lib/python3.8/site-packages/pyShelly/coap.py", line 40, in _init_socket
    sock.bind((self._root.bind_ip, COAP_PORT))
OSError: [Errno 48] Address already in use
```

**Comment by hakana** [comment]
Have you restarted HA?

**Comment by asherungar** [comment]
> Have you restarted HA?

Yes many times, also killed the python process itself and as soon as HA comes up the error is shown. When HA is shutdown no other process is shown to use the port.

**Comment by michelwilson** [comment]
I seem to have a similar issue, after upgrading to 0.2.1 all my devices show as being connected using mDns, poll, and updates to the state are only shown after a long long time. The COAP port is shown as being in use by the Python process, and I don't see the "Address already in use" error in my logs (but this could be a logging setting being different, not sure how to change this).
What can I do to provide more debugging info?

**Comment by Yernike** [comment]
I have the same problem, any solution please?

**Comment by michelwilson** [comment]
For me the solution was to explicitly specify the ip address on which to bind, in `configuration.yaml`:
```
shelly:
  discovery: true
  host_ip: 1.2.3.4
```

**Comment by hakana** [comment]
I have made a change that will be available in 0.2.2 Beta 3 that will be released shortly.

**Comment by hakana** [comment]
Beta 3 released, I hope this will be solved.. Please help me to verify!

**Comment by michelwilson** [comment]
What did you change exactly, and how can I verify? Should CoAP now work without explicitly specifying the address to bind to?

**Comment by hakana** [comment]
I has change the code where the socket bind for listening to CoAP messages. Now it binds to the address 0.0.0.0 and that works better when I tested.
