### ISSUE TITLE
[BUG] Attribute option...

### ISSUE THREAD

**Issue by mycanaletto** [StyraHem/ShellyForHASS#508]
Hello !
When I go in the options to choose attributes, I never have the same choices that are presented...

I reload and it's yet another mix of choices, has anyone ever had that?

Merci

**Comment by hakana** [comment]
The attributes is updated on multiple steps

**Comment by mycanaletto** [comment]
Yes on several pages and then it's the sensors, I'm talking about the attribute pages.

**Comment by wauswaus** [comment]
I have noticed this as well.
Also sometimes just a tickbox is displayed without text:
![afbeelding](https://user-images.githubusercontent.com/70056029/106170191-846f3e80-6190-11eb-8705-dd5e6c490199.png)

**Comment by hakana** [comment]
Working ok when I tested in the latest version 0.2.2 - Beta 2.

I close this issue, please let me know if still a problem.
