### ISSUE TITLE
New device on network adds additional sensors even with discovery off

### ISSUE THREAD

**Issue by inforsgit** [StyraHem/ShellyForHASS#51]
This issue caused some misleading behaviour (which originally caused me to open Issue #49 ). Although everything there is working properly, it still exposed what I believe is a slight bug.

My configuration.yaml is as follows:

```
shelly:
  discovery: false
  additional_information: true
  sensors:
    - all
  devices:
    - id:.....
```
i.e. Discovery is off and I have to manually add new devices.

With this configuration I had expected that adding a new Shelly device to the network (in this case a Shelly Plug S) would be completely invisible in Home Assistant until I specified it in the configuration.yaml. However, after configuring the device in the Shelly app, the following sensors (device ID replaced with fffff) appeared in the HA states:

```
- sensor.shelly_shplg_s_ffffff_cloud_status_attr
- sensor.shelly_shplg_s_ffffff_device_temp_attr
- sensor.shelly_shplg_s_ffffff_mqtt_connected_attr
- sensor.shelly_shplg_s_ffffff_over_temp_attr
- sensor.shelly_shplg_s_ffffff_rssi_attr
- sensor.shelly_shplg_s_ffffff_uptime_attr
```

In my opinion these should not be created because Discovery is OFF. No other entries were created (e.g. power consumption or the switch entity).

**Comment by hakana** [comment]
Are you get them back if you restart Home Assistant? Can you see any values of the sensors?

**Comment by inforsgit** [comment]
I didn't try a restart I'm afraid but I have another new plug that I can try and do the same thing with. Certainly the sensors were producing plausible values.

I believe that to reproduce (in case you want to check) the following steps should be sufficient:

1. Set `discovery: false`
2. Setup new device in Shelly App
3. Check sensors in Home Assistant States

**Comment by hakana** [comment]
I found it, will be fixed in next release. I will release it today or tomorrow.

**Comment by inforsgit** [comment]
Great, thank you! Not a big deal but always good to stamp out the bugs ;) Cheers!

**Comment by hakana** [comment]
Fixed in latest release
