### ISSUE TITLE
[BUG] Shelly 1L second channel / switch not available in beta 0.2.2.beta1

### ISSUE THREAD

**Issue by kongo09** [StyraHem/ShellyForHASS#518]
## Environment

- ShellyForHASS release with the issue: 0.2.2.beta.1
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: core-2021.1.5
- Operating environment (Home Assistant/Supervised/Docker/venv): supervisor-2021.01.7

## Describe the bug
The Shelly 1L gets discovered. SW1 of the device is attached to the relay. SW2 is detached. SW1 is represented by a binary sensor, but SW2 is not shown.

![image](https://user-images.githubusercontent.com/640121/105852943-674a3c80-5fe5-11eb-92a7-dd02a38904ab.png)

Switch state is enabled in the sensor settings:

![image](https://user-images.githubusercontent.com/640121/105852974-74672b80-5fe5-11eb-9575-1f57ef43e5c1.png)

## Steps to Reproduce
Adopt a Shelly 1L and observe the sensors.

## Expected behavior
I would expect two sensor, one for each input. That's the behaviour of the built-in Shelly integration as well.

## Screenshots
see above

## Traceback/Error logs
none

## Additional context
none

**Comment by hakana** [comment]
Ok, I see. Yes, it is a bug and will be fixed in the next release.

**Comment by kongo09** [comment]
I see 1L mentioned in beta 2 - does that refer to this bug?

**Comment by hakana** [comment]
Yes this issue should be fixed in beta 2.

**Comment by kongo09** [comment]
I can confirm this is working now. Thanks so much for the great effort!

**Comment by hakana** [comment]
Great!
