### ISSUE TITLE
[BUG] Error in loop Debug server

### ISSUE THREAD

**Issue by FeromonDE** [StyraHem/ShellyForHASS#526]
## Environment

- ShellyForHASS release with the issue: 0.2.2-b3
- Last working ShellyForHASS release (if known): 0.2.1
- Home Assistant Core release with the issue: 2021.3.0
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

Аfter restarting the integration from integration UI, the log is filled with errors.

## Steps to Reproduce

Restart the integration from integration UI. Check home-assistant.log

## Traceback/Error logs

```2021-03-04 10:47:41 ERROR (Debug server) [pyShelly] Error in loop Debug server
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/loop.py", line 36, in _start_loop
    self.loop()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/debug.py", line 89, in loop
    connection, client_address = self._socket.accept()
AttributeError: 'NoneType' object has no attribute 'accept'
```

**Comment by scooper1** [comment]
this is quite nasty when it occurs - appears to eat memory  leading to lockout of home assistant
