### ISSUE TITLE
[BUG] binary_sensor defaults to switch icon in Lovelace interface

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#529]
## Environment

- ShellyForHASS release with the issue: 0.2.2.beta.3
- Last working ShellyForHASS release (if known): not known
- Home Assistant Core release with the issue: 2021.3.2
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant Core

## Describe the bug

I added the three inputs of the shelly i3 as switches, but they default to a switch icon in Lovelace (mdi:light-switch)

But my inputs are not always _fysical switches_. I use the i3 to make all kinds of sensors smart:
For this use I change the device_class to door, lock, there are plenty types:
https://www.home-assistant.io/integrations/binary_sensor/#device-class
After changing the `device_class` the states are right for their type (open/close, wet/dry, locked/unlocked)
However the icon does not represent the `device_class` and remains a 'switch'.

I can change the icon back to a door, lock, etc but In that case we lose the ability to have a "dynamic icon", that changes to show the state of the `binary_sensor`.

## Steps to Reproduce

- Add a shelly i3 to your setup
- Activate the `binary_sensor` entities:
```
  sensors:
    - switch
```
- Add customisation for `device_class: door`

## Expected behavior

Icon of the entity changes to a door that shows open or closed state

```
mdi:door-closed
mdi:door-open
```

## Traceback/Error logs

No related error logs, I assume that the switch icon is a feature, however it limits the use of the `binary_sensor` abilities.
```txt

```

**Comment by hakana** [comment]
Try to set the icon to empty and see if that works. I will look into this also but right now I don't have access to the system.

**Comment by filmgarage** [comment]
I am not sure if I understand you correctly with setting the icon to 'empty'...
Like the following in the customize section?
```
homeassistent:
  customize:
    binary_sensor.some_shelly_switch
      device_class: door
      icon:
```
I tried this an it has no effect, but maybe I should try something else?

**Comment by filmgarage** [comment]
Sorry, it took some time to update, working now with the above code!
