### ISSUE TITLE
Add support for Shelly Flood

### ISSUE THREAD

**Issue by inforsgit** [StyraHem/ShellyForHASS#53]
The first Shelly Flood flood/rain sensors are now being delivered. Would it be possible to add support for them to ShellyForHASS?

I'm afraid I don't see any documentation for it in the Shelly CoAP API but I wanted to raise this as a placeholder for when it's completely documented.

**Comment by hakana** [comment]
Yes the CoAP doc is a bit behind but we can solve it most of the times anyway.

If you have a sensor you can help adding them by running a python script and send me the output for the flood sensor.

https://github.com/StyraHem/ShellyForHASS/blob/master/util/test.py

**Comment by inforsgit** [comment]
Sure thing - I'll get it set up later and let you know. Thanks!!

**Comment by hakana** [comment]
Also Shelly dimmer is added
