### ISSUE TITLE
Shelly Light

### ISSUE THREAD

**Issue by max-rh** [StyraHem/ShellyForHASS#55]
Hi,
I would like to thank you for just a great integration for Shelly in HA.
I have a an issue with the latest update 0.18; the status sensors is cool addition but unfortunately if the shelly switch is defined as light the sensor always show as off, dont know if this is  bug in this release or i have something wrong.

Thanks alot

**Comment by hakana** [comment]
Can you share you shelly part in config.yaml?

**Comment by max-rh** [comment]
Sure: here is my Shelly config:

`shelly:
  discovery: true
  sensors:
    - all
  devices:
    - id: XXXXX
      light_switch: true
      name: Entrance Light
    - id: XXXXX
      light_switch: true
      name: Kitchen Entrance Light
    - id: XXXXX
      name: First Floor UHS Pump
    - id: XXXXX-1
      name: Boiler
    - id: XXXXX-2
      name: Ground Floor UHS Pump
    - id: XXXXX
      name: Main Ref.
    - id: E5C8A7
      name: Secondary Ref.`

and i noticed that the status is not consistant, as you can see here it shows one of the lights are off
![image](https://user-images.githubusercontent.com/25219094/63647403-7a3e4a80-c729-11e9-8816-32d1e42c3f19.png)
but actually both lights are off:
![image](https://user-images.githubusercontent.com/25219094/63647410-9346fb80-c729-11e9-9a66-ed15d97e6efe.png)

Thanks for your help :)

**Comment by max-rh** [comment]
and plz note that once I updated to 0.18 I lost all automation related to the shellies cause once updated it changed all the entities id and replaced them with duplication, for example, the `light.shelly_shsw_1_XXXXX` was replaced with `light.shelly_shsw_1_XXXXX_2`; perhaps i should open a separate issue for this?

**Comment by hakana** [comment]
The switch state show the state of the physical switch not the lamp state.

**Comment by max-rh** [comment]
Ah, ok, so this means that the load is actually turned off but the physical button attached to the SW input is actually high ?, correct ?

**Comment by hakana** [comment]
Yes, exactly!

**Comment by max-rh** [comment]
Thanks sir for the clarification.
And fix for the naming scheme issue i mentioned earlier ?

Would you like me to open a new issue for it to keep it opened ?

**Comment by hakana** [comment]
Yes, I will do a new release in some hours

**Comment by max-rh** [comment]
Thanks, for a great integration :)
