### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mclaudiopt** [StyraHem/ShellyForHASS#56]
hi there
i installed but cannot get it to work
on monster card only appears this
![image](https://user-images.githubusercontent.com/48178294/63642091-956d7380-c6b1-11e9-9373-93b479a9e3e9.png)

altough i have several devices

**Comment by hakana** [comment]
What os, hardware and HA setup do you have?

**Comment by mclaudiopt** [comment]
hassio
NUC intel image installed
but will follow #52
