### ISSUE TITLE
[BUG] Problem with utility_meter / FW Update

### ISSUE THREAD

**Issue by Alex-joomla** [StyraHem/ShellyForHASS#580]
## Environment

- ShellyForHASS release with the issue: 0.2.3.beta.2
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: core-2021.9.7
- Operating environment (Home Assistant/Supervised/Docker/venv):  HASS OS

## Describe the bug

Every now and then (in this case during a fw update) Shelly energy meters report a negative or a zero value. This causes utility_meters to fail. 

here is the long story:
[https://github.com/home-assistant/core/issues/56005](url)

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
I close this as it is an old issue and I can't reproduce this. Please reopen if still a problem.
