### ISSUE TITLE
Shelly 2.5 in roller mode is "clicking" the relays twice

### ISSUE THREAD

**Issue by PMPoulsen** [StyraHem/ShellyForHASS#583]
Just integrated a Shelly 2.5 in blind mode for my projector screen.
I noticed that when I use the Shelly For Hass integration I can hear and "see" (by movement) the output relay "clicking" first quickly On-Off then On for the direction I decided. This is not happening when i use embedded webserver in the 2.5 for controlling movement, here there is only 1 "click".
The first set of "on-off" is in the correct direction of movement though so not a big issue but still not expected.
this issue is happening for both directions of movement (up / down)

**Comment by hakana** [comment]
I can't reproduce this, is this still a problem?

**Comment by PMPoulsen** [comment]
Sorry for not closing this report before, but it has dissapeared. I have moved the relay position, not sure if that did the trick though.
