### ISSUE TITLE
Support for Shelly Plus 1PM

### ISSUE THREAD

**Issue by SinnoTech** [StyraHem/ShellyForHASS#589]
## Is your feature request related to a problem? Please describe.

Shelly plus 1pm does not discover

## Describe the solution you'd like

Shelly plus 1pm to be discovered. 

## Describe alternatives you've considered

No alternative

**Comment by hakana** [comment]
Will be added in the next release coming any day.

**Comment by nick9one1** [comment]
Any update on the next release?

**Comment by hakana** [comment]
Yes, everything is ready. Only need some time to package it to a release.

**Comment by maryjam01** [comment]
What is your plan to pack a release? ;-)

**Comment by nick9one1** [comment]
It's in the beta version :)

**Comment by SinnoTech** [comment]
How do I change my shellyforhass to use your beta version?

**Comment by SinnoTech** [comment]
I have the beta version installed but it does not discover the shelly plus 1pm?

**Comment by hakana** [comment]
@SinnoTech Are you running HA on same network?

Are you using docker?

**Comment by SinnoTech** [comment]
> @SinnoTech Are you running HA on same network?
> 
> 
> 
> Are you using docker?

Hey

I'm running HA on an HA blue on the same network as all my other shellies.

Set the shelly plus 1pm up in the same way as the older shellies (one, plug s, 3em, dimmer2). 

Is there a setting i need set on the shelly?

supervisor-2021.10.8
core-2021.11.5
Home Assistant OS 6.6

HACS:
Integration version:	1.18.0
Frontend version:	20211128181314

ShellyForHASS:
0.3.1.beta.2
![image](https://user-images.githubusercontent.com/74432416/144671052-b13e52f2-26df-4dec-8c5b-72b6958455a2.png)

**Comment by SinnoTech** [comment]
![image](https://user-images.githubusercontent.com/74432416/144671093-615916ca-daac-4a52-aa35-5605648503c8.png)

**Comment by SinnoTech** [comment]
![image](https://user-images.githubusercontent.com/74432416/144671120-2bc2722d-9cc8-416a-8a7f-48bd36e23c08.png)

**Comment by SinnoTech** [comment]
![image](https://user-images.githubusercontent.com/74432416/144671150-81e56c50-0857-4bfc-bc47-ca0d4aeb3eb6.png)

**Comment by SinnoTech** [comment]
![image](https://user-images.githubusercontent.com/74432416/144671177-b09fee51-f0b2-4e46-9c2c-d0802982ea57.png)

**Comment by SinnoTech** [comment]
![image](https://user-images.githubusercontent.com/74432416/144671202-97008fb5-d731-4da0-8b17-4618a7dc9087.png)

**Comment by hakana** [comment]
Plus and Pro devices is discovered using mDns. Can you test if you see the mDns packages using tcpdump on HA instance?

You can also test to use the mqtt by config the shelly mqtt settings.

**Comment by SinnoTech** [comment]
Okey i ran tcpdump and between a bunch of screenshots to try and catch something (A LOT of network traffic!) i found this for the shelly plus 1pm:

![image](https://user-images.githubusercontent.com/74432416/144700232-80e1e7b9-ecb8-45a3-a3a5-f11645b7d790.png)

**Comment by SinnoTech** [comment]
I have also configured mqtt on the shelly plus 1pm. and it pics up on my mosquitto server. Should I somehow add it to shellyForHASS in order to display it as a device?

mqtt server is also set up in the shellyForHASS dashboard.

**Comment by SinnoTech** [comment]
I still have an issue with the plus 1pm and also my pro4pm not discovering. 

Any more info i can provide to find a solution?
