### ISSUE TITLE
Entity ID renamed to old name after update the component via HACS

### ISSUE THREAD

**Issue by kolossboss** [StyraHem/ShellyForHASS#59]
I renamed the shellys entity_id to something more readable.
But after the last two updates, the shellys entity_id changed to the old name and breaks my configuration. 

Is this a normal behavior?

Thanks a lot

**Comment by Betoniara** [comment]
the same for me, _2 is added to the entity name

**Comment by hakana** [comment]
I did a change in release 0.0.18 that mess up the unique id of the shelly entities. Use entity register and remove all shelly entities and reboot. I'm sorry for this :(

**Comment by mclaudiopt** [comment]
hi there @hakana i am now online for tviewer

**Comment by kolossboss** [comment]
@hakana
Thanks for reply. 
But this also happend to me with update from 0.0.18 to 0.0.19!
Is this also related to the issue in 0.0.18?

**Comment by hakana** [comment]
Yes, the problem was in 0.0.18 so as I change it back in 0.0.19. I did that so the upgrade from 0.0.15 to 0.0.19 will work. I removed the 0.0.18 release and hope not so many installed it.

**Comment by hakana** [comment]
@mclaudiopt Yes I can check now, can you send email to hakan(at)tarra.se
