### ISSUE TITLE
Bad custom name

### ISSUE THREAD

**Issue by bigboban** [StyraHem/ShellyForHASS#60]
This is my config:

```
shelly:
  discovery: false
  version: true #add version sensor
  sensors:
    - all
  devices:      #devices to be added
    - id: 5BxxE0
      light_switch: true
      entity_id: shelly_switch_wc
```

And this is result of entity names:

```
sensor.shelly_shelly_switch_wc_cloud_status_attr
light.shelly_shsw_1_5bxxe0
```

**All entities except main switch/light have correct (customized) name but only "main" entity has still generated name -> BUG!**

Second thing is customized entity names start with word "shelly" but this is not blocker for me, i will remove "my" shelly prefix and it will not be doubled in entity name.

**Comment by hakana** [comment]
Fixed (duplicate)
Yes, or you can set the id_prefix to empty to remove the in prefix for all Shellies.
