### ISSUE TITLE
[BUG] Firmware Update breaks statistics (utility meter...)

### ISSUE THREAD

**Issue by Alex-joomla** [StyraHem/ShellyForHASS#605]
## Environment

- ShellyForHASS release with the issue: 0.2.3.beta.2
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 2021.11.3
- Operating environment (Home Assistant/Supervised/Docker/venv):  HASSIO

## Describe the bug

  Every Firmwareupdate and occasionally on device restarts the utility meter statistics fails because of a corrupt database entry (See screenshots). There is a thread @ utility meter group which describes the Problem and how to fix this. Please fix it, otherwise all long term Energy metering is impossible. In the screenshots you see the time, wenn the shelly 3em got updated.
The negative Value must not be there.
`totalverbrauch.haus` is a template sensor which adds the three phases to one value

## Screenshots

<img width="1785" alt="Bildschirmfoto 2021-11-14 um 20 44 16" src="https://user-images.githubusercontent.com/32268233/141850318-9d80b932-c812-43f1-a4ea-31069e40f60d.png">
<img width="1790" alt="Bildschirmfoto 2021-11-14 um 20 42 54" src="https://user-images.githubusercontent.com/32268233/141850321-a32369d6-2423-4143-85ad-c0c3f4e92aa5.png">
<img width="1788" alt="Bildschirmfoto 2021-11-14 um 20 42 25" src="https://user-images.githubusercontent.com/32268233/141850325-548e79f8-1889-4b9f-ae32-9a0dc298c149.png">
<img width="1740" alt="Bildschirmfoto 2021-11-14 um 20 37 35" src="https://user-images.githubusercontent.com/32268233/141850329-64866a2d-0899-41ae-a20e-9e46331309f8.png">

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
Please enter a URL to the specific fix
