### ISSUE TITLE
[FR] Use full resolution of the UNI temperature measurements

### ISSUE THREAD

**Issue by pbix** [StyraHem/ShellyForHASS#609]
## Is your feature request related to a problem? Please describe.
  DS18B20 Temperature sensors interfaced with the UNI do not include all the resolution available when read by HA.

## Describe the solution you'd like
  In the web page of the device we can see the resolution of the temperature sensors reported with 0.1 degF resolution.  However, within HA the sensors appear with not more than 1 degF resolution.  Sometimes it appears that the resolution is not more than +/-2 degF.  The solution I would like would import temperature measurements with all the resolution that is available in the sensor.

## Describe alternatives you've considered
  I have not thought of any alternative solution to this issue.

## Additional context
  I am using the DS18B20 sensors supported by the device.  The device also supports DHT22 sensors but I have not tested them.  This issue is related to [https://github.com/StyraHem/ShellyForHASS/issues/334](url)

I am pasting a screen shot of the UNI web interface for reference below which shows the temperature measurements.  Up to three of these measurements will be displayed depending on how many sensors are connected.

![image](https://user-images.githubusercontent.com/289729/143249955-e1bbd8a1-34f2-477c-b542-7e92980ef1a8.png)

**Comment by hakana** [comment]
You need to change the settings for the plugin to show 1 decimal for temperature. Install latest beta and you can easy change this settings in the gui, select Shelly in the sidebar.

**Comment by pbix** [comment]
Using the integration v0.3.2 I was able to access settings under the Shelly sidebar to show 1 decimal for temperature.  Thanks for your support.
