### ISSUE TITLE
Shelly forHass not starting due change in 2021.12 homeassistant.util.get_local_ip() removed

### ISSUE THREAD

**Issue by martin82private** [StyraHem/ShellyForHASS#612]
## Environment

- ShellyForHASS release with the issue:  2021.12
- Last working ShellyForHASS release (if known): 2021.11
- Home Assistant Core release with the issue: 2021.12
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Traceback/Error logs

```txt

```

## Additional context
<!--
--

>

**Comment by martin82private** [comment]
sorry can t edit the previos post:
homeassistant.util.get_local_ip() removed
Removed util.get_local_ip() in favor of components.network.async_get_source_ip().

Previous implementation was determining local IP based on the routing versus a fixed public ip “8.8.8.8”. New function instead allows to choice the destination and determine local_ip based on the source interface needed to get there.
![Screenshot 2021-12-03 231108](https://user-images.githubusercontent.com/53186904/144679892-79bd7413-7357-4349-923d-791442c007b1.png)

**Comment by monsterciattolo** [comment]
I have the same behavior and Shelly EM is not recognized

**Comment by fishbone-git** [comment]
see pull request #613

**Comment by monsterciattolo** [comment]
Great! When will the fix be release?

**Comment by fishbone-git** [comment]
that's up to the man dev.  But, these don't need to be built.  You can make the same edits in your own setup, config/custom_components/shelly/__init.py, if that helps. It just two lines in the file, then you reboot.  click on the pull request link above to get the details if you want to try that.

**Comment by GertJanArts** [comment]
Works. Thanks

**Comment by HFeenstra** [comment]
> that's up to the man dev. But, these don't need to be built. You can make the same edits in your own setup, config/custom_components/shelly/__init.py, if that helps. It just two lines in the file, then you reboot. click on the pull request link above to get the details if you want to try that.

The steps in the pull request are not visible, other words I can’t find the lines I have to change. Can you please share the steps?

**Comment by monsterciattolo** [comment]
I installed the 0.3.1 beta 3 and works fine with 2012.12.0

**Comment by phil-schneider** [comment]
When will there ne a public Release? It's 8 days since it has been reported and now home assistant Release has sadly broken this Integration.
Fixing by editing the file if a Quick win for All devs, but not for the mainstream
It would be really nice and helpfull if you could create a Release.

**Comment by HFeenstra** [comment]
> I installed the 0.3.1 beta 3 and works fine with 2012.12.0

I can confirm this works for now! Thank you

**Comment by hakana** [comment]
I have released 0.3.1 public release now

**Comment by robertop13es** [comment]
I have installed a new version right now, and it's working fine

Best regards

**Comment by hakana** [comment]
0.3.1 is now released as public
