### ISSUE TITLE
[FR] Convert firmware update switches to new button entities

### ISSUE THREAD

**Issue by kongo09** [StyraHem/ShellyForHASS#617]
## Is your feature request related to a problem? Please describe.

Currently, the integration provides switches to initiate firmware updates. However, this is not really a switch action.

## Describe the solution you'd like

Starting from HA 2021.12 a new button entity is provided. This reflects the action for a firmware update better.

## Describe alternatives you've considered

The current switch solution works.

## Additional context

https://www.home-assistant.io/blog/2021/12/11/release-202112/#the-button-entity

**Comment by iw6ovz** [comment]
The component doesn't work!

**Comment by kongo09** [comment]
> The component doesn't work!

It works very well. There is a fix needed for the latest 2021.12 but that's already addressed in the upcoming release. Try the beta of you're stuck on 2021.12

**Comment by hakana** [comment]
Release 0.3.1 public is available now!

**Comment by kongo09** [comment]
This has not been addressed in 0.3.1

You probably confused the off-topic discussion that the component wouldn't work with the initial request of converting the switch entity to a (new) button entity for firmware upgrades?

**Comment by iw6ovz** [comment]
It's ok Now!

**Comment by kongo09** [comment]
> It's ok Now!

You are off-topic here

This feature request is about the firmware update switch:

![image](https://user-images.githubusercontent.com/640121/145716327-d0d29833-98de-47e5-8bf3-1d995e0aa06c.png)

**Comment by hakana** [comment]
I understand and will look on it asap
