### ISSUE TITLE
[BUG] new shelly sidebar items are not readable in dark theme

### ISSUE THREAD

**Issue by kongo09** [StyraHem/ShellyForHASS#620]
## Environment

- ShellyForHASS release with the issue: 0.3.1
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 2021.12
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised
- Dark Theme in Lovelace!

## Describe the bug

Shelly sidebar cards are not readable

![image](https://user-images.githubusercontent.com/640121/145716263-a54a376f-64e7-4767-a72d-6e0df3521948.png)

## Expected behavior

background color should reflect the background color of the theme

## Traceback/Error logs

```txt

```

**Comment by julian100004** [comment]
Can confirm this

**Comment by emufan** [comment]
Confirm as well.

And did not find to disable the menu entry. How to do this?
