### ISSUE TITLE
[BUG] After switching to stable 0.3.1 "voltage" entities of EMs are unavailable

### ISSUE THREAD

**Issue by fuzzybear62** [StyraHem/ShellyForHASS#622]
## Environment

- ShellyForHASS release with the issue: 0.3.1
- Last working ShellyForHASS release (if known): 0.2.2
- Home Assistant Core release with the issue: core-2021.12.0
- Operating environment (Home Assistant/Supervised/Docker/venv): supervisor-2021.12.1

## Traceback/Error logs

```txt

```

**Comment by vkcvkcvkc** [comment]
Can confirm this!
![Kuvatõmmis 2021-12-13 180515](https://user-images.githubusercontent.com/9640436/145846482-e31b3efa-457e-40eb-92fb-2b18a40919da.png)

**Comment by andrebbruno** [comment]
> Can confirm this! ![Kuvatõmmis 2021-12-13 180515](https://user-images.githubusercontent.com/9640436/145846482-e31b3efa-457e-40eb-92fb-2b18a40919da.png)

Same here!

**Comment by naked-head** [comment]
Just updated to 0.3.2, same problem: no voltage on EM and 4 Pro but working on 2.5

**Comment by hakana** [comment]
Yes, I have not been able to look on that yet...

**Comment by monsterciattolo** [comment]
The same on Shelly 2.5: voltage sensor not available

**Comment by hakana** [comment]
I have found the problem and working on a new version with a fix.
