### ISSUE TITLE
id with name 041702 is not valid

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#63]
One of my Shellies has the ID: 041702
Somehow it will not be recognised in my config when I type it like this:

`  - id: 041702`

However, if I add quotes it gets configured correctly....

`  - id: "041702"`

Any idea what is going on?

**Comment by hakana** [comment]
I guess HA think it is a number and remove the 0 in the beginning and I do a text compare in the src. I guess I can fix it by add zeroes if shorter then 6 digits.

**Comment by filmgarage** [comment]
That makes sense. Must be what is going on... Thanks!

**Comment by filmgarage** [comment]
I look through my config and this one works fine:

`- id: 008001`

Without quotes that is...

**Comment by hakana** [comment]
I will have a look

**Comment by hakana** [comment]
0123456 is read as a octet number in Home Assistant. I have updated the readme examples to have the "" around the id.
