### ISSUE TITLE
[BUG] config.yaml > "light_switch: true" being ignored

### ISSUE THREAD

**Issue by mossc001** [StyraHem/ShellyForHASS#633]
## Environment

- ShellyForHASS release with the issue: 3.x onwards
- Last working ShellyForHASS release (if known): 2.2
- Home Assistant Core release with the issue: 2012.12.x
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised

## Describe the bug

Override settings written into the config.yaml are being ignored; Shelly 1's and 2.5's which were configured as "light_switch" are now configured as a standard switch, and the configuration seems to be ignored.

`
shelly:
  sensors:
    - all
  devices:  #configure devices
    - id: "e0980696####"
      light_switch: true  #add this switch as a light
    - id: "e0980696####"
      light_switch: true  #add this switch as a light
    - id: "68c63af####-1"
      light_switch: true  #add this switch as a light
`

## Steps to Reproduce

Update to Shelly 3.x and reboot.

## Expected behavior

The device/switch is recognised as a light.

## Screenshots

Screenshots attached.

![2021-12-17 08_28_42-Configuration - Home Assistant](https://user-images.githubusercontent.com/46225420/146515904-0b72252d-c56a-484a-accc-8e71f46e4c0a.png)

![2021-12-17 08_35_37-File editor - Home Assistant](https://user-images.githubusercontent.com/46225420/146515923-2bb0dcdf-76da-4a22-bb03-9ecf13714dff.png)

**Comment by nanni85** [comment]
Same problem for me with 0.3.3

**Comment by nanni85** [comment]
@mossc001 you have solved? i have lost all automations with this bug...

**Comment by mossc001** [comment]
@nanni85 , same, every automation relating to the light entity is not working. I tried everything, upper case entity ID, lower case, changing some settings around, but it still does not work.

I cannot see any errors either. How about you?

**Comment by nanni85** [comment]
Hello, @hakana 
can you help us?

**Comment by b2eboy** [comment]
Same here. Lost all controls and related automations.

**Comment by mossc001** [comment]
@nanni85 & @b2eboy , any success or have you changed your automations now?

**Comment by b2eboy** [comment]
I was not able to make it work. There's too many shellies on my network to change it manually everywhere.
I downgraded back to old version until it will be more clear based on this discussion.

**Comment by jsole** [comment]
Is there any work arround yet? Should I remove the yaml configuration to get the lights automatically? Thanks!

**Comment by hakana** [comment]
It is maintained but my time is limited so I'm trying to fix things as fast as possible. I will spend some time coming days and this is an issue I will try to fix.

**Comment by jsole** [comment]
Hi hakana, thanks! It will be great to get those shellys as lights again. It's hard to get the google assistant working if they're not lights anymore.

If I can help you in some way just tell me. I've got a bunch of shelly 1 and a shelly 2.5

**Comment by SLeopold1986** [comment]
What can I do to fix this issue? It is really bad that there is no fix for that for so a long time.
