### ISSUE TITLE
Hass version 0.98

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#64]
Anyone installed HASS version 0.98 already?

Lot's of changes concerning the entity_id registration.
Are there breaking changes (since ShellyForHASS uses this registry in the latest version extensively...) ?

**Comment by catalinbordan** [comment]
I installed today. I don't see any problems until now.

**Comment by jodur** [comment]
I upgraded my old venv homeassistant to hass.io with 0.98.1 yesterday and didn't notice any problems.

**Comment by filmgarage** [comment]
Excellent, I updated too. All works fine!
