### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MarkLIII** [StyraHem/ShellyForHASS#664]
## Environment

- ShellyForHASS release with the issue: 0.3.3
- Last working ShellyForHASS release (if known): 0.3.3
- Home Assistant Core release with the issue: 2022.3.1
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Describe the bug

After updating core to latest version, I get fault:
Logboekdetails (FOUT)
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 21:48:35 (9 occurrences)
Last logged: 22:21:30

Unable to install package paho-mqtt==1.5.1: ERROR: Cannot install paho-mqtt==1.5.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

I have followed up the steps in your repo to overcome this bug...

## Screenshots

![image](https://user-images.githubusercontent.com/84196368/156843796-9dd349bf-34d4-4b49-b338-51745327af4a.png)

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
Fixed in release ShellyForHass version 0.3.5

**Comment by hakana** [comment]
Fixed in release ShellyForHass version 0.3.5
