### ISSUE TITLE
[BUG] The sensor and attribut of RSSI and RSSI Level don't work

### ISSUE THREAD

**Issue by ZancaAngelo** [StyraHem/ShellyForHASS#671]
## Environment

- ShellyForHASS release with the issue: 0.3.4
- Home Assistant Core release with the issue: 2022.4.5

## Describe the bug

In my system I have installed and activeted many pieces of shelly 1, shelly EM and shelly H&T, and after updating the core of H.A. at the latest version, the RSSI information of only Shelly 1 and EM alone is no longer read. 
All shelly's are always integrated through cloud communication and not MQTT, and this is the first time this problem appears to me. 
I tried reinstalling the integration, and repametrizing it, but nothing has changed.
The only error I find in the logs concerns the MQTT communication but that I don't use.

Can you help?

## Screenshots
![Immagine 2022-04-26 131157](https://user-images.githubusercontent.com/50366331/165287791-aec54b34-c690-465c-b50f-8d1f40a00aa3.png)
![Immagine 2022-04-26 130835](https://user-images.githubusercontent.com/50366331/165287326-fe714f35-16b4-43d5-a953-3a5a67bb28a7.png)

## Traceback/Error logs
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/shelly/__init__.py:330
Integration: Shelly smart home (documentation)
First occurred: 23 aprile 2022, 18:18:03 (1 occurrences)
Last logged: 23 aprile 2022, 18:18:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/shelly/__init__.py", line 330, in start_up
    pys.start()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyShelly/__init__.py", line 185, in start
    self._mqtt_server.start()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 123, in start
    self._init_socket()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 129, in _init_socket
    sock.bind((self._root.bind_ip, self._root.mqtt_port))
OSError: [Errno 98] Address already in use

**Comment by ZancaAngelo** [comment]
even after updating to the beta version 1.0.0  , the problem continues to persist, and there is no additional information in the logs, pared to what has already been published

**Comment by hakana** [comment]
What show the protocol attribute for the device? Is it different compared with devices that show rssi?

Have ju checked if you have other rssi entities for the device with _2 in the end of entity id?

**Comment by ZancaAngelo** [comment]
I've checked the list of the entities, and don't have any entity with _2 at the end, for my suring I'ved delete 1 entity, for execute  new discovery, and the system found the entity but no the attribute of the RSSi.

it is not clear to me what you mean by protocol attribute, for this reason I attach some picture for you
![Immagine 2022-05-02 081623](https://user-images.githubusercontent.com/50366331/166193047-030ac8cb-aecf-490d-81f8-de48aa53994b.png)
![Immagine 2022-05-02 081835](https://user-images.githubusercontent.com/50366331/166193052-33064a66-7f75-4ac0-a220-c366d3a8c06b.png)
![Immagine 2022-05-02 081908](https://user-images.githubusercontent.com/50366331/166193053-a62d7276-8873-4543-b39a-97fc7beba012.png)
![Immagine 2022-05-02 082008](https://user-images.githubusercontent.com/50366331/166193054-5299b1cb-093f-4271-9112-11e1749bebf7.png)
![Immagine 2022-05-02 082225](https://user-images.githubusercontent.com/50366331/166193057-f597539e-7910-46b3-b09e-00ce2e802e9d.png)
![Immagine 2022-05-02 082357](https://user-images.githubusercontent.com/50366331/166193059-bb30eda1-e8a9-4f94-a4fa-d0c760cb9675.png)
