### ISSUE TITLE
Tons of warnings in logs - "S4H-Cloud (...) Wrong authorization header provided (...) Please login again"

### ISSUE THREAD

**Issue by anthonws** [StyraHem/ShellyForHASS#688]
Home Assistant Core 2022.6.6
ShellyForHASS 1.0

I don't know when it started (which HA and/or ShellyForHASS version), but looking at my logs I can see this warning message flooding the log file.

Any advice?

> 2022-06-22 10:21:32 WARNING (S4H-Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"invalid_header":"Unauthorized! Wrong authorization header provided!","invalid_token":"The login information is invalid! Please login again!"}}'
> 2022-06-22 10:21:38 WARNING (S4H-Cloud) [pyShelly] Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"invalid_header":"Unauthorized! Wrong authorization header provided!","invalid_token":"The login information is invalid! Please login again!"}}'

**Comment by Masterz69** [comment]
HAOS 2022.7.7. Getting:
Logger: pyShelly
Source: /usr/local/lib/python3.10/site-packages/pyShelly/cloud.py:105
First occurred: 26 July 2022, 20:42:33 (3119 occurrences)
Last logged: 23:51:37

Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"invalid_header":"Unauthorized! Wrong authorization header provided!","invalid_token":"The login information is invalid! Please login again!"}}'
Error receive JSON from cloud, Unauthorized : b'{"isok":false,"errors":{"max_req":"Request limit reached!"}}'

So, is it token is wrong (suddenly) or limit reached ? What is actual reason of login failure ?

**Comment by anthonws** [comment]
In my case, ShellyCloud had no longer a token... I simply ignored using the ShellyCloud in my config, as I don't need it.
