### ISSUE TITLE
Cover & reverse direction

### ISSUE THREAD

**Issue by GoNzCiD** [StyraHem/ShellyForHASS#70]
I have a cover configured by Enable the reverse directions check. Buttons from shelly app, shelly web and ha using ShellyForHASS works fine, but the status for the cover shows closing when the cover is opening and opening when the cover is closing.

**Comment by SuperNeo84** [comment]
Hi,

should you try, the calibration on shelly web, i think that, without this operation the status remain wrong.

**Comment by GoNzCiD** [comment]
The calibration an de operation is fine, and works. 
But I have noticed than if en shelly web is marked the reversion option, the ShellyForHASS component detect the closing/openning movement incorrect.

**Comment by SuperNeo84** [comment]
Hi,

i have your the same configuration, with the reverse direction check to "true", the calibration completed, but on HA the functionality is reverse.
Yesterday i tried to invert the cable on SW1 & SW2 directly on my Shelly 2.5, then i removed the reverse direction check on Shelly Web App, the result:

Shelly Web App: work fine
Phisical Button (Up/Down): work fine
HA with ShellyForHass: works in reverse

![Immagine](https://user-images.githubusercontent.com/56050309/67661494-ac566d80-f961-11e9-941d-c310a4f36a56.jpg)

The arrow Up is activate, but the cover is Closed, instead the arrow down is de-activate.

i tried to remove from HA my shelly 2.5, restart HA, remove manually the entities of shelly 2.5, and then i reconfigured it, but the problem still remain.

should i try a new calibration, in this configuration?

**Comment by GoNzCiD** [comment]
@SuperNeo84 maybe you have to delete de entity en HA & reboot to register it again with the new properties/configuration.

**Comment by ArminasTV** [comment]
Hello, just to say, I exactly have the same issue.
So, not solution ?
When I http://deviceip/status : 
The value of state and last_direction is good but not HA.

**Comment by ArminasTV** [comment]
I have the same issue but the calibration solved it.

**Comment by GoNzCiD** [comment]
> 
> 
> I have the same issue but the calibration solved it.

Do you had inverted controls and after calibrate the status while cover is in motion show oppening while it's oppening? or did you have the same issue than @SuperNeo84 ?

**Comment by SuperNeo84** [comment]
hi everybody,

in effect, after i had remove the "Inverted Check" on shelly webapp and i had inverted the cable SW1 & SW2 on the shelly 2.5 i didn't perfermo a new calibration. I only tryed to delete shelly 2.5 from configuration & from HA and rebooted

**Comment by pablitofernandez** [comment]
> > I have the same issue but the calibration solved it.
> 
> Do you had inverted controls and after calibrate the status while cover is in motion show oppening while it's oppening? or did you have the same issue than @SuperNeo84 ?

@GoNzCiD Did you manage to fix this? Because I have the exact same issue. Calibration didnt help and @SuperNeo84 solution of swapping SW1 for SW2 neither. 

Help!!

**Comment by GoNzCiD** [comment]
> 
> 
> > > I have the same issue but the calibration solved it.
> > 
> > 
> > Do you had inverted controls and after calibrate the status while cover is in motion show oppening while it's oppening? or did you have the same issue than @SuperNeo84 ?
> 
> @GoNzCiD Did you manage to fix this? Because I have the exact same issue. Calibration didnt help and @SuperNeo84 solution of swapping SW1 for SW2 neither.
> 
> Help!!

For me, connecting right the direction wires, calibrate and remove the entity from HA, it solve the issue.

**Comment by pablitofernandez** [comment]
So changing SW1 for SW2? Or changing O1 for O2?

**Comment by pablitofernandez** [comment]
Don't worry. I have switched O1 for O2, then factory reset, then calibration and now it's working correctly! Thanks!!
