### ISSUE TITLE
Cover can not share to HomeKit

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#71]
I am not sure when my issue started. But I am sure it worked when my Shellies were still controlled by MQTT.
My cover (sunshade) is working fine with the Shelly platform as long as I only use Home Assistant (Lovelace UI, automations, etc) to control it. However, I use HomeKit on all my apple devices as the front-end for my Home. I do get the cover as an entity in Apple HomeKit, but it does not react to voice commands or basic controls via the Apple Home app.

**Comment by filmgarage** [comment]
Digging deeper I found the solution. Apparently I had to re-calibrate the cover. Now it is working again in HomeKit as well as it was working in Home Assistant.

**Comment by hakana** [comment]
Great!
