### ISSUE TITLE
[FR] Please Add 'Unavailable State' to sensors

### ISSUE THREAD

**Issue by auanasgheps** [StyraHem/ShellyForHASS#724]
## Is your feature request related to a problem? Please describe.

My feature request is related to a problem which is described [here](https://community.home-assistant.io/t/energy-dashboard-shows-crazy-and-unrealistic-energy-spike/479252). #711 is affected too.

The _Total Consumption_ sensor of my Shelly EM reported `0`, then restored the correct amount. This is not the correct behavior, because in a scenario like this one the energy consumption reported to HA is literally double the actual amount because it's summing 0 + the new value.
I have no idea why Total Consumption has reported 0: the power consumption at the time is correct.
![image](https://user-images.githubusercontent.com/20586878/197539369-91652950-9bc2-4459-b746-9b20c8396ee4.png)

## Describe the solution you'd like

As suggested [here](https://community.home-assistant.io/t/energy-dashboard-shows-crazy-and-unrealistic-energy-spike/479252/8):
integration developer should implement an “unavailable state”

This feature should be enabled for all Shelly sensors, not just Total Consumption.

## Describe alternatives you've considered

There are manual workaround that I can consider like filtering the sensor output.

## Additional context

You can find more information [here](https://community.home-assistant.io/t/energy-dashboard-shows-crazy-and-unrealistic-energy-spike/479252/8).

I am using: 
- Home Assistant 2022.10.x
- Shelly For Hass 1.0.2

**Comment by Cippo2019** [comment]
Yes, this is exactly what I mean..

**Comment by auanasgheps** [comment]
Perfect, I updated the issue!

**Comment by Cippo2019** [comment]
DId you get info on that  ?
thanks in advance

**Comment by auanasgheps** [comment]
I gave up and started using the official Shelly integration, so I will close this issue because I don't really care about it anymore.
