### ISSUE TITLE
Shelly H&T

### ISSUE THREAD

**Issue by sentinel43** [StyraHem/ShellyForHASS#74]
Hi. I have over 30 shelly units, shelly1, shelly1pm, shelly 2, shelly2.5 and shelly H&T and I really like what you did with shellyForHASS. Thumbs up. I tried to figure out one thing and I will kindly ask you for advice because I cant find answer anywhere. After hassio restart entities regarded to battery powered devices, in this case shelly H&T, are reported like unvaliable entity. They will show up as soon as I manually wake them up or after fer hours when first state change occur and H&T wake up. Is there any way to stop that behavior? Are they gone because shellyforhass can't find them during start, which is probably because h&T is mostly in sleep mode? Should I add them manually to configuration.yaml or is there any other way which will show them up after hassio restart? I am using shelly H&T to trigger shelly1pm which operate underfloor heating valves . Any help or advice will be more than wellcome.

**Comment by tofuSCHNITZEL** [comment]
yes I have this issue too.
since the H&T will go into deep sleep (even if I check "uses external power") shellyforhass cant find them until they are woken manually or they wake up due to a state change...
is there any way that shelly for has can create the shelly items (or at least the h&t) with "persistence" so they exist after reboots preferrably with the last value?

**Comment by hakana** [comment]
I will try to find a solution for that! When uses external power it wake up every 10 min and reporting status even if no temp change. In normal mode it wake up each 12 hour, if I remember right.

**Comment by ricarva** [comment]
Just wanted to chime in on this. Have the same problem, and ir seems to cause instability in the Generic Thermostat component: not finding the H&T on startup, the Thermostat functionality is of course compromised, but also seems to conflict with the Switch used in the same component/integration,

I'm also getting some instability in having Home Assistant register the changes reported by the H&T. All updates show up on the Shelly app, but HA seems to randomly have stopped listening to the device.

Please advise if I can do anything to help better understand any of these issues.

**Comment by sentinel43** [comment]
> 
> 
> I will try to find a solution for that! When uses external power it wake up every 10 min and reporting status even if no temp change. In normal mode it wake up each 12 hour, if I remember right.

Yes You are right. I tried to find out any solution to keep last value from shelly H&T after home assistant restart and if not using mqtt. I found one workaround but for that shelly H&T must be connected to the cloud.  In my case, if shelly h&t is unavaliable asfter hassio restart, and probably will be in 99,9% of cases because it is usually in sleep mode, hassio will pull temperature value from cloud by reading device status from cloud by using api. After that I added template sensor which combine readings from cloud and reading rom shelly h&t, so in any case you will have temperature reading. That template sensor I use for heating control.

sensor:
  - platform: rest 
    name: temp_cloud_db  #I am creating new sensor which will hold reading from cloud
    unit_of_measurement: '°C'  #added unit of measurement, °C in my case
    resource: https://shelly-5-eu.shelly.cloud/device/status # my shelly cloud server
    method: POST
    payload: 'auth_key=xxxxxxxxxxxxxxxxx&id=xxxxxxxxx' # enter your auth key and device id
    scan_interval: 86400
    headers:
        User-Agent: Home Assistant
        Content-Type: application/x-www-form-urlencoded
    value_template: '{{ value_json.data.device_status.tmp.value }}' 

After that I added template sensor which combine cloud and/or h&t sensor readings

- platform: template 
    sensors:
      temp_db_combined:  #new sensor which will combine shelly cloud and shelly h&t, give the name you want
        friendly_name: "Temperatura dnevni boravak kombinirano"
        unit_of_measurement: '°C'
        value_template: >-
          {% if states('sensor.shelly_shht_1_XXXXXX_temperature') != 'unknown' %} #sensor.shelly_shht_1_XXXXXX_temperature is my entity_id of shelly h&t
            {{states('sensor.shelly_shht_1_XXXXXX_temperature')}}
          {% else %}
            {{states('sensor.temp_cloud_db')}}
          {% endif %}
        entity_id:
         - sensor.shelly_shht_1_58ed9f_temperature
         - sensor.temp_cloud_db

**Comment by tofuSCHNITZEL** [comment]
I found another solution here: https://community.home-assistant.io/t/binary-sensor-last-known-state-when-unavailable/59967/3

this could be adapted for the h&t but it seems pretty "hacky" to me.
is there no way fron HA side to have a sensor hold the last value? (at least as an option?)

**Comment by ricarva** [comment]
@tofuSCHNITZEL you've removed your workaround using the filter sensor. Was it not working properly?

It actually looked somewhat elegant to me, and I was going to give it a try.

**Comment by tofuSCHNITZEL** [comment]
I thought it worked but right now its state is also unknown. just like the shelly sensor.

**Comment by sfanicola** [comment]
hi guys... so no solution for now? I've got the same annoying problem and I'm tired of manually waking up all my sensors.

**Comment by sentinel43** [comment]
> 
> 
> hi guys... so no solution for now? I've got the same annoying problem and I'm tired of manually waking up all my sensors.

You can read in post above how I solved that problem. Maybe not very elegant but it is working and I am happy with it.

**Comment by tcarlsen** [comment]
I have the same "issue" and its "destroying" my lovelace untill the shelly device updates

the history for the sensor should still be in the database? so I think the best solution would be:

if sensor not found : show latest entry in db.

**Comment by tofuSCHNITZEL** [comment]
Exactly and there are entities that retain their status over reboots like boolean inputs... So it should be possible from the HA side. Unfortunately the HA python code goes beyond my understanding.

**Comment by sentinel43** [comment]
> 
> 
> I have the same "issue" and its "destroying" my lovelace untill the shelly device updates
> 
> the history for the sensor should still be in the database? so I think the best solution would be:
> 
> if sensor not found : show latest entry in db.

I was reading about that solution, problem is that database should be started before home assistant, and on rpi3 running hassio I had no idea how to do that. Did You guys tried my solution?

**Comment by tcarlsen** [comment]
I read it yeah. But one of the reasons I use HA is to be cloudless. So adding cloud is not a solution for me

**Comment by sentinel43** [comment]
I am going to close this because this is not Shelly smart home issue.

**Comment by tofuSCHNITZEL** [comment]
> I am going to close this because this is not Shelly smart home issue.

Is it not? Having the last sensor value retained is something that requires change in this integration, not in HA...

**Comment by GNUGradyn** [comment]
Shelly H&Q on USB power. same issue. Sensor shows unavailable most of the time. completely useless in this state.

**Comment by ricarva** [comment]
> Shelly H&Q on USB power. same issue. Sensor shows unavailable most of the time. completely useless in this state.

@GNUGradyn this has been fixed for over a year. Your issue is most probably not related.
