### ISSUE TITLE
rgbw2 manual config

### ISSUE THREAD

**Issue by Loki1147** [StyraHem/ShellyForHASS#76]
Not really an issue.

What i have to write in the configuration.yaml for the rgbw2? id+??

Thanks nice work! everything works perfect for me.

**Comment by hakana** [comment]
I don't understand what you asking?

**Comment by Loki1147** [comment]
i mean " Without discovery - manually specify devices"

For the shelly2.5
     - id: "693651-1"   
      name: Buero Deckenlampe 

and i want to ask how the config looks like for the RGBW2

**Comment by hakana** [comment]
Just the id without -1. You can find the id in Shelly app, it should be 6 digits. You can set name and sensors for it.

**Comment by hakana** [comment]
The id 6 digits is for the unit, -1 -2 is when you want to set the name for different channels.

**Comment by Loki1147** [comment]
if i use only the id HA didn't find the rgbw2.  Only with the discovery.

**Comment by hakana** [comment]
Can you share your shelly config?

**Comment by Loki1147** [comment]
# Settings
  discovery: false
  version: true
  upgrade_switch: true
  devices:      

    - id: "B09636"
      name: Schlafzimmer Stufe
      light_switch: true 
    - id: "693651-1"   
      name: Buero Deckenlampe
    - id: "693651-2"   
      name: Schlaf Deckenlampe
    - id: "6939BE-1"   
      name: Kabuff Luefter
    - id: "6939BE-2"   
      name: Kabuff Deckenlampe    

    - id: "59E020"
      name: Schlafzimmer Deckenlampe  

    - id: "59EA71"
      name: Wohnzimmer Deckenlampe

**Comment by hakana** [comment]
If you enable discovery, does the unit get right name then?

**Comment by Loki1147** [comment]
You mean "Schlafzimmer Stufe"?

The unit gets the name: "Shelly RGBW2 [B09639]"

**Comment by hakana** [comment]
Its because you have written wrong id in config. Should en with 9 not 6 ;)

**Comment by Loki1147** [comment]
Haha *Facepalm* Thanks xD
