### ISSUE TITLE
Flood Sensor doesn't change state

### ISSUE THREAD

**Issue by CiquattroFPV** [StyraHem/ShellyForHASS#81]
I have a flood sensor and I noticed that the Flood Sensor doesn't change the state when a flood is detected/trigger .. it remain false all the time.

**Comment by CiquattroFPV** [comment]
Any update on this? Do you need more information? How I can help for resolve the issue?

**Comment by CiquattroFPV** [comment]
Any update on this? Do you need more information? How I can help for resolve the issue?

**Comment by chemelli74** [comment]
@CiquattroFPV , can you please retest with 0.1.6b6 ? Please update firmware to latest version as well.

Thank you,

Simone

**Comment by CiquattroFPV** [comment]
I have tested it but it doesn't change the state on Home assistant binary_sensor when an event is triggered.

**Comment by chemelli74** [comment]
Please enable debug log and post it.

Thank you,

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
