### ISSUE TITLE
Unable to install pyShelly

### ISSUE THREAD

**Issue by bhaap** [StyraHem/ShellyForHASS#82]
Unable to install package pyShelly==0.1.0: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7x/hnv6rb7918d579px046gqmp00000gn/T/pip-install-72mn78ko/pyShelly/
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Home assistant 0.99.3
running on macOS

**Comment by hakana** [comment]
Look like a local problem, maybe wrong permissions.

**Comment by bhaap** [comment]
wrong persmissions to run the command python?

**Comment by bhaap** [comment]
h-server:~ h-server$ sudo cd /private/var/folders/7x/hnv6rb7918d579px046gqmp00000gn/T/pip-install-96ldjqmm/pyShelly/
/usr/bin/cd: line 4: cd: /private/var/folders/7x/hnv6rb7918d579px046gqmp00000gn/T/pip-install-96ldjqmm/pyShelly/: No such file or directory

It seems like the folder its trying to enter and run the command from does not exsist. Shure this is a permission problem and not that its macOS and not Linux?

**Comment by hennk** [comment]
I just got the same error, on a Python VirtEnv in Ubuntu 18.04:

```
Collecting pyShelly==0.1.0
  Using cached https://files.pythonhosted.org/packages/32/b5/dce44a7fce6818537dab58e3589222838b5df57ae0400996ed5046d27a15/pyShelly-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-le9m8xr4/pyShelly/setup.py", line 8, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 54: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-le9m8xr4/pyShelly/

```

Could this be a locale problem?

**Comment by hennk** [comment]
I can confirm that at least in my case, homeassistant's locale was not set up correctly (it was set to simply "C"), and it failed while trying to read the README.md of the package.

Changing it to UTF-8, I was able to install the package correctly
