### ISSUE TITLE
struggle to get automation based on shelly_switch_click event working

### ISSUE THREAD

**Issue by fverschure** [StyraHem/ShellyForHASS#84]
Hi, First of all thanks for creating this great addon. 
I used to configure MQTT for my shellies, but am trying shellyforhass now. Basic functionality works great out of the box.

now I am aiming to create an automation to toggle a light with a momentary button connected to a shelly, but I cannot get it to work with the code example. 

How can I capture the shelly_switch_click event to see what is happening?
Is there any other way to debug this and find out why it is not working?

I would also want to create a event for a long press. Is this possible?

**Comment by theCheek** [comment]
I am also having this issue:

From automations.yaml
`- id: '1569775164666'
  alias: Courtyard Purple on Entryway Switch Double Clicked
  trigger:
  - event_data:
      click_cnt: 2
      entity_id: sensor.entrance_entryway_physical_switch
      state: true
    event_type: shelly_switch_click
    platform: event
  condition: []
  action:
  - data:
      color_name: purple
      entity_id: light.courtyard_lights
    service: light.turn_on`

When i turn the physical switch on and off, it doesn't do anything at all. I've tried removing the state: true but still nothing.

**Comment by hakana** [comment]
Under development tools / events you can subscribe and see all events. Enter shelly-switch-click or * for all events. Btw, can you see the switch as a sensor in JA?

**Comment by theCheek** [comment]
Thanks Hakana. It appears that its about timing. I subscribed to the shelly_switch_click event and see that it is registering, however getting a consistent result to the number of clicks seems difficult. Sometimes when I click it on and off twice, it registers as two single clicks, and sometimes as 2 clicks. Must be something to do with the latency between the switch and HA.

**Comment by fverschure** [comment]
> Under development tools / events you can subscribe and see all events. Enter shelly-switch-click or * for all events. Btw, can you see the switch as a sensor in HA?

for me it does not show the clicks when monitoring the event. I can see the switch as a sensor and control it as well.

**Comment by hakana** [comment]
Ok, I will test this next week and see if I can find a solution.

**Comment by theCheek** [comment]
> > Under development tools / events you can subscribe and see all events. Enter shelly-switch-click or * for all events. Btw, can you see the switch as a sensor in HA?
> 
> for me it does not show the clicks when monitoring the event. I can see the switch as a sensor and control it as well.
That's weird. Are you using the event shelly_switch_click (not shelly-switch-click)?

**Comment by theCheek** [comment]
Ok so a little update. I took the plunge this weekend and moved my Hassio from my raspberry pi 3 to an old bit much more powerful laptop (running it in docker). I can confirm now that the switch click event is much more reliable. So definitely it was a latency issue of the Pi. I would recommend maybe putting some sort of customisable time period for the clicks, so that people can circumvent the lag issue of less powerful hosts.

**Comment by fverschure** [comment]
@theCheek: reliability for an event driven automation should not rely on processor power imho.
Even when listening to all events I do not capture any event related to the switch toggle unfortunately (I do see state changes for power consumtions of the shellies passing through the event log.
Eventually I will also move to another more powerful platform like a intel nuc, but there is another reason for me to do this. 
Regardless it is a pity that it is not working. Can I help you by sharing some log data or anything else?

**Comment by theCheek** [comment]
@fverschure it would appear that my issue was not the same as yours, so I apologise for hijacking your thread. Sounds like you don't get any switch toggle event, my issue was the registration of number of clicks.
Maybe post the relevant configuration.yaml for your Shelly's to rule out any config errors?

**Comment by gerard33** [comment]
I have a Shelly dimmer and when pressing button 2 it only shows up as an event under `shelly_switch_click` if I press the button (which is a momentary switch) for a few seconds (minimum of 5 seconds). When just pressing the button once or double clicking, this doesn't show up as an event.
I am running HA on an Intel NUC i3, so it's powerful enough and HA has the right sensor -> `sensor.shelly_shdm_1_f3a312_2_switch`

I am now using the following workaround so I am able to use the 2nd button.

I have configured an url in the Shelly Dimmer webpage under `BUTTON 2 SWITCHED ON URL` which opens a PHP page on my NAS (the page must run on a server which supports PHP).
The url is:
`http://192.168.1.102/hass/shelly_button_2.php?type=light&entity_id=xiaomi&service=toggle`
- `192.168.1.102/hass` -> replace with the url of your server
- `type` -> e.g. `light`, `switch`, `input_boolean`
- `entity_id` -> the name of the entity id, so if you have `light.garage`, you need to use `garage` here
- `service` -> `toggle` (this is the most logic for a momentary switch, as the Shelly also directly registers an OFF when the switch flips back), other options e.g. `on`, `off`

The PHP script is shown below. If you want to use this you need to change the following in the script:
- `192.168.1.131:8123` -> your HA url
- `YOUR_TOKEN_HERE` -> your token

Instructions to get a token -> https://developers.home-assistant.io/docs/en/external_api_rest.html
Inspiration for the PHP script came from -> https://www.reddit.com/r/homeassistant/comments/9koxbc/help_with_curl_and_php/

```php
<?php
    // get variables
    $type = $_GET["type"];
    $entity_id = $_GET["entity_id"];
    $service = $_GET["service"];

    // create curl resource
    $ch = curl_init();
    $data = array("entity_id" => $type . "." . $entity_id, );
    $data_string = json_encode($data);

    // set url
    curl_setopt($ch, CURLOPT_URL, "http://192.168.1.131:8123/api/services/" . $type . "/" . $service);
    //curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        "Authorization: Bearer YOUR_TOKEN_HERE",
        "Content-Type: application/json",
    ));
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);

    //return the transfer as a string
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    // $output contains the output string
    $output = curl_exec($ch);

    // close curl resource to free up system resources
    curl_close($ch);

    echo $output
?>
```

When pressing button 2 with this method there is an instant reaction.

Hopefully the ShellyForHASS component is able to catch the events immediately after pressing or double pressing the button in a future release, but in the meanwhile the above method can be used.

**Comment by theCheek** [comment]
i might just be missing something, but i am not seeing any events for shelly_switch_click.

The switch sensor is now showing up as a binary_sensor - is this normal?

from configuration.yaml:
`  devices:  #configure devices
    - id: "C[redacted]-1"
      light_switch: true  #add this switch as a light
      name: Kitchen Strip Lights
      sensors:
        - switch
        - current_consumption
        - total_consumption`

and now this is showing up as: binary_sensor.shelly251_kitchen_strip_lights_switch

but i can't seem to catch any switch events. Any ideas?

**Comment by gerard33** [comment]
@theCheek I have the same, but after a long press I see events, see my post above

> I have a Shelly dimmer and when pressing button 2 it only shows up as an event under shelly_switch_click if I press the button (which is a momentary switch) for a few seconds (minimum of 5 seconds). But this is also not working all the time.
When just pressing the button once or double clicking, this doesn't show up as an event.

The switch sensors are showing as a binary sensor for me as well.

**Comment by theCheek** [comment]
Thanks @gerard33 for confirming this isn't just an issue with my setup. Yesterday when monitoring shelly_switch_click event suddenly it started reacting with the correct feedback, however after I wrote an automation for it (change philips hue lights to different primary colour when number of clicks = 2 ) it didn't work, and then suddently the event monitoring also didn't work. It's weird.

I like your work around and will take a look at using the shelly button switched on url.

**Comment by xatr0z** [comment]
Having the same issue, will watch this for updates. Some info:

- Shelly 2.5
- Switch connected to 0 in detached mode
- When I toggle the switch I can't see any event when listening to *.
- However the MQTT message is published, and I can see the binary_sensor entity.

**Comment by paolograssi** [comment]
All, I fully understand that MQTT stops cloud but I just configured it and works extremely well.

Consider it as another option?

**Comment by chemelli74** [comment]
> All, I fully understand that MQTT stops cloud but I just configured it and works extremely well.
> 
> Consider it as another option?

Nope, as you already have MQTT integration ;-)
This plugin is about having an alternative to get both Cloud and local.

Simone

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.7.b2) and latest firmware ( v1.6.0) and recheck.

Simone

**Comment by xatr0z** [comment]
> 
> 
> Please update to latest beta (0.1.7.b2) and latest firmware ( v1.6.0) and recheck.

Udpated shelly to 1.60, the plugin to 0.1.7-beta.2 via HACS and restarted home assistant. After flipping the switch (in detached mode) nothing changes and still no events (when listening to *).

**Comment by chemelli74** [comment]
As shared with the author, we proceed to close this issue.

Once 0.1.7 final is released, if there will be again the need, feel free to open a new issue.

Simone

**Comment by xatr0z** [comment]
I don't understand the last update, is this unfixable, something in my setup, ...? As said before, updating to  0.1.7-beta.2 didn't resolve the issue for me.

**Comment by gerard33** [comment]
With 0.1.7 the events are now visible for me. One click, double clik and triple click all are available in the event viewer. Great work, thanks 👍🏻
