### ISSUE TITLE
component not working in Hass.io 0.100.2 ?

### ISSUE THREAD

**Issue by pathia** [StyraHem/ShellyForHASS#85]
Tonight I upgraded my hass io from 0.99.2 to 0.100.2 and after that my Shellies are not available anymore. 
I have tried to get some debug logs, but I don't get anything.
```
logger:
  logs:
    custom_components.shelly: critical
```
Can anyone confirm this or let me know if it does work for you in 0.100.2 ?

**Comment by filmgarage** [comment]
I upgraded to 0.100.2 as well on two HA machines, both working fine. Only having an issue with a shelly bulb. It is discovered by the shelly component but I cannot control the bulb.

**Comment by vincenzosuraci** [comment]
I installed this custom component using HACS. But it does not discover any Shelly device. I'm on Hassio 0.100.2.

**Comment by pathia** [comment]
Closing this issue as it had nothing to do with the ShellyForHASS component. It had to do with multicast filtering on my access point.
