### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by vincenzosuraci** [StyraHem/ShellyForHASS#86]
I have Home Assistant installed on a Raspberry Pi 3B+.
My system is update to the following version: 
**Hass.io supervisor**
Version	189
Latest version	189
**Host system**
Hostname	hassio
System	HassOS 2.10
Deployment	production

I installed HACS and then ShellyForHASS. But no devices are detected (I have more than 40 Shelly devices at home). All the Shelly devices are connected in the same LAN via a Orbi Netgear Mesh Network WiFi. I can ping the devices as well as access to their web pages (they have static IP addresses). But it seems that ShellyForHASS is not able to discover them.

Any suggestion?

**Comment by Misiu** [comment]
@vincenzosuraci did You add `shelly:` into your configuration.yaml (as mentioned [here](https://github.com/StyraHem/ShellyForHASS#examples))?
I missed that when I tried this component at first.

**Comment by vincenzosuraci** [comment]
I did it, following the instructions. But nothing happen. I read about multicast filter issues on the router, but I do not have setup any multicast filter. So, I'm wondering if this component really works...

**Comment by Misiu** [comment]
did You try running `test.py`?
I also have issues with this component, but in one network (at my place no problems) at my parent house some shelly devices are unavailable after some time, but they get online after a while.

Sadly I don't know Python, but looking at code I think that there aren't many pieces of information logged.
I've contacted Shelly support via Facebook, but thet said that everything works on their side.
I don't know why some of us have such problems.

@vincenzosuraci maybe You should give [the MQTT version](https://github.com/bieniu/ha-shellies-discovery) a try? Sadly you will lose the cloud if You enable MQTT. Also please write on Shelly Facebook page that they should support the cloud and MQTT together (I already did, but if we keep asking they eventually will add it)

If you try MQTT script please write about your experience here.

**Comment by vincenzosuraci** [comment]
I run `test.py` and it did not work. So, it seems to be a network problem. I have a netgear Orbi mesh wifi network. I do not know how to enable IGMP or, in general, how to avoid multicast UDP connections to be blocked.

VS

**Comment by Misiu** [comment]
@vincenzosuraci try contacting Netgear support. This should be doable, but maybe it is a hidden option in the Netgear admin panel.

**Comment by mospring** [comment]
@vincenzosuraci Have you solved the problem? I have the same problem with ORBI and my shellies...

**Comment by chemelli74** [comment]
@vincenzosuraci , @mospring, , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by mospring** [comment]
I could solve the issue for me setting ORBI to the Router mode (not Access Point Mode).
