### ISSUE TITLE
Entity sensor.shelly_shsw_25_xxxxxx_1_consumption is incorrectly being triggered for updates while it is disabled

### ISSUE THREAD

**Issue by peterbuga** [StyraHem/ShellyForHASS#96]
not quite an issue, you can leave it on the lowest priority or ignore it altogether but i thought i should mentioned it 

`WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.shelly_shsw_25_xxxxxx_1_consumption is incorrectly being triggered for updates while it is disabled. This is a bug in the shelly integration.`

this happens if you disable the entity from the Configuration > Entity Registry section

**Comment by chemelli74** [comment]
@peterbuga , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by peterbuga** [comment]
@chemelli74 thanks for looking into this
as instructed (at the time of writing) i updated the shellys fw + used 0.1.6b8 of the component but the warning message is still showing up :( 

it was a bit harder to catch it up with because now the component throws a lot of update INFO message but i was able to filter them out with the bellow configuration:
```
logger:
  default: info
  logs:
    pyShelly: warning
```

let me know if there's more i can do to help/test (as i mentioned above it's not a big deal and i didn't had time to check the code but i assume that an IF check if the create entity is not disabled could disable sending update events in HA, just a hunch)

**Comment by hakana** [comment]
Yes, I know this and will fix ett later

**Comment by hakana** [comment]
This warning happens when disabling an entity in HA. It only shows once and not when restarting HA. It is some synchronization problem and I will not spend time to fix it in this release.

**Comment by chemelli74** [comment]
Going t o close this issue as needs a fix from HA.
Please open a issue there if you feel that it must be fixed.

Simone
