### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by elmgrenen** [StyraHem/ShellyForHASS#97]
I'm having issues adding this component to HA, I've tried with HACS and without it.

No devices are showing at all, I have two plugs and one Shelly bulb. I managed to get it to work at a friends house, he had one plug and one bulb and I only got the plug to work, not the bulb.

What am I doing wrong? I've added shelly: to my config.yaml and all files are in custom_components/shelly

**Comment by Puntoboy** [comment]
Same issue here. The entity is listed, but nothing under Devices.

**Comment by hakana** [comment]
Probably the firewall that not allow UDP on port 5683 or a Switch. Can you see any errors in log from Shelly?

**Comment by Puntoboy** [comment]
OK I can see the Shelly devices on the Overview page and listed under entity_id but not under devices. I can control them from the overview page.

How do I create the automations?

**Comment by joriskalz** [comment]
Having the same issue, entities are available but nothing under devices. No related error messages in the log.  No automations possible.

**Comment by chemelli74** [comment]
@Puntoboy, @joriskalz , can you please retest with 0.1.6b6 ? Please update firmware to latest v1.5.7 as well.

Thank you,

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
